### ISSUE TITLE
Logging options not working.

### ISSUE THREAD

**Issue by tonsmets** [fergiemcdowall/search-index#100]
While working with the awesome package you made, I came across the fact that my options are simply ignored:
```
var options = { indexPath: 'SearchCache', logLevel: 'error', logSilent: true }
var si = require('search-index')(options)
```
Because my console looks like this:
![schermafbeelding 2015-05-04 om 14 19 46](https://cloud.githubusercontent.com/assets/6669915/7453384/a889b9a0-f268-11e4-9eaa-5ae1697d8de2.png)

Is this a known bug? Or is this configurable elsewhere?

**Comment by fergiemcdowall** [comment]
Hi I literally rewrote this yesterday, and am pushing out a new version as we speak.

Long story short- logging is moving to bunyan.js so that it works in the browser.

**Comment by tonsmets** [comment]
Great to hear! Looking forward to it. Thanks for your fast response!

**Comment by fergiemcdowall** [comment]
`0.5.1` now out. Set `logLevel` in the startup options to control logging. Loglevel is a bunyan.js logLevel value (https://github.com/trentm/node-bunyan#levels).

(note: logSilent is no longer a thing)

**Comment by tonsmets** [comment]
Thanks! It's working like a charm!

**Comment by fergiemcdowall** [comment]
nice- thanks for the feedback.
