### ISSUE TITLE
Make less gigantic autogenerated IDs

### ISSUE THREAD

**Issue by fergiemcdowall** [fergiemcdowall/search-index#101]
If indexing documents that dont contain an ID field. The autogenerated IDs are so gigantic that they affect the size of the index.

Make autogenerated IDs smaller.

**Comment by eklem** [comment]
I'm using [jhash](https://github.com/ysmood/jhash):

```javascript
var Id = function(input) {
    // Creating an ID, and adding it to each item
    // Contains jhash of item value strings
    jhash.setSymbols('0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ');
    id = jhash.hash(input)
    return id
}
```
... and add different stuff as input depending on the source so I know I get unique ID's:

```javascript
obj.id = ifttnorch.id(obj.date + obj.urlimage + obj.title + obj.text)
```

**Comment by fergiemcdowall** [comment]
Thanks for the tip!

**Comment by eklem** [comment]
No problem! And if you add all value strings for an item, you'll be sure to get a unique ID, and then you'll get rid of duplicates too.

**Comment by fergiemcdowall** [comment]
"fixed", or at least smaller than they were before
