### ISSUE TITLE
A way to select the fields that are available for fielded search

### ISSUE THREAD

**Issue by fergiemcdowall** [fergiemcdowall/search-index#102]
Having fielded search makes the index really big. The fewer fields are individually searchable/weightable, the smaller the index will be. Fields that cannot be individually searched on will still be available under `*` search

**Comment by fergiemcdowall** [comment]
Kind of related to #98

**Comment by mewwts** [comment]
I envision that in many applications auto-complete is the most important. This would drastically decrease the index size right?

**Comment by fergiemcdowall** [comment]
I need to check but I think this may actually reduce index size since autocomplete is pre-compiled so anything that reduces total entries, also reduces index size.

Fielded search, deleteability and long IDs are currently the 3 things that cause embigenning.

**Comment by mewwts** [comment]
Can we incorporate some kind of compression on the index? Or does leveldb already do that?

**Comment by fergiemcdowall** [comment]
LevelUP implements [snappy](https://code.google.com/p/snappy/) and the replications files are gziped.

Quite possibly room for improvement in how it is all implemented though...

**Comment by mewwts** [comment]
Sounds pretty good. :+1:

**Comment by fergiemcdowall** [comment]
See also #109

**Comment by fergiemcdowall** [comment]
now in master as of https://github.com/fergiemcdowall/search-index/commit/2fe2a571297efa5ac6541d711cdd80cf084a79ac
