### ISSUE TITLE
Synonym functionality

### ISSUE THREAD

**Issue by fergiemcdowall** [fergiemcdowall/search-index#103]
make synonyms possible

**Comment by fergiemcdowall** [comment]
Possibly by implementing #99

**Comment by sam2x** [comment]
any news about this feature ? can't find it in source code

**Comment by fergiemcdowall** [comment]
Till on the todo list: it will be possible once OR functionality is implemented

**Comment by fergiemcdowall** [comment]
Synonyms are now possible by using OR. Will write up a howto soon
