### ISSUE TITLE
Phrase search

### ISSUE THREAD

**Issue by fergiemcdowall** [fergiemcdowall/search-index#105]
By indexing n-grams, phrase search can be implemented.

Depends on https://github.com/fergiemcdowall/term-vector/issues/1

**Comment by larsvoigt** [comment]
It would be awesome to have this feature!

**Comment by fergiemcdowall** [comment]
Dupe of #14

**Comment by fergiemcdowall** [comment]
fergiemcdowall/term-vector#1 now fixed

**Comment by larsvoigt** [comment]
:+1:

**Comment by larsvoigt** [comment]
Great @fergiemcdowall !
