### ISSUE TITLE
[Question] Searching in selected batches

### ISSUE THREAD

**Issue by tonsmets** [fergiemcdowall/search-index#106]
In my implementation of this awesome search plugin, I currently add two batches (with different names) of data to the index. When searching this index, I'm only able to search in both "datasets".

Is there a possibility to specifiy a batchName to do all searching in? This would make it possible to fill the index once with all "datasets" I need, and then have the possibility to search trough all data, or trough 1 or more specified batches.

**Comment by fergiemcdowall** [comment]
Yes, if you add the batchname as a property to each document, and then filterOn that field when indexing

**Comment by eklem** [comment]
With regular filters you can then search one or all batches. If you use numbers I guess you can use range filters to search some of them.

**Comment by tonsmets** [comment]
Thanks for the quick responses! I tried your suggestion and it worked like a charm!
