### ISSUE TITLE
[feature] Option: don't store field(s) 

### ISSUE THREAD

**Issue by larsvoigt** [fergiemcdowall/search-index#109]
Analyse the field, but don't store the content: 
In my case I have a field with large content that should be analysed, but 
it is  not necessary to store it with the indexed document.

**Comment by eklem** [comment]
For my use, when document processing, I'm pushing to a new object that I then index. Then I can fine-tune what I index and what not. I guess you can also delete key/values? Or did you want easier, built in stuff?

**Comment by mewwts** [comment]
@larsvoigt that would be a cool feature.
@fergiemcdowall it could reduce index size while still allowing filtering? or am I misunderstanding?

**Comment by fergiemcdowall** [comment]
@larsvoigt that is definitely a pain point for a lot of users that could and should be fixed

**Comment by larsvoigt** [comment]
Thanks. Great to hear. I'm looking forward.  :+1:

**Comment by fergiemcdowall** [comment]
You can now select which fields are available for *fielded search* which may save a lot of space and also speed things up.

Next step is to specify fields to be skipped for indexing: so they are non-searchable, but will still be returned with a document from the index.

**Comment by fergiemcdowall** [comment]
Functionality is in place. We might make the syntax for doing this prettier at some point.

**Comment by larsvoigt** [comment]
Hei hei, it looks like you work all night long @fergiemcdowall ;-). Every day new features. 
When the new version is published on npm, I will test this feature and the other new features in my application .
