### ISSUE TITLE
Option to ignore stop words

### ISSUE THREAD

**Issue by alexturpin** [fergiemcdowall/search-index#111]
Hey all,

Currently, it's understanding that as soon as a stop word is present, the search is halted. So for example, the keywords `['fish', 'and', chips']` can return no results even though `['fish', 'chips']` do. An option to simply ignore the stop words instead of having them halt the search would be tremendous.

Cheers

**Comment by fergiemcdowall** [comment]
Yes, should be done. This functionality is in `term-vector`, so we just need to make it available.

**Comment by alexturpin** [comment]
@fergiemcdowall Looking more into it, it seems as if `term-vector` does simply remove the stop words. Perhaps the problem then is that the search requires all keywords be present, and since _and_ was removed by `term-vector` there are no results returned? Although I figure that's probably be design.

**Comment by alexturpin** [comment]
For my purposes, I will simply be removing the stop words from the list of keywords I pass to `search-index`, but perhaps there should be a built-in way to do this.

**Comment by fergiemcdowall** [comment]
Hmmm, there is probably an argument for removing stopword stripping from search-index altogether, and instead encourage users to handle it in an index pipeline

**Comment by fergiemcdowall** [comment]
FWIW, you can hack this by changing https://github.com/fergiemcdowall/search-index/blob/master/lib/indexing/indexer.js#L103 to:

```javascript
try {docVector = tv.getVector(doc[fieldKey] + '', {stopwords:[], separator:/[\|' \.,\-|(\n)]+/})}
```

That way stopwords will not be removed

**Comment by fergiemcdowall** [comment]
Stopword functionality just got improved, see: https://github.com/fergiemcdowall/search-index/blob/master/README.md#initialization and your specific "fish and chips" example in the tests here: https://github.com/fergiemcdowall/search-index/blob/master/test/general-tests/stopword-test.js

**Comment by fergiemcdowall** [comment]
Fixed

**Comment by alexturpin** [comment]
Awesome! Thanks a lot.
