### ISSUE TITLE
Which features to implement - Processing over file size ?

### ISSUE THREAD

**Issue by eklem** [fergiemcdowall/search-index#112]
I was thinking. Search index file size is always an issue. High processing demands for a search solution has historically been an issue. But `Search-index` can now run in the browser. This means we should prioritize nice features that create higher processing demands over features that creates bigger search indexes.

What do you think?

**Comment by fergiemcdowall** [comment]
I think the two issues are linked. When you make the index smaller, you are generally giving the software less to do.

There should definitely be more opportunity for tradeoffs- for examples: do I want to sacrifice the ability to delete in return for a smaller index? and so on.

**Comment by fergiemcdowall** [comment]
Closing this discussion- conclusion: faster indexes are generally smaller?
