### ISSUE TITLE
[question] search query 

### ISSUE THREAD

**Issue by larsvoigt** [fergiemcdowall/search-index#113]
Hello,  
short question: 
Is it possible to "say" search-index that it should looking for all hits 
in ```body "logic or" title```? 
```
 var query = {
            "query": {"body": "apple", "title": "apple"},
            "offset": 0,
            "pageSize": 100
        };
```
I think I get always a "logic and" result set.  More specific the result contains only hits that the engine found in ``` body ∧ title ```. 

Thanks Lars

**Comment by fergiemcdowall** [comment]
search-index only does `AND` search, `OR` search is coming soon(ish)

**Comment by fergiemcdowall** [comment]
closing...
