### ISSUE TITLE
Function chaining

### ISSUE THREAD

**Issue by fergiemcdowall** [fergiemcdowall/search-index#119]
It would be really cool if you could chain functions.

Appending `close` function would be particularly useful

**Comment by mewwts** [comment]
What exactly do you mean? :8ball:

**Comment by fergiemcdowall** [comment]
so you could to stuff like .add().add().close()

**Comment by mewwts** [comment]
Oh, right!

Den fredag 3. juli 2015 skrev Fergus McDowall <notifications@github.com>
følgende:

**Comment by mewwts** [comment]
Is this really something we want/need? I generally love these APIs, but I can't really see how it's useful for search-index.

**Comment by fergiemcdowall** [comment]
I could think of a few cases when it would be nice to have- for example when indexing the reuters test dataset, you could do .add(file1).add(file2).add(file3) etc. But only nice to have.

**Comment by fergiemcdowall** [comment]
Going to put this one to sleep, unless there is anyone who really wants it...
