### ISSUE TITLE
save index cache to.... disk?

### ISSUE THREAD

**Issue by hems** [fergiemcdowall/search-index#120]
Am i wondering if once you loaded and indexed the content in memory would be possible to store this "cache" on disk, so next time the application opens it wouldn't need to load it all in memory straight away?

I believe sqlite kinda does that with it's indexes?

or...

did i understand something wrong?

**Comment by fergiemcdowall** [comment]
Yes, in fact, on-disk storage with instant startup/shutdown should be the default. Are you experiencing problems with startup times?

**Comment by hems** [comment]
@fergiemcdowall i'm not having problems, it was a question after checking the readme file. 

I just realised there is a ````indexPath: 'si2'```` on the example and that will be where the storage actually happens.
