### ISSUE TITLE
Generating of the teaser field a bit buggy

### ISSUE THREAD

**Issue by eklem** [fergiemcdowall/search-index#122]
I thing the teaser field is a bit buggy. I've experienced over time that it every now and then returns content even if no match to search query.

If you need a sample dataset in JSON, let me know.

![Check the last result item](https://cloud.githubusercontent.com/assets/236656/8486385/85264bca-2104-11e5-9aa5-92201dc83557.png)

**Comment by fergiemcdowall** [comment]
How can I reproduce this bug? Is there one document and search pair that always has the problem, or is it unpredictable?

**Comment by fergiemcdowall** [comment]
The default behaviour when displaying the teaser field with no hits is to return the first sentence. Is that what you are experiencing? What is the expected behaviour vs actual behaviour?

**Comment by eklem** [comment]
I think so, but not sure if it happens always. But, there has been a lot of other issues, so I can close this and reopen if I find any irregularities.

My guess is it's the expected behaviour. I've made it so I would like to use a text-field containing HTML when no teaser, but that's a more special case.
