### ISSUE TITLE
Indexing option for "non-deletable"

### ISSUE THREAD

**Issue by fergiemcdowall** [fergiemcdowall/search-index#125]
An option to make a document non-deleteable

This saves a significant amount of space in the index

**Comment by fergiemcdowall** [comment]
implemented in f3346a1

**Comment by mewwts** [comment]
I actually suggest have all documents non-deletable by default. With today's index structure, having docs deletable takes up so much space.

**Comment by fergiemcdowall** [comment]
Yes, I agree
