### ISSUE TITLE
Ability to replicate index deltas

### ISSUE THREAD

**Issue by fergiemcdowall** [fergiemcdowall/search-index#127]
Some kind of versioning that enables you to only update the delta of an index.

When replicating an index, this will allow you to only update the changed part of the index

**Comment by mewwts** [comment]
:+1:

**Comment by fergiemcdowall** [comment]
I can see this taking the form of a `merge` function, where you can simply pass in another index for merging. Alternatively it could be a part of `DBWriteStream()` where you set `{ merge: true }` in the options.

**Comment by fergiemcdowall** [comment]
You can now "merge" one index into another, which is quite a neat way of dealing with deltas
