### ISSUE TITLE
cache functionality

### ISSUE THREAD

**Issue by fergiemcdowall** [fergiemcdowall/search-index#13]
Cache queries, so that results can be returned without performing an actual search.

Must be kept off of a multinode installation since old caches cannot be removed if the keys are hashed, and it is faster if it is local.

**Comment by bugs181** [comment]
I almost feel like this would be better suited to the application layer. What would be the benefits of adding it to the library itself? There are those of us who believe the node-way of task specific features belong to individual modules.

**Comment by mewwts** [comment]
I tend to agree with @bugs181 on this one!

**Comment by fergiemcdowall** [comment]
@bugs181 @mewwts I basically agree with you.

The advantage of dealing with it at the `search-index` layer is that you can be smarter about handling caching and updating together (since a naïve external cache must delete everything after even a minor update).

Cache functionality is only really useful once you have a lot of data on a single node, and even then only for queries that look up lots of data and are therefore non-specific and not so useful (ie: queries with search terms that are very common in the index). Since we are concentrating on "small data" just now, cache functionality is probably something to think about at some point in the future, if at all.

**Comment by fergiemcdowall** [comment]
On reflection I totally agree with you guys :)
