### ISSUE TITLE
Include browserified build in repo.

### ISSUE THREAD

**Issue by mewwts** [fergiemcdowall/search-index#132]
I'm not entirely sure this is necessary.

But by pointing browserify to the build by including:

```
"browser": "my-build.js"
```
in `package.json`, we allow search-index to be required from other modules that runs in the browser. 

See: https://github.com/substack/browserify-handbook#packagejson

**Comment by fergiemcdowall** [comment]
Yes, we should definitely do that!

**Comment by mewwts** [comment]
Is this implemented? Or did you close it by mistake?

**Comment by fergiemcdowall** [comment]
Closed by mistake- doh!

**Comment by fergiemcdowall** [comment]
I just noticed that we already have it- but I am a bit unsure if the latest changes to search-index broke it or not, because its not covered by the tests (should definitely be fixed in this release)

Am investigating...

**Comment by mewwts** [comment]
Should def. be covered by tests. Wanted to have a look at how to test in browsers, without messing too much with our nice mocha setup :-)

**Comment by fergiemcdowall** [comment]
Way forward? https://github.com/nathanboktae/mocha-phantomjs

**Comment by fergiemcdowall** [comment]
The browser examples seem to be working but am a bit lost as to the best way to test them...

**Comment by eklem** [comment]
Browserified tests?

**Comment by mewwts** [comment]
We must also run the tests in the browser, right? Write the tests, browserify them, and then run them in the browser with some funky test-runner?

**Comment by fergiemcdowall** [comment]
Yes, it seems that we have to use phantomJS, since it is the only "browser" that can be invoked by test scripts.

(on a side note- phantomJS can also be used to make .png previews of webpages during indexing)

**Comment by mewwts** [comment]
:+1:

**Comment by mewwts** [comment]
OK. So we have a browserified build of this. We need to figure out how to do testing. Closing and opening new issue.
