### ISSUE TITLE
Testing search-index in the browser.

### ISSUE THREAD

**Issue by mewwts** [fergiemcdowall/search-index#136]
See #132

**Comment by mewwts** [comment]
Just leaving this here https://github.com/substack/browserify-handbook#testing-in-node-and-the-browser

**Comment by mewwts** [comment]
But we do perhaps need to write a few specific tests for the browsers?

**Comment by mewwts** [comment]
These are the browser-specific tests that elasticsearch-js has:
https://github.com/elastic/elasticsearch-js/blob/master/test/unit/browser_builds/generic.js

That's not a lot, but probably in the direction of what we need. Perhaps we need to test connection to IndexedDB.

**Comment by fergiemcdowall** [comment]
Yes- we need a scriptable browser that supports indexeddb

-- 
Apologies for brevity- this message was sent from my mobile

**Comment by mewwts** [comment]
I'm gonna go ahead and work on some tests for running search-index in the browser.

**Comment by mewwts** [comment]
[Testling](https://www.npmjs.com/package/testling) looks a bit more lightweight phantomjs.

**Comment by mewwts** [comment]
Progress on this is a bit slow, will meet up with @fergiemcdowall on sunday to exchange ideas.

**Comment by fergiemcdowall** [comment]
related: #210

**Comment by fergiemcdowall** [comment]
Broswerify + chromedriver tests now set up
