### ISSUE TITLE
Pre-requisite(s) exist but aren't mentioned in README

### ISSUE THREAD

**Issue by bean5** [fergiemcdowall/search-index#142]
I am new to this project, but it appears that underscore is pre-requisite to this tool. I didn't know until after I tried running it. Should pre-requisites be mentioned in the README?

**Comment by eklem** [comment]
Nice catch. Think it should be defined as required, and auto-installed. @fergiemcdowall?

**Comment by bean5** [comment]
//I don't think it was defined as required in the natural project either.

**Comment by fergiemcdowall** [comment]
Hi @bean5 , lodash is defined in [package.json](https://github.com/fergiemcdowall/search-index/blob/master/package.json), so everything should work if you type `npm install search-index` into the project you are working on

**Comment by fergiemcdowall** [comment]
Im assuming that this is now working :)
