### ISSUE TITLE
Encode key using Bytewise

### ISSUE THREAD

**Issue by cshum** [fergiemcdowall/search-index#143]
[Bytewise](https://github.com/deanlandolt/bytewise) supports Array prefix, string and numeric encoding such as

``` js
encode(['foo', 45]) < encode(['foo', 123]) < encode(['foo', Infinity])
encode(['add']) <  encode(['add', 'item', 789]) < encode(['add', '~'])
```

Which simplifies much of the custom string prefix or left-padding of numbers e.g.

``` js
'DELETE-DOCUMENT~' + docToBeIndexed.id[0].field + '~' + searchableField
searchableField + '~' + vecField[0] + '~' + facet + '~' + docFacet
```

**Comment by mewwts** [comment]
This looks promising, thanks @cshum ! :+1: 
The (use-cases)[https://github.com/deanlandolt/bytewise#use-cases] looks fitting.

**Comment by fergiemcdowall** [comment]
Aha! Suddenly we have some reading to do..!

**Comment by fergiemcdowall** [comment]
Have had a good look at use cases. The most recent version of `search-index` doesn't require numeric sorting in the keys. For the time being I am going to put this on ice. If anybody sees a place for bytewise in `search-index`, then submit a PR and we will be super-happy!

**Comment by mewwts** [comment]
Well tbh the number padding scheme isn't the most beautiful. Can bytewise
help with that?

Den søndag 23. august 2015 skrev Fergus McDowall <notifications@github.com>
følgende:

**Comment by fergiemcdowall** [comment]
Are we still padding numbers? I thought we werent doing that anymore..?

**Comment by mewwts** [comment]
Haha, could be my bad, was looking over the presentation from webrebels :p

Den mandag 24. august 2015 skrev Fergus McDowall <notifications@github.com>
følgende:

**Comment by fergiemcdowall** [comment]
Ohhhhhh- you mean for making searchable numbers. Yes- that is definitely a use case.

Sorry- I was thinking about sorting the TFIDFs. Yes absolutely. Total short-circuit on my part

**Comment by mewwts** [comment]
Haha no worries :)

**Comment by mewwts** [comment]
Hey @cshum, I'm really into this idea. Was wondering if you were working on it, or if I should have a go?

**Comment by cshum** [comment]
Not only numbers but this should also avoid most of higher/lower range problems.

This will cause incompatibility with current keys though. Not very confident with this yet until I fully grasp the indexing logics. @mewwts you should have a go.

**Comment by fergiemcdowall** [comment]
I _think_ that the high/low range problems are fixed. The tests we have for English, Chinese, and Norwegian are now passing.

The numeric sorting thing is definitely something that could be improved though.

In theory, you could encode a field with Bytewise externally, index it with search index, and decode it on the way out, and everything would work fine, so it could be that no changes to the lib are needed

**Comment by mewwts** [comment]
I think perhaps we can shave off quite a few bytes using this globally, @fergiemcdowall.

**Comment by eklem** [comment]
The leftpadding of numbers is something of a blocker to a lot of really nice functionality. Is this something we could solve this year?

**Comment by eklem** [comment]
@fergiemcdowall This one is fixed now, isn't it?
https://github.com/fergiemcdowall/search-index/issues/436#issuecomment-458912527
