### ISSUE TITLE
result highlighting

### ISSUE THREAD

**Issue by mblakele** [fergiemcdowall/search-index#147]
It would be useful if search-index exposed an interface for highlighting search results. This is best done inside the search library because the search library knows which terms really match, including ngrams, stops, fields, etc.

Different applications will want to highlight in different ways. The interface would probably take a query, options, and a callback function. Options might include limiting highlighting to a maximum size or duration, for acceptable performance on large documents. The callback would receive an object that describes the matches found: maybe structured something like `{fieldName: matchingTerm: [run1, run2, ...]}}`.

**Comment by fergiemcdowall** [comment]
Have you checked out the teaser functionality? It highlights search terms on specified fields. https://github.com/fergiemcdowall/search-index/blob/master/doc/search.md#teasers-and-search-term-highlighting

**Comment by mblakele** [comment]
Will do, thanks. For some reason searching the repo for snippet and highlight didn't turn that up. But hopefully this issue will feed their search index, and I'll open a new one if needed.

**Comment by fergiemcdowall** [comment]
I actually improved to docs in light of this issue after you opened it :) https://github.com/fergiemcdowall/search-index/commit/1c9d94ac1a8c3f6fecb916f4c8abbd21b5988b47

**Comment by mblakele** [comment]
If you want to improve on that I'd target https://github.com/fergiemcdowall/search-index/search?q=snippet&type=Code&utf8=%E2%9C%93 and https://github.com/fergiemcdowall/search-index/search?utf8=%E2%9C%93&q=highlight&type=Code — both match this issue but don't match https://github.com/fergiemcdowall/search-index/blob/master/doc/search.md#teasers-and-search-term-highlighting

**Comment by mewwts** [comment]
Thanks for the suggestions @mblakele. Don't hesitate coming back with more :+1:
