### ISSUE TITLE
Matcher doesn't work in languages that use Unicode.

### ISSUE THREAD

**Issue by lannka** [fergiemcdowall/search-index#150]
The root cause is in matcher.js:
    H(reverseIndex.createReadStream({
      start: 'TF~*~' + beginsWith,
      end: 'TF~*~' + beginsWith + '~~~'
    }))

The above selector would basically only select prefix of pure ASCII strings. Since all Unicode are behind '~'. After changing '~' to the ''􏿿" (U+10FFFF, the last UTF8), it worked for Chinese characters.

**Comment by fergiemcdowall** [comment]
good point.

would you be able to make a  test case for this with Chinese characters?

**Comment by lannka** [comment]
Created a pull request for the fix: https://github.com/fergiemcdowall/search-index/pull/151

**Comment by fergiemcdowall** [comment]
merged

**Comment by fergiemcdowall** [comment]
This should now be fixed on master

**Comment by fergiemcdowall** [comment]
:+1:
