### ISSUE TITLE
How can I mark my doc ID field unsearchable?

### ISSUE THREAD

**Issue by lannka** [fergiemcdowall/search-index#153]
By default, the ID field is searchable. How can I turn it off? Otherwise the matcher will return those internal doc IDs to end users.

I tried using the opt below, but it throws an exception. Seems the code treats "id" field differently than the others.

var opt = {
  fieldOptions: [{
    fieldName: 'id',
    searchable: false
  }]
};

**Comment by fergiemcdowall** [comment]
Oh- that doesnt work? In that case we have found a bug...

-- 
Apologies for brevity- this message was sent from my mobile

**Comment by lannka** [comment]
It throws an exception when the fieldName is 'id'. It works fine if I change 'id' to other doc fields.

**Comment by lannka** [comment]
I made a test case: https://github.com/fergiemcdowall/search-index/pull/154

**Comment by fergiemcdowall** [comment]
Great- will check it out...

**Comment by fergiemcdowall** [comment]
OK- I just uncommented the the lines making the ID field not searchable so that the tests pass

**Comment by fergiemcdowall** [comment]
Temporary workaround is to rename the ID field to, say "docID" with `searchable: false` and then allow search-index to automatically generate an internal ID

**Comment by lannka** [comment]
Rename ID field doesn't work for my case since I need to manage the ID, and use the ID to update the doc.

**Comment by lannka** [comment]
Have a fix here: https://github.com/fergiemcdowall/search-index/pull/158

**Comment by fergiemcdowall** [comment]
OK- taking a look at the fix now...

**Comment by fergiemcdowall** [comment]
A very elegant fix! Should be merged soon.

**Comment by lannka** [comment]
Hi @fergiemcdowall , I'm not familiar with how npm version works. I thought bumping up the number in package.json would do the trick. But seems not. The version at npm side is still 0.6.4. What step did I miss?

**Comment by fergiemcdowall** [comment]
I just published version 0.6.5 to npm. (Right now, I am the only person that can publish search-index to npm)

**Comment by lannka** [comment]
I see, that's fine. Thanks for doing it.
