### ISSUE TITLE
so not really sure what I am doing wrong here

### ISSUE THREAD

**Issue by leerlemoniii** [fergiemcdowall/search-index#156]
```
shortchange[0] = {};
        shortchange[0].id=changes.doc.id;
        shortchange[0].firstname=changes.doc.firstName;
        shortchange[0].lastname=changes.doc.lastName;
        shortchange[0].middlename=changes.doc.middleName;
si.add({"batchname":"wadol"}, shortchange, function(err){
    if (!err) {
              q.query = {"*": [changes.doc.lastName]};
                si.search (q, function (err, results) {
                    console.log(err);
                    console.log (results);
                  }
              }
}
```
I would think this should return hits as the index part of the code works creating what I think is index files in the wadolsearch folder...  Ad further doing  si.tellMeAboutMySearchIndex says there are 4 (as expected docs)  but the search returns empty.... any clues

**Comment by fergiemcdowall** [comment]
Hmmm, there are no obvious errors in your code- if you only have 4 docs, maybe you can set up a testable [gist](https://gist.github.com/)? That way it can be debugged.

**Comment by leerlemoniii** [comment]
I figured it out... I had errors earlier in the code that was actually creating empty search result in the last name field so thanks for looking...

**Comment by fergiemcdowall** [comment]
Glad you got it working :)
