### ISSUE TITLE
Can I connect it directly to mongo database?

### ISSUE THREAD

**Issue by AlexanderKozhevin** [fergiemcdowall/search-index#161]

**Comment by fergiemcdowall** [comment]
You have to do a query on your MongoDB and then `add` the returned documents into `search-index`. I have done it a few times with CouchDB and it is fairly straight forward

**Comment by mewwts** [comment]
It can also run on top of MongoDOWN, in which case you instantiate search index by
```
var si = require('search-index')({db: require('mongodown')})
```
In this case search index utilizes mongodb as it's database. Hope this helped!
