### ISSUE TITLE
TypeError: Cannot read property 'filter' of undefined

### ISSUE THREAD

**Issue by mblakele** [fergiemcdowall/search-index#164]
I see this error intermittently with 0.6.3 and 0.6.6. I think it's related to node restarting while indexing is in progress. I have a callback on my calls to `search-index.add`, but when this error appears the callback isn't called.

Workaround: I've added hooks to my code to call `search-index.close` on `['SIGINT', 'SIGHUP', 'SIGTERM', 'SIGQUIT']`. However I still seem to see this error occasionally even with graceful shutdown.

```
TypeError: Cannot read property 'filter' of undefined
    at Transaction.<anonymous> (/Users/mblakele/Source/fubar/node_modules/search-index/lib/indexing/deleter.js:51:29)
    at next (/Users/mblakele/Source/fubar/node_modules/search-index/node_modules/level-transactions/node_modules/ginga/index.js:122:24)
    at /Users/mblakele/Source/fubar/node_modules/search-index/node_modules/level-transactions/index.js:125:5
    at dispatchError (/Users/mblakele/Source/fubar/node_modules/search-index/node_modules/levelup/lib/util.js:64:35)
    at /Users/mblakele/Source/fubar/node_modules/search-index/node_modules/levelup/lib/levelup.js:222:14
```

**Comment by fergiemcdowall** [comment]
Hmmm- interesting

Do you have a testable case that we could look at? What does your data look like?

**Comment by mblakele** [comment]
No test case, sorry: it's intermittent. I reindex all content as node is starting up, in a single batch. Node restarts automatically whenever JS files change, so dev instances restart frequently.

Each entry looks like:

```
{
        id: id,
        body: body,
        categories: categories,
        title: title
}
```

The field `categories` is an array of strings. The body is a large markdown string. ID and title are short strings.

**Comment by mblakele** [comment]
For this particular app I can empty the index whenever it goes bad — but right now I have no way to detect that. If this particular error would call my `add` callback, I could work around the problem.

**Comment by fergiemcdowall** [comment]
Does the same data always produce the same bug? Or does it come and go even if the data stays the same?

**Comment by mblakele** [comment]
It can happen without content changes. There are only about 32 entries in the startup batch. I think it's a database integrity problem related to shutdown during index operations. That may mean it's really a leveldown or levelup problem. But I'd like to see search-index surface it in a way that allows application-level recovery, even if that means dropping the index and starting fresh.

As another workaround I've now added a sha1 hash field to each entry, using the `object-hash` npm module. I build a candidate batch, run queries by id to get the sha1 values, and rebuild the batch to only include entries that have changed. This reduces the number of items that need indexing on startup, usually to 0. That should make the exception happen much more rarely.

**Comment by fergiemcdowall** [comment]
Yes, if theres a lot of opening and closing of a `search-index` going on, then leveldown can start to be a bit strange (see https://github.com/Level/leveldown/issues/194 for example).

Glad that you have found a way to mitigate the problem. Maybe generating a new `search-index` every time might also be a workaround?

**Comment by fergiemcdowall** [comment]
PS: If you want, you can send me some code to look at

**Comment by mblakele** [comment]
I agree with everything you've written, and thanks for the leveldown bug reference.

Would you entertain a PR that implements error handling in `deleter.deleteBatch` code in its `done` handler? I recognize that it's a bit odd to do error handling after the transaction supposedly succeeded. But as it stands it's difficult for my code to handle this situation. I have a callback on `si.add` but it's never called. I can't wrap `si.add` with try-catch because the error happens some time after that function call.

**Comment by fergiemcdowall** [comment]
Yes, please do a PR :)

**Comment by mblakele** [comment]
As of 0.6.9 I can't seem to reproduce this anymore. I'll let you know if that changes.

**Comment by fergiemcdowall** [comment]
Thats good. There was a weird instantiation problem with 0.6.8...

**Comment by mewwts** [comment]
I also think we buffed level-versions somewhere in the last couple of weeks.

**Comment by mblakele** [comment]
Turns out this wasn't fixed: a bug in my code was masking it. Reopening, and I have a test case that reproduces the problem reliably on my laptop: https://github.com/mblakele/search-index-164-test-case. This code just inserts the same document rapidly until something fails. On my laptop I see the TypeError deleter within a few seconds.

**Comment by fergiemcdowall** [comment]
Thanks for the test case- I will take a look at it ASAP. If I can reproduce the error, then fixing it should be fairly trivial. BTW what version of node are you on?

**Comment by mblakele** [comment]
```
$ node -v
v2.3.3
```

**Comment by fergiemcdowall** [comment]
OK- test case is breaking for me to, so it should be fixable...

**Comment by mewwts** [comment]
FYI: by increasing the timeout to `100` this issue doesn't appear. Pretty sure hammering search-index with docs to add will break it, so perhaps we need some kind of internal queue, as a reindex needs to calibrate and all that?

**Comment by fergiemcdowall** [comment]
Good point...

**Comment by mblakele** [comment]
@mewwts is that timeout change a potential workaround? If so can you detail the change?

Normally I'm not hammering like this, but in developer mode I hot-reload any changed files as the watch module tells me about them.

**Comment by mewwts** [comment]
Yes, the `setTimeout`. When you do `si.add`, search-index doesn't expect any other add operations before the callback of `si.add` is fired. So my hunch is that when multiple `si.add`s are run concurrently, one add is allowed to run while another is waiting for e.g. the deleter module. Not quite sure how to fix this, but if you want to add a bunch of documents, perhaps consider batching them?

**Comment by mblakele** [comment]
Well, I'm already using batching. But I fire off changes when they happen, and that isn't predictable. That calls for some sort of semaphore or queuing. Ultimately I think that belongs inside search-index, but I may implement something in my code as a work around.

**Comment by mewwts** [comment]
I agree that it ideally should handle unpredictable `add`s. Will give it some thought. If you come up with something please do come back with a comment or PR.

**Comment by fergiemcdowall** [comment]
A bit late here, but https://github.com/mblakele/search-index-164-test-case/pull/1 shows you how to run this script without crashyness.

A constraint of `search-index` at the moment is that documents must be added sequentially. A batch must give a callback before another batch can be indexed.

**Comment by eklem** [comment]
I think maybe [concurrentAdd](https://github.com/fergiemcdowall/search-index/blob/master/docs/API.md#concurrentadd) solves this?
