### ISSUE TITLE
Search breaks on 'some' keyword

### ISSUE THREAD

**Issue by bugs181** [fergiemcdowall/search-index#168]
To elaborate, if the query object only provides the term 'some', it becomes empty.

To reproduce:

    si.add({ batchName: 'testBatch' }, [{ id: 1234, 'name': "some title" }])

Query that breaks:

    var query = 
    { 
	    "query": { 
		     '*': ['some'] 
	    }
    }

Failed Result:

    { query: { '*': [ '' ] },
      hits: [],
      totalHits: 0,
      facets: undefined }
    total hits: 0

Success result for 'title'

    { totalHits: 1,
      query: 
       { query: { '*': [ 'title' ] },
         maxFacetLimit: 100,
         offset: 0,
         pageSize: 100 },
      facets: {},
      facetRanges: undefined,
      hits: 
       [ { id: '1234',
           relevance: [Object],
           score: 10.5,
           document: [Object] } ] }

**Comment by bugs181** [comment]
Now that I think about it, this could be due to 'some' being a stop-word. Like 'the', 'and', etc.

**Comment by fergiemcdowall** [comment]
Yes, instantiate `search-index` with something like

```
var stopwordList = require('stopword').getStopwords().remove('some'); //pseudocode- you need to write your own remove function
var si = require('search-index')({
  stopwords: stopwordList
});
```
