### ISSUE TITLE
Empty backup.gz on running indexgenerator

### ISSUE THREAD

**Issue by eklem** [fergiemcdowall/search-index#175]
I get an empty backup.gz (just the header line) when running [indexgenerator](https://github.com/fergiemcdowall/search-index/blob/master/doc/examples/browserify-replicate-full-index-to-browser/indexgenerator.js). My guess it's the changed si.add API that's causing some problems.

**Comment by fergiemcdowall** [comment]
Hmmm, the recent update to the `add` API possibly broke this...

**Comment by eklem** [comment]
I'll clone and do some testing

**Comment by fergiemcdowall** [comment]
The examples have now been extracted out into their own repositories (links in documentation). They have some limited testing, so they should all be working

**Comment by eklem** [comment]
:+1:
