### ISSUE TITLE
Suggestion for indexing a website

### ISSUE THREAD

**Issue by jacargentina** [fergiemcdowall/search-index#178]
I'm doing the indexing of my website with `simplecrawler`. Which would be your suggested way to *update* the index after first indexing occurs?

I mean, should i maintain the documents? There is some way to *update* those, or simply would it delete and re-add with the refreshed webpages data?

The other option i can think of, is building a new index on an alternative directory, and after it finishes, replace the previous one (so i dont have lo leave the website without search capability at all while crawling it)

Btw, great and useful project!

**Comment by mewwts** [comment]
If you just index the document with the same id, `search-index` will update (read: delete and index and calibrate the index) the document you've added! It can take a bit longer time, since calibration occurs, but nevertheless, I think this would be best!

**Comment by mewwts** [comment]
If the page is quite large and you have to index a lot of documents, I really suggest looking into this example https://github.com/mewwts/search-index-webworker-example, where `search-index` is running in a separate thread in the browser.

**Comment by fergiemcdowall** [comment]
@jacargentina just to clarify- is your app running in node.js, a browser, or something else?

**Comment by jacargentina** [comment]
node.js, keystonejs website ;)
