### ISSUE TITLE
Output of snapshot function doesn't survive HTTP request.

### ISSUE THREAD

**Issue by mewwts** [fergiemcdowall/search-index#184]
I'm doing some mad science where I'm trying to serve a snapshot of the index over HTTP. So this is probably not directly an `si`-problem, but I need to solve this anyways.

Unfortunately, after getting the file, the encoding is messed up, and search is broken! 

This is an example of how a string ends up looking:
```
"*￮￮￮"
```
This it how it's supposed to look: judging by the regular replication example:

```
"*ï¿®ï¿®ï¿®"
```

Any ideas?

**Comment by mewwts** [comment]
This somehow solved itself,

see https://github.com/mewwts/search-index-replicate-over-http-example

**Comment by fergiemcdowall** [comment]
Hmmm- need to keep an eye out for this...
