### ISSUE TITLE
Inconsistent callback argument order

### ISSUE THREAD

**Issue by johnhaley81** [fergiemcdowall/search-index#185]
In of the the library's callbacks the argument order is the node standard `(err, result)` order. Except for 3 methods: `snapShot`, `snapShotBatch`, and `tellMeAboutMySearchIndex`.

Having those methods also conform to this standard I think will help keep the API consistent.

**Comment by fergiemcdowall** [comment]
Indeed it would! Should be fairly easy to fix to

**Comment by fergiemcdowall** [comment]
`tellMeAboutMySearchIndex` is now fixed, `snapShotBatch` is deprecated, and `snapShot` is going to be turned into a streamy, non-callbacky function: #231

**Comment by johnhaley81** [comment]
:+1:

**Comment by johnhaley81** [comment]
This is fantastic! But FYI it was an API breaking change and probably should have been a minor bump instead of bugfix bump.

**Comment by fergiemcdowall** [comment]
Yes, it probably should have been
