### ISSUE TITLE
Make it possible to index from URLs

### ISSUE THREAD

**Issue by fergiemcdowall** [fergiemcdowall/search-index#187]
It would be cool if you could simply send search-index a url to index, and then index directly from the URL

**Comment by eklem** [comment]
That's a nice step towards a server-less search solution. Google, watch out!

**Comment by eklem** [comment]
This could maybe also showcase that if the JSON hasn't changed (header info on file), nothing new is added.

**Comment by eklem** [comment]
@erikperez Here is the stuff you would need for indexing a JSON over HTTP

**Comment by fergiemcdowall** [comment]
Basically we would need to implement some sort of streaming `add` interface

**Comment by fergiemcdowall** [comment]
I see now that although this is cool functionality, it is way out of scope for the core lib

**Comment by eklem** [comment]
Were you thinking of indexing a site, or index from a JSON file as a URL?

**Comment by fergiemcdowall** [comment]
JSON from a URL.

A better way to state the problem is to have the ability to index from streams, since that would solve this case, and some others as well

**Comment by eklem** [comment]
The [`search-index-indexer`](/eklem/search-index-indexer) does this now (not stream), but can only run on the server. But I see that this will be possible in the browser using [`vue`](/vuejs/vue) and [`vue-resource`](/vuejs/vue-resource).
