### ISSUE TITLE
A little unclear and segmented documentation?

### ISSUE THREAD

**Issue by eklem** [fergiemcdowall/search-index#188]
I'm trying to index an array of JSON items and set the filter possibility on one field, but not really sure what I really need since the documentation seems a bit segmented or a bit complex to read.

I have "[Creating search indexes](https://github.com/fergiemcdowall/search-index/blob/master/doc/create.md)" where I see that I can define `options`. I have "[Adding documents to search indexes](https://github.com/fergiemcdowall/search-index/blob/master/doc/add.md) where I have `batchOptions `and `batchOptions.fieldOptions`. Are `options` and `batchOptions` the same? And is it the [API-documentation](https://cdn.rawgit.com/fergiemcdowall/search-index/better_docs/doc/api/module-search-index.html) or the readme-file that is correct when it comes to the order of data and options?

**Comment by fergiemcdowall** [comment]
Garrrgh- yes this could be simpler.

You can set options for when `require`-ing, when `add`-ing, and also per field in a given batch.

Basically `batchOptions` is options on a BATCH level, whereas `fieldOptions` are options on a FIELD level.

You could for example set phrase length to 2 for the whole batch, but extend this to 5 for the title field.

Makes sense?

**Comment by eklem** [comment]
Cool! Makes sense. I'll see if I get it working, and add an example, fitting the test-doc/json.

**Comment by fergiemcdowall** [comment]
Docs should be better now, but please point out and/or submit improvements

**Comment by eklem** [comment]
Thanks! Will do =)

**Comment by eklem** [comment]
Just to be a little naive on this one. Can you define fieldOptions in the general options when you require search-index?
