### ISSUE TITLE
Stop working when updating from 0.5.0 to 0.6.11

### ISSUE THREAD

**Issue by gomezbl** [fergiemcdowall/search-index#189]
Hi, I've recently updated the module from 0.5.0 to last version (0.6.11) and the search functionality of my site has stopped working. I guess that the API has changed, but, what changed exactly to provoke stop working when searching?

Update: after investigation, I've notice that .add method parameters order have changed (in 0.5.0, data was the second, in new version, is in first place). Any document about the changed?

Thanks.

**Comment by eklem** [comment]
I know that the indexing API `si.add` has changed. But searching, I'm guessing it's the switch to a json query language. I'll check a little.

**Comment by eklem** [comment]
Can't seem to find the commit just now, but how does your query syntax/URL look now. Here's the documentation for how it's supposed to be i version 0.6.11. I know this has changed, but don't remember just when.

https://github.com/fergiemcdowall/search-index/blob/master/doc/search.md

**Comment by gomezbl** [comment]
Hi, after changing si.add(...) for the new parameters order, all is woking fine again fortunatelly.

If the documentation is updated, I'll have a look to see the changes and improvements.

Thanks.

**Comment by mewwts** [comment]
Sorry, @gomezbl, but glad you got this to work!

**Comment by gomezbl** [comment]
Thanks you too!, amazing module.
Regards, Rafa.
