### ISSUE TITLE
levelUP module configuration

### ISSUE THREAD

**Issue by michaelmior** [fergiemcdowall/search-index#20]
Would you consider having `search-index` use the `levelup` module directly instead of via `level`? Along with some way to pass configuration options to the constructor, this would allow use of `level-js` so `search-index` would be usable in the browser as well as via Node.js. I'd be willing to work on a patch for this.

**Comment by fergiemcdowall** [comment]
Now fixed, thanks to @anandthakker ! :)

**Comment by eklem** [comment]
Best xmas present in 2014 @fergiemcdowall ?

**Comment by michaelmior** [comment]
Thanks @anandthakker! Sorry I never got around to tackling this myself.

**Comment by fergiemcdowall** [comment]
@eklem yes! :)
