### ISSUE TITLE
Inconsistent documentation for arguments to add() function

### ISSUE THREAD

**Issue by kdumovic** [fergiemcdowall/search-index#201]
`doc/quickstart.md` has options first and data second:
```
si.add(opt, data, function (err) {
  if (err) console.log('oops! ' + err);
  else console.log('success!');
});
```

`doc/add.md` also has options first and data second:
```
//add
si.add(batchOptions, data, function (err) {
  if (!err) console.log('success!');
});
```

But `doc/api/module-search-index.html` suggests that data be passed in first and options second: 
`(inner) add Adds a document to the index(batch, batchOptionsopt, callback)`

And `README.md` has data first and options second:
```
si.add(data, opt, function (err) {
  //add stuff to index
});
```

I tried adding multiple files to the index like below and wasn't actually populating it. I had to reverse the order of the first two arguments.
```
      si.add({}, data, function(err) { // broken code
          if (!err) console.log('success!');
      });
      si.add(data, {}, function(err) { // working code
          if (!err) console.log('success!');
      });
```

**Comment by fergiemcdowall** [comment]
Yes, we recently changed the API for `.add`, the correct order is data first options second:

```javascript
 si.add(data, {}, function(err) { // working code
   if (!err) console.log('success!');
 });
```

Thanks for pointing out that it is still wrong in some parts of the documentation- I will fix it now

**Comment by mewwts** [comment]
Sorry for breaking this for you @kdumovic, but the API is more consistent now.
