### ISSUE TITLE
Filter by distance using some kind of geo search

### ISSUE THREAD

**Issue by fmmsilva** [fergiemcdowall/search-index#205]
Is it possible?

**Comment by fergiemcdowall** [comment]
Yes- you can index the latitude and longitude and then do a 'range filter'. That will give you all results in a geographic 'box'.

**Comment by fmmsilva** [comment]
How? Do you have any examples? Is it also possible to find results on a sphere, for example? Using a radius to find all results that are near some geopoint..?

**Comment by mewwts** [comment]
Index a document with two fields `long` and `lat`. Those two should contain numbers. Then, at querytime, you would have to specify a filter on `long` and `lat`.

Something like:

```
{
  query: {
    '*': ['*']
  },
  filters: {
    'long': [[00012, 00013]],
    'lat': [[00032, 00043]]
  }
}
```
I know the number padding is ugly, but we're trying to fix it :-1:

**Comment by fmmsilva** [comment]
@mewwts thanks, my friend!

**Comment by mewwts** [comment]
Good luck @fmmsilva!
