### ISSUE TITLE
Diff in "bundle" and "bundle install" in rails.. 

### ISSUE THREAD

**Issue by SanjayYadav90** [fergiemcdowall/search-index#206]
Hi ,

As you'll be knowing the we use two command to install gem in a rails application.
one is bundle,
another is bundle install so, 
Can you tell what is the difference between "bundle" and "bundle install".

Regards 
Sanjay

**Comment by fergiemcdowall** [comment]
Hi Sanjay- this makes no sense :) are you commenting on the right project?

**Comment by SanjayYadav90** [comment]
hi @fergiemcdowall ,
its ok but if you know you can tell me about, which is not going to make bad impact on you.

Thanks

**Comment by fergiemcdowall** [comment]
Sorry- I dont really understand the question.
