### ISSUE TITLE
API docs 404

### ISSUE THREAD

**Issue by mblakele** [fergiemcdowall/search-index#207]
https://cdn.rawgit.com/fergiemcdowall/search-index/better_docs/doc/api/module-search-index.html is throwing 404 right now.

```
$ wget -SO - 'https://cdn.rawgit.com/fergiemcdowall/search-index/better_docs/doc/api/module-search-index.html'
--2015-10-09 10:17:45--  https://cdn.rawgit.com/fergiemcdowall/search-index/better_docs/doc/api/module-search-index.html
Resolving cdn.rawgit.com... 198.232.124.74
Connecting to cdn.rawgit.com|198.232.124.74|:443... connected.
HTTP request sent, awaiting response... 
  HTTP/1.1 404 Not Found
  Date: Fri, 09 Oct 2015 17:17:45 GMT
  Content-Type: text/html; charset=UTF-8
  Content-Length: 162
  Connection: keep-alive
  X-Content-Type-Options: nosniff
  X-Robots-Tag: none
  Access-Control-Allow-Origin: *
  Cache-Control: max-age=300
  Last-Modified: Wed, 20 May 2015 18:35:01 GMT
  ETag: W/"a2-14d729b7b76"
  Server: NetDNA-cache/2.2
2015-10-09 10:17:46 ERROR 404: Not Found.
```

**Comment by mewwts** [comment]
Looks like you're trying to find the branch `better_docs`. I'm pretty sure that's deleted by now :8ball:

**Comment by fergiemcdowall** [comment]
Where is this linked from? Does it need to be fixed?

**Comment by mblakele** [comment]
It's linked from https://github.com/fergiemcdowall/search-index/blame/master/README.md#L40

**Comment by eklem** [comment]
The link should maybe be changed to https://cdn.rawgit.com/fergiemcdowall/search-index/master/doc/api/module-search-index.html ? Think I remember this is how it looked when it was actually working. Just a file that has been moved I think.

**Comment by mblakele** [comment]
https://cdn.rawgit.com/fergiemcdowall/search-index/master/doc/api/module-search-index.html :ok:
