### ISSUE TITLE
Memory leaks with large json files

### ISSUE THREAD

**Issue by kdumovic** [fergiemcdowall/search-index#208]
To preface, the json files I'm using aren't really that large. I have 100 of them, ranging in size from 20-300kb, with one or two outliers ~800kb. The entire folder is ~9mb.

Unflattened, each json file has 15 keys. My script takes 7 seconds to process them, uses up to 100mb of memory and outputs an si folder of size ~4mb. If I run my script again without deleting the si folder, it takes 20 seconds, uses up to 300mb of memory and outputs an si folder of size ~13mb. My search-index still only has 100 documents but the index on disk tripled in size. Why is this? Are there not any checks against duplicates?

[Flattened](http://stackoverflow.com/questions/19098797/fastest-way-to-flatten-un-flatten-nested-json-objects), my json files have between 300-3000 keys. My script takes ~100 seconds to process them (the time spent actually flattening is negligible), it starts using ~200mb of memory and increases to around ~1.1gb(!!) before the scripts exits, and outputs an si folder of size ~28mb. If I run my script again without deleting the si folder, it hangs indefinitely, using more and more memory (1.5gb+) until I manually exit.

Could you please shed some light on why this behavior is the way it is? And what is expected? Thank you!

Note: I'm using version 0.6.11 because of breaking changes loading these files with later versions. I'll open another issue about those.

**Comment by fergiemcdowall** [comment]
Hmmm- that sounds like an interesting test case. If you want to DM me your flattened data, I can try to debug the problem.

**Comment by kdumovic** [comment]
Sure, I'd really appreciate that! What's your email?

**Comment by fergiemcdowall** [comment]
fergusmcdowall@gmail.com

**Comment by fergiemcdowall** [comment]
Im going to close this issue since we need some open performance benchmarks to hammer on.
