### ISSUE TITLE
Should work with Tonic

### ISSUE THREAD

**Issue by fergiemcdowall** [fergiemcdowall/search-index#210]
It would be great if this worked: https://tonicdev.com/npm/search-index

**Comment by boucher** [comment]
Hey there, Tonic developer here. Can I ask what isn't working? Maybe we can help.

**Comment by fergiemcdowall** [comment]
Wow- thanks! :)

Something like this _should_ work, but doesn't:

```javascript
var si = require("search-index");
si.add({id: 1, title: "a cool title", body: "bod"}, {}, function (err) {
  if (!err) console.log('success!');
});
```

**Comment by mewwts** [comment]
I get this,
```err: Failed to require LevelDOWN (Cannot find module 'leveldown/package'). Try `npm install leveldown` if it's missing```, 
when writing this: ```require("search-index")()```, @boucher.

**Comment by boucher** [comment]
Ok, we'll take a look and see what's going on.

**Comment by boucher** [comment]
I think the problem is that leveldown is declared as a devDependency of levelup, and right now we aren't installing dev dependencies. We're thinking about changing that, but in the meantime I'll see what else we might be able to do here.

**Comment by mewwts** [comment]
Woops. It might be that leveldown should be a dependency actually. Thanks @boucher!

**Comment by fergiemcdowall** [comment]
Leveldown _seems_ to be in the normal `dependencies` stanza. I wonder if leveldown works on Tonic at all...? (it sometimes needs some shimmying)

@boucher - what is the best way to test and debug on tonic? Is there a way to test a new module version on Tonic without having to deploy a new module version to npm?

**Comment by boucher** [comment]
Leveldown is in *your* dependencies, but it's in *levelup*'s `devDependencies` block, and it's in levelup that the leveldown require is failing. 

We don't have a fantastic way to test unpushed packages yet. What you could do is something that downloads the files (from e.g. github, or dropbox) and then tries to require them. Obviously we'd like to do something better.

**Comment by tolmasky** [comment]
So what's going on here if I'm not mistaken is that level up is just "inheriting" level down from your dependency:

```
you/node_modules/leveldown
                               levelup
```

The search path here includes you/node_modules, so even though its a devDependency of levelup, it set your inclusion. Our system currently doesn't handle this but will very shortly, so I think this should fix itself in about a week,

**Comment by fergiemcdowall** [comment]
There are a few ways to get this to work and none of them are particularly elegant. Going to close this issue for now, and if there is any further interest in getting `search-index` to work on Runkit (as Tonic is now called), then we can take it from there.
