### ISSUE TITLE
Boolean search and advanced search

### ISSUE THREAD

**Issue by fmmsilva** [fergiemcdowall/search-index#212]
Is it possible to do boolean search or any other type of advanced search?

Example: 'car and bike', 'car -bike', 'truck or airplane'

**Comment by eklem** [comment]
Hi @fmmsilva ! It's in the planning, but not implemented yet.
Feature-issues for [OR-queries](https://github.com/fergiemcdowall/search-index/issues/99) and [NOT-queries](https://github.com/fergiemcdowall/search-index/issues/104)

Feel free to add your comments on what you need and want!

**Comment by eklem** [comment]
And AND is the default query type.

**Comment by fmmsilva** [comment]
Thanks eklem!

**Comment by eklem** [comment]
No problem, glad I could help!
