### ISSUE TITLE
What am I doing wrong?

### ISSUE THREAD

**Issue by fmmsilva** [fergiemcdowall/search-index#213]
This is my code:

```js
var q = {
    query : {
        '*': ['dor']
    }
}
si.search(q, function (err, searchResults) {
    console.log(searchResults)
});
```

I have 53589 docs in my index and some of them contains the word 'dor'.
I got the following result (no document found):

```js
{ totalHits: 0,
  totalDocsInIndex: 53589,
  documentFrequencies: { '*￮dor': 0 },
  fieldWeight: { '*￮dor': 1 },
  query: 
   { query: { '*': [Object] },
     maxFacetLimit: 100,
     offset: 0,
     pageSize: 100 },
  facets: {},
  facetRanges: undefined,
  hits: [] }
```

**Comment by fergiemcdowall** [comment]
Hi @fmmsilva 

It seems to be an indexing issue: `documentFrequencies: { '*￮dor': 0 }` means that there are no documents in the index that contain "dor"

This works for me:

```javascript
var si = require('search-index')({});
var doc = {title: 'this is a dor', body: 'a really interesting body'};

si.add(doc, {}, function(err){
  if (!err) console.log('success!');
  var q = {
    query : {
      '*': ['dor']
    }
  }
  si.search(q, function (err, searchResults) {
    console.log(searchResults)
  });
});
```

If you dont make any headway- make a small script that recreates the problem, and I can fix it for you

F

**Comment by fmmsilva** [comment]
I got the following message when adding items to index:

{"name":"search-index","hostname":"MacBook.local","pid":12761,"component":"indexer","level":40,"err":{"message":"Key not found in database [DOCUMENT-COUNT]","name":"NotFoundError","stack":"NotFoundError: Key not found in database [DOCUMENT-COUNT]\n    at /Users/fmmsilva/repos/test/node_modules/search-index/node_modules/levelup/lib/levelup.js:217:15"},"msg":"Key not found in database [DOCUMENT-COUNT]","time":"2015-10-24T19:56:53.987Z","v":0}

**Comment by fmmsilva** [comment]
There is a way to list all the docs inside the index?

**Comment by fmmsilva** [comment]
I am using the following options and getting the documents from a MySQL database:

```js
var si = require('search-index')({
    deletable: true,
    indexPath: 'data/index',
    logLevel: 'info',
    fieldsToStore: 'all'
});
```

**Comment by fergiemcdowall** [comment]
Hmmm- Ive never seen that error before

If you could make a testable case (1 script that tries to add data, and then fails), I can fix it for you

**Comment by fmmsilva** [comment]
Ok.. Just a second...

**Comment by fmmsilva** [comment]
It seems to work without mysql connection... crazy!

**Comment by fmmsilva** [comment]
Now I got the following error: **[Error: Malformed document]**
```js
[ { id: 999,
    name: 'PEGINTRON 222 MCG PO LIOF INJ CT FA VD INC + AMP DIL X 0,7 ML' },
  { id: 1000,
    name: 'PEGINTRON 296 MCG PO LIOF INJ CT 4 FA VD INC + 4 AMP DIL X 0,7 ML ' } ]
```

**Comment by fergiemcdowall** [comment]
Glad you got it working :) The batch above is definitely OK. The [Error: Malformed document] is being thrown by something else.

**Comment by fmmsilva** [comment]
Thanks for your help!! Do you have any plans for implementing OR search? I tried to simulate mixing matchers but it's not performing very well..

**Comment by fergiemcdowall** [comment]
Yes, OR search is going to be implemented. Its something that a lot of people ask for, it opens up a lot of possibilities, and it shouldnt be too difficult.
