### ISSUE TITLE
API-reference link gives a 404

### ISSUE THREAD

**Issue by eklem** [fergiemcdowall/search-index#214]
In the `README.md` the last link points no where:
https://cdn.rawgit.com/fergiemcdowall/search-index/better_docs/doc/api/module-search-index.html

**Comment by mblakele** [comment]
Duplicate of #207

**Comment by fergiemcdowall** [comment]
This a dirty hack that uses a 3rd party service (rawgit) to make the generated API docs render as HTML.

I think the solution is simply to make API docs by hand for the time being

**Comment by eklem** [comment]
Think it's just the better-doc folder that's been thrashed, so link needs to be changed. Check #207
