### ISSUE TITLE
Filter overview in the documentation?

### ISSUE THREAD

**Issue by eklem** [fergiemcdowall/search-index#215]
I'm not quite understanding how to define facets/filters anymore. It's good that every small part has it's own documentation, but I'm not able to see the big picture. So I have 4 fields that I want to filter on, can I set that up in the options-line at the top of my code, or do I add that at the si.add-part?

**Comment by fergiemcdowall** [comment]
Oh wow- filters are really badly explained. That definitely needs to be improved

**Comment by eklem** [comment]
Before you listed fields to filter on like this:
```
   "filters":[
      "categories",
      "types",
      "tags"
   ],
```
And now ... ? Specify it in the config for a specific field?

**Comment by eklem** [comment]
Like this, maybe?
```
var batchOptions = {};
batchOptions.fieldOptions = [
  {fieldName: 'categories', filter: true},
  {fieldName: 'types', filter: true},
  {fieldName: 'tags', filter: true},
  ...
];
```

**Comment by fergiemcdowall** [comment]
yes

**Comment by eklem** [comment]
I'll add it to the documentation tomorrow!

**Comment by eklem** [comment]
Is it possible to also define sorting type in the query JSON?

https://github.com/fergiemcdowall/search-index/blob/master/lib/search/searcher.js#L76-L81

**Comment by eklem** [comment]
A bit ambiguous wording there. I'm thinking of type of sorting on the filters listed.

**Comment by fergiemcdowall** [comment]
Hi Espen! What you mean by type sorting on filters?

**Comment by eklem** [comment]
Filter-sorting. Standard is the ones with the most hits first, but I was hoping to sort the filters alphabetically, and found that piece of code that seemed like solving that (check the link)

**Comment by fergiemcdowall** [comment]
Ah, yes you can do something like this:

```javascript
      var q = {};
      q.query = {'*': ['africa', 'bank']};
      q.facets = {
        totalamt: {sort: 'keyDesc'},
        mjtheme: {
          sort: 'keyAsc',
          ranges: [
              [
                'A',
                'J'
              ],
              [
                'K',
                'Z'
              ]
          ]
        }
      };
```

here the `totalamt`facet is sorted by `keyDesc` (key descending, in this scenario: highest numbers first) and `mjtheme` is sorted by `keyAsc` (key ascending, sort alphabetically). You can also use `valueAsc` and `valueDesc`

**Comment by fergiemcdowall** [comment]
There are two `facet-test.js` files that contain examples

**Comment by eklem** [comment]
Thanks!
