### ISSUE TITLE
levelup raised error

### ISSUE THREAD

**Issue by larsvoigt** [fergiemcdowall/search-index#216]
Search index works fine and all my test cases pass. 
But new is levelup raised this error
```
  {
    "name": "search-index",
    "hostname": "ubuntu",
    "pid": 11913,
    "component": "indexer",
    "level": 40,
    "err": {
      "message": "Key not found in database [DOCUMENT-COUNT]",
      "name": "NotFoundError",
      "stack": "NotFoundError: Key not found in database [DOCUMENT-COUNT]
     **/node_modules/search-index/node_modules/levelup/lib/levelup.js:217:15"
    },
    "msg": "Key not found in database [DOCUMENT-COUNT]",
    "time": "2015-10-27T13:45:37.642Z",
    "v": 0
  }
```

Can this be ignored?  How can I switch off this error ?
Thanks

**Comment by larsvoigt** [comment]
see also here https://travis-ci.org/larsvoigt/epub-full-text-search#L292

**Comment by larsvoigt** [comment]
I had set the `logLevel` to `warn` so search-index report me, I think, "internal" information.
Search-Index works fine for me :+1: . So the default `logLevel=error` should  be enough.

**Comment by fergiemcdowall** [comment]
Good! :)
