### ISSUE TITLE
Filters not precise enough?

### ISSUE THREAD

**Issue by eklem** [fergiemcdowall/search-index#219]
I have a facet called `type` that contain, among others, the filters `me` and `method`. If I filter on `me` I also get the results of the `method` filter. I guess this is the range-stuff that kicks in. The filter-part of the URL looks like this:

```
"filter":{"types":[["me","me"]]}
```
I guess I've found a glitch. I would like to only filter on the filter exactly equal to `me`. Do we have a solution for this now, or do we need to figure out how to solve it?

**Comment by fergiemcdowall** [comment]
So 

```javascript
"filter":{"types":[["me","me"]]}
```

gives the same result as
```javascript
"filter":{"types":[["me","me"]], "method":[["me","me"]]}
```
?

Maybe you can post a test case or PM me what you have and I can debug it?

**Comment by eklem** [comment]
I'll test a little and give you a testcase!

**Comment by eklem** [comment]
Just to explain a bit more. The facet `type` has several filters, among them, both `method` and `me`. The second image shows the search filtered on `me`. That should give only one result, but you get 13 (12 for `method` and one for `me`). I'll PM some JSON.

![screen shot 2015-11-05 at 10 45 40](https://cloud.githubusercontent.com/assets/236656/10965011/7b2e50a0-83aa-11e5-887d-b4d1f33a7a1b.png)

![screen shot 2015-11-05 at 10 44 19](https://cloud.githubusercontent.com/assets/236656/10965013/8149c546-83aa-11e5-8b2a-e69e46f45f19.png)

**Comment by eklem** [comment]
But if I do:
```
"filter":{"types":[["me","me"],["method","method"]]}
```
I get only the results from the method-filter. I have one result with the `me`-filter, and 12 with `method`-filter, and they do not overlap.
![screen shot 2015-11-05 at 15 13 44](https://cloud.githubusercontent.com/assets/236656/10970617/2ffe033e-83d0-11e5-8b1b-9e132ace6a4f.png)

**Comment by fergiemcdowall** [comment]
Hmm- it _should_ work

**Comment by eklem** [comment]
I'll make a test case for you when I get this bug working: [Facets/filters not working](https://github.com/fergiemcdowall/norch-angular-app/issues/15)

**Comment by fergiemcdowall** [comment]
I just rewrote all of the logic for this, so it _should_ work now.

Im going to take a chance and close this bug- please reopen if the problem crops up again...
