### ISSUE TITLE
searcher doesn't seem to work with nGramLength 2 or more

### ISSUE THREAD

**Issue by eklem** [fergiemcdowall/search-index#220]
I'm testing nGramLenght 2, and the matcher works quite well, giving me autocomplete on phrases, but I get no search results. Do we have tests for this or is it a bug?

Anyway, for nGramLength 2 or more: matcher works, searcher not.

**Comment by fergiemcdowall** [comment]
Just a hunch- does it work with `nGramLength:[1, 2]`?

**Comment by eklem** [comment]
Ihaa, that works! And looking good =)
![screen shot 2015-11-05 at 11 03 53](https://cloud.githubusercontent.com/assets/236656/10965397/f966b1d6-83ac-11e5-8f8b-29aa3d8b13a3.png)

**Comment by eklem** [comment]
I'll add to the documentation.

**Comment by eklem** [comment]
Fixed with https://github.com/fergiemcdowall/search-index/commit/06d571d07320fb76f32c13d331ae4cce59812004

**Comment by mewwts** [comment]
:+1:

**Comment by eklem** [comment]
And it's a thing of beauty!
![screen shot 2015-11-05 at 14 40 06](https://cloud.githubusercontent.com/assets/236656/10969865/32ab8106-83cb-11e5-8151-9ce90b53d0c7.png)

**Comment by fergiemcdowall** [comment]
Wow- looks great! :)

**Comment by mewwts** [comment]
^ !!!
