### ISSUE TITLE
Searching a phrase

### ISSUE THREAD

**Issue by jbayard64** [fergiemcdowall/search-index#221]
I try ti search a phrase and i use 
> q.query = {
>   'title': ['Test Michel']
> }

But the searchResults return 0 hit.
When i search 
> q.query = {
>   'title': ['Test', 'Michel']
> }

it find one hit.
The title of the founded document is "Test Michel (fête)".
I don't understand why my first search doesn't work. Is there a error un my syntax ?
PS : the results are the same when i use '*' instead of "title", to search across all fields

Question : can we use a wildcard (like *) in the word to search ?

**Comment by eklem** [comment]
I think you need to split up your queries into single words. At least if you've set the nGramLengt to 1 when indexing. If you increase the nGramLength to this, I think you will get a result for:
```
q.query = {
'title': ['Test Michel']
}
```

Check [this solved/closed issue for a bit more on nGramLength](https://github.com/fergiemcdowall/search-index/issues/220), and [the updated docs on nGramLength](https://github.com/fergiemcdowall/search-index/blob/master/doc/add.md#ngramlength).

**Comment by jbayard64** [comment]
Thanks for your answer.
I had forgotten this parameter, and now it works well.
But I have to rebuild all the index after changing nGramLength. Is it necessary to del then add each document, or is there a function to re-index existing documents in index ?

What's the impact to use nGramLength:[1, 2, 3, 4]  rather than a single value ? The search is more flexible bu,t the index is it bigger, or/and is the response time affected?

**Comment by eklem** [comment]
`search-index` updates an entry if the ID already exists in the index. This is done by deleting the existing one and then adding it. If you don't generate your entries ID's , then `search-index` will do it for you, but I'm not sure how that one works, and then I don't know if you'll get the same ID's.

I'm only guessing, but think that both size of index and query result speed is affected negatively. Any input on both the ID generating done by search-index and how size/speed is affected @fergiemcdowall ?

**Comment by eklem** [comment]
Just testing a small index here:
```nGramLength: 1```
gives me an index size of 960 KB

```nGramLength: [1, 2]```
gives me and index size of 1,7 MB

```nGramLength: [1, 2, 3, 4]```
gives me an index size of 3,1 MB

**Comment by fergiemcdowall** [comment]
@jbayard64 Generating a greater amount of ngram lengths increases the size of the index, which will in theory make things slightly less fast.

Simply re-adding the document with the alternative ngram length should be enough to ensure that everything is updated (caveat: if you set your index to nondeletable, then you must destroy the index and start from scratch). It is in any case faster to destroy the index and rebuild from scratch.

**Comment by eklem** [comment]
Don't hesitate if you have more questions, @jbayard64 !
Closing this since we've seemd to figure out the issue, but feel free add another comment if you still wonder about something here.

**Comment by jbayard64** [comment]
Thank you very much for your accurate answers.
After some tests, I prefer to keep the smallest index with nGramLength: 1, because I expect tens of thousands of documents.
For search, I did a split('') on the searched words, which expanded the results.
