### ISSUE TITLE
Setting field weight only at batch level?

### ISSUE THREAD

**Issue by eklem** [fergiemcdowall/search-index#222]
Is the [field weight](https://github.com/fergiemcdowall/search-index/blob/master/doc/add.md#default-field-options) only possible to set at a batch level when indexing? I wanted to weight fields a bit more for some documents, but not others. Same batch, same type of docs. Should I then create different batches, or is there a smoother, more elegant way?

**Comment by fergiemcdowall** [comment]
Yes, I think you can do this at batch (and therefore document) level

**Comment by fergiemcdowall** [comment]
in other words: you _should_ be able to do this at batch level

**Comment by eklem** [comment]
Setting it at a batch-level works! But if I want to set it differently for one item in a batch with several items, is that possible also?

**Comment by fergiemcdowall** [comment]
To do that you would need to have a separate batch that just contains that one document.

**Comment by eklem** [comment]
Yep, that was the solution I picked. A bit cumbersome, but an okay workaround. And thinking of it, it shouldn't be solved with setting a field weight at document level. Maybe a best bet module at query side would be a better match for this issue.

**Comment by fergiemcdowall** [comment]
It should be possible to set boosts, but its been a while since I looked at it. Will have another look at how best to do boosting and "best bets" at a document level.

**Comment by eklem** [comment]
boosting at query time is a good solution, and it will solve many use cases. And no need to re-index to change relevance stuff slightly.
