### ISSUE TITLE
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory

### ISSUE THREAD

**Issue by eklem** [fergiemcdowall/search-index#225]
Calling the indexer with a batch of 300 items, and it errors after a while. Memory leak? Uses 1,5 GB approximately, before crashing. The machine has plenty more.

```
<--- Last few GCs --->

   18347 ms: Scavenge 1398.2 (1456.8) -> 1398.2 (1456.8) MB, 2.7 / 0 ms (+ 2.1 ms in 1 steps since last GC) [allocation failure] [incremental marking delaying mark-sweep].
   19185 ms: Mark-sweep 1398.2 (1456.8) -> 1397.9 (1456.8) MB, 838.5 / 0 ms (+ 3.1 ms in 2 steps since start of marking, biggest step 2.1 ms) [last resort gc].
   20019 ms: Mark-sweep 1397.9 (1456.8) -> 1397.5 (1456.8) MB, 833.6 / 0 ms [last resort gc].


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x1f38d1844a49 <JS Object>
    1: /* anonymous */(aka /* anonymous */) [/Users/eklem/node_modules/search-index/lib/indexing/indexer.js:125] [pc=0xec03b7afde3] (this=0x1f38d1804139 <undefined>,filterKey=0x1f38d183cd31 <String[1]: m>)
    2: arguments adaptor frame: 3->1
    3: /* anonymous */(aka /* anonymous */) [/Users/eklem/node_modules/lodash/index.js:3049] [pc=0xec03b79b55d] (this=0x1f38d1804139 <undefined>,collectio...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
Abort trap: 6
```

**Comment by eklem** [comment]
Saw something about memory leaks when console logging, so set logSilent to true. Same problem.

**Comment by fergiemcdowall** [comment]
Hi @eklem - 300 docs should be well within what `search-index` can manage (the test suite uses a batch of 1000 articles). Can you set up a test case for your data? If so I can take a look at it for you.

There seem to be a lot of memory issues popping up at the moment- I wonder if this is due to the code, of if people are just using it more seriously..?

**Comment by eklem** [comment]
Think it's maybe Node that's messing with us, but not sure. I'll set up a test case tomorrow!

**Comment by eklem** [comment]
Hehe, worked a lot to get my modules easy installable (dependencies, etc), and now everything just works =) Will open it again if more problems!

**Comment by eklem** [comment]
Still getting it, need to run it several times before it happens
```
{"name":"search-index","hostname":"Oles-MacBook-Pro.local","pid":15180,"component":"indexer","level":30,"msg":"indexing pWbOI","time":"2015-12-07T11:29:01.655Z","v":0}

<--- Last few GCs --->

  107463 ms: Mark-sweep 1381.4 (1456.8) -> 1388.6 (1456.8) MB, 1126.8 / 9 ms [allocation failure] [GC in old space requested].
  108659 ms: Mark-sweep 1388.6 (1456.8) -> 1388.6 (1456.8) MB, 1196.0 / 9 ms [allocation failure] [GC in old space requested].
  109816 ms: Mark-sweep 1388.6 (1456.8) -> 1370.2 (1456.8) MB, 1156.9 / 9 ms [last resort gc].
  110884 ms: Mark-sweep 1370.2 (1456.8) -> 1381.0 (1456.8) MB, 1068.4 / 8 ms [last resort gc].


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x3c3c6e344a49 <JS Object>
    1: getOptions [/Users/eklem/github_modules/search-index-indexer/node_modules/levelup/lib/util.js:~20] [pc=0x35af63babeb5] (this=0x3a164d9da2f9 <an Object with map 0x123ef8f5da19>,options=0x139db8004101 <JS Function (SharedFunctionInfo 0x2d3db8c463e9)>)
    2: get [/Users/eklem/github_modules/search-index-indexer/node_modules/levelup/lib/levelup.js:~196] [pc=0x35af63baa163] (this=0xd637cf981...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
Abort trap: 6
```
Clone this one, `npm install` and `node index.js` to test:
`git@github.com:eklem/search-index-indexer.git`

**Comment by fergiemcdowall** [comment]
@eklem if you have any test cases kicking around they would be much appreciated :)

**Comment by eklem** [comment]
This one: [search-index-indexer](https://github.com/eklem/search-index-indexer). Not sure if I got the config for facets/filters right though.

**Comment by fergiemcdowall** [comment]
I just clone that repo and then run `node index.js` n'cest pas?

**Comment by eklem** [comment]
Yepp! Stil got that error. Manage to avoid by indexing fewer and setting nGramLength go [1,2] and not [1,2,3,4].

**Comment by eklem** [comment]
To test it with the `search-index-indexer` , you need to switch to the big JSON file. There are two in the repo. And also correct the two paths (one path for JSON file, and one for config).

**Comment by eklem** [comment]
This now work! :tada:

**Comment by eklem** [comment]
And memory usage is down to at least 1/3 of what it was before.
