### ISSUE TITLE
[question / bug] Adding documents to the index without recreating index

### ISSUE THREAD

**Issue by mike182uk** [fergiemcdowall/search-index#226]
Hey,

I was having a play around with this to see if it would fit a use case on a project i am working on. I want to be able to add, update and delete documents in the index without having to recreate the whole index each time. I have the following code:

```js
var si = require('search-index')({
    indexPath: './test',
    logLevel: 'debug'
});

function addDoc(doc) {
    return new Promise(function (resolve, reject) {
       si.add(doc, function (err) {
           if (err) return reject(err);

           resolve(doc);
       });
    });
}

var doc1 = { title: 'doc 1', id: 'doc-1' };
var doc2 = { title: 'doc 2', id: 'doc-2' };
var doc3 = { title: 'doc 3', id: 'doc-3' };

Promise.all([
    addDoc(doc1),
    addDoc(doc2),
    addDoc(doc3)
]).then(function () {
    si.search({ query: { '*': ['doc'] }}, function (err, results) {
        console.log(results);
    });
}).catch(function (err) {
    console.log(err)
});
```

I would expect `search` to find 3 matching documents and report that there are 3 documents in the index. It actually reports that there is 1 document in the index and returns this as a match. This is the last document that was added (`doc-3`). It almost like each `add` is truncating the contents of the index. This was the log output on a fresh run with no pre-existing db:

```
[2015-12-01T16:08:16.692Z]  WARN: search-index/indexer/25573 on mikes-mbp: Key not found in database [DOCUMENT-COUNT]
    NotFoundError: Key not found in database [DOCUMENT-COUNT]
        at /Users/mike/code/search-index-test/node_modules/search-index/node_modules/levelup/lib/levelup.js:217:15
[2015-12-01T16:08:16.695Z]  INFO: search-index/indexer/25573 on mikes-mbp: indexing doc-1
[2015-12-01T16:08:16.703Z]  WARN: search-index/indexer/25573 on mikes-mbp: Key not found in database [DOCUMENT-COUNT]
    NotFoundError: Key not found in database [DOCUMENT-COUNT]
        at /Users/mike/code/search-index-test/node_modules/search-index/node_modules/levelup/lib/levelup.js:217:15
[2015-12-01T16:08:16.703Z]  INFO: search-index/indexer/25573 on mikes-mbp: indexing doc-2
[2015-12-01T16:08:16.706Z]  WARN: search-index/indexer/25573 on mikes-mbp: Key not found in database [DOCUMENT-COUNT]
    NotFoundError: Key not found in database [DOCUMENT-COUNT]
        at /Users/mike/code/search-index-test/node_modules/search-index/node_modules/levelup/lib/levelup.js:217:15
[2015-12-01T16:08:16.706Z]  INFO: search-index/indexer/25573 on mikes-mbp: indexing doc-3
[2015-12-01T16:08:16.713Z]  INFO: search-index/indexer/25573 on mikes-mbp: batch indexed!
[2015-12-01T16:08:16.714Z]  INFO: search-index/indexer/25573 on mikes-mbp: batch indexed!
[2015-12-01T16:08:16.714Z]  INFO: search-index/indexer/25573 on mikes-mbp: batch indexed!
[2015-12-01T16:08:16.715Z]  INFO: search-index/searcher/25573 on mikes-mbp: {"query":{"*":["doc"]},"maxFacetLimit":100,"offset":0,"pageSize":100}
```

and this was the result of the `console.log(results)`:

```
{ totalHits: 1,
  totalDocsInIndex: 1,
  documentFrequencies: { '*￮doc': 1 },
  fieldWeight: { '*￮doc': 1 },
  query:
   { query: { '*': [Object] },
     maxFacetLimit: 100,
     offset: 0,
     pageSize: 100 },
  facets: {},
  facetRanges: undefined,
  hits:
   [ { id: 'doc-3',
       tf: [Object],
       score: 0.545144315135374,
       document: [Object] } ] }
```

As a test, i ran the script 3 times, each time adding just 1 document at a time, and this had the desired behaviour of appending documents to the index.

So i guess my question is, have i misunderstood how this works?

**Comment by mike182uk** [comment]
Hmm, i've just downgraded to `0.6.11`, run the same script, and i' am getting the expected results:

```
{ totalHits: 3,
  query:
   { query: { '*': [Object] },
     maxFacetLimit: 100,
     offset: 0,
     pageSize: 100 },
  facets: {},
  facetRanges: undefined,
  hits:
   [ { id: 'doc-3',
       relevance: [Object],
       score: 21,
       document: [Object] },
     { id: 'doc-2',
       relevance: [Object],
       score: 21,
       document: [Object] },
     { id: 'doc-1',
       relevance: [Object],
       score: 21,
       document: [Object] } ] }
```

and this is the log output

```
[2015-12-01T16:30:35.700Z]  INFO: search-index/calibrater/43147 on mikes-mbp: Index is empty or not calibrated
[2015-12-01T16:30:35.710Z]  INFO: search-index/indexer/43147 on mikes-mbp: indexing doc-1
[2015-12-01T16:30:35.725Z]  INFO: search-index/indexer/43147 on mikes-mbp: indexing doc-2
[2015-12-01T16:30:35.733Z]  INFO: search-index/indexer/43147 on mikes-mbp: indexed Batch at 2015-12-01T16:30:35.671Z
[2015-12-01T16:30:35.736Z]  INFO: search-index/indexer/43147 on mikes-mbp: indexing doc-3
[2015-12-01T16:30:35.738Z]  INFO: search-index/indexer/43147 on mikes-mbp: indexed Batch at 2015-12-01T16:30:35.688Z
[2015-12-01T16:30:35.741Z]  INFO: search-index/indexer/43147 on mikes-mbp: indexed Batch at 2015-12-01T16:30:35.693Z
[2015-12-01T16:30:35.742Z]  INFO: search-index/searcher/43147 on mikes-mbp: {"query":{"*":["doc"]},"maxFacetLimit":100,"offset":0,"pageSize":100}
```

could this be a regression in newer versions of the package `>0.6.11`?

**Comment by fergiemcdowall** [comment]
Hi @mike182uk, I suspect that the problem is here:

```javascript
Promise.all([
    addDoc(doc1),    // <- each addDoc returns a callback
    addDoc(doc2),
    addDoc(doc3)
])
```

I havent used Promises a great deal, but I think that since addDoc isn't promisey and just returns a vanilla callback, `Promises.all` is simply initiating three `addDoc` functions and then jumping out of `Promise.all` before they have completed. AddDoc could be a little faster in 0.6.11 and that is why the code works when you downgrade.

Another approach would be to index a batch of documents like so:

```javascript
var doc1 = { title: 'doc 1', id: 'doc-1' };
var doc2 = { title: 'doc 2', id: 'doc-2' };
var doc3 = { title: 'doc 3', id: 'doc-3' };
var batch = [doc1, doc2, doc3]           // <- index this instead
                                         // (has the advantage that the index must only be recalibrated once)
```

Support for Promises should definitely be built in to `search-index`

**Comment by mike182uk** [comment]
Thanks for taking a look @fergiemcdowall. The `addDoc` function is my function and it wraps `si.add` in a promise. When the callback of `si.add` is fired the promise is resolved. `Promise.all` resolves each `addDoc` promise sequentially, then once all of the promises have been resolved (all `si.add` callbacks have been fired) we query using `si.search`. This should mean that a race condition is not occurring. I also tested sleeping inside the `addDoc` function for 2 secs (`require('sleep').sleep(2)`) and still got the same result.

In my use case i want to be able to add to an index after it has been initialised (so initially batch add a bunch of documents, then sometime in the future add new documents, without having to re-add every single document to the index again)

**Comment by aenario** [comment]
Hi @mike182uk, from what I have seen of the code, search-index doesnt support parallel adding. 

If we ignore promises, your code is equivalent 
```javascript
var i=0;
si.add(doc1, function(){if(++i==2) callback()}
si.add(doc2, function(){if(++i==2) callback()}
```

which will trigger the following action in search-index
```
doc1 GET RI/doc = []
doc2 GET RI/doc = []
doc1 PUT RI/doc = [doc1]
doc2 PUT RI/doc = [doc2]
```
So at the end, RI/doc = [doc2], and doc1 is lost.

You can either use a lock mechanism so only one add is executed at the time, (ie. change your addDoc to
 ``` 
waitLock().then(new Promise(){...}
```
or, as @fergiemcdowall proposed, use the batch mechanism from search-index.

**Comment by mike182uk** [comment]
Hey @aenario, that makes sense. For some reason i was thinking `Promise.all` resolved the promises sequentially, but it does not. I'll give the batching method a shot, or resolving the promises sequentially correctly :smile: . Thanks for your help @aenario @fergiemcdowall
