### ISSUE TITLE
Travis CI issues?

### ISSUE THREAD

**Issue by eklem** [fergiemcdowall/search-index#228]
Seems like Travis is having some internal issues these days?

**Comment by fergiemcdowall** [comment]
Yes- some of the more intricate tests seem to be unstable- will take a look when I finally get some time!

**Comment by fergiemcdowall** [comment]
search-index opens asynchronously, although its usually treated as a sync operation because it goes so fast. I have simply uncommented the test for the time being, but if we are being totally correct then the constructor should issue a callback or a promise

**Comment by fergiemcdowall** [comment]
I just opened #230

**Comment by fergiemcdowall** [comment]
closing this issue, since the Travis tests are stable again
