### ISSUE TITLE
Add Travis CI tests for v.5.3.0 (stable)

### ISSUE THREAD

**Issue by eklem** [fergiemcdowall/search-index#229]
v.5.3.0 is defined as a stable version 5. Should we add it to Travis CI tests?
https://nodejs.org/en/

**Comment by fergiemcdowall** [comment]
Yes, and we should also probably make the tests more stable- the newer versions of node seem to be throwing up some bugs in the test suite.

**Comment by eklem** [comment]
Cool =)

**Comment by fergiemcdowall** [comment]
Oooooh- not only does it pass in node 5, it actually runs a lot quicker ****happy hands****
