### ISSUE TITLE
Problem when search with ["my", "way"]

### ISSUE THREAD

**Issue by tunghoang91** [fergiemcdowall/search-index#232]
I tried query like bellow.

```
si.search({"query": {"*":["my", "way"]}}, function(err, results) {

      console.log('total hits: ' + results.totalHits);

      console.log(results);

    });

```
And result display on screen:
```

{ query: { '*': [ '' ] },

  hits: [],

  totalHits: 0,

  facets: undefined }

total hits: 0
```
You can see the query be ['']. I don't know why?
I try example at here: https://github.com/fergiemcdowall/search-index-simple-node-js-example
And it have same problem.

Thanks!

**Comment by fergiemcdowall** [comment]
Hmmm- I cant reproduce that behaviour at all, can you make a test case?

FYI- if you look in the 'test' folder, you will see a lot of examples to get you started.

**Comment by tunghoang91** [comment]
Sorry guy, the words "my" and "way" in the english-stop words collections. and then remove it in query.
Thanks :)

**Comment by eklem** [comment]
Nice you figured it out @tunghoang91! Don't hesitate to create another issue if you have a question or possible bug.

**Comment by mewwts** [comment]
:+1:

**Comment by fergiemcdowall** [comment]
@tunghoang91 so THATS what happens if you only search for stopwords :)
