### ISSUE TITLE
Can't seem to get results when searching for indexed text

### ISSUE THREAD

**Issue by joshterrill** [fergiemcdowall/search-index#234]
I'm trying to write something where I can upload a document, grab the text out of the document and store the text (and filename and mimetype) in search-index.

I've stored a document just fine, but when I go to search through text in it, nothing seems to ever come up.

So when I put wildcards (`*`) in both the search fields, I get the document that I have stored in the database:

```
app.post('/search', function(req, res) {
    var q = {};
    q.query = {
      '*': ['*']
    };
    si.search(q, function (err, searchResults) {
      if (!err) {
        res.json({results: searchResults});
      } else {
        res.json({error: err});
      }
    });
});
```

![Imgur](http://i.imgur.com/PILI1Ac.png)

But when I search for a word that is inside the `text` field, like the word "traditional", I get no results:

```
  app.post('/search', function(req, res) {
    var q = {};
    q.query = {
      '*': ['traditional']
    };
    si.search(q, function (err, searchResults) {
      if (!err) {
        res.json({results: searchResults});
      } else {
        res.json({error: err});
      }
    })
});
```

![Imgur](http://i.imgur.com/sYJKw4y.png)

**Comment by fergiemcdowall** [comment]
Hmmm- you definitely have a document in the index, and your query syntax seems to be OK (disclaimer: might be missing something- have not had morning coffee yet). This means that there may be something unusual about the way you are indexing it. The examples and tests should provide some clues. If you can post a test case which indexes the document and reproduces the error, then we can fix it for you.

**Comment by joshterrill** [comment]
Well, all my code is hosted here if you want to take a look at it: https://github.com/joshterrill/doc-search
If you're on a linux machine, you should be able to run `npm run deploy` to download the server dependencies, node modules, bower dependencies, and then start the server. When you go to `http://localhost:3000/extract` there is a document upload form that should support uploading RTF's (the only kind of document I've tested so far with catdoc and textract). The document gets posted to `/extract`, then catdoc parses the content of the RTF into plain text, and search-index stores it.

**Comment by fergiemcdowall** [comment]
Your code looks OK, there are no obvious errors.

We can only really look at contained test cases. If you can throw one together, we can fix it for you. Or you might find out what the problem is in the process of making the test case :)

**Comment by joshterrill** [comment]
I'm not really sure how to create a test case. But I'll look into this stuff again.

**Comment by joshterrill** [comment]
Okay, something is not right here. I created a route that basically just creates a simple object and pushes that through:

```
app.get('/test', function(req, res) {
    var pushObject = {"test": "123", "test2": "456"};
    si.add(pushObject, function (err) {
      if (!err) {
        res.json({success: true});
      } else {
        res.json({error: err});
      }
    });
});
```

And when I go to search it with:
```
    var q = {};
    q.query = {
      "*": ["123"]
    };
    si.search(q, function (err, searchResults) {
      if (!err) {
        res.json({results: searchResults});
      } else {
        res.json({error: err});
      }
    })
```

I still get 0 results....

**Comment by joshterrill** [comment]
I even followed this quickstart guide verbatim and can't get it to return results...

https://github.com/fergiemcdowall/search-index/blob/master/doc/quickstart.md

**Comment by EthanRubinson** [comment]
Hey there, I believe I'm running into a very similar problem as joshterrill. I'm indexing a document (markdown syntax) with the fields "title" and "body", then searching for it like so:
`
q.query = {
      "title": searchString.split(" "),
      "body" : searchString.split(" ")
    };
`

However it only ever seems to return results if the string matches exactly with a word in the title.

**Comment by joshterrill** [comment]
I can't even get anything to return, even if I match a word exactly as it
is in the db. Like I said I can't get the example to even work in the quick
start guide. Seems like it may be a problem with the module?

**Comment by EthanRubinson** [comment]
Try wrapping your object in an array:

```javascript
var pushObject = [{"test": "123", "test2": "456"}];
```

**Comment by joshterrill** [comment]
Still does not work.

**Comment by EthanRubinson** [comment]
Try downgrading to search-index 0.6.15? You'll have to delete the module from `node-modules/`, modify the `package.json` file and do another `npm install`. If that doesn't work I'll fork your repo and give it a whirl tomorrow. Besides the other issue I'm facing, everything else works great for me.

**Comment by fergiemcdowall** [comment]
@EthanRubinson yes, you need to arrayify search terms like so:

```javascript
q.query = {
      "body": ['donald', 'duck']  // return documents containing either 'donald' or 'duck'
};
```

...so that you can do phrase search like so (if you have indexed with ngrams of 2 or more):

```javascript
q.query = {
      "body": ['donald duck']  // returns documents with the phrase 'donald duck'
};
```

And yes, emptying before reindexing is faster. FYI `empty` is renamed `flush` in latest versions

**Comment by joshterrill** [comment]
@ethanrubinson I tried downgrading and still no luck. I'm not sure what's
going on... could you see if you can even get the example to work in the
quick start guide? I linked to it a few posts above. You can try to fork my
repo if you want but just know in order to get the document uploading and
parsing to work you'll have to have cat doc installed which if you're on a
Linux box is pretty easy. I've put the command that installs it in an npm
script in the package.json.

**Comment by EthanRubinson** [comment]
@fergiemcdowall 

I am arrayify-ing the search terms: `searchString.split(" ")` returns an array ("Search Terms 12 3" -->  ["Search", "Terms", "12", "3"]. What I was wondering is if the search terms needed to show up in **both**  queried indexed fields or in **either** field for the corresponding doc to be returned.

**Comment by fergiemcdowall** [comment]
If I understand you correctly: **both**

each `<fieldName>: [<searchterms>]` has to return `true` for document to be returned. The searchterms are `AND-y` , meaning that they all have to be present in the specified field

**Comment by fergiemcdowall** [comment]
@joshterrill I will try to post a gist to get you started within the next couple of hours

**Comment by joshterrill** [comment]
I'm searching for "*":["test"] which is a word that I have stored in my
database. It's still not showing up in the results when I query it though.

**Comment by EthanRubinson** [comment]
@fergiemcdowall Ah, yes that is exactly what I was asking. I'm going to submit a PR for your search.md doc, it's not clear on there if that was the case :+1: 

Thanks!

**Comment by joshterrill** [comment]
@fergiemcdowall thanks!

**Comment by joshterrill** [comment]
I actually just got this to work. I have no idea what I did wrong, but it had something to do with the si options that I had set. And I used the options that were recommended in the docs.

Here's what I had:
```
var siOptions = {
  deletable: true,
  fieldedSearch: true,
  indexPath: 'si',
  logLevel: 'error',
  nGramLength: 5,
  fieldsToStore: 'all'
}
```

I deleted all of the options except `indexPath` and now it works.

**Comment by fergiemcdowall** [comment]
:+1:

**Comment by joshterrill** [comment]
Could you explain why those options weren't yielding any results? I'm confused by it a tad.

**Comment by fergiemcdowall** [comment]
The code snippets you have posted look fine, and should work. Maybe you have found a bug. We would love to get reproducible test case (a simple script that `add`s a document, searches and gives brokenness) so that it can be debugged. Then a proper answer can be given

**Comment by joshterrill** [comment]
Okay I'll write a test case tomorrow and see what I come up with.

**Comment by eklem** [comment]
Just saw a possible error in your siOptions, @joshterrill. Not sure if your `nGramLength` definition will work. I figured this out the hard way a while ago, but got it working, [defining multiple nGramLength's as an array](https://github.com/fergiemcdowall/search-index/blob/87df5e5a82ba3e68cace586a4c246a293add87fa/doc/add.md#ngramlength):
```
{
  ...
  nGramLength: [1, 2, 3],
  ...
}
```

**Comment by fergiemcdowall** [comment]
`nGramLength` _should_ work with a single integer, so if it doesn't then that is a bug

**Comment by eklem** [comment]
Ok, from what I remember, this is what happened when just using a single integer higher than 1.
https://github.com/fergiemcdowall/search-index/issues/220

Matcher worked, search not. But something in the code may have changed?
