### ISSUE TITLE
Add wiki page for stopwords and why it's a common error

### ISSUE THREAD

**Issue by eklem** [fergiemcdowall/search-index#236]
Add a wiki page, explaining how stopwords work, and that it's quite common error when getting no results back from your index.

```JSON
/search?q={"*": ["my", "way"]}
```

[Stopword arrays available](https://github.com/fergiemcdowall/stopword/tree/master/lib) in `search-index` for the different languages.

**Comment by fergiemcdowall** [comment]
How about adding it to the markdown documentation?

**Comment by eklem** [comment]
Didn't think you wanted it in the documentation, but I'm more than happy to do that, @fergiemcdowall

**Comment by eklem** [comment]
Fixed in this PR https://github.com/fergiemcdowall/search-index/commits?author=eklem
