### ISSUE TITLE
Unclear or missing features

### ISSUE THREAD

**Issue by simplychaos** [fergiemcdowall/search-index#238]
Is there a way to tell on what line of a file a search result was found on? And/or a character range offset. Would be very useful for jumping to the line of a result.

I'm also confused about ranges, you never explain what they're for?

**Comment by fergiemcdowall** [comment]
In a manner of speaking- you would need to index every line as a separate field.

Ranges allow you to create aggregations and filters. Think of the left hand column in amazon when you search for something- it will tell you how many products are in the following ranges (for example): $0-10, $10-50, $50-$100, >$100 ; and then you could say for example: "give me everything between $50 and $100".

**Comment by fergiemcdowall** [comment]
But yes- point taken, documentation needs to be improved

**Comment by simplychaos** [comment]
Thanks!

**Comment by eklem** [comment]
I can try to document this a little better, showing and explaining how the index actually works.

**Comment by eklem** [comment]
Came to think about this again. Could it be possible to do something with fields here? If you put each sentence or paragraph in it's own field (within one document). Could you then get a response on which field you got the hit in, and use a a-name-tag to point to it?

You would then get a long list of fields per document:

- sentence-1
- sentence-2
- sentence-3
- ...
- sentence [n]

**Comment by eklem** [comment]
And, closing this.This explanation (how the index work) will be part of the [`search-index-cookbook`](https://github.com/eklem/search-index-cookbook): [How does a/the index work?](https://github.com/eklem/search-index-cookbook/issues/7)

**Comment by fergiemcdowall** [comment]
and the bit about explaining facet/filter ranges

**Comment by eklem** [comment]
Ah, yes: https://github.com/eklem/search-index-cookbook/issues/8
