### ISSUE TITLE
TypeError: callbacky is not a function

### ISSUE THREAD

**Issue by kuba12kozak** [fergiemcdowall/search-index#240]
Hi,
I've got a problem while starting node.js application. I got this error

> /root/aplikacja/node_modules/search-index/search-index.js:63
      return callbacky(err, SearchIndex)
             ^

> TypeError: callbacky is not a function
    at /root/aplikacja/node_modules/search-index/search-index.js:63:14

I tried to rename it manually to callback thinking it's just a misspelling but then I got

> ReferenceError: callback is not defined

Do you have any ideas how can I resolve this problem?
Any help will be apreciated. Thanks!

**Comment by kuba12kozak** [comment]
Ok, I changed initialisation of the module because there is an outdated example in here and this problem disappeared but now I have another problem.
I use express.js in my project and while rendering a page I have a callback function where I start search-index and  try to index html returned by the render function. Here is this piece of code:

`
	res.render('about', {about: results[0].content}, function(err, html) {

	if(err)	console.log(err);
	var dataset = {
		link: "/about",
		data: html
	}
	searchIndex({indexPath: 'testindex', logLevel: 'info'}, function(err, si) {
		si.add(dataset, {}, function(err) {
			if(!err) {
				console.log("About indexed");
			}
			else 	console.log(err);
		});
	});
});
`

(Sorry  for the first and last line but without the line of separation between first and second line the text was like everything together in one line).

The most wierd is that "About indexed" appears in console. The page doesn,t load and I got this in console:

> {"name":"search-index","hostname":"application","pid":27658,"level":30,"msg":"batch indexed!","time":"2016-02-16T01:30:06.175Z","v":0}
{"name":"search-index","hostname":"application","pid":27658,"level":30,"msg":"indexing 1-a7409594e187730daada4f9ef79669d05556acc3","time":"2016-02-16T01:30:06.178Z","v":0}
{"name":"search-index","hostname":"application","pid":27658,"level":30,"msg":"batch indexed!","time":"2016-02-16T01:30:06.350Z","v":0}
About indexed
/root/aplikacja/node_modules/search-index/node_modules/search-index-getter/docGetter.js:22
    levelup(givenOptions.indexPath || 'si', {
    ^

> ReferenceError: levelup is not defined

**Comment by fergiemcdowall** [comment]
Yes, the constructor was changed in 0.7.0, and that creates the "callbacky" error. There should be a better error message.

Your code works. Its saying "about indexed" because you are doing `if (!err)` which means "if no error", which is good! ;)

**Comment by fergiemcdowall** [comment]
The following works:

```javascript
var searchIndex = require('search-index')
var dataset = {
  link: "/about",
  data: "this is some data"
}
searchIndex({indexPath: 'testindex', logLevel: 'info'}, function(err, si) {
  si.add(dataset, {}, function(err) {
    if(!err) {
      console.log("About indexed");
    }
    else    console.log(err);
  });
});
```

**Comment by kuba12kozak** [comment]
Ok, one more update. I forgot to add `res.send(html)` to my callback. Now eveything seems to be allright but when I try to refresh the page the above levelup error appears.

**Comment by fergiemcdowall** [comment]
If you instantiate search-index outside of res.send, then it should be ok (you shouldn't set up a new index for every request)

**Comment by kuba12kozak** [comment]
Ok. I see. Do I have to put all my expressjs mappings or is it possible to make it other way because it's not the way I want to do that.

**Comment by kuba12kozak** [comment]
Ok. I got it. Thanks a lot for help.

**Comment by fergiemcdowall** [comment]
:+1:

**Comment by kristiandupont** [comment]
I'm a bit confused. Is the first parameter to `add` supposed to be an array or a single entry?

I previously had a series of `add` calls, adding a document at a time which seemed to work more or less, except that calling `tellMeAboutMySearchIndex` afterwards would reveal a much lower number than what I actually added. I figured the problem was that I should add documents in a batch, as an array because the documentation implies that. But that gives me this `callbacky` error, and looking at this thread, it looks like what I did before was right. However, quickly scanning the adder repo, it does look like it expects an array. Is it perhaps both?

**Comment by fergiemcdowall** [comment]
Hi @kristiandupont - most people get this error because the constructor changed in version 0.7.x

Are you initialising your `search-index` the callbacky way like this?:

```javascript
searchIndex({indexPath: 'testindex', logLevel: 'info'}, function(err, si) {
  // can now do si.add, si.search, etc
});
```

**Comment by fergiemcdowall** [comment]
If you post your code, we can debug it for you

**Comment by kristiandupont** [comment]
I am using the callbacky way, yes. I will try and post some code. But as to my question: is it supposed to accept arrays?

**Comment by fergiemcdowall** [comment]
Arrays. So a single entry must be wrapped in square brackets (Array of length 1)

**Comment by kristiandupont** [comment]
Thanks!
