### ISSUE TITLE
GLIBC issues on Debian 7

### ISSUE THREAD

**Issue by kuba12kozak** [fergiemcdowall/search-index#241]
Hi,
I run my app on Ubuntu and it works well, However on Debian 7 it throws me this error:

> /root/app/node_modules/search-index/node_modules/leveldown/node_modules/bindings/bindings.js:83
        throw e
              ^
Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.14' not found (required by /root/app/node_modules/search-index/node_modules/leveldown/build/Release/leveldown.node)
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at bindings (/root/app/node_modules/search-index/node_modules/leveldown/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/root/app/node_modules/search-index/node_modules/leveldown/leveldown.js:4:46)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)

I did some research and find out that the last stable version of glibc for Debian 7 is 2.13. It is possible to download later version (http://stackoverflow.com/questions/10863613/how-to-upgrade-glibc-from-version-2-13-to-2-15-on-debian/15766756) but it is still in an experimental phase and it's not safe to do that.
My question is does anybody know how to safely fix this problem?

**Comment by fergiemcdowall** [comment]
@kuba12kozak underneath the hood, this is a `leveldown` issue. There is a discussion of the problem, with a few possible resolutions, here: https://github.com/Level/leveldown/issues/200

**Comment by fergiemcdowall** [comment]
The ideal fix for this is to fallback on another key value store when installation fails

**Comment by fergiemcdowall** [comment]
I have poked around some of the *down implementations that rely purely on `fs`. I havent found one that works, but when one becomes available, we can program a fallback from leveldown. In the meantime, I am going to close this, since it is a somewhat specific problem relating to `leveldown`
