### ISSUE TITLE
`callbacky` breaks promisify'ing search-index

### ISSUE THREAD

**Issue by johnhaley81** [fergiemcdowall/search-index#242]
Just FYI :)

**Comment by johnhaley81** [comment]
Ah, scratch that. Something else was broken. Closing this out :)

**Comment by fergiemcdowall** [comment]
Yes- that error seems to pop up when (among other things) you dont specify a callback. It should definitely be more descriptive, since a few people have reported it.

**Comment by fergiemcdowall** [comment]
...as in it should actually describe the error and possible solution instead of a cryptic complaint about 'callbacky'
