### ISSUE TITLE
Install - checksum mismatch

### ISSUE THREAD

**Issue by calvinfroedge** [fergiemcdowall/search-index#244]
Project looks very cool. Perhaps you know why install is broken?

Platform details:
```
npm ERR! Darwin 14.5.0
npm ERR! node v4.1.1
npm ERR! npm  v2.14.4
```

Error details:
```
npm ERR! shasum check failed for /var/folders/l7/mqtbzlmj0rjd7k_mxk5wmv3h0000gn/T/npm-10237-97734baf/registry.npmjs.org/leveldown/-/leveldown-1.4.4.tgz
npm ERR! Expected: 5978b7b3e7ffa595b179391126035a9717ead765
npm ERR! Actual:   399e2cd6da80f85ff5e2f1d48123c60eeaa45fdb
npm ERR! From:     https://registry.npmjs.org/leveldown/-/leveldown-1.4.4.tgz
```

**Comment by fergiemcdowall** [comment]
Version `0.7.5` of `search-index` was just published, I'm guessing (hoping) that you just got unlucky and installed when everything was updating and that it will work if you delete your `node_modules` and try it again.

**Comment by fergiemcdowall** [comment]
Closing for now since the problem cannot be replicated. Please reopen if the problem persists on your end @calvinfroedge
