### ISSUE TITLE
High memory usage when adding documents to index

### ISSUE THREAD

**Issue by brandonchartier** [fergiemcdowall/search-index#245]
I'm seeing my memory usage balloon up to 1GB used when indexing ~2,000 documents, which seems odd. The documents aren't particularly large, at ~4KB each, either.

Sample code is very basic:
```js
request(API, (err, res, body) => {
  si.add(JSON.parse(body), err => {
    ...
  });
});
```

I can get memory usage down to ~250MB if I chunk the data and add it from a queue, but this ends up taking a very long time. Obviously 1GB doesn't work when I'm using a 512MB Digital Ocean droplet, and 250MB doesn't work most of the time, so I'm thinking this might be a strange edge case. Is there a better way to optimize this? If this is normal, I will learn to live with it, and you can close this immediately.

Thank you!

**Comment by fergiemcdowall** [comment]
The index has to be recalibrated every time it changes. You will see better performance if you add your data in batches, since `search-index` will treat every batch as 1 change: try 1 large batch of 2000 docs, or two batches of 1000 docs

Also: re-adding documents is expensive. If you simply want to empty your index and start again, either delete the datastore, or use `flush` before indexing.

**Comment by eklem** [comment]
It's gotten better with the newest version of `search-index`, but still high a little hight? ~400 MB  for approximately 350 items in a batch. I switched from v0.6.4 to v.0.7.6 and decreased from 1.3 GB to 400 MB.

![screen shot 2016-02-23 at 09 51 38](https://cloud.githubusercontent.com/assets/236656/13246309/27ce940a-da13-11e5-8109-6185d606997a.png)

**Comment by fergiemcdowall** [comment]
What version are you on @brandonchartier ?

**Comment by brandonchartier** [comment]
@fergiemcdowall I've updated to 0.7.6, with similar results.

I was removing the index before every test, now using the flush method, but I will just go with a batched solution (50 at a time takes 2 minutes and caps out around ~350-400MB of memory), unless you have any other performance tips. Feel free to close this, since it doesn't seem to be a bug.

Thank you!

**Comment by fergiemcdowall** [comment]
Great! if the data is not sensitive feel free to send it over and we can take a look at it
