### ISSUE TITLE
Field weighting, query side

### ISSUE THREAD

**Issue by eklem** [fergiemcdowall/search-index#247]
We need some documentation on field weighting, query side. Both the [search](https://github.com/fergiemcdowall/search-index/blob/master/doc/search.md) doc and the [API reference on search](https://github.com/fergiemcdowall/search-index/blob/master/doc/API.md#search) could use a little update?

If [this (first post) is how it works](https://github.com/fergiemcdowall/search-index/issues/81#issue-63562389), I can do the updating.

**Comment by fergiemcdowall** [comment]
Weighting needs some tests, somehow it seems to have fallen through the cracks

**Comment by eklem** [comment]
Ok, should I test manually and document what I find?

**Comment by fergiemcdowall** [comment]
please do!

**Comment by fergiemcdowall** [comment]
moved here: https://github.com/fergiemcdowall/search-index/issues/263

**Comment by eklem** [comment]
So, I've tested a fielded OR-search where I switch between weighting the two fields in the query:

1:`http://146.185.142.231:3030/search?q={"query":[{"AND":{"user":["eklem"]}}, {"AND":{"text":["test"]}}], "weight":{"user": 100}}`
2:`http://146.185.142.231:3030/search?q={"query":[{"AND":{"user":["eklem"]}}, {"AND":{"text":["test"]}}], "weight":{"text": 100}}`

Nothing happens in the order of the document or the relevance math. Check the screenshots below, or try the URL's yourself.

![skjermbilde 2016-05-21 kl 20 29 21](https://cloud.githubusercontent.com/assets/236656/15450117/8d47fbee-1f93-11e6-9b06-c4a8c3c594e3.png)
![skjermbilde 2016-05-21 kl 20 29 07](https://cloud.githubusercontent.com/assets/236656/15450118/8d72f6e6-1f93-11e6-93f6-9edba6d93b5f.png)

**Comment by fergiemcdowall** [comment]
Have now reimplemented weighting as "boosting". See https://github.com/fergiemcdowall/search-index/blob/master/test/node/general-tests/boost-test.js for examples. Updated docs coming soon...
