### ISSUE TITLE
Troubles with browser build

### ISSUE THREAD

**Issue by s-panferov** [fergiemcdowall/search-index#248]
Hello. Thanks for the amazing library. I have some troubles with browser build, the error is 

```
Uncaught TypeError: exists is not a function
```

```
exports.getRoot = function getRoot (file) {
  var dir = dirname(file)
    , prev
  while (true) {
    if (dir === '.') {
      // Avoids an infinite loop in rare cases, like the REPL
      dir = process.cwd()
    }
    /// HERE
    if (exists(join(dir, 'package.json')) || exists(join(dir, 'node_modules'))) {
      // Found the 'package.json' file or 'node_modules' dir; we're done
      return dir
```

Is it a known issue?

**Comment by fergiemcdowall** [comment]
You're welcome! :)

I havent seen that issue before- how do I replicate it?

**Comment by s-panferov** [comment]
Steps to reproduce:

*Create simple example:*

```
var si = require('search-index');
console.log(si);
```

*Create bundle using browserify:*

```
browserify -t brfs index.js > bundle.js
```

*Create simple html page*

```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>DocScript Explorer</title>
  </head>
  <body>
      <script src="/bundle.js"></script>
  </body>
</html>
```

Error appears in the devtools console.

**Comment by s-panferov** [comment]
It seems that ignoring `leveldown` helps:

```
browserify -i leveldown -t brfs index.js > bundle.js
```

But I need to check how it works.

**Comment by s-panferov** [comment]
I've also noticed that `db` options is not passed here:

https://github.com/fergiemcdowall/search-index/blob/master/search-index.js#L74

And so `level-js` backed is not available to use as specified in your examples:

https://github.com/fergiemcdowall/search-index-replicate-index-to-browser-example/blob/master/main.js#L5

**Comment by s-panferov** [comment]
After adding 

```
db: options.db
```

line everything seems to work. 

But the next inconvenient thing that I met is that I have to inline my search index into a bundle using `fs` module. This approach have several disadvantages:

* My serialized search index on file system have size 5Mb size. After I inline it to the bundle, it grows up to 10Mb. I believe it's because base64 conversion of binary data.

*I have several indexes and due to its sizes I really want to load them on-demand.

Is it possible to load indexes using `fetch`? I think that I must find some steams wrapper on top of `ReadableByteStream`...

**Comment by fergiemcdowall** [comment]
OK- first of all this is ALL MY FAULT.

1) There should be automated testing for the browser- thats not set up yet. The example has gradually stopped working with the newer releases, and this has not been picked up-

2) The API has undergone some small, but significant changes recently, and the HOWTO docs have not been updated.

3) You are absolutely right- it would be better to fetch the data separately.

Anyway- glad you got it working. I am going to put some work into the whole browserification workflow so that it is back to being as painless as it was before.

**Comment by s-panferov** [comment]
Here is my investigation results how to make it work with `fetch`:

```
let searchIndex = fetch('/doc/index.gz')
.then(res => res.arrayBuffer());
.then(idx => {
    let buf = new buffer.Buffer(idx);
    let bufferStream = new stream.PassThrough();
    bufferStream.end(buf);
    si(options, (err, index) => {
        index.replicate(bufferStream, function(callback){
          console.log('db serialized');
        });
    });
})
```

**Comment by fergiemcdowall** [comment]
This turned into a discussion which I think had a resolution? Going to close: please reopen if there is an outstanding issue

**Comment by fergiemcdowall** [comment]
This is now set up in the tests, but is still really badly documented.  The test command is currently: `"browserify test/browser/browserify-test-uncompiled.js > test/sandbox/bundle.js && tape test/browser/selenium-test.js"`

The magic is happening in this file: https://github.com/fergiemcdowall/search-index/blob/master/test/browser/browserify-test-uncompiled.js
