### ISSUE TITLE
Option for case insensitive indexing/searching

### ISSUE THREAD

**Issue by jlopezr** [fergiemcdowall/search-index#25]
I don't know if I have forgot something, but I index a few documents and when I tried to make a query the query seems to be case sensitive. If I look for "this", and a field contains "This is an example" search-index does not return it.

This is the expected behaviour? Should I index all the document in lowercase?

**Comment by fergiemcdowall** [comment]
The original bug was because english stop words are removed by default as per the list in the `natural` library

`search-index` is already case insensitive and will continue to be so until somebody reeeeeeally, really wants case insensitivity
