### ISSUE TITLE
API design problem

### ISSUE THREAD

**Issue by larsvoigt** [fergiemcdowall/search-index#251]
Hi all, 
search-index is very well! 
But now I would like to update my project from 0.64 to the latest version of search-index.
At first I got an error _TypeError: callbacky is not a function_.  Ahh okay  #240 you changed the constructor in version 0.7. I use your module behind a kind of 'own interface'. The new 0.7 constructor required a callback (the callback hell :-)) to get the instance of si. This is not really practical.  What is the intention?  I have never seen any npm module that do this. Now the issues is my whole module instantiation would be depends on the search-index callback. Do you have any ideas how can I solve this problem? 

Example:

``` javascript
module.exports = function (options) {
    var defaultOption = {'indexPath': indexDB};
    var options = options || defaultOption;
    var si;

    searchIndex(options, function (err, si) {

        if (err) {
            console.log(err)
        } else {
            this.si = si
        }
    });
    this.add = function (jsonDoc, callback) {
           this.si.add(jsonDoc, opt, callback);
     }
}


var mm = new MyModule();
mm.add(dataSet, function (err) {...});

```
Thanks a lot!
Lars

**Comment by fergiemcdowall** [comment]
Hi Lars

First of all- sorry this broke your code! I know it sucks when that happens, and even though semver allows for breaking API changes on 0.x.x releases, its still can be quite disruptive when it happens.

The rationale behind this change is that search-index should be able to use any key-value store surfaced by levelup, and since levelup has gone over to the callback way of doing things, search-index also has to. Callbacks actually make sense in this scenario since connecting to databases can often take a few seconds, and the delay is on other machines.

suggestion for your code follows...

**Comment by fergiemcdowall** [comment]
In your module file called `larsModule.js`:

```javascript
module.exports = function (options, callback) {
  const defaultOption = {indexPath: 'aMeaningfullName'};
  const searchIndex = require('search-index')
  var larsModule = {}
  var options = options || defaultOption;

  searchIndex(options, function (err, si) {
    if (err) {
      console.log(err, null)
    } else {
      larsModule.si = si
      larsModule.add = si.add
      larsModule.search = si.search
      return callback(null, larsModule)
    }
  })

}
```

Invoke like so from your app file called `index.js`:

```javascript
const larsModule = require('./larsModule.js')

larsModule({}, function(err, lm) {
  lm.add([{
    title: 'a realllly cool document',
    body: 'this is my doc'
  }], function (err) {
    lm.search({query:{title: ['cool']}}, function(err, results){
      console.log(results)
    })
  });
})

```

Drop the two files into a dir and run `npm install search-index` and then `node index.js`

**Comment by larsvoigt** [comment]
Thanks @fergiemcdowall.  I see it [levelup] (https://github.com/fergiemcdowall/search-index/blob/master/search-index.js#L73).

**Comment by fergiemcdowall** [comment]
We commented at the exact same time- so here is a bump incase you missed the code I posted :)

**Comment by larsvoigt** [comment]
Great stuff @fergiemcdowall I will test it. But that is what I wanted to avoid, the callback hell ;-) ;-).

**Comment by fergiemcdowall** [comment]
It is very callbacky, but it actually fixes some unpredictable bugs in the test suite, so the clunkier syntax is making it more stable.

**Comment by larsvoigt** [comment]
I fit my project code with the help of your example.  It works like a charm. :+1: 
Thank you @fergiemcdowall !

**Comment by fergiemcdowall** [comment]
:tada:
