### ISSUE TITLE
Search with keywords' initial, not whole word

### ISSUE THREAD

**Issue by EasyFrankie** [fergiemcdowall/search-index#252]
Hi there, great search library. 
```
//My data
[  
  {
    "name" : "mazda2 2016",
    "category" : "car"
    "id" : "1", 
  },  
  {
    "name" : "mazda6 floor mat",
    "category" : "accessory",
    "id" : "2", 
  }  
]
//My query
var q = {
          "query" : {
            '*' : ['mazda'],
           "category": ['car']
          }
};
search_index_singleton.search(q, ...
```

What I want is to get object with id "1" as the result, which match: 

1.   contain  "mazda" in its fields: which in the data is "mazda2"
2.   with category of 'car'

But my code can only return object with id "1" ONLY when I search with whole word:

```
var q = {
          "query" : {
            '*' : ['mazda2'],
           "category": ['car']
          }
};
```

**Is there a way that I can return object contain keywords startted with initial that I stated in the "query" field?**  The matcher function seem not able to specify "category"

Thanks!

**Comment by fergiemcdowall** [comment]
Yes, that is what the **matcher** is for- check out https://github.com/fergiemcdowall/search-index/blob/master/doc/autosuggest.md

**Comment by jdgarcia** [comment]
Are there any plans for **matcher** to support something like `contains`? For example, searching for `scroll` would match both `fix scrollbar` and `make scrollable`?

**Comment by fergiemcdowall** [comment]
I see what you mean- that would be a great improvement

**Comment by johnhaley81** [comment]
:+1: to `contains`

**Comment by EasyFrankie** [comment]
Thanks for your answer, but as I see, matcher cannot support specify a value for a field as query of search: 

What I want is get object with any property **begin with** "mazda" and object's "category" property is **equal** to "car",  means only match object which both satisfy the two needs at the same time. 

I cannot find similiar function in matcher's document, can I do this kind of match? 

B.R.

Frank

**Comment by fergiemcdowall** [comment]
Have you investigated the `field` option that you can send to matcher? Given that your documents have a field called "car" populated with the car names you want to match, you could do something like this:

```javascript
si.match({field: 'car', beingsWith:'mazda'}, function (err, matches) {
  //matches should contain cars beginning with 'mazda' ('mazda1', 'mazda2', etc...)
})
```

**Comment by EasyFrankie** [comment]
Thank you for your answer. Sorry for I didn't express myself clearly.

What I want to get is not only document with "name" field that begin with 'mazda', but also that document **MUST have another field  "category" equal to "car"**, so for the following data:

I **ONLY** want to get **document 1** because its **"category" field is eqal to "car"**; document 2's name also starts with "mazda", but it's "category" field is not "car", it's "accessory", which I do not want.
```
[
  //document 1
  {
    "name" : "mazda2 2016",
    "category" : "car"
    "id" : "1", 
  },  
  //document 2
  {
    "name" : "mazda6 floor mat",
    "category" : "accessory",
    "id" : "2", 
  }  
]
```

**Comment by fergiemcdowall** [comment]
**Matching** = _matching words_. (partial word matches possible)
**Searching** = _matching documents_. (can only match words in the document, can filter documents based on the content of fields)

If you are wanting to get a resultset of documents, then you can't search with partial words. Some restructuring of your data will probably allow you to achieve what you want.

**Comment by EasyFrankie** [comment]
I got it, thanks for your answer, but I still think it would be much better if I can search with some wildcard like 'mazda*', : )

**Comment by fergiemcdowall** [comment]
Search is a tradeoff between precision and recall. Wildcard search improves recall, but really hoses relevance. It also creates monster indexes that take a lot of space, and run more slowly.

People tend to think that Google, Yahoo, etc, support partial word matching, but they actually dont. What they do have is synonyms/stemming and autosuggest, which will in almost all cases give the best user experience.

If you absolutely, definitely, certainly want partial word matching to return documents in `search-index` you can try one or more of the following:

 * Idea 1: Split the word up before indexing and put the partials into a hidden field `{carTypePartialsHidden: 'maz mazd, mazda, mazda1'}`
 * Idea 2: Index the fields to be searched on as filters `{carTypeFilter: ['mazda2']}`. Do a search and then filter on a range of values from "mazda" to "mazda~" (will pick up all documents with a carTypeFilter between "mazda" and "mazda~" such as "mazda1234jsd")
 * Idea 3: Do some magic where you use the matcher to return possible completions from the index, search for all possible completions, and then mesh the search results together.
 * Maybe something else..?

**Comment by eklem** [comment]
If this type of matching (*word*) would become a feature, I think it is important that it's something that is off by default, and that you can turn on if needed. I know it sounds kind of negative, but small index sizes are important to another feature of search-index: That it can run in the browser.
