### ISSUE TITLE
Start using Greenkeeper for auto updating dependencies versions?

### ISSUE THREAD

**Issue by eklem** [fergiemcdowall/search-index#254]
We used Greenkeeper before, updating to latest versions of all dependencies. Was it too noisy, or why did it/we stop?

**Comment by fergiemcdowall** [comment]
I cant remember why (or even _if_) we actively stopped using it- I am totally open for using it again

**Comment by eklem** [comment]
Maybe @mewwts knows? You set it up, didn't you?

**Comment by fergiemcdowall** [comment]
Actually, looking at the amount of pull requests it generated (several per day), it probably creates more work than it saves

**Comment by eklem** [comment]
Ah, ok. That's true.

**Comment by mewwts** [comment]
I think using it is a good idea. It will track breaking changes in our deps as far as I know.

**Comment by eklem** [comment]
I'm not the one to accept/deny the pull requests, so this is you that decides, @fergiemcdowall  =) If we don't use something like Greenkeeper, maybe we should do a version bump for dependencies on a regular basis. Go through all dependencies and bump the ones needed, and see if our modules passes the tests.

**Comment by fergiemcdowall** [comment]
I update all the modules every now and again. I'd say the easiest is to keep them up-to-date-ish, but not bleeding edge. In principle, if a pull request passes all the tests, then anyone can merge
