### ISSUE TITLE
Features turned on versus index size - Example

### ISSUE THREAD

**Issue by eklem** [fergiemcdowall/search-index#255]
I think we need an example on what different features turned on and off does to the index size. This is hard to explain with accurate math, so one test data set, and 3, 4, 5 or 6 different feature setups and what the index size then equals to.

Having the example that people can run themselves, makes it easier to check what the conditions are for the back end of your choice.

**Comment by fergiemcdowall** [comment]
Yes, and maybe even make it a part of a larger "search-index cookbook" that covers common/interesting use cases

**Comment by eklem** [comment]
:+1: Yes! Nice to look at which features you want, and what kind of trade-offs you do. I'll try to do this one.

**Comment by fergiemcdowall** [comment]
Maybe a first step would be just to make a set of 10-20 chapter titles?

**Comment by eklem** [comment]
Think [search-index-indexer](/eklem/search-index-indexer/) is ready for this now. Easy to just use different config files on same dataset.

**Comment by fergiemcdowall** [comment]
One of the unintentional benefits of the new index structure is that deletability and filterability no longer incur a large size penalty. The only thing that increases size is having searchable fields, and storeable fields. This is hopefully a bit easier to understand, although it still needs to be documented somewhere

**Comment by eklem** [comment]
Cool! What is storable fields? Fields that can only be displayed, but not searched?

**Comment by fergiemcdowall** [comment]
Yes, its the cached version of the document.

Actually on second thoughts I wonder if `cache` is a better name than `storeable`..?

**Comment by fergiemcdowall** [comment]
(So, if you have big docs, you might choose not to cache them in order to save space.)

**Comment by eklem** [comment]
`cache` sounds a little temporary? `display`/ `display-only` ?

**Comment by eklem** [comment]
But thanks for the answer. I'll ask and help with documentation when you are a bit more ready with 0.9.

**Comment by RajPratim21** [comment]
Can you give me an overview of what is n general size of an index file with search-index. Particularly what I am interested is let's say for a json file of size 100 MB what will be size of index file, and is index DB(default  called as "si") and index file refers to same ? kindly help.

**Comment by eklem** [comment]
The .str-files here, combined, will give you an index size of approximately 100 Mb with config.json. But the option nGramLength has a lot to say. Also, I think fielded search has quite a lot to say.

**Comment by RajPratim21** [comment]
@eklem , do the index file refers to the .ldb (binary files) inside the index DataBase ? which is the index file whose size I should check? and I plan to use it with a chrome extension, so can I store the DB into the hard-drive , or with search-index everything is being stored into main memory. I will be grateful to you for your answers.

**Comment by fergiemcdowall** [comment]
@RajPratim21 if you are planning on using it with a chrome extension, then you are probably going to swap out leveldown with level.js which will store the index in chrome's indexedDB. As for the size,  you really just have to experiment a bit and see what happens.

**Comment by RajPratim21** [comment]
@fergiemcdowall  Thank you for your response.

**Comment by fergiemcdowall** [comment]
Closing for now since this question applied mostly to the last version
