### ISSUE TITLE
Create a cookbook

### ISSUE THREAD

**Issue by eklem** [fergiemcdowall/search-index#256]
A cookbook on different developer use cases, and recipes / how to achieve these with search-index.

Some suggested topics:
- [ ] Autocomplete (matcher) (with more than one word)
- [ ] Indexing only for an autocomplete function
- [ ] "Phrase search"
- [ ] Faceted/filtered search
- [ ] Hit highlighting
- [ ] Stopwords
- [ ] Field weighting
- [ ] Fielded search
- [ ] Running in the browser
- [ ] Offline searching
- [ ] Features vs. index file size

With a cookbook, the documentation can be made smaller/stricter, and the cookbook can be the place to elaborate a bit more on how to achieve stuff.

**Comment by fergiemcdowall** [comment]
:+1:

**Comment by eklem** [comment]
Should we make it as a separate module? Then we can add example data and example code more freely.

**Comment by eklem** [comment]
Ok, [made a separate module](https://github.com/eklem/search-index-cookbook). We can merge the two later, if we see that that's the best thing to do. Less noise here in the `search-index`-module

**Comment by fergiemcdowall** [comment]
Yes, thats the best way to do it
