### ISSUE TITLE
Possible to index only for an autocomplete function?

### ISSUE THREAD

**Issue by eklem** [fergiemcdowall/search-index#257]
Is it possible to index only for an autocomplete function? To only have an autocomplete index, and not care about document (search) results? That could make for a good "running in the browser" use case, and it would keep the index really small if documents were kept out of it.

**Comment by fergiemcdowall** [comment]
This would be a great improvement.

Its sort of kind of possible at the moment, but it should be made more "pure"

**Comment by eklem** [comment]
You would have to delete one of the index files? Also, this would be perfect with the opensearch.xml-feature: To have one index for autosuggests, and another for searching. Here you use the last array to define the actuall url when you click on something that has been autosuggested by the matcher: http://www.opensearch.org/Specifications/OpenSearch/Extensions/Suggestions/1.1#Example_3 (First and second is suggested words, and hit they have)

**Comment by fergiemcdowall** [comment]
The matcher uses the Term Frequency part of the index, which the searcher also uses. There are performance benefits from sharing the index.

However, as the matcher becomes more powerful it will eventually need its own index anyway, so it could definitely be split up.

**Comment by eklem** [comment]
Ok, but before you split up, you may only need a flag/setting to add just the term frequency part to the index?

**Comment by fergiemcdowall** [comment]
Implementing #324 would go a long way towards fixing this

**Comment by fergiemcdowall** [comment]
This is now possible using some of the new indexing options that have just been added: `wildcard`, `fastSearch` in combination with some of the older params: article coming...
