### ISSUE TITLE
Allow overriding stop words and word separators on a per-field basis

### ISSUE THREAD

**Issue by ConnorKrammer** [fergiemcdowall/search-index#258]
There are cases where it's useful to index separate fields using different sets of stop words or with field-specific word separators. How difficult is this to add?

**Comment by EasyFrankie** [comment]
Vote +1. 

Is it possible to add other word seperator such as '@' when I do the searching?

**Comment by ConnorKrammer** [comment]
@EasyFrankie You can do that by setting the separator regex on the index config object. For example:

```javascript
var config = {
    // ... other config
    separator: /[\|'@ \.,\-|(\n)]+/, // Include @ symbol
};
```

Here I copied the default separator regex and added "@" to it. You just have to be careful not to break the other separators when you modify the regex. Also keep in mind that this will operate across all fields, not just one. (Which is way I opened this issue.)

However, if you were asking if you can add a new separator at search time instead of index time, I don't think you can.

**Comment by fergiemcdowall** [comment]
I havent actually tested this, but it should be possible to set stopwords and field separators in the field options:

```javascript
{
  batchName: 'my batch',
  fieldOptions: [
      {
        fieldName: 'myFieldName',
        stopwords: ['my', 'stopword', 'list'],
        separator: /[\|'@ \.,\-|(\n)]+/
      },
      {
        fieldName: 'anotherFieldName',
        stopwords: ['another', 'stopword', 'list'],
        separator: /[\|'@ \.,\-|(\n)]+/
      }
  ]
}
```

**Comment by fergiemcdowall** [comment]
The above object is a batch options BTW

**Comment by eklem** [comment]
Think this is how it works internally, at least for the stopwords. When using the [`search-index-indexer`](https://github.com/eklem/search-index-indexer) to test for some bugs, the config file gets a stopword-array for each field defined in the [config](https://github.com/eklem/search-index-indexer/blob/master/config.json).

**Comment by eklem** [comment]
So, at the end, the config-file looks like this:
```json
{
    "batchname": "batch",
    "nGramLength": [
        1,
        2,
        3,
        4
    ],
    "fieldOptions": [
        {
            "fieldName": "type",
            "filter": true,
            "nGramLength": 1,
            "searchable": true,
            "weight": 0,
            "fieldedSearch": true,
            "stopwords": [
                "$",
                "0",
                "1",
                "2",
                "3",
                "4",
                "5",
                "6",
                "7",
                "8",
                "9",
                "_",
                "a",
                "about",
                "after",
                "all",
                "also",
                "am",
                "an",
                "and",
                "another",
                "any",
                "are",
                "as",
                "at",
                "b",
                "be",
                "because",
                "been",
                "before",
                "being",
                "between",
                "both",
                "but",
                "by",
                "c",
                "came",
                "can",
                "come",
                "could",
                "d",
                "did",
                "do",
                "e",
                "each",
                "f",
                "for",
                "from",
                "g",
                "get",
                "got",
                "h",
                "had",
                "has",
                "have",
                "he",
                "her",
                "here",
                "him",
                "himself",
                "his",
                "how",
                "i",
                "if",
                "in",
                "into",
                "is",
                "it",
                "j",
                "k",
                "l",
                "like",
                "m",
                "make",
                "many",
                "me",
                "might",
                "more",
                "most",
                "much",
                "must",
                "my",
                "n",
                "never",
                "now",
                "o",
                "of",
                "on",
                "only",
                "or",
                "other",
                "our",
                "out",
                "over",
                "p",
                "q",
                "r",
                "s",
                "said",
                "same",
                "see",
                "should",
                "since",
                "some",
                "still",
                "such",
                "t",
                "take",
                "than",
                "that",
                "the",
                "their",
                "them",
                "then",
                "there",
                "these",
                "they",
                "this",
                "those",
                "through",
                "to",
                "too",
                "u",
                "under",
                "up",
                "v",
                "very",
                "w",
                "was",
                "way",
                "we",
                "well",
                "were",
                "what",
                "where",
                "which",
                "while",
                "who",
                "with",
                "would",
                "x",
                "y",
                "you",
                "your",
                "z"
            ]
        },
        {
            "fieldName": "user",
            "filter": true,
            "nGramLength": 1,
            "searchable": true,
            "weight": 0,
            "fieldedSearch": true,
            "stopwords": [
                "$",
                "0",
                "1",
                "2",
                "3",
                "4",
                "5",
                "6",
                "7",
                "8",
                "9",
                "_",
                "a",
                "about",
                "after",
                "all",
                "also",
                "am",
                "an",
                "and",
                "another",
                "any",
                "are",
                "as",
                "at",
                "b",
                "be",
                "because",
                "been",
                "before",
                "being",
                "between",
                "both",
                "but",
                "by",
                "c",
                "came",
                "can",
                "come",
                "could",
                "d",
                "did",
                "do",
                "e",
                "each",
                "f",
                "for",
                "from",
                "g",
                "get",
                "got",
                "h",
                "had",
                "has",
                "have",
                "he",
                "her",
                "here",
                "him",
                "himself",
                "his",
                "how",
                "i",
                "if",
                "in",
                "into",
                "is",
                "it",
                "j",
                "k",
                "l",
                "like",
                "m",
                "make",
                "many",
                "me",
                "might",
                "more",
                "most",
                "much",
                "must",
                "my",
                "n",
                "never",
                "now",
                "o",
                "of",
                "on",
                "only",
                "or",
                "other",
                "our",
                "out",
                "over",
                "p",
                "q",
                "r",
                "s",
                "said",
                "same",
                "see",
                "should",
                "since",
                "some",
                "still",
                "such",
                "t",
                "take",
                "than",
                "that",
                "the",
                "their",
                "them",
                "then",
                "there",
                "these",
                "they",
                "this",
                "those",
                "through",
                "to",
                "too",
                "u",
                "under",
                "up",
                "v",
                "very",
                "w",
                "was",
                "way",
                "we",
                "well",
                "were",
                "what",
                "where",
                "which",
                "while",
                "who",
                "with",
                "would",
                "x",
                "y",
                "you",
                "your",
                "z"
            ]
        },
        {
            "fieldName": "tags",
            "filter": true,
            "nGramLength": 1,
            "searchable": true,
            "weight": 0,
            "fieldedSearch": true,
            "stopwords": [
                "$",
                "0",
                "1",
                "2",
                "3",
                "4",
                "5",
                "6",
                "7",
                "8",
                "9",
                "_",
                "a",
                "about",
                "after",
                "all",
                "also",
                "am",
                "an",
                "and",
                "another",
                "any",
                "are",
                "as",
                "at",
                "b",
                "be",
                "because",
                "been",
                "before",
                "being",
                "between",
                "both",
                "but",
                "by",
                "c",
                "came",
                "can",
                "come",
                "could",
                "d",
                "did",
                "do",
                "e",
                "each",
                "f",
                "for",
                "from",
                "g",
                "get",
                "got",
                "h",
                "had",
                "has",
                "have",
                "he",
                "her",
                "here",
                "him",
                "himself",
                "his",
                "how",
                "i",
                "if",
                "in",
                "into",
                "is",
                "it",
                "j",
                "k",
                "l",
                "like",
                "m",
                "make",
                "many",
                "me",
                "might",
                "more",
                "most",
                "much",
                "must",
                "my",
                "n",
                "never",
                "now",
                "o",
                "of",
                "on",
                "only",
                "or",
                "other",
                "our",
                "out",
                "over",
                "p",
                "q",
                "r",
                "s",
                "said",
                "same",
                "see",
                "should",
                "since",
                "some",
                "still",
                "such",
                "t",
                "take",
                "than",
                "that",
                "the",
                "their",
                "them",
                "then",
                "there",
                "these",
                "they",
                "this",
                "those",
                "through",
                "to",
                "too",
                "u",
                "under",
                "up",
                "v",
                "very",
                "w",
                "was",
                "way",
                "we",
                "well",
                "were",
                "what",
                "where",
                "which",
                "while",
                "who",
                "with",
                "would",
                "x",
                "y",
                "you",
                "your",
                "z"
            ]
        }
    ]
}

```

**Comment by ConnorKrammer** [comment]
I just tested it, and adding a `separator` value for an individual field seems to override the default like you said.

**Comment by fergiemcdowall** [comment]
:tada: closing...

**Comment by ConnorKrammer** [comment]
Alright, so I have to retract my previous statement: separator values are **not** passed on, because of the following line in search-indexer-adder's indexer.js:

```

**Comment by ConnorKrammer** [comment]
Alright, so I have to retract my previous statement: separator values are not passed on, because of the [following lines](https://github.com/fergiemcdowall/search-index-adder/blob/master/indexer.js#L110) in search-indexer-adder's indexer.js:

```javascript
var v = tv.getVector(field + '', {
    separator: batchOptions.separator,   // In particular, this one.
    stopwords: fieldOptions.stopwords,
    nGramLength: fieldOptions.nGramLength
});
```

However, changing that to take `fieldOptions` first with `batchOptions` as a fallback doesn't quite solve it either if you don't want spaces to be a word separator. (This is useful for, say, article tags, where each tag is an atomic unit but may contain spaces.)

To figure out why *that* is an issue, you have to look at [line 15 of the stopword module](https://github.com/fergiemcdowall/stopword/blob/master/lib/stopword.js#L15) as well as [line 33 in the term-vector module](https://github.com/fergiemcdowall/term-vector/blob/master/lib/term-vector.js#L33) (line 20 in the current npm release, but you added documentation at the top). In the stopword module, the list of tokens is joined into a string using a single space as a separator. In term-vector it's then broken apart on the space separator. This creates issues if spaces aren't valid word separators, since it will break tokens internally.

Stopwords also don't appear to be passed on, because of [line 106 and 107 in the search-indexer-adder module](https://github.com/fergiemcdowall/search-index-adder/blob/master/indexer.js#L107). `fieldOptions.stopwords` is always set to be equal to `batchOptions.stopwords`. That seems to be an easy fix, however. (It's a one-line change.)

**Comment by ConnorKrammer** [comment]
@fergiemcdowall @eklem 

Alright, so I have to retract my previous statement: separator values are not passed on, because of the [following lines](https://github.com/fergiemcdowall/search-index-adder/blob/master/indexer.js#L110) in search-indexer-adder's indexer.js:

```javascript
var v = tv.getVector(field + '', {
    separator: batchOptions.separator,   // In particular, this one.
    stopwords: fieldOptions.stopwords,
    nGramLength: fieldOptions.nGramLength
});
```

However, changing that to take `fieldOptions` first with `batchOptions` as a fallback doesn't quite solve it either if you don't want spaces to be a word separator. (This is useful for, say, article tags, where each tag is an atomic unit but may contain spaces.)

To figure out why *that* is an issue, you have to look at [line 15 of the stopword module](https://github.com/fergiemcdowall/stopword/blob/master/lib/stopword.js#L15) as well as [line 33 in the term-vector module](https://github.com/fergiemcdowall/term-vector/blob/master/lib/term-vector.js#L33) (line 20 in the current npm release, but you added documentation at the top). In the stopword module, the list of tokens is joined into a string using a single space as a separator. In term-vector it's then broken apart on the space separator. This creates issues if spaces aren't valid word separators, since it will break tokens internally.

Stopwords also don't appear to be passed on, because of [line 106 and 107 in the search-indexer-adder module](https://github.com/fergiemcdowall/search-index-adder/blob/master/indexer.js#L107). `fieldOptions.stopwords` is always set to be equal to `batchOptions.stopwords`. That seems to be an easy fix, however. (It's a one-line change.)

**Comment by eklem** [comment]
Adding it as a bug, and re-opening.

**Comment by fergiemcdowall** [comment]
*Chanting, waving placard with fist in air:* "PULL REQUEST, PULL REQUEST, PULL REQUEST"

**Comment by fergiemcdowall** [comment]
@ConnorKrammer would you have time to throw together what you describe in a pull request?

**Comment by ConnorKrammer** [comment]
@fergiemcdowall It'd have to be three pull requests, I suppose, since I'd have to change two modules and part of this repo. I don't have much more time at the moment, but I can do it later today, maybe tomorrow.

Question: aside from term-vector, where is the stopwords module used? The simplest solution I can think of is to return tokens from stopwords instead of a joined string (which is immediately broken back into tokens anyway), but I don't want to break something I don't know about.

**Comment by ConnorKrammer** [comment]
Note to self when I do this: take a look at [line 108](https://github.com/fergiemcdowall/search-index-adder/blob/master/indexer.js#L108), since it assumes a space between tokens.

**Comment by ConnorKrammer** [comment]
I've more or less got this wrapped up, but I have a question about how search keys are composed: what do the `TF` and `RI` prefixes stand for?

**Comment by fergiemcdowall** [comment]
**T**erm **F**requency and **R**everse **I**ndex

**Comment by ConnorKrammer** [comment]
Thanks.

I ask because the modules make certain assumptions about separators that need shoring up a bit. The big one is that spaces are always assumed to be a safe separator, but might actually not be. Another is that the key and token separators never appear in an indexed field or field name. I've solved the first pretty adequately, but I thought I'd put together a lightweight key utility module so that we can pull out a lot of the hardcoded separators and DRY up the codebase (particularly the adder and searcher modules).

I'd do that separately though, if you're interesting in such a thing.

**Comment by fergiemcdowall** [comment]
For this improvement (can set separators for individual fields) there are the following requirements: 

- That the separator uses the standard [string split regex format](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/split)

- Any character should be safe as a separator since `search-index` uses the last possible unicode character (`￮`) as a system separator. If it was somehow possible to input a character that ends up after ￮ in an incremental sort, then the system wont work (so in other words- its cool, dont worry :smile: )

- The user should be able to separate with or without spaces, and indeed with or without any character. Its "fine" to not specify a separator, and that means that the whole field is indexed as one token (which would give you a basic kind of phrase search)

**Comment by ConnorKrammer** [comment]
1. Done.
2. There should still be issues if the user indexes on a field named "test￮field", for example, since that messes up the assumptions made when splitting keys into component parts on that character. There are also issues if the user (for whatever strange reason) decides that they need to search for a term including that system separator.
3. Done. I store a small field info key with the FI prefix that holds the separator that the user indexed the field on. This fails if the user indexes two batches where the same field has a different separator defined in each batch, however.

**Comment by fergiemcdowall** [comment]
Isnt it just a case of making a small one line change here?: https://github.com/fergiemcdowall/search-index-adder/blob/master/indexer.js#L110

`search-index` should be as forgiving as possible. There are definitely scenarios where it is desirable to index the same field in two batches with different separators in each batch.

**Comment by ConnorKrammer** [comment]
Yeah, I actually thought that too until I ran some tests. The problem originates from the space as a separator assumption I mentioned earlier. For example, on [line #33](https://github.com/fergiemcdowall/term-vector/blob/master/lib/term-vector.js#L33) and [line #68](https://github.com/fergiemcdowall/term-vector/blob/master/lib/term-vector.js#L68) of term-vector.js.

**Comment by ConnorKrammer** [comment]
My method of fixing this was to use a specific delimiter character instead of the generic space. I picked `￭`, which is right before `￮`. That solves it on the adding side, but then you need to store the separator regex so that you can compare against it properly when searching.

**Comment by fergiemcdowall** [comment]
Oh- in that case theres a bug in `term-vector`. Will fix ASAP. Space As A Separator Assumption = BAD

**Comment by ConnorKrammer** [comment]
I actually have a working solution on my side and was just getting ready to put together a set of pull requests to address the issue. If you want to fix it faster and give me a bit of time to get things organized, I can push my branches online. You can glance at my code to see how I fixed the problem and if you want to handle it differently.

**Comment by ConnorKrammer** [comment]
All right, all the changes that I plan to make pull requests for have been uploaded to my forked repositories. Here's a brief summary:

 - Remove assumption that spaces are valid separators: [stopwords](https://github.com/ConnorKrammer/stopword/commit/222dfb84be3710bedd7cd3d89fee32490fef5ed8)
 - Remove assumption that spaces are valid separators: [term-vector](https://github.com/ConnorKrammer/term-vector/commit/cfa723c5bfc2d2ca510cf3c6cb2c682090684b61)
 - Get custom separators per field working correctly when added: [search-index-adder](https://github.com/ConnorKrammer/search-index-adder/commit/26ad01b2734cbe5e5fac3ebd34607156a53df5b8)
 - Search correctly on fields that were created using custom separators: [search-index-searcher](https://github.com/ConnorKrammer/search-index-searcher/commit/b4ab8d080f05a6a19f3cedd0addefe51b587d424)

Additionally, [this commit](https://github.com/ConnorKrammer/search-index-adder/commit/26ad01b2734cbe5e5fac3ebd34607156a53df5b8) in search-index-adder fixes #259.

I've also finished putting together and testing (manually; no automated tests yet) a proposed key handler utility module that would help clean up the adder and searcher modules; you can look at that [here](https://github.com/ConnorKrammer/search-index-key-utils/blob/master/lib/key-utils.js).

**Comment by ConnorKrammer** [comment]
The proposed key handler utility is also nice because it further abstracts away all the string constants and key assembly processes.

**Comment by fergiemcdowall** [comment]
OK- I also started looking at the "separate not using space" issue in term-vector

**Comment by ConnorKrammer** [comment]
I'm pretty satisfied with how I've done it, but I'm interested in hearing your thoughts.

**Comment by ConnorKrammer** [comment]
Note that as per my above edit I've also pushed [this](https://github.com/ConnorKrammer/search-index-searcher/commit/65266960745a1b4a328c1dfc93f8cf053f5605da) and [this](https://github.com/ConnorKrammer/search-index-adder/commit/8c5220fe3a6fc40aeed7ad39a5c6c66e52fe7dd6) to implement field-specific stopwords correctly.

**Comment by fergiemcdowall** [comment]
Ah- you linked to the change, not the lib- doh! (too early in the morning...)

**Comment by ConnorKrammer** [comment]
I also didn't say that explicitly, so not totally your fault. :P

**Comment by fergiemcdowall** [comment]
@ConnorKrammer can you submit a pull request for `term-vector` ? That is a really valuable fix, and I can push it out ASAP.

**Comment by ConnorKrammer** [comment]
Okay, will do. It's dependent on my changes to stopword, also--want me to open a PR there too?

**Comment by fergiemcdowall** [comment]
yes

**Comment by ConnorKrammer** [comment]
Note also that [this commit](https://github.com/ConnorKrammer/search-index-adder/commit/11da8b0e7044da40a9298a384e8292049988b65a) to search-index-adder is required to finish removing the space as a delimiter assumption.

**Comment by fergiemcdowall** [comment]
OK- `term-vector` and `stopword` are both now updated to allow unambiguous tokenisation, including tokenisation rules that dont use spaces. Note that `stopword.removeStopwords` now returns an Array.

**Comment by ConnorKrammer** [comment]
term-vector is actually still broken on the spaces front, due to [this line](https://github.com/fergiemcdowall/term-vector/blob/master/index.js#L54).

**Comment by fergiemcdowall** [comment]
Ahh good point- that is the separator for ngrams, which is always set to space, but should be customisable

This test passes:

```javascript
  it('should be possible to customise seperators (exclude spaces)', function () {
    var text = 'some|words|like ståle synnøve Kjærsti|Gerät Kjærsti Grünnerløkka Kjærsti'
    var options = {}
    options.separator = /[\|]+/
    var vec = tv.getVector(text, options)
    vec.should.eql([ [ 'gerät kjærsti grünnerløkka kjærsti', 1 ],
      [ 'like ståle synnøve kjærsti', 1 ],
      [ 'words', 1 ] ])
  })
```

**Comment by fergiemcdowall** [comment]
I feel on reflection that the ngrams shouldnt actually have an output seperator, but should instead be Arrays

**Comment by ConnorKrammer** [comment]
Consider two cases:

```javascript
var singleToken = ["this is a single token"]; // no separator, so single token
var multiToken = ["this", "is", "a", "multi", "token"]; // space delimiter

var key1 = "TF￮fieldname￮" + singleToken.join(' ') + "￮￮";
var key2 = "TF￮fieldname￮" + multiToken.join(' ') + "￮￮";

var q = { query: { fieldname: ["this is a"] } };
```

This causes problems depending on your separator type and ngram length.

**Comment by ConnorKrammer** [comment]
Re: latest comment -- won't that cause problems with search speed and index size?

**Comment by ConnorKrammer** [comment]
Did you ever take a look at that [utility library](https://github.com/ConnorKrammer/search-index-key-utils/blob/master/lib/key-utils.js) I put together? It handles the current key form in a way that allows absolutely anything as a separator.

**Comment by fergiemcdowall** [comment]
Oh- thats a handy lib.

Re the ngrams thing- the keys will be unchanged, its just that moving the `.join`form term-vector to the host lib, so that if you had to have ngrams with another separator, you could. But as far as `search-index` is concerned, there is no change

**Comment by ConnorKrammer** [comment]
Okay, I thought you were referring to how they'd be encoded in the keys.

**Comment by ConnorKrammer** [comment]
Question: what's the reasoning for keeping all the modules in their own repos? They're all tightly coupled anyway (with the exception of stopwords and perhaps term-vector), so I'm curious why you split them up. Mainly because of the trouble it causes if implementing a change that touches multiple modules simultaneously.

**Comment by fergiemcdowall** [comment]
Its mainly to do with readability, slightly to do with reusability, and a lot to do with being able to configure custom search bundles.

The `term-vector` and `stopword` modules are actually downloaded more than `search-index`. People seem to be using them in other apps. The `search-index-*` modules exist separately so that you can pick & mix functionality for different use cases. On particular use case is being able to `browserify` bundles than only replicate and search (you dont want the weight and complexity of indexing in a read-only index).

You are right though- it is a headache bubbling up changes from underlying modules

**Comment by fergiemcdowall** [comment]
The original bug: "cant set stopwords and separators at a field level" is now fixed in the latest version of `search-index` (0.7.12). Thanks for @ConnorKrammer for bringing it up and identifying the fix.

**Comment by ConnorKrammer** [comment]
@fergiemcdowall Sorry to do this to you, but it's not quite there yet. The problem is that there's currently no way of recovering a separator for a given field, and that has implications for how searches work.

For example:

```javascript
var indexMe = {
    testField: "This is a string. Sep. Sep."
};

var fieldOptions = {
    testField: { separator: ' ' },
    nGramLength: 2
};

// add to index

var q = {
    query: { testField: ["Sep. Sep."] }
};

// search will get zero hits

var q2 = {
    query: { testField: ["Sep Sep"]}
};

// search will match correctly
```

Why is this happening? Well, in search-index-adder the query is [run through the stopword remover](https://github.com/fergiemcdowall/search-index-searcher/blob/master/searcher.js#L23) and stripped of all stopwords. That requires it to be tokenized, so it's split on a separator... but that separator happens to be the default of `/[\|' \.,\-|(\n)]+/`, which splits on more than just the space. This means that our query gets tokenized into `sep￮sep` instead of `sep.￮sep.` (notice the difference in periods). Since the field was originally tokenized on only spaces, it needs the latter to match, not the former.

The solution is to store the separator regex and recover it so that you can use it to tokenize the query correctly. You can view my fork of the search-adder and search-indexer modules to see how I approached this, though you may want to do it differently.

**Comment by fergiemcdowall** [comment]
Im _pretty_ sure that the following will work as it is set up just now:

```javascript
var indexMe = {
    testField: "This is a string. Sep. Sep."
};

var fieldOptions = {
    testField: { separator: ' ' }, // only spaces
    nGramLength: 2
};

// add to index

var q = {
    query: { testField: ["string.", "sep."] } // search should match (note that testField takes a lowercased array)
};

var q = {
    query: { testField: ["string", "sep"] } // search should NOT match since "."s are missing
};
```

**Comment by ConnorKrammer** [comment]
Sorry, I had an error in my example--I shouldn't have used a space as a separator, because that's also the default ngram separator in the example. Your example should work (though there's a slightly related quirk that can happen there; I'll mention that in a moment.)

Fixed example:

```
var indexMe = {
    testField: "This is a string_sep_sep"
};

var fieldOptions = {
    testField: { separator: '_' }, // not a space
    nGramLength: 2 // need this because we're testing how searches work across separators
};

// add to index

var q = {
    query: { testField: ["sep_sep"] } // search will not match
};

var q2 = {
    query: { testField: ["sep sep"]} // search will match
};
```

Setting the field's `nGramSeparator` to an underscore doesn't work either, because then `q2` will match, but `q` won't. This is happening because the search query isn't run through the same tokenization system as the original text.

The related quirk I mentioned: Including separators in your query (aside from the ngram separator) will cause you to get zero hits. Consider:

```
var indexMe = {
    testField: "This is a person's name: Mr. Gregor"
};

var fieldOptions = {
    testField: { separator: /\. /g }, // Spaces and periods
    nGramLength: 2 // need this because we're testing how searches work across separators
};

// add to index

var q = {
    query: { testField: ["Mr. Gregor"] } // search will not match
};

var q2 = {
    query: { testField: ["Mr Gregor"] } // search will match (missing period)
};
```

This happens for the same reason: the query isn't being run through the same tokenization system as the text was when it was indexed. In the "Mr. Gregor" example, the 2-word ngram is tokenized as `mr gregor`, with no period,and therefore can't match a query that contains a period. The fact that it matches the space is just coincidental because that's also the ngram separator.

Using spaces, which are incredibly common, has the effect of masking a lot of potential errors that crop up when they're not used.

**Comment by ConnorKrammer** [comment]
@fergiemcdowall Sorry, I had an error in my example--I shouldn't have used a space as a separator, because that's also the default ngram separator in the example. Your example should work (though there's a slightly related quirk that can happen there; I'll mention that in a moment.)

Fixed example:

```
var indexMe = {
    testField: "This is a string_sep_sep"
};

var fieldOptions = {
    testField: { separator: '_' }, // not a space
    nGramLength: 2 // need this because we're testing how searches work across separators
};

// add to index

var q = {
    query: { testField: ["sep_sep"] } // search will not match
};

var q2 = {
    query: { testField: ["sep sep"]} // search will match
};
```

Setting the field's `nGramSeparator` to an underscore doesn't work either, because then `q2` will match, but `q` won't. This is happening because the search query isn't run through the same tokenization system as the original text.

The related quirk I mentioned: Including separators in your query (aside from the ngram separator) will cause you to get zero hits. Consider:

```
var indexMe = {
    testField: "This is a person's name: Mr. Gregor"
};

var fieldOptions = {
    testField: { separator: /\. /g }, // Spaces and periods
    nGramLength: 2 // need this because we're testing how searches work across separators
};

// add to index

var q = {
    query: { testField: ["Mr. Gregor"] } // search will not match
};

var q2 = {
    query: { testField: ["Mr Gregor"] } // search will match (missing period)
};
```

This happens for the same reason: the query isn't being run through the same tokenization system as the text was when it was indexed. In the "Mr. Gregor" example, the 2-word ngram is tokenized as `mr gregor`, with no period,and therefore can't match a query that contains a period. The fact that it matches the space is just coincidental because that's also the ngram separator.

Using spaces, which are incredibly common, has the effect of masking a lot of potential errors that crop up when they're not used.

**Comment by fergiemcdowall** [comment]
I see your point- do you have any really good killer use cases? The "Mr. Gregor" case is fairly easily solved by simply stripping away spaces and periods in the indexing and query pipelines. When do you absolutely, positively have to preserve ngram separators?

**Comment by ConnorKrammer** [comment]
Any time a safe separator isn't known and that separator might appear in the text. (And with dynamic, user-generated content indexed off the web, that's basically 100% of the time.)

I'm using this project to index a blog and its comments, and even a simple setup like that caused me to run into the separator limitations. That's what lead me to open this issue, and then to write a working implementation on my own fork. (The pull requests were just for the spaces thing, but I actually did all of it. That key handling library I showed you was going to be the final step to completely sanitizing all input and output so that it worked for any character--even the system separator `￮`.)

I'm not sure how killer the use case has to be, but the library is currently working on a set of assumptions that create some very non-obvious edge cases. That'll happen any time someone wants to match against something containing a separator, or when the default space isn't a valid separator but something else is. For example, underscore separated content tags, or URLs, or even just English contractions (can't, won't, shouldn't, etc.). At the moment `'` is a valid word separator, so if I want to search with the default settings I can't even use an apostrophe in one of the search terms.

**Comment by fergiemcdowall** [comment]
I see your point about contractions. Phrases like "Can't be done" should definitely work out of the box.

**Comment by ConnorKrammer** [comment]
It's possible to keep hammering down edge cases until it probably works most of the time, but a robust solution is going to save a lot of time and pain in the future, for both maintainers and users.

For what it's worth, I spend a long time thinking about this. I'm a pretty lazy guy, but I couldn't think of a way around it.

**Comment by fergiemcdowall** [comment]
Re english contractions:

A quick and dirty hack would be to alter the separator regex to that it matches " '", "' ", "'. " instead of just "'"

**Comment by ConnorKrammer** [comment]
Yep, at the cost of slowing down a regex that could be executed hundreds of thousands of times in the course of indexing a set of documents.
