### ISSUE TITLE
Better handling of numeric values

### ISSUE THREAD

**Issue by ConnorKrammer** [fergiemcdowall/search-index#259]
The way searches handle numeric values doesn't appear to be consistent across the `query` and `filter` options. For example:

 ```javascript
var q = {};

// Equivalent for both numeric and string values of num
q.query =  { num: [1000] };
q.query = { num: ["1000"] };

// Equivalent for string values of num (but unexpected behaviour)
// Both fail entirely on numeric values of num
q.filter = { num: [[0, 5]] };
q.filter = { num: [["0", "5"]] };
```

The way that `q.query` behaves seems logical: the field is searched for the presence of the number. That holds true whether the field contains a string or a number, and whether the query is phrased in terms of a string or a number. All good here.

However, filters (and I assume facets; I didn't test them) aren't consistent like that. To start, filtering on a numeric field doesn't seem to be possible--all of my attempts returned zero results. Filtering on string fields worked, but not in the way I expected. Using the above query, for example, doesn't filter for all values from 0 to 5; it actually filters for values that contain a *substring* that can be any value from 0 to 5. That means that values of  "0", "1", "2", ..., "5" work as expected, but so do "10", "33", and "12345". This explains why zero-padded strings are used in the API reference and test suite, but isn't consistent with how queries work--queries operate by matching full word units, but filters don't, at least in this case. This behaviour is also undocumented so I had to spend a significant amount of time to figure it out. (Filters in general are poorly documented, and don't appear on the [search page](https://github.com/fergiemcdowall/search-index/blob/master/doc/search.md). In the [API reference](https://github.com/fergiemcdowall/search-index/blob/master/doc/API.md#search) the `filter` option is incorrectly listed as the plural form `filters`.)

**Edit**: I think I've just concluded that I have no idea how facets or filters are supposed to work. I tried faceting a string, and it came back to me broken down by letter. I expected it to come back broken down by all possible values for that string across all documents in the index. Is there somewhere I find this documented?

**Comment by eklem** [comment]
The last part, when faceting a string. You need the string in an array I think.

**Comment by fergiemcdowall** [comment]
Thanks for the feedback: filters and facets need to be better explained, and this is something that is in the pipeline.

In search-index all field values are treated as strings- this is a conscious design decision to keep indexes compact, and to avoid the "schema hell" that plagues strongly typed search engines such as Solr.

Re the wierd substring issue: strings are also arrays under the hood. You shouldnt be able to filter on a field that is not in an array format, but I suspect a bug has allowed you to index a single string as an array. Make sure that your filter field is in array format.

If you have time to make a small test case and post it here, then we can sort it out for you

**Comment by eklem** [comment]
Check [this JSON](https://github.com/eklem/search-index-indexer/blob/master/data-missing-field.json). Here I'm creating facets on `user`, `tags` and `type`.

**Comment by ConnorKrammer** [comment]
Okay, I figured out where the bug was that treated strings as arrays. As an added bonus, it also fixed the inconsistency with how numbers are treated by filters.

I'll put in a pull request to fix this later today.

**Comment by fergiemcdowall** [comment]
Great! and +1 for pull request

**Comment by fergiemcdowall** [comment]
Strings can now no longer be recognised as arrays when the field is being filtered on. If your filter field contains "banana" then search-index will index `['banana']` and not `['b','a','n','a','n','a']`

**Comment by eklem** [comment]
That's great. Quite a lot of confusion about this one.
