### ISSUE TITLE
Document how to add word stemmer to search and indexing pipelines

### ISSUE THREAD

**Issue by ConnorKrammer** [fergiemcdowall/search-index#260]
For users searching text where some degree of forgiveness is preferred (such as in old documents, or text where the user isn't familiar with the content) we can increase recall by adding an optional stemming step to the indexing/search pipeline. This means that "walk", "walking", "walked", and "walks" would all map to the same word stem. One nice benefit from doing this, aside from increased search recall, is that the number of unique words in the index will be reduced, allowing for potentially smaller indexes (when the option is turned on).

The basic process for doing this would be to run fields through the stemmer when they are first being indexed, and to run search queries through the stemmer as well when searching the index (because otherwise they won't match reliably). Since we have field-specific separators and stopwords, we should probably allow field-specific stemming if we implement this.

[Here's one implementation for the English language.](https://github.com/wooorm/stemmer) One thing to consider is that stemmers require different algorithms for each language, so it might be best to accept a function in fieldOptions and let the user choose the implementation. Alternatively, we could open up an entire text processing pipeline to allow arbitrary manipulations of text by the user; that would allow this feature and many others.

**Comment by fergiemcdowall** [comment]
Yes this is definitely something that most people would need in their implementations.

**Comment by eklem** [comment]
A document processing pipeline where it's easy to plug in different modules would be really handy.

**Comment by fergiemcdowall** [comment]
This functionality now exists, so its just a case of making an example.

**Comment by nevf** [comment]
+1 Definitely something I need in order to use search-index.

**Comment by eklem** [comment]
@fergiemcdowall: It's now a popular demand by @ConnorKrammer, @drzraf, @abastardi, @nevf,  and me =)

**Comment by drzraf** [comment]
starting some reverse engineering about this: _Synonyms_, like _stemmers_ may be implementable through [docproc](https://github.com/fergiemcdowall/search-index/blob/master/docs/add.md#document-processing-pipeline) => https://github.com/fergiemcdowall/docproc
There, it _seems_ that the `vector` is field to fill with word's variant/synonyms/...

That may point to the [CreateCompositeVector.js](https://github.com/fergiemcdowall/docproc/blob/master/pipeline/CreateCompositeVector.js) file.
But so far, constructor does not take paremeter and there are no real clue from there.

**Comment by fergiemcdowall** [comment]
@drzraf yes, that would be the correct approach. Simply add processing stages in or around `docproc`

**Comment by drzraf** [comment]
Do you have a sample about the expected way to index synonyms?
ex: indexing "dog" would also return the result when searching "animal"?
Another point I missing documentation is about stemming.
Should we simply add `word` and `stem(word)`  to the `vector` array?
