### ISSUE TITLE
Q: How the index works?

### ISSUE THREAD

**Issue by eklem** [fergiemcdowall/search-index#267]
Just a quick question, Fergus. The index consists of two different things:

1. The actual documents
2. The word index

And the word index is the one where stopwords gets stripped before entering? But what about the document index, that keeps everything?

**Comment by fergiemcdowall** [comment]
The actual documents and a REVERSE INDEX (also known as an INVERTED INDEX). Documents are then scored using tf-idf. Its a pretty basic, but robust algorithm

**Comment by eklem** [comment]
Thanks! Are the stopwords used on the documents too?

**Comment by fergiemcdowall** [comment]
Documents are stored "as is", stopwords are not stripped

**Comment by eklem** [comment]
Thank you, then I have a bit more for [stopwords](/eklem/search-index-cookbook/blob/master/doc/reference/stopwords.md) and [search-index](/eklem/search-index-cookbook/blob/master/doc/reference/search-index.md) over at the [`search-index-cookbook`](/eklem/search-index-cookbook) =)

**Comment by eklem** [comment]
And one more question about this. We have the matcher and the searcher. And the matcher uses a different part of the index, where you have partial words?
