### ISSUE TITLE
Open a new room on gitter.im?

### ISSUE THREAD

**Issue by BlueBlock** [fergiemcdowall/search-index#273]
To aid quick discussion and help could you create a room for this repo on gitter.im?

**Comment by fergiemcdowall** [comment]
Thats a good idea- am offline for the next couple of hours, but will look into it ASAP.

One thing though: Slack vs Gitter- which is better and why?

**Comment by BlueBlock** [comment]
I've honestly never used slack but have been using gitter.im for participating in another project. 

If gitter.im doesn't seem to work out the room could always be removed.

**Comment by blahah** [comment]
A vote for Gitter from me.

On Slack vs Gitter - gitter is specifically designed for discussion of code projects (especially github repos). Slack is more like a general team chat app - the code-specific stuff is an afterthought rather than the core purpose.

**Comment by eklem** [comment]
And Gitter gives you full history, while Slack purges history/tail longer than 10000 messages.

**Comment by eklem** [comment]
https://gitter.im/fergiemcdowall/search-index
