### ISSUE TITLE
Quickstart attempt but I'm not sure what 'options' should be

### ISSUE THREAD

**Issue by BlueBlock** [fergiemcdowall/search-index#274]
I'm attempting to try the quickstart and my code is below. I get an error "Cannot read property 'deleteBatch'. Is 'options' supposed to contain values?

        var jsonFile = "test.json";
        var searchIndex = require('search-index');
        var options = {};
        var data = require(jsonFile);
        searchIndex(options, function(err, si) {
          si.add(data, undefined, function (err) {
            if (err) console.log('oops! ' + err)
            else console.log('success!')
          })
        });

**Comment by fergiemcdowall** [comment]
Your `.add` should look something like this for it to work (use `{}` instead of `undefined`):

`si.add(data, {}, function (err) {`

**Comment by fergiemcdowall** [comment]
It should probably fail gracefully if the options object is `undefined` though...

**Comment by BlueBlock** [comment]
Is there a minimal working example?

**Comment by fergiemcdowall** [comment]
The search API just changed- try:

q.query = {AND:{'*': ['united']}};

There are lots of examples in the `test` directory

**Comment by BlueBlock** [comment]
Excellent, thanks!

**Comment by fergiemcdowall** [comment]
The quickstart should have been updated but wasnt- I just did it now
