### ISSUE TITLE
Ability to merge resultsets

### ISSUE THREAD

**Issue by fergiemcdowall** [fergiemcdowall/search-index#277]
It should be possible to query 2 or more search-index nodes and then merge the results. Possibly/probably a separate lib

**Comment by eklem** [comment]
Nice! This is good suff, @fergiemcdowall



[image: --]

Espen Klem
[image: https://]about.me/klemespen
<https://about.me/klemespen?promo=email_sig>

**Comment by fergiemcdowall** [comment]
related to #127

**Comment by fergiemcdowall** [comment]
implemented with https://github.com/fergiemcdowall/search-index/commit/3183ddc63158d9842f3051e62d87c73f9001c167
