### ISSUE TITLE
Replication and Options (fieldsToStore)

### ISSUE THREAD

**Issue by iSOcH** [fergiemcdowall/search-index#278]
i'm trying to create and replicate an index with `fieldsToStore` set on initialisation.
when querying that index after replication I get hits, but the documents returned from `search` are always `undefined`.
the same operation without `fieldsToStore` returns the documents as they were stored.

with `fieldsToStore`
```
{ totalHits: 1,
  totalDocsInIndex: 3,
  documentFrequencies: { '*￮austausch': 1 },
  fieldWeight: { '*￮austausch': 0 },
  query: [ { AND: [Object], NOT: [Object] } ],
  buckets: [],
  categories: [],
  hits:
   [ { id: '0.7027325540540822,39',
       score: 0,
       tfidf: [Object],
       document: undefined } ] }
```

without `fieldsToStore`:
```
{ totalHits: 1,
  totalDocsInIndex: 3,
  documentFrequencies: { '*￮austausch': 1 },
  fieldWeight: { '*￮austausch': 0 },
  query: [ { AND: [Object], NOT: [Object] } ],
  buckets: [],
  categories: [],
  hits:
   [ { id: '39',
       score: 0.4230871553996776,
       tfidf: [Object],
       document: [Object] } ] }
```

do I have to set `fieldsToStore` (or something similiar) when receiving data from a replication? i empty the target index using `flush()` before calling `replicate`

another difference I noticed between source and target of replication (also only when using `fieldsToStore`) is in the id field: on source I get `id: '39'` and on target it's `id: '0.7027325540540822,39'`

**Comment by fergiemcdowall** [comment]
Hmm- thats strange, `document` _should_ be the document, minus the fields which you didnt want to store.

**Comment by iSOcH** [comment]
thanks for you quick response :)
so I do not have to configure the fields on the target?
the search works well on the source...

**Comment by fergiemcdowall** [comment]
During initialisation yes.

The initialisation API was recently rewritten, and I see now that `fieldsToStore` should most probably be a `fieldOptions` parameter

**Comment by eklem** [comment]
Wouldn't it be nice to be able to just "copy" without thinking and defining too much?

**Comment by fergiemcdowall** [comment]
@eklem if you dont define anything- it will just default to storing the field, which is what is expected (was that what you meant? )

**Comment by eklem** [comment]
My bad, exactly what I wanted @fergiemcdowall =)

**Comment by iSOcH** [comment]
@fergiemcdowall so... is there a sample for the functionality i'd like to use?

I do the following:

source:
- create index with `fieldsToSet` (and `deletable: false`)
- `add` documents without additional options
- `snapshot` and send the data to target

target (initial):
- create empty index (without any options except for path and `deletable: false`)

target (on receiving data):
- `flush()` existing index
- `replicate` without options

**Comment by fergiemcdowall** [comment]
Here is a snippet from the tests that demonstrates how it works

```javascript
  it('should index one file of test data and only store id and title (but allow all other fields to be searchable)', function (done) {
    this.timeout(5000)
    var opt = {}
    opt.fieldsToStore = ['id', 'title']
    opt.batchName = 'reuters'
    si8.add(data, opt, function (err) {
      (err === null).should.be.exactly(true)
      done()
    })
  })

  it('doc should still be present in index', function (done) {
    var q = {}
    q.query = {
      AND: {'*': ['stock']}
    }
    si8.search(q, function (err, searchResults) {
      should.exist(searchResults)
      ;(err === null).should.be.exactly(true)
      searchResults.hits.length.should.be.exactly(4)
      searchResults.hits[0].id.should.be.exactly('4')
      searchResults.hits[1].id.should.be.exactly('9')
      searchResults.hits[2].id.should.be.exactly('10')
      searchResults.hits[3].id.should.be.exactly('8')
      searchResults.hits[0].document.should.eql({
        id: '4',
        title: 'TALKING POINT/BANKAMERICA <BAC> EQUITY OFFER'
      })
      done()
    })
  })
```

The API for this will almost certainly change before 1.0.0 since `fieldsToStore` definitely belongs in `fieldOptions` as "store" or something similar

**Comment by fergiemcdowall** [comment]
Here is the test file https://github.com/fergiemcdowall/search-index/blob/master/test/node/reuters-tests/indexing-options-test.js

**Comment by fergiemcdowall** [comment]
Oh- Sorry. I think we have been talking past each other (my fault)

`fieldsToStore` only takes effect on indexing. When you replicate the index, you can only replicate "as is", you cannot morph it in any way (although that would be really interesting to investigate).

In the example above, you will always replicate the documents as they were when you indexed them.

What is the use-case you would like to solve?

**Comment by iSOcH** [comment]
thanks for that example - that test however does not include `snapshot` and `replicate`.

I did notice where the problem comes from, my assumption regarding `fieldsToStore` having an influence was wrong - it seems the data generated from `snapshot` is not portable... it works if sender and receiver are both linux, and when they're both windows, but not when mixed :/

**Comment by fergiemcdowall** [comment]
@iSOcH hmmm- replicating from linux to windows _should_ work, since the export file is simply gzipped text. This is possibly an encoding issue.

Have you tried examining the file on your windows machine? Is it readable?

**Comment by iSOcH** [comment]
seems like you're right... I now managed to make my linux target understand data sent from both windows and linux :)
but the windows target is now completely broken :D

**Comment by iSOcH** [comment]
... now it seems everything works - even without specifying the encodings...

... is it possible that 0.8.3 or 0.8.4 is incompatible with 0.8.2 in this regard?

**Comment by fergiemcdowall** [comment]
Functioning replication is only guaranteed between indexes running the exact same version of `search-index`. All 0.8.x indexes _should_ work with each other, but its not tested, and therefore not guaranteed.

**Comment by iSOcH** [comment]
thanks for the info :+1:
would be nice if that was documented somewhere (or is it and I did not find it?)

**Comment by eklem** [comment]
Added it to the documentation task/issue

**Comment by fergiemcdowall** [comment]
@iSOcH please feel free to submit improvements to the docs!
