### ISSUE TITLE
Ability to index from streams

### ISSUE THREAD

**Issue by fergiemcdowall** [fergiemcdowall/search-index#280]

**Comment by eklem** [comment]
Meaning it can continue to index when new stuff appears?

**Comment by fergiemcdowall** [comment]
Meaning that it doesnt have to download an entire Array before it starts to index. In this case batching would be handled internally.

**Comment by eklem** [comment]
If you work on this, I'll look at the other end =)

**Comment by eklem** [comment]
And it sounds a lot more robust!

**Comment by fergiemcdowall** [comment]
Now works, but implemented in a "hidden" API

https://github.com/fergiemcdowall/search-index/blob/master/test/node/general-tests/stream-test.js#L38
