### ISSUE TITLE
Level Up backends

### ISSUE THREAD

**Issue by disordinary** [fergiemcdowall/search-index#283]
Hi,

The documentation is out of date and a quick look through the source code makes it look like there is no longer the option to replace leveldb as the backend for levelup?

**Comment by eklem** [comment]
This should still be working, @fergiemcdowall ? Think it's just about documentation.

**Comment by eklem** [comment]
It's on [the list](https://github.com/fergiemcdowall/search-index/issues/263) of what to improve in the documentation.

**Comment by disordinary** [comment]
If you point me to an example somewhere, or even in vaguely the right direction I'll amend the documentation and put through a pull request. I couldn't find any examples in the test suite either. 

I got it working but I had to hack things a bit, so if there is an elegant way I'd love to know.

**Comment by eklem** [comment]
I'm not a good enough programmer to know, but does this tell you something? A browserify-example: https://github.com/fergiemcdowall/search-index-replicate-index-to-browser-example/blob/master/main.js

**Comment by fergiemcdowall** [comment]
@disordinary The general mechanics of passing a pre-existing `levelup` to `search-index` are demonstrated here: https://github.com/fergiemcdowall/search-index/blob/master/test/node/general-tests/providing-levelup-test.js

You can of course instantiate that `levelup` with any `leveldown`.

So to change the backend, you make a new `leveldb` with the `leveldown` of your choosing, and then pass that `leveldb` to `search-index`

**Comment by fergiemcdowall** [comment]
I just added an sqlite test/demo to the tests directory: https://github.com/fergiemcdowall/search-index/blob/master/test/node/general-tests/sqlite-test.js

**Comment by disordinary** [comment]
Brilliant, thanks @fergiemcdowall
