### ISSUE TITLE
How to sort indexed documents?

### ISSUE THREAD

**Issue by Feelnoobskill** [fergiemcdowall/search-index#286]
I have following structure of indexed documents:
`[{date: 1464122926, text: 'some text'}, {date: 1464122916, text: 'some another text'}]`

I want to sort documents by date. Here is my code:
`      var q = {};
        q.query = {
            AND: [{'*': ['text']}] 
        };
        q.categories = {
            field: 'date',
            sort: 'valueDesc'
        };
`

But it seems that it doesn't  work and my documents are in random order. What I'm doing wrong?

**Comment by fergiemcdowall** [comment]
Yo @Feelnoobskill thanks for reaching out.

Short answer: if you use timestamps in the `id` field, then the order will always be newest to oldest when doing a `*` search: `{AND: [{'*': ['*']}]}`. You could then use filters, buckets and categories to filter out results that you want.

```javascript
[
  {
    id: 1464122926
    text 'some text'
  },
  {
    id: 1464127894
    text 'some more text'
  },
]
```

Longer answer: `search-index` sorts things by relevance. If you type in "text", it will find the documents that contain "text", and then order them by their relevance for the word "text". So "Texty McTextFace text text text", would come higher than say, "This is really about something else, but hey- text amirite?".

**There is also the possibility to sort on a given field**. So another option is to do specify a sort field. The docs are a bit rubbish at the moment- but if you read this unit test you will see how it is done: https://github.com/fergiemcdowall/search-index/blob/master/test/node/general-tests/sorting-test.js

**Comment by Feelnoobskill** [comment]
@fergiemcdowall thanks for such quick and usefull response
