### ISSUE TITLE
Query aliases

### ISSUE THREAD

**Issue by fergiemcdowall** [fergiemcdowall/search-index#287]
Now that queries are more powerful, they are also more user hostile. Simple queries are quite complicated to write. For example:

"find everything, sort on ID"
`{AND: {'*': ['*']}}` could be `*`

"find banana"
`{AND: {'*': ['banana']}}` could be `banana`

If no query is specified, `search-index` could default to `*`

**Comment by eklem** [comment]
I think the `*`-search could be a good thing to turn on, but maybe not something everybody would want? I was thinking about asking for it, but then thought it may be some cases that wouldn't fit so well.

**Comment by fergiemcdowall** [comment]
done

**Comment by eklem** [comment]
Cool. Also testing last couple of days with 5000 items in index. The "*"-query becomes really slow when that many results. Here's a working example on that: http://oppskrift.klemespen.com:3030/search?q={%22query%22:[{%22AND%22:[{%22*%22:[%22*%22]}]}],%22categories%22:[{%22field%22:%22ingredients%22,%22limit%22:10}],%22pageSize%22:10}

**Comment by fergiemcdowall** [comment]
Yes, I see what you mean- _hopefully_ this dataset will work a bit faster on the new version. Its always nice to try out new datasets though!!

**Comment by eklem** [comment]
I'm crossing my fingers! The "*"-query could be a great way of populating pages and showing something more than an empty page when people enter.
