### ISSUE TITLE
Stopwords filtering when querying?

### ISSUE THREAD

**Issue by eklem** [fergiemcdowall/search-index#288]
Could it be an idea to have an option to filter out stopwords before they are matched against term frequency. Keep it in the search box, but just not query the index?

**Comment by fergiemcdowall** [comment]
I dont think so...

Stopwords were filtered query-side before, but it created a lot of confusion (Im sure there are a few bugs in the archive)

Another reason is that stopwords can be set per field/batch when indexing so there is no good way to know _which_ stopwords to use

**Comment by eklem** [comment]
Yes, was afraid of something like tha =)
