### ISSUE TITLE
Fix examples to fit newest API

### ISSUE THREAD

**Issue by eklem** [fergiemcdowall/search-index#289]
- [x] search-index-indexing-in-browser
- [ ] search-index-localstorage-example
- [x] search-index-replicate-index-to-browser-example
- [ ] browserify-index-and-search-in-webworker 
- [ ] indexing-from-pouchdb
- [x] simple-node-js-example

The examples needs a little brushup to fit the newest API
https://github.com/fergiemcdowall/search-index/blob/master/doc/EXAMPLES.md

**Comment by eklem** [comment]
PR for `simple-node-js-example`: https://github.com/fergiemcdowall/search-index-simple-node-js-example/pull/1

**Comment by eklem** [comment]
When trying to upgrading the others, I get different browserify-issues that I don't understand anything of.

**Comment by eklem** [comment]
Some changes in `search-index` that is not compatible with `browserify` ?

**Comment by fergiemcdowall** [comment]
The pouchdb and localstorage examples are nice-to-have rather than essential. Webworkers have come along a bit in the last year or so, so the webworker howto/example will probably have to be written again from scratch.

**Comment by fergiemcdowall** [comment]
External examples are difficult to keep updated. I propose that we keep a limited set of "core" examples in the `doc` directory- then it will be easier to tie them in to the relevant version.

**Comment by fergiemcdowall** [comment]
I _think_ the docs are all updated now? Taking the chance and closing

**Comment by eklem** [comment]
I'll create new issues if I see something =)
