### ISSUE TITLE
Problems with search function

### ISSUE THREAD

**Issue by Feelnoobskill** [fergiemcdowall/search-index#290]
Hi @fergiemcdowall,
Something strange has happened with my code and right now I can search only if I'll type full text. 
For example:
```javascript
si.add([
  {date: 1464122926, text: 'some text'},
  {date: 1464122916, text: 'some another text'}
],
function (err) {
  if (! err) {
    var q = {}; 
    q.query = { AND: [{'*': ['text']}] };
    si.search(q, function (err, results) {
       console.log(results);
    })
  }
})
```

In this case I'll get empty result, but if I'll change  query to `q.query = { AND: [{'*': ['some text']}] };` it will give me results. Thanks for help

**Comment by fergiemcdowall** [comment]
So you want hits on `['some text']` and hits on `['some', 'text']` ? If so, this is how you do it:

```javascript
require('search-index')({
  nGramLength: [1, 2, 3],   // allow phrase search on phrases of length 1, 2 and 3 words
  stopwords: []             // dont strip out stopwords
}, function(err, si) {
  si.add([
    {date: 1464122926, text: 'some text'},
    {date: 1464122916, text: 'some another text'}
  ], function (err) {
    if (! err) {
      var q = {};
      q.query = { AND: [{'*': ['text']}] };
      si.search(q, function (err, results) {
        console.log(results);
      })
    }
  })
})
```

1) Use `nGramLength` to activate phrase search

2) Set stopwords to `[]`. By default, `search-index` will remove common english words like 'some' and 'another', so you need to empty your stopword list to allow them to be searchable (you could also remove them from the stopword list individually)

**Comment by Feelnoobskill** [comment]
The problem is that I want to find documents that contains 'text' in it.
Here is some examples:
`si.add([
            {date: 1464122926, text: 'some text'},
            {date: 1464122916, text: 'some another text'}
        ], function (err) {
            if (! err) {
                var q = {};
                q.query = { AND: [{'*': ['text']}] };
                si.search(q, function (err, results) {
                    console.log(results);
                })
            }
        })`
Returns: 
`{ query: [ { AND: [Object], NOT: [Object] } ],
  hits: [],
  totalHits: 0,
  facets: undefined }`

But it should return both documents, right?
Another example:
`si.add([
            {date: 1464122926, text: 'some text'},
            {date: 1464122916, text: 'some another text'}
        ], function (err) {
            if (! err) {
                var q = {};
                q.query = { AND: [{'*': ['some text']}] };
                si.search(q, function (err, results) {
                    console.log(results);
                })
            }
        })`
So I put full text into search and result is:
`{ totalHits: 1,
  totalDocsInIndex: 2,
  documentFrequencies: { '*￮some text': 1 },
  query: [ { AND: [Object], NOT: [Object] } ],
  buckets: [],
  categories: [],
  hits:
   [ { id: '1-808a12b03294df9d1c302a837e0ff89f6b4a3dd2',
       score: 0.4320166484854422,
       tfidf: [Object],
       document: [Object] } ] }`

**Comment by fergiemcdowall** [comment]
Does the example that I posted work for you? How are you initializing search-index? Could you post a test case that includes the initialization parameters? (like the one I posted above)

**Comment by Feelnoobskill** [comment]
Seems like something strange is going on in my project because I installed search-index module into another folder and it's working.Anywa here is the code that isn't working for me:
```javascript
var options = { 
        indexPath: path.join(__dirname, index_folder), 
        logLevel: 'error', 
        'separator': /[\|',|(\n)]+/,
        stopwords: []
    };

    require('search-index')(options, function (err, si) {

        si.add([
            {date: 1464122926, text: 'some text'},
            {date: 1464122916, text: 'some another text'}
        ], function (err) {
            if (!err) {
                var q = {};
                q.query = {AND: [{'*': ['text']}]};
                si.search(q, function (err, results) {
                    console.log(results);
                })
            }
        });

    });
```

**Comment by fergiemcdowall** [comment]
Oh- its your `separator` param thats wrong- you need to include the space char in your string split regex.

Try this:

```javascript
separator: /[\|', |(\n)]+/,
```

**Comment by fergiemcdowall** [comment]
and btw: thanks for formatting your code- much easier to read!

**Comment by Feelnoobskill** [comment]
Thanks for help.

Yeah, I'm sorry for the formatting. I'm new to writing issues at Github (facepalm) but I found how to format it correctly :). Sorry about that

**Comment by fergiemcdowall** [comment]
So you got your search to work?

**Comment by Feelnoobskill** [comment]
Yes, finally. Many thanks
But its weird, because it worked earlier without adding space char
