### ISSUE TITLE
match() with just a subset?

### ISSUE THREAD

**Issue by jacargentina** [fergiemcdowall/search-index#293]
AFAIK match works on all words on every field of every document stored on the index, right?
In my case i have an index with a field named `book`, and other named `text` with the book page contents.

I want to write a suggestion list but only for the words on `text` whose `book: the-book-key`

Hope it is understood. Anyway if its not possible to implement right on the matcher, another option should be to build a different index for each book, and then match on the appropiate index.

**Comment by fergiemcdowall** [comment]
You can match on tokens from an individual field- see here for an example: https://github.com/fergiemcdowall/search-index/blob/master/test/node/general-tests/matching-test.js#L131

**Comment by eklem** [comment]
But to have it narrowed down per document (which here is a book), which is what I think you're asking for @jacargentina, is not currently possible, @fergiemcdowall ?

**Comment by jacargentina** [comment]
@eklem exactly:i just need the matchs on field `text` but where its field `book` equals `a specific book`

**Comment by fergiemcdowall** [comment]
Oh- i see!

At the moment you have to generate a field in every document called '<text><bookid>' and then specify that field in the matcher. Since the fieldname is unique to each book, it should work.

**Comment by fergiemcdowall** [comment]
Oh- i see!

At the moment you have to generate a field in every document called 'text<bookid>' and then specify that field in the matcher. Since the fieldname is unique to each book, it should work.

-- 
Apologies for brevity- this message was sent from my mobile

**Comment by jacargentina** [comment]
Yeah, nice trick. I'll try that.
