### ISSUE TITLE
Offtopic: Regexp for separator with version numbers as a term

### ISSUE THREAD

**Issue by jacargentina** [fergiemcdowall/search-index#294]
I know it may not be the best to post this here; but hope my fellow `search-index` devs/users would help me faster thas posting on SO

I'm coming a long way after posting the issue #180 

Now i'm realising that my custom separator `/[ (\n)]+/` is solving the version numbers problem, but now i have a problem with the rest of the words, as the dot is not separating my words, so all finishing sententes dots are being indexed as the last character for their words

Anybody can point me the correct RegExp to handle both cases well?

**Comment by fergiemcdowall** [comment]
How are your version numbers formatted?

**Comment by jacargentina** [comment]
The version numbers are a.b.c.d (ej `16.2.0.0`)

**Comment by eklem** [comment]
I'm not so good at regexp but the [Regular Exressions 101](https://regex101.com/#javascript) is a nice sandbox for figuring it out.

**Comment by fergiemcdowall** [comment]
Sorry for the slow response @jacargentina , we are all on holiday. I guess one potential fix could be to use another separator to separate your words which doesnt appear in your text. Any unicode symbol should work (apart from the very last one).

**Comment by fergiemcdowall** [comment]
Going to close this- please reopen if it is still an issue
