### ISSUE TITLE
nGramLength: number? array of numbers?

### ISSUE THREAD

**Issue by jacargentina** [fergiemcdowall/search-index#295]
I'm confused on the docs about this.

Here https://github.com/fergiemcdowall/search-index/blob/master/doc/create.md#ngramlength it is a number

But here, https://github.com/fergiemcdowall/search-index/blob/master/doc/add.md#ngramlength it talks about inheriting (the number) but then explains about an array (override a number with an array?) uh?

**Comment by fergiemcdowall** [comment]
Its all explained over at https://www.npmjs.com/package/term-vector

A number will give you ngrams of only that length. An array specifies a set of lengths, and an object can specify ranges of lengths

-- 
Apologies for brevity- this message was sent from my mobile

**Comment by jacargentina** [comment]
So the docs are out-of-sync!

**Comment by eklem** [comment]
Fixed!
