### ISSUE TITLE
OpenError: IO error: LockFile si/LOCK: The process cannot access the file because it is being used by another process.

### ISSUE THREAD

**Issue by xdvarpunen** [fergiemcdowall/search-index#301]
Hello,

I am using search-index behind the GET method inside Express module through Promises. I wonder how could this error be overcome? Forage or nowadays Norch is doing same; being called from Express. How it solves this? 

-XDVarpunen

**Comment by xdvarpunen** [comment]
Error message:

```
> at C:\express_searchIndex\node_modules\levelup\lib\levelup.js:119:34
> at C:\express_searchIndex\node_modules\abstract-leveldown\abstract-leveldown.js:39:16
```

**Comment by xdvarpunen** [comment]
Apparently there is possibility to change backend database to SQLite for search-index, cool! Checking it out =>

**Comment by fergiemcdowall** [comment]
@xdvarpunen thats the error you get if the DB is already in use (because of the way leveldb works, it can only be owned by a single process)

**Comment by fergiemcdowall** [comment]
Depending on your usecase, passing a DB to your `search-index` might help: https://github.com/fergiemcdowall/search-index/blob/master/test/node/general-tests/providing-levelup-test.js

**Comment by xdvarpunen** [comment]
@fergiemcdowall yes, how can I overcome using only one process? If I understood right, NodeJS is queuing the calls and thus it would be fine to be used by one call at the time. That's where I am lost.

**Comment by xdvarpunen** [comment]
@fergiemcdowall do you mean for each call I create new search-index?

**Comment by fergiemcdowall** [comment]
I think at this point, the easiest thing is do to provide a test case that reproduces the problem, then we can fix it for you

**Comment by xdvarpunen** [comment]
I'll do that

**Comment by xdvarpunen** [comment]
https://github.com/juliangruber/multilevel Is this possible to include?

**Comment by xdvarpunen** [comment]
Here is the test case project: https://github.com/xdvarpunen/unlocksearchindex

**Comment by fergiemcdowall** [comment]
How do I run it? What is the desired output?

**Comment by fergiemcdowall** [comment]
Oh - see:

```
PS C:\unlocksearchindex>npm install
PS C:\unlocksearchindex>node .\index.js
```

**Comment by fergiemcdowall** [comment]
Right your project is a little too big to simply push a bug fix. The problem is that you are instantiating a new search-index every time you search here: https://github.com/xdvarpunen/unlocksearchindex/blob/master/search/searchsi.js#L213-L230

You need to instantiate a new search-index when you start the server, and then always use that search-index.

**Comment by xdvarpunen** [comment]
Ahaa, yeah I found from test the following snippet: 

```
var db, si
 it('should make a new search-index with the existing leveldb', function (done) {
    searchIndex({
      indexes: db
    }, function(err, thisSi) {
      si = thisSi
      done()
    })
  })
```

I'll see if it works =>

**Comment by xdvarpunen** [comment]
I added it and got following error: 

```
> C:\unlocksearchindex\search\searchsi.js:171
>       if (err) { rej(err); throw err; }
>                            ^
> 
> Error: EBUSY: resource busy or locked, unlink 'C:\unlocksearchindex\si\000008.log'
>     at Error (native)
```

**Comment by xdvarpunen** [comment]
This looks like Windows problem, the logging could be turned off....

**Comment by xdvarpunen** [comment]
Works fine (: The singleton was the solution! Thanks! c:

**Comment by fergiemcdowall** [comment]
Glad to hear it!
