### ISSUE TITLE
Indexing memory consumption and time

### ISSUE THREAD

**Issue by xdvarpunen** [fergiemcdowall/search-index#302]
Hello,

How long should document take to index? And how much memory should be reserved if we are index large documents(talking about novel as string of text)?

-XDVarpunen

**Comment by eklem** [comment]
We don't have any specific numbers yet, but when you start using filters and nGramLength longer than 1, your index will grow quite a lot, and memory use will be high. But with the changes coming now, the memory use will be better, even though the indexing time will grow a little. We'll create some benchmark numbers for the different features over at [search-index-cookbook](https://github.com/eklem/search-index-cookbook).

**Comment by fergiemcdowall** [comment]
@xdvarpunen as always, the answer is "it depends"

Basic things you can do to speed up indexing:
* Make documents smaller
* Reduce number of fields in document, or set `searchable: false` in the batch options
* Make index non-deletable
* Dont use categories or filters
* [Increase the node memory limit](http://prestonparry.com/articles/IncreaseNodeJSMemorySize/)

More complicated things:
* Create several smaller search indexes and then run them as a cluster
* Create several smaller search indexes and use the merge functionality to munge them all together.

If you want to discuss your specific case, we are often hanging out on the [Gitter chatroom](https://gitter.im/fergiemcdowall/search-index)
