### ISSUE TITLE
having trouble getting search-index to work

### ISSUE THREAD

**Issue by agumbs1** [fergiemcdowall/search-index#303]
I'm sure I'm doing something wrong.  I tried to get this working on windows and linux(ubuntu) with no success. In the process below, my test (step 5) doesn't make it inside the callback.  One other thing i'm curious about.  I believe this **sometimes** works of first invocation but not on subsequent calls.  Not sure why this would be.
1) npm init
2) npm install search-index
3) npm install -g jasmine
4) jasmine init
5) run test
  console.log('start test')
        var searchIndex = require('search-index')
        var doc = {
            id: 1,
            title: 'Mad Science is on the Rise',
            body: 'Mad,  mad things are happening.'
        }
        var data = [doc]
        searchIndex({
            deletable: true,
            fieldedSearch: true,
            indexPath: 'si',
            logLevel: 'error',
            nGramLength: 1,
            store: true
        }, function(err, si) {
            console.log('callback')
            si.add(data, opt, function(err) {
                if (err) console.log('oops! ' + err)
                else console.log('success!')
            })
        })

**Comment by fergiemcdowall** [comment]
Yo @agumbs1 !

Your code looks good (although I am in a tiny norwegian cabin without a PC at the moment, so I cant actually test it)

One thing you could try is to "git clone" the search-index repo and run "npm install && npm test". It should work, and then you can work your way back from the test cases in the "test" folder.

F

**Comment by fergiemcdowall** [comment]
@agumbs1 closing for now- please reopen if you still require assistance
