### ISSUE TITLE
Configurable batch sizes for streamy si.add

### ISSUE THREAD

**Issue by eklem** [fergiemcdowall/search-index#306]
Could it be an idea to be able to set max batch sizes when indexing / adding items to an index? I think ould be nice when having limited hardware.

It could be part of the config?

**Comment by fergiemcdowall** [comment]
It is there (under the hood). Set `batchSize` when indexing. `batchSize` == max number of documents before indexing kicks in, if a stream comes to an end, then the docs will be indexed before batchSize is reached.

```javascript
    Indexer.createWriteStream = function (batchOptions) {
      batchOptions = _defaults(batchOptions || {}, {batchSize: 1000})
      return new IndexBatch(batchOptions, options)
    }
```

(TODO: Obviously some docs are big, and some are small, so maybe a batchSize in Kb would be more sensible)

**Comment by eklem** [comment]
Cool! We'll test and see if something more is needed.

**Comment by eklem** [comment]
Tested it. Set `batchSize: 100` and managed to index stuff that has crashed search-index before! 👍
