### ISSUE TITLE
Auto discover field names

### ISSUE THREAD

**Issue by eklem** [fergiemcdowall/search-index#307]
If tellMeAboutMySearchIndex could list out fields that have filter enabled, it could be used by a UI to do a "*"-query and show all available filters. This would make new users experience the power of search-index a lot quicker.

And the UI could also do the same for already enabled fielded-search list-out in tellMeAboutMySearchIndex.

**Comment by fergiemcdowall** [comment]
Yup thats a good point- there should be a way of keeping track of available filters in the search index

**Comment by fergiemcdowall** [comment]
In the latest release every field is filterable, so no need to track filterable fields

**Comment by eklem** [comment]
Cool. I guess a default frontend to work "out of the box" should have a way of selecting which fields that should be filtered on.

**Comment by eklem** [comment]
But, could it be an idea then that  tellMeAboutMySearchIndex could list out all available fields in the index?

**Comment by fergiemcdowall** [comment]
Yes, that would be a good idea.

**Comment by eklem** [comment]
And I guess [norch.io](http://norch.io) needs a cute little frontend to show off all the goodness people have indexed =)

**Comment by fergiemcdowall** [comment]
Since `tellMeAboutMySearchIndex` is now deprecated, a new function such as `availableFields` would fix this

**Comment by eklem** [comment]
Was going to ask about that yesterday, thanks!

**Comment by fergiemcdowall** [comment]
just going to keep this issue open so that we remember to implement it :)

**Comment by eklem** [comment]
I'll develop norch-vuejs-app so that it takes config/setup from a JSON file. Then you can use `availableFields` to let the user configure the frontend on norch.io. That will make it really easy to test the data and functionality just after they've indexed.

**Comment by fergiemcdowall** [comment]
`availableFields` now available: https://github.com/fergiemcdowall/search-index/blob/master/doc/API.md#availablefields
