### ISSUE TITLE
Strange index sizes

### ISSUE THREAD

**Issue by eklem** [fergiemcdowall/search-index#308]
I index 4000 items and get a directory file size of 2.0 GB. I re-index the last item and get a new directory file size of 303 MB. Some potential for getting lower file sizes the first index round? Let me know if you want a test-case.

**Comment by fergiemcdowall** [comment]
hmmm- odd. I wonder if this is a levelup problem or a search-index problem...

**Comment by eklem** [comment]
Think it has been like this for a long time. We know about the issue now, but it's not something that needs immediate action, so just let it be for now. The search-index-indexer is good for testing =)

**Comment by fergiemcdowall** [comment]
The indexes should now be a bit smaller, and in `0.10.x` they will be a lot smaller. Leveldb seems to create indexes of varying size for some reason.

**Comment by eklem** [comment]
It's true, it's a miracle!
search-index' christmas present came early this year =)

**Comment by fergiemcdowall** [comment]
Hehe 🎁  🎁
