### ISSUE TITLE
How to swap levelup backend?

### ISSUE THREAD

**Issue by paolochiodi** [fergiemcdowall/search-index#309]
I've recently tried to update search-index from an old version and found that I am not able to specify the levelup backend passing it as the option `db` anymore.
I found out the undocumented `indexes` option where I can pass a levelup instance, but it seems awkward since I need to create it with the `valueEncoding: 'json'`.

Is this the correct way to swap the levelup backend? 
Was the removal of the `db` option intentional?

Previous code:
```js
    Search({
      db: Memdown
    }, function(err,si){
    ....
    })
```

New code:
```js
    Search({
      indexes: Levelup('si', {db:Memdown, valueEncoding: 'json'})
    }, function(err,si){
   ....
   })
```

**Comment by fergiemcdowall** [comment]
It still works- You can see how to do it by looking at the test: https://github.com/fergiemcdowall/search-index/blob/master/test/node/general-tests/providing-levelup-test.js

**Comment by paolochiodi** [comment]
Thanks, I overlooked the tests.

**Comment by fergiemcdowall** [comment]
@paolochiodi docs definitely need improvement- it's good to ask questions.

**Comment by eklem** [comment]
It's on the list of todo's: [Better documentation - the list](https://github.com/fergiemcdowall/search-index/issues/263)
