### ISSUE TITLE
Strange behaviour on Non-deletable index

### ISSUE THREAD

**Issue by colophonemes** [fergiemcdowall/search-index#310]
I'm having an issue creating a non-deleteable index for use in-browser. I'm getting the following error message:

```sh
Error: this index is non-deleteable, and some of the documents you are deleting have IDs that are already present in the index. Either reinitialize index with "deletable: true" or alter the IDs of the new documents
```

The input data is unique (no overlapping IDs). I've tried both explicitly setting an ID and letting `search-index` do it automatically.

The code looks like this:

```js
searchIndex(siOpts, function(err, si) {
    if(err) throw err;
    si.add(talks, {
        fieldOptions: [
            {
                fieldName: 'thumbnail',
                searchable: false
            },
            {
                fieldName: 'canonical',
                searchable: false
            },
            {
                fieldName: 'tags',
                filter: true,
            },
            {
                fieldName: 'speakers',
                filter: true
            }
        ]
    },
    function(err){
       // err throws here: Error: this index is non-deleteable, and some of the documents you are deleting have IDs that are already present in the index. Either reinitialize index with "deletable: true" or alter the IDs of the new documents
       ....
   }
});
```

Example data:
```js
[
  { id: 'abc123',
    title: 'Talk 1',
    canonical: '/talks/talk-1/',
    thumbnail: 'https://example.com/thumb1.jpg',
    speakers: [ 'Speaker 1' ],
    tags: [ 'Tag 1', 'Tag 2' ] 
},
  { id: 'xyz789',
    title: 'Talk 2',
    canonical: '/talks/talk-2/',
    thumbnail: 'https://example.com/thumb2.jpg',
    speakers: [ 'Speaker 2' ],
    tags: [ 'Tag 3', 'Tag 4' ] 
} 
]
```

Any ideas?

Cheers
Sam

**Comment by fergiemcdowall** [comment]
Hmmm. Not immediately obvious why that isn't working- if you feel so inclined you can provide a testable gist that we can have a look at

However, the delete functionality has now been completely replaced in the forthcoming `0.9.0` version. There is no longer a space penalty for having deletable indexes, and the `deletable` flag will become obsolete. So another option is just to hang tight for a week or two until the new version is released.

**Comment by colophonemes** [comment]
OK, I might do that. I noticed that you've commented out the code that throws the error in the `search-index-deleter` dependency, so hoped something was coming soon :)

How stable is the current `0.9.0` branch? Could I start working off that until the official release?

**Comment by fergiemcdowall** [comment]
`0.9.0` is not in a stable state, but I am hoping to get it there in a week or two. The API will change quite a bit, the size of the library should be smaller, and performance should be better.

**Comment by colophonemes** [comment]
No worries, thanks for the help!
