### ISSUE TITLE
how to query for mutiple words in one query

### ISSUE THREAD

**Issue by vinothg** [fergiemcdowall/search-index#311]
**Example Index** 
[
  {"make":"ASTON MARTIN",
   "model":"DBS",
   "variant":"COUPE"
  },
  {"make":"ASTON MARTIN",
   "model":"DBS",
   "variant":"COUPE 2 SEATER"
  }
]

Given a string "ASTON US CAR MAKER SEATER", i want the second index to return because it matches for words in make field (**ASTON**) and variant field (**SEATER**). 

Is this possible ?

**Comment by fergiemcdowall** [comment]
Yes, do:

```javascript
var q = {}
q.query = {
  AND: {
    'make': ['aston'],
    'variant':['seater']
  }
}
si.search(q, function (err, searchResults) {
  //do something with searchResults
})
```

(see: https://github.com/fergiemcdowall/search-index/blob/master/doc/search.md#fielded-search)

**Comment by vinothg** [comment]
Thanks. Given a string like "ASTON US CAR MAKER SEATER", is it possible to search in all fields i.e i will not know which part of the string is make and which part is variant.

**Comment by fergiemcdowall** [comment]
Yes, you can do:

```javascript
q.query = {
  AND: {
    '*': ['aston', 'us', 'car', 'maker', 'seater']
  }
}
```

**Comment by vinothg** [comment]
Thanks a lot. I tried the with the same query but it returns no hits.

```
function searchTerm(){
  var q = {};
  q.query = {
    AND: {
      '*': ['aston', 'us', 'car', 'maker', 'seater']
    }
  }
  si.search(q, function(err, results) {
    console.log('Result is ' + JSON.stringify(results));
  });
}
```
However if i pass the query with exact keywords it works properly. If i pass extra words, it doesn't return results.

```
q.query = {
  AND: {
    '*': ['aston', 'seater']
  }
}
```

**Comment by fergiemcdowall** [comment]
> However if i pass the query with exact keywords it works properly. If i pass extra words, it doesn't return results.

Yes, that is the intended functionality. You should ideally strip [stop words](https://en.wikipedia.org/wiki/Stop_words) out of a query before sending it to a search engine.

**Comment by fergiemcdowall** [comment]
You could also do an OR query:

```javascript
  q.query = [{
    AND: {
      '*': ['aston', 'us', 'car', 'maker', 'seater']
    }
  }, {
    AND: {
      '*': ['aston', 'seater']
    }
  }]
```
