### ISSUE TITLE
matcher to work on sertain fields only?

### ISSUE THREAD

**Issue by eklem** [fergiemcdowall/search-index#312]
Would it be an idea to choose which fields to do the reverse index/word index on? It could save a lot of memory in the indexing process if I only needed one or a few, not so text rich, fields?

I'm looking at food recipes, and the idea was to only have a word index on titles, and not description and ingredients

**Comment by eklem** [comment]
Ah, a little quick here. I guess that the fields available for the searcher is also available for the matcher. So what we need is the possibility to [only index for the matcher](https://github.com/fergiemcdowall/search-index/issues/257)/searcher or both.

**Comment by fergiemcdowall** [comment]
Yes, thats right- matcher terms are specified by all fields that are `searchable`
