### ISSUE TITLE
category sorting not working so well in 0.8.15

### ISSUE THREAD

**Issue by eklem** [fergiemcdowall/search-index#314]
With sorting on categories defined: http://oppskrift.klemespen.com:3030/search?q={%22query%22:[{%22AND%22:[{%22*%22:[%22kake%22]}]}],%22categories%22:[{%22field%22:%22ingredients%22,%22limit%22:10,%22sort%22:%22keyDesc%22}],%22pageSize%22:10}

Without sorting on categories defined: http://oppskrift.klemespen.com:3030/search?q={%22query%22:[{%22AND%22:[{%22*%22:[%22kake%22]}]}],%22categories%22:[{%22field%22:%22ingredients%22,%22limit%22:10}],%22pageSize%22:10} 

This may be different in 0.9.0. I'll test that later.

**Comment by fergiemcdowall** [comment]
Hmmm.

The sort logic was not as good as it could have been in 0.8.x, and has been rewritten in 0.9.0. Almost certainly will be leaving it as it is in 0.8.x though...
