### ISSUE TITLE
How to get out filter ready categories/buckets

### ISSUE THREAD

**Issue by eklem** [fergiemcdowall/search-index#315]
@fergiemcdowall and @mewwts ! A JavaScript question from the semi illiterate. I'm looping and looping through a search result set to grab what I need for filtering. It seems it should be a better way. An example of what I have is this:

```JSON
{
  "categories": [
    {
      "key": "ingredients",
      "value": [
        {
          "key": "sukker",
          "value": 365
        },
        {
          "key": "egg",
          "value": 291
        },
        {
          "key": "hvetemel",
          "value": 261
        },
        {
          "key": "bakepulver",
          "value": 198
        },
        {
          "key": "smør",
          "value": 198
        }
      ]
    }
  ]
}
```

And what I want from it is this:
```JSON
[
  {
    "field": "ingredients",
    "gte": "sukker",
    "lte": "sukker"
  },
  {
    "field": "ingredients",
    "gte": "egg",
    "lte": "egg"
  },
  {
    "field": "ingredients",
    "gte": "hvetemel",
    "lte": "hvetemel"
  },
  {
    "field": "ingredients",
    "gte": "bakepulver",
    "lte": "bakepulver"
  },
  {
    "field": "ingredients",
    "gte": "smør",
    "lte": "smør"
  }
]
```

How is this best/simplest done? I'm doing this in the browser, and looking to browserify it later, so I would like to keep additional libraries out of it.

It's for the `norce-vuejs-app`, so I need it to be general, working without knowing what the field is going to be.

**Comment by fergiemcdowall** [comment]
Have you looked at the built in Array functions `.map`, `.filter` and `.forEach` ?

**Comment by mewwts** [comment]
`obj.categories[0].value.map(function(val) {return {field: obj.categories[0].key, gte: val.key, lte: val.key};})`

**Comment by mewwts** [comment]
Assuming the object is called `obj`, I'd do:
`obj.categories[0].value.map(function(val) {return {field:
obj.categories[0].key, gte: val.key, lte: val.key};})`

2016-09-30 12:05 GMT+02:00 Espen Klem <notifications@github.com>:

**Comment by eklem** [comment]
No, I'm googling my eyes sore here, and hard when not knowing what to search for 😃  I'll check that out! And thanks for the example, @meewts 👍

**Comment by eklem** [comment]
@mewwts How do I get to return a full array of objects?

**Comment by eklem** [comment]
Sorry, got it working, @mewwts. "Move along! nothing to see here."
