### ISSUE TITLE
Missing docs on updating the API to 0.9

### ISSUE THREAD

**Issue by jacargentina** [fergiemcdowall/search-index#317]
I've updated to v 0.9 and now my code is not working.

This repo does not contains the 0.9 code? There is missing documentations on the migration instructions to the new API ?

**Comment by fergiemcdowall** [comment]
Zoinks! Is 0.9.0 (it shouldnt be) on npm or did you install from github? Switch to the 0.9.0 branch in github, and you will see the right docs

**Comment by fergiemcdowall** [comment]
Its still a work in progress...

**Comment by jacargentina** [comment]
Well, you've published it to npm 7 hours ago.

![search-index-on-npm](https://cloud.githubusercontent.com/assets/517228/19124366/377123c4-8b33-11e6-8d1e-919e04f6b130.png)

**Comment by fergiemcdowall** [comment]
Ah- didnt mean to do that...

-- 
Apologies for brevity- this message was sent from my mobile

**Comment by fergiemcdowall** [comment]
OK- I just unpublished 0.9.0 from the npm registry. The README npm is showing seems to be a cached version of the 0.9.0 doc- hopefully it will return to the 0.8.15 README soon. `npm install search-index` should now install `0.8.15` again

**Comment by fergiemcdowall** [comment]
Actually, I have decided to just republish version 0.9.1. Its pretty much finished, although the docs could use some love
