### ISSUE TITLE
Example for search-query in browser

### ISSUE THREAD

**Issue by aschilling** [fergiemcdowall/search-index#322]
Hi,

I read through all of your examples but could not figure out how to run a query on a SearchIndex build within the browser using the minified version and highland.js. In particular, I do not understand how to assign the created SearchIndex described here https://github.com/fergiemcdowall/search-index/blob/master/doc/browser.md to a variable on which I can run search("document").

I am sorry if this is a basic question, but I could not figure out how to do it.

Best regards and keep up your great work

**Comment by fergiemcdowall** [comment]
First of all: thanks for asking the question, basic questions are the best ones.

I have altered https://github.com/fergiemcdowall/search-index/blob/master/doc/browser.md to make it (slightly) clearer. The search index is assigned to the variable `myCoolSearchIndex`

Maybe a live demo that people can poke about with themselves would be useful here?

**Comment by aschilling** [comment]
Thank you for your clarification and your encouraging words.

Unfortunately, I am still struggling on how to assign the SearchIndex to a variable so I can query it later in my JavaScript scripts. I have already tried to assign it to a variable within the "on end" block, but this does not work:
```
        .on('end', function() {
          // now you can perform search queries
          idx = myCoolSearchIndex;
          myCoolSearchIndex.search('pickled onions').on('data', function(doc) {
            console.log(doc);
          });
```

Another thing I am struggling with is how to fill the search index. I have already tried to use some of the approaches outlined here: https://github.com/fergiemcdowall/search-index/blob/master/doc/add.md but without success.

Would it be possible to extend the browser example with excerpts that add documents via file such as https://raw.githubusercontent.com/fergiemcdowall/reuters-21578-json/master/data/fullFileStream/justTen.str and from native JavaScript using push functionality?

**Comment by fergiemcdowall** [comment]
If you do this, then mySearchIndex will eventually become a variable that can be reused

```javascript
const SearchIndex = require('search-index')
var mySearchIndex
SearchIndex({
  indexPath: 'fergie'
}, function (err, aShinyNewSearchIndex) {
  mySearchIndex = aShinyNewSearchIndex
})
```

A live demo would definitely be helpful here

**Comment by fergiemcdowall** [comment]
I threw up a demo of search-index working in the browser here: https://cdn.rawgit.com/fergiemcdowall/search-index/master/doc/demo/index.html

You should be able to work back from that, but by all means let us know if there are things that don't work, or are difficult to grok

**Comment by fergiemcdowall** [comment]
the "cdn.rawgit" url seems to be taking a lond time to update- check out https://rawgit.com/fergiemcdowall/search-index/master/doc/demo/index.html for the latest version

**Comment by aschilling** [comment]
Thank you very much for your help and the example. The example worked very well until today. Now, it throws an exception when I try to load text into the array. Is it possible that you changed functionality within the search-index.min.js file?

**Comment by fergiemcdowall** [comment]
Oh- thanks, yes I pushed a new version of search-index out yesterday.

It uses object streams, so you dont have to do parsing on the way in and the way out. However that broke the demo, which was still parsing the results into objects (when they were already objects)

Diff: https://github.com/fergiemcdowall/search-index/commit/280abf82406fe042637dbed7dcc3d504df858df3

Should be fixed now
