### ISSUE TITLE
A little unclear filter documentation

### ISSUE THREAD

**Issue by eklem** [fergiemcdowall/search-index#325]
The [regular documentation](https://github.com/fergiemcdowall/search-index/blob/master/doc/search.md#filters) and the [API-documentation](https://github.com/fergiemcdowall/search-index/blob/master/doc/API.md#categorize) is a little different on how query filtering works. Which is the correct version?
## Regular documentation

``` javascript
query: {
  AND: {
    'description': ['swiss', 'watch']
    'price': [{
       gte: '1000',
       lte: '8'
    }]
  }
}
```
## API

``` javascript
  si.buckets({
    query: [
      {
        AND: {'*': ['*']}
      }
    ],
    buckets: [
      {
        field: 'price',
        gte:   '2',
        lte:   '3',
        set:   false
      }
      {
        field: 'price',
        gte:   '4',
        lte:   '7',
        set:   false
      }
    ]
  }).on('data', function (data) {
    // do something with the data
  }).on('end', function () {
    // finshed
  })
```

``` javascript
  si.categorize({
    query: [
      {
        AND: {'*': ['swiss', 'watch']}
      }
    ],
    category: {
      field: 'manufacturer'
    }
  }).on('data', function (data) {
    // do something with the data
  }).on('end', function () {
    // finshed
  })
```

**Comment by fergiemcdowall** [comment]
I _think_ it is all correct?

The first code you posted is a filter (FIND me a **description** of **swiss watch** with a **price** between **1000** and **8**)

The second is a way to SHOW user defined aggregations on **price**

The third is a way to SHOW an aggregation on manufacturer, based on the information that is in the index- "show me how many documents this query returns for every manufacturer" (has the advantage that the user doesn't have to know what information is in the index.

**Comment by eklem** [comment]
Ah, ok, then it's just a minimal bug in the first one. Think `1000` and `8`should switch places. And maybe we also need to show how to filter on categories

It looks really slick, but I think there is an issue when you want to remove filters. Not a bug, but you leave some more up to the developers to remove filters, since what you have in the query is both user textual input and different types of filters?

**Comment by eklem** [comment]
And maybe the most important question: Will the categories that are used as filters still be marked as active in the `si.categorize`-function? If so, I'll stop complaining =)

**Comment by fergiemcdowall** [comment]
All (valid) complaints greatly appreciated ;)

At the moment, everything is sorted as strings, so gte:1000 and lte:8 captures all numbers between 1 and 89999...

it certainly makes sense for filters to be marked as active in `si.categorize` - in fact IIRC it _should_ be working like that

**Comment by eklem** [comment]
The old one does, so that's good if still so!
Didn't understand the string thingy? lte:8 means 1,2,3,4,5,6,7 and 8 and gte:1000 means 1000 and up to 999999...

**Comment by eklem** [comment]
Anyway, I'll close this =) . Working on a general search frontend, and while it's a lot to do still, it's coming along quite nice: http://oppskrift.klemespen.com/norch/index4.html

**Comment by fergiemcdowall** [comment]
👍

**Comment by eklem** [comment]
Have thought a little more about how applying filers are working now, and think it's not so wise. If you have one or more OR or NOT queries, you'd have to apply one filter to all OR and NOT, won't you? And being able to add different filters to different part of an OR-query seems a bit strange? What do you think?

**Comment by fergiemcdowall** [comment]
At the moment you can filter per OR clause, which I think makes the most sense

**Comment by eklem** [comment]
Not sure if I agree fully, but maybe not the big issue for me in a while. What do you think would be a usecase for filtering differently on each OR-query?

**Comment by fergiemcdowall** [comment]
Its just that filtering each or query allows you to do both (filter the whole result set, or define different filters per OR clause). So if somebody _did_ have a usecase for per OR clause they could implement it.
