### ISSUE TITLE
Possibility to export and import search index

### ISSUE THREAD

**Issue by aschilling** [fergiemcdowall/search-index#326]
Hi everybody,

Is it possible to save a SearchIndex to a text file, such as a JSON file, and import it later? The concrete situation I am struggling with is that I would like to create a SearchIndex for various data in advance so that clients do not have to build it themselfs but only have to import the created SearchIndex. 

As you have probably guesed already my question concerns the minified version of search-index.

Sorry if this is a basic question, I am currently doing my first steps with search-index

**Comment by fergiemcdowall** [comment]
Yes- in fact import/export is one of the big "selling points" of `search-index`. You can import/export entire indexes, and also do merges

See https://github.com/fergiemcdowall/search-index/blob/master/doc/replicate.md

**Comment by aschilling** [comment]
Thank you for the clarification and the link.

**Comment by fergiemcdowall** [comment]
Hit us up here or on https://gitter.im/fergiemcdowall/search-index if you have any questions/comments/feedback
