### ISSUE TITLE
not working at all

### ISSUE THREAD

**Issue by bagbag** [fergiemcdowall/search-index#327]
I tried a quite long while now implementing search-index into my project, but it just doesn't want to work. Then I got the idea to test your sample project to see if that works and ops, it doesnt.

<details>
  <summary>

code</summary>

  <p>

``` javascript
const request = require('request');
const JSONStream = require('JSONStream');

var index;
const indexData = function(err, newIndex) {
  if (!err) {
    index = newIndex
    request('https://raw.githubusercontent.com/fergiemcdowall/reuters-21578-json/master/data/fullFileStream/000.str')                      // get a stream of documents
      .pipe(JSONStream.parse())       // turn into JSON
      .pipe(index.defaultPipeline())  // vectorize
      .pipe(index.add())              // index
      .on('data', function(data) {});
  }
}
require('search-index')({}, indexData);

setInterval(() => {
    index.tellMeAboutMySearchIndex(function(err, info) {
        console.log(info)
    });
}, 1000);
```

</p></details>

Then I also tried the examples app and it didn't work either.

the output of `index.tellMeAboutMySearchIndex` is always:

> { totalDocs: 0,
>   lastUpdate: 0,
>   indexPath: 'myCoolIndex',
>   deletable: undefined,
>   fieldedSearch: undefined,
>   store: undefined,
>   logLevel: 'error',
>   nGramLength: undefined,
>   nGramSeparator: undefined,
>   separator: undefined,
>   stopwords: undefined }

I'm using `node v6.5.0`

**Comment by fergiemcdowall** [comment]
Thanks for pointing this out, it seems like everything indexes OK (so you can actually search), but there is a glitch with `tellMeAboutMySearchIndex`.

**Comment by fergiemcdowall** [comment]
TODO: fix `tellMeAboutMySearchIndex`

**Comment by bagbag** [comment]
search also doesn't work:

![search-index](https://cloud.githubusercontent.com/assets/4116942/19849752/2484cb68-9f55-11e6-85c4-2045cda638dd.png)

**Comment by fergiemcdowall** [comment]
All text is indexed as lower case by default- so a search for "america" will work. You can turn this off by doing `preserveCase: false` when indexing so that "America" will hit, and "america" will not.

**Comment by bagbag** [comment]
No matter what I try, it doesn't work.

![search-index](https://cloud.githubusercontent.com/assets/4116942/19853341/e7680b0a-9f68-11e6-9d63-296f9baf6fbd.png)

**Comment by fergiemcdowall** [comment]
Hmmm- it might be a more general problem with your setup.

If you do `git clone https://github.com/fergiemcdowall/search-index.git`

and then enter the cloned directory and do

`npm install && npm test`

do the tests pass?

**Comment by bagbag** [comment]
> $ npm test
> 
\> search-index@0.9.4 test C:\Users\patri\Desktop\search-index
\> npm run empty-sandbox && date && npm run test-node && npm run test-browserify && standard test/* lib/*
> 
> 
\> search-index@0.9.4 empty-sandbox C:\Users\patri\Desktop\search-index
\> rm -rf test/sandbox && mkdir test/sandbox
> 
> Syntaxfehler.
> 
> npm ERR! Windows_NT 10.0.14393
> npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "empty-sandbox"
> npm ERR! node v6.5.0
> npm ERR! npm  v3.10.3
> npm ERR! code ELIFECYCLE
> npm ERR! search-index@0.9.4 empty-sandbox: `rm -rf test/sandbox && mkdir test/sandbox`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the search-index@0.9.4 empty-sandbox script 'rm -rf test/sandbox && mkdir test/sandbox'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the search-index package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     rm -rf test/sandbox && mkdir test/sandbox
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs search-index
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls search-index
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     C:\Users\patri\Desktop\search-index\npm-debug.log
> npm ERR! Test failed.  See above for more details.

**Comment by fergiemcdowall** [comment]
Hmm, you need to run the tests in a unix-style environment.

Back to the original problem: Its possible if node-gyp is installed, it will work fine for you https://github.com/nodejs/node-gyp#installation

**Comment by bagbag** [comment]
Under Arch:

> 137 passing (21s)
>   1 failing
> 
>   1) sqllite compatability:  should be able to index and search as normal:
>      Error: timeout of 10000ms exceeded. Ensure the done() callback is being called in this test.
> 
> npm ERR! Linux 4.8.4-1-ARCH
> npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "test-node"
> npm ERR! node v6.9.1
> npm ERR! npm  v3.10.9
> npm ERR! code ELIFECYCLE
> npm ERR! search-index@0.9.4 test-node: `mocha test/node/general-tests --recursive --timeout 10000`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the search-index@0.9.4 test-node script 'mocha test/node/general-tests --recursive --timeout 10000'.

so it really is my setup under windows.

**Comment by fergiemcdowall** [comment]
Oh dear- you seem to be jinxed today.

Probably if you run the test app on your Arch box, then it will work.

Probably if you bump the timeout on the tests `mocha test/node/general-tests --recursive --timeout 60000`, then it will work.

Probably if you make sure that `levelup` works on your windows box, then `search-index` will work there as well.

**Comment by fergiemcdowall** [comment]
Closing for now, please reopen a new issue if difficulties persist
