### ISSUE TITLE
Problem quering over fields with multiple values

### ISSUE THREAD

**Issue by fdelavega** [fergiemcdowall/search-index#328]
Hi,

I am having some trouble making queries over list fields. In my use case, I have some offerings which can belong to different categories. Then it is possible to search all the offerings in a category both, including the id of the category or its name.

For example, creating the document with the following data, we have the fields categoriesId, and categoriesName:

<pre>
[
   {
      "id":"offering:21",
      "originalId":"21",
      "sortedId":"000000000021",
      "body":[
         "And Filter Operator",
         ""
      ],
      "userId":"b0946ffa20357194688e54b1cf143c9c",
      "productSpecification":"000000000017",
      "categoriesId":[
         "1",
         "5"
      ],
      "categoriesName":[
         "WireCloud Component",
         "WireCloud Operator"
      ],
      "href":"http://store.lab.fiware.org/DSProductCatalog/api/catalogManagement/v2/catalog/19/productOffering/21:(0.1)",
      "name":"And Filter Operator",
      "lifecycleStatus":"Launched",
      "isBundle":false,
      "catalog":"19"
   }
]
</pre>

If I execute queries like the following, It works perfectly:

<pre>
{"query":[{"AND":[{"lifecycleStatus":["launched"]}],"NOT":[null]}]}
</pre>.

But with the following query, it returns 0 hits:
<pre>
{"query":[{"AND":[{"categoriesId":["5"]},{"lifecycleStatus":["launched"]}]}
</pre>

**Edit**: If the provided id has 2 or more characters, it works ("categoriesId":["11", "15"])

**Comment by fergiemcdowall** [comment]
I think you have a little typo in your query, try this:

```javascript
{
  query: [{
    AND: {
      categoriesId: ['5'],
      lifecycleStatus: ['launched']
    }
  }]
}
```

I put your case into the tests, just to be sure: https://github.com/fergiemcdowall/search-index/blob/master/test/node/general-tests/328-test.js (passing)

**Comment by fdelavega** [comment]
Hi,

I am obtaining the same result with that query:

<pre>
{"query":[{"AND":[{"categoriesId":["5"],"lifecycleStatus":["launched"]}],"NOT":[null]}],"hits":[],"totalHits":0} 
</pre>

Indeed the method getDocumentFreqencies of the searcher class is giving the same results with both queries (I mean the one I was using before) one hit for the status and 0 for the category Id, which results in a 0 hits result.

The estrange think about this, is that is not something that fails in all the cases, the following query:
<pre>
{"query":[{"AND":[{"categoriesId":["13"]},{"lifecycleStatus":["launched"]}]}
</pre>

and 

<pre>
"query":[{"AND":[{"categoriesId":["13"],"lifecycleStatus":["launched"]}]
</pre>

Work properly. Making different queries I have seen that the only ones that are not giving me results are those that have a categoryIid of a single character (In my case 1, 5 and 7)

Taking into account that you have included it in a test, I think that there should be something in the environment

**Comment by fergiemcdowall** [comment]
I think the best way forward here is to create a reproducible test case that shows the broken behaviour, and then we can take it from there.

**Comment by fdelavega** [comment]
as a wokarround I have included a fixed string at the begining of the ids (now are cat:5), which this change it works properly

**Comment by fergiemcdowall** [comment]
It sounds like you have uncovered a bug that needs to be fixed possibly relating to the way that numeric strings are handled. Will leave this open in case anybody else experiences a similar problem

**Comment by fergiemcdowall** [comment]
I'm pretty sure that this is now fixed- but please reopen if it persists
