### ISSUE TITLE
Missing `JSONStream.stringify()` for read streams

### ISSUE THREAD

**Issue by mjesun** [fergiemcdowall/search-index#329]
I just noticed that the example on how to store a precomputed index fails; mainly because `dbReadStream` emits `data` events with objects as a payload, and `fs.createWriteStream` can only receive `String`s or `Buffer`s.

The solution I adopted was to pipe the stream through `JSONStream.stringify()`, but I'm not sure if this expected. If so, I can create the PR updating the docs to reflect its need.

**Comment by fergiemcdowall** [comment]
Thanks for pointing that out- PR much appreciated

**Comment by fergiemcdowall** [comment]
@mjesun where was this mistake in the docs? If you post the link, then I can correct it

**Comment by fergiemcdowall** [comment]
OK- I think I have fixed this specific mistake in the docs. There may be some more typos/mistakes/inconsistencies lurking in the docs, so please let us know if you stumble upon them

**Comment by mjesun** [comment]
Oops, sorry! I did not notice your last comment. Glad to see you fixed it! :)
