### ISSUE TITLE
Using existing index takes more time than computing it from scratch

### ISSUE THREAD

**Issue by mjesun** [fergiemcdowall/search-index#330]
I'm trying to index a bunch of documentation pages (~25), each with approximately 1.5k words. When I index them via `callbackyAdd` on the browser, it takes around 30 seconds to be done.

However, when I precompute the index in node (~11 Mb the resulting file) and then load the index in the browser, the process takes around 40 seconds. The code seems to be doing a ton of operations over Indexed DB, which I assume they're normal; but I don't get why it takes so long.

**Comment by fergiemcdowall** [comment]
> However, when I precompute the index in node (~11 Mb the resulting file) and then load the index in the browser, the process takes around 40 seconds

Yes, for most use cases it makes sense to generate indexes on a server and then replicate the index into browsers. Do you have a strong reason to create indexes in the browser?

**Comment by mjesun** [comment]
No, actually I did it this way to speed up index creation; but I'm assuming I'm doing something wrong since the loading time of a precomputed index is higher than just creating the index from scratch in the browser (40 s vs 30 s)

**Comment by fergiemcdowall** [comment]
Oh- sorry I misread your first message.

Yes, that is strange- if you post your code then we can take a look at it

**Comment by mjesun** [comment]
This is the piece of JS for creating the index in node:
```javascript
searchIndex({indexPath: 'search'}, (err, index) => {
    async.map(glob.sync('public/docs/**/*.html'), processFile, (err, data) => {
        if (err) {
            return callback(err);
        }

        index.callbackyAdd({}, data.filter((x) => x), (err) => {
            index.dbReadStream()
                .pipe(JSONStream.stringify())
                .pipe(fs.createWriteStream('public/index.json'))
                .on('close', callback); 
        });
    });
});
```


And this is how I import the index in client side:
```javascript
let index = fetch('public/index.json').then((res) => res.text()).then((data) => {
    return new Promise((resolve, reject) => {
        console.log('Indexing...');

        searchIndex({indexPath: 'search'}, (err, index) => {
            let stream = index.dbWriteStream();

            JSON.parse(data).forEach((x) => {
                stream.write(x);
            });

            stream.end(() => {
                console.log('Indexing finished!');
                resolve(index);
            });
        });
    });
});
```

As you can notice I'm not using `JSONStream` in the browser (because of compatibility issues), but the code works and I'm not even sure this is the cause of the problem.

Time between both `console.log` is approximately of 40 seconds, indexing 25 documents with three fields (`file`, `title` and `text`); having `text` approximately 1500 words each. When randomly stopping the debugger, it seems to always stop at an IDBTransaction, or other Indexed DB related operation.

**Comment by fergiemcdowall** [comment]
OK- so you are generating an index on the server which takes 30 seconds, and then importing the index into the browser (with the fetch API- w00t!) which takes 40 seconds.

Your code looks fine, I cant see any obvious ways to speed it up. I would expect the fetch API to become slightly faster over the next few months.

What kind of application are you building? Do your users expect search to be available from the first second?

**Comment by mjesun** [comment]
I don't think the problem is in the fetch API. This are the times:

* The request only takes 224 ms (local server).
* Parsing the JSON takes about 300 ms (and notice I'm doing it synchronously, I could even use `res.json()` to make it async)
* Pushing to the stream just takes a few milliseconds.

I could make users wait for the first time, while the index is loaded into the IndexedDB; however this happens every time I reload the page.

**Comment by fergiemcdowall** [comment]
Once the indexedDB is populated, that data stays with the page even after it is closed and reopened. So you only have to inflict this on your users the first time they visit a page on your domain.

One way to solve this problem is to redirect queries to a Norch server (search-index over http) while the index is replicating, and then switch to full offline mode once the index is replicated

Another thing to investigate would be loading JSON directly into indexedDB without going through search-index and leveljs. The API is a bit hairy, but it could shave off some seconds.

**Comment by mjesun** [comment]
So I think I have to build up a system that "versions" the precomputed index, to avoid re-inserting it if it has not changed. Then the API usage for `search-index` would be the same?

**Comment by fergiemcdowall** [comment]
Yes `0.8.x` is the branch of norch that corresponds with `0.9.x` in search index. Its all under pretty heavy development at the moment.

You _should_ (crossing all fingers and toes) be able to spin up a free norch server on Heroku by [clicking this link](https://dashboard.heroku.com/new?button-url=https%3A%2F%2Fgithub.com%2Ffergiemcdowall%2Fnorch%2Ftree%2F0.8.0&template=https%3A%2F%2Fgithub.com%2Ffergiemcdowall%2Fnorch%2Ftree%2F0.8.0) (docs for 0.8.0 branch are [here](https://github.com/fergiemcdowall/norch/tree/0.8.0) )

**Comment by fergiemcdowall** [comment]
Closing for now, but yes- lets create some benchmarks that can be improved
