### ISSUE TITLE
del method not returning a stream

### ISSUE THREAD

**Issue by maxime-helen-sb** [fergiemcdowall/search-index#333]
From this part of the [documentation](https://github.com/fergiemcdowall/search-index/blob/master/doc/API.md#del), it is meant .del() method returns a stream.

However, as tested [here](https://github.com/fergiemcdowall/search-index/blob/master/test/node/general-tests/delete-test.js#L75),  the method returns undefined and takes a callback as parameter.

Am I missing something?

**Comment by fergiemcdowall** [comment]
You are right- the docs are wrong. Well spotted!

-- 
Apologies for brevity- this message was sent from my mobile
