### ISSUE TITLE
Unhandled error causes other error later (update docs)

### ISSUE THREAD

**Issue by jacargentina** [fergiemcdowall/search-index#334]
After updating from previous versions, now the index is built, but when querying i was getting this error on file `search-index-searcher/lib/ScoreTopScoringDocsTFIDF.js:30`

```javascript
/home/.../javascript/website/node_modules/search-index-searcher/lib/ScoreTopScoringDocsTFIDF.js:30
            vector[field + sep + token] = docVector[token]
                                                   ^
TypeError: Cannot read property 'fiscales' of undefined
    at /home/.../javascript/website/node_modules/search-index-searcher/lib/ScoreTopScoringDocsTFIDF.js:30:52
    at Array.forEach (native)
    at /home/.../javascript/website/node_modules/search-index-searcher/lib/ScoreTopScoringDocsTFIDF.js:29:41
    at dispatchError (/home/.../javascript/website/node_modules/levelup/lib/util.js:64:35)
    at /home/.../javascript/website/node_modules/levelup/lib/levelup.js:222:14
```

But this error comes because other previous unhandled error on line 27, which has a nice comment about that:

`err // TODO something clever with err`

The error is:

`ERROR NotFoundError: Key not found in database [DOCUMENT-VECTOR￮/book/impresoras-fiscales￮title￮]`

**Comment by fergiemcdowall** [comment]
Hmm- yes. This should be made non-crashy. What do your data and queries look like?

**Comment by jacargentina** [comment]
It is a complete website index. The query looks like:

`{"query":[{"AND":{"title":["fiscales"]},"boost":10},{"AND":{"content":["fiscales"]}}]}`

The data... i can send u the index (is not that big) in private. E-Mail ? IRC ?

**Comment by jacargentina** [comment]
@fergiemcdowall  Any advice or a workaround?

**Comment by fergiemcdowall** [comment]
IIRC from email convo, we found out that we could get it to work for object streams, but there was an issue with indexing Arrays of documents. If you could share one of your data files (in the Array format) then we can take a look at it

**Comment by fergiemcdowall** [comment]
Wow- this data spectacularly breaks `search-index` for no obvious reason.

**Comment by fergiemcdowall** [comment]
Sorry- my bad- it actually works fine. Try this code:

```javascript
const SearchIndex = require('search-index')
const Readable = require('stream').Readable

var index

const search = function () {

  // searching for "nexion"

  index.search('nexion').on('data', function(d) {
    console.log(d)
  })
}

const indexer = function(err, thisIndex) {
  index = thisIndex
  // where ./raw.json is an Array of documents
  var data = require('./raw.json')
  var s = new Readable({ objectMode: true })
  data.forEach(function(item) {
    s.push(item)
  })
  s.push(null)  // end the stream
  s.pipe(index.defaultPipeline())
    .pipe(index.add())
    .on('data', function(d) {
      // this event has to be listened to for some reason
    })
    .on('end', search)
}

SearchIndex({}, indexer)

```

**Comment by jacargentina** [comment]
I'm populating the index with many many calls to that 15 items (newer and different each time) array... may be that triggers the bug?

**Comment by fergiemcdowall** [comment]
At this point we probably need some code that reproduces the bug

**Comment by fergiemcdowall** [comment]
...to say for certain

**Comment by jacargentina** [comment]
@fergiemcdowall looking slowly to your code, i've found ' ve missed the `on('data', ...)` handler on my code. Adding that solves my indexing problem!

So, i must note that the API docs are missing that _required_ handler when feeding the streamer. Could u add that?

**Comment by fergiemcdowall** [comment]
@jacargentina yes, that is such a common gotcha. Taking a look at the API docs now- if you see any more mistakes, please let us know

**Comment by jacargentina** [comment]
Hi again. The `add.md` should have those corrections too?

**Comment by fergiemcdowall** [comment]
Good point- just updated it
