### ISSUE TITLE
Example code fix for Windows (update docs)

### ISSUE THREAD

**Issue by nevf** [fergiemcdowall/search-index#335]
The example code at [here](https://github.com/fergiemcdowall/search-index/blob/master/doc/quickstart.md) doesn't work on Windows because Windows adds a CR+LF to the end of stdin whereas Linux will be just a LF.

To fix replace:
```index.search(rawQuery.toString().slice(0, -1))```
with:
```index.search(rawQuery.toString().replace( /\r?\n|\r/g, '' ))```

**Comment by nevf** [comment]
@fergiemcdowall Thanks for updating the doc, however the regex code ```index.search(rawQuery.toString().replace( /\r?\n|\r/g, '' ))``` should work for both *nix and Windows and therefore can replace ```index.search(rawQuery.toString().slice(0, -1))```

**Comment by fergiemcdowall** [comment]
Ah- OK, I just replaced it now.

BTW: its totally OK to submit a pull request for this type of stuff. The documentation never gets the love that it deserves, and even fixes to small typos are welcome. This change is definitely worthy of a PR

**Comment by fergiemcdowall** [comment]
Also- with PRs, contributors are properly credited
