### ISSUE TITLE
Can't index geonames data (Indexing stops at "deltaIndex is 1006 long, emitting")

### ISSUE THREAD

**Issue by AlexandruMV** [fergiemcdowall/search-index#337]
Run indexing with batchSize: 1000
```
...
{"name":"pipeline","hostname":"Alexs-MacBook-Pro.local","pid":51666,"level":30,"normalised":{"id":"662222","body":"zerind zerind"},"raw":{"id":"662222","body":"Zerind Zerind"},"stored":{"id":"662222","body":"Zerind Zerind"},"tokenised":{"id":["662222"],"body":["zerind","zerind"]},"vector":{"id":{"662222":1,"*":1},"body":{"zerind":1,"*":1},"*":{"662222":1,"*":1,"zerind":1}},"id":"662222","msg":"","time":"2016-11-28T13:49:02.324Z","v":0}
{"name":"pipeline","hostname":"Alexs-MacBook-Pro.local","pid":51666,"level":30,"normalised":{"id":"662223","body":"zencani zancani zencani zenconi zenkan zenkàn"},"raw":{"id":"662223","body":"Zencani Zancani Zencani Zenconi Zenkan Zenkàn"},"stored":{"id":"662223","body":"Zencani Zancani Zencani Zenconi Zenkan Zenkàn"},"tokenised":{"id":["662223"],"body":["zencani","zancani","zencani","zenconi","zenkan","zenkàn"]},"vector":{"id":{"662223":1,"*":1},"body":{"zencani":1,"zancani":0.75,"zenconi":0.75,"zenkan":0.75,"zenkàn":0.75,"*":1},"*":{"662223":1,"*":1,"zencani":1,"zancani":0.75,"zenconi":0.75,"zenkan":0.75,"zenkàn":0.75}},"id":"662223","msg":"","time":"2016-11-28T13:49:02.324Z","v":0}
{"name":"search-index","hostname":"Alexs-MacBook-Pro.local","pid":51666,"level":30,"msg":"processing doc 662154","time":"2016-11-28T13:49:02.349Z","v":0}
{"name":"search-index","hostname":"Alexs-MacBook-Pro.local","pid":51666,"level":30,"msg":"processing doc 662155","time":"2016-11-28T13:49:02.358Z","v":0}
{"name":"search-index","hostname":"Alexs-MacBook-Pro.local","pid":51666,"level":30,"msg":"deltaIndex is 1006 long, emitting","time":"2016-11-28T13:49:02.358Z","v":0}
```
Beyond this nothing is happening. App is unresponsive and need to close with ctrl+c.

**Comment by fergiemcdowall** [comment]
Search index has an internal batching mechanism, so it will read in docs and then calibrate the index. The index could just be calibrating. How long does it hang for?

**Comment by AlexandruMV** [comment]
I don't know. I killed the proccess after several minutes

**Comment by fergiemcdowall** [comment]
in that case, maybe there is a problem with your data. If you post it here (or link to it), we can check it out

**Comment by AlexandruMV** [comment]
No problem. I try to index data from geonames: http://download.geonames.org/export/dump/RO.zip and I use the name and alternateNames. Documents look someting like this:
```
{ id: '662477', body: 'Comuna Volovăţ ' }
{ id: '662478', body: 'Volovăţ Volovat Volovăţ' }
{ id: '662479', body: 'Voloşcani Mici ' }
{ id: '662480', body: 'Voloşcani Mari ' }
{ id: '662481', body: 'Pârăul Voloşcanii ' }
{ id: '662482', body: 'Dealul Voloşcanii ' }
{ id: '662483', body: 'Voloșcani ' }
{ id: '662484', body: 'Voloicel Voloicelu Voloicelul' }
{ id: '662485', body: 'Comuna Voloiac ' }
{ id: '662486', body: 'Voloiac ' }
```

**Comment by fergiemcdowall** [comment]
Ok- will test asap

-- 
Apologies for brevity- this message was sent from my mobile

**Comment by AlexandruMV** [comment]
thank you

**Comment by fergiemcdowall** [comment]
The link you sent is to a large tab separated csv file.

In order to reproduce this bug, we will need the large JSON file that is causing the problems.

**Comment by AlexandruMV** [comment]
I don't have a big JSON. I stream and transform data from csv. This is the code (extracted from my app) but now is closing after first batch:
```
const fs = require('fs');
const csv = require('csv');
const request = require('request');
const SearchIndex = require('search-index');
const yauzl = require('yauzl');

const url = 'http://download.geonames.org/export/dump/RO.zip';

SearchIndex({
  logLevel: 'info',
  batchSize: 1000
}, (err, index) => {
  if (err) throw err;

  let parse = csv.parse({
    delimiter: '\t', relax: true,
    relax_column_count: true,
    max_limit_on_data_read: 1000000
  }, (err, data) => {
    if (err) throw err;
  });

  let transform = csv.transform((item, callback) => {
    return callback(null, {
      id: item[0],
      body: item[1] + ' ' + item[3].split(',').join(' ')
    });
  });

  let parseFile = (callback) => {
    yauzl.open('/tmp/RO.zip', { lazyEntries: true }, (err, zipfile) => {
      if (err) return callback(err, null);

      zipfile.readEntry();
      zipfile.on('entry', (entry) => {
        console.log(entry.fileName);
        if (entry.fileName === 'RO.txt') {
          zipfile.openReadStream(entry, (err, readStream) => {
            if (err) throw err;
            readStream
              .pipe(parse)
              .pipe(transform)
              .pipe(index.defaultPipeline({
                id: { searchable: false },
                body: { searchable: true }
              }))
              .pipe(index.add())
              .on('error', function (error) {
                console.log(error);
              })
              .on('finish', () => {
                console.log('file end');
                zipfile.readEntry();
              });
          });
        } else {
          zipfile.readEntry();
        }
      });
      zipfile.on('close', () => {
        if (err) return callback(err, null);
        return callback(null, null);
      });
    });
  };

  let stream = request(url).pipe(fs.createWriteStream('/tmp/RO.zip'));
  stream.on('finish', () => {
    parseFile((err, data) => {
      console.log(err, data);

      index.countDocs(function (err, docCount) {
        console.log(err, docCount);

        index.close((err) => { console.log(err); });
      });
    });
  });
});
```

**Comment by fergiemcdowall** [comment]
Hey @AlexandruMV 

The nature of search applications is that they are tightly associated with other systems. However, since we are just a gang of volunteers, we don't have capacity to debug entire applications.

If you can create a reproducible error report that only contains require()s for search-index and native node libs, then we can take a look at it.

**Comment by AlexandruMV** [comment]
I don't use search-index in my project anymore. I don't have time to try to reproduce this but if someone else have the same issue I will try to help.

**Comment by drzraf** [comment]
I'm experiencing a similar behavior.
It's my first attempt in trying search-index. I'm trying to index 10 documents of ~20 shorts fields each.
It takes up to 1 minutes and a half to complete with the largest part being
after receiving the `"[search-index-adder] deltaIndex is 1023 long, emitting"` message.

(It's ~22 secondes for 2 _documents_ (actually two plain JS objects) and 38 secondes for 4 documents)
I hope it could be some bug inside null/object/array handling... because otherwise it would not be realistically usable for my in-browser use-case.

**Comment by drzraf** [comment]
* `search-index.min.js` being from unzip'ed v0.14.0
* Chomium 60 + devtools > IndexedDB > Delete database "IDBWrapper-si"
* => `search-indexing complete in 10721`  (> 10 seconds for one JSON object, IDB contains 246 keys)

Reproducer:

```html
<!DOCTYPE html>
<html>
<head>
 <script src="search-index.min.js"></script>
 <script>
const textstore = {
	index: null,
	indexing_time: 0
};

const asarr = [{ "id":395,
		 "title":"TheTitle, It takes more than 7 seconds to index me",
		 "cat1":["aa","bb","cc","dd"],
		 "cat2":["fr"],
		 "city":"here",
		 "test1":null,
		 "theme":"féfé",
		 "theme2":[],
		 "address":"89 rue from Here,<br \/>\r\n790 Foo",
		 "permalink":"https:\/\/foo/here/title/",
		 "teaser":"Whatever text fits here ... testé \u00e9 \u00e0 partir<strong><br \/>AA<\/strong>",
		 "votes":{"usr":28,"score":107,"avg":3.82},
		 "thumbnail":"https:\/\/foo/250x250.jpg" }];

var d = new Date().getTime();
ready = new Promise(function(resolve, reject) {
    SearchIndex({logLevel:'debug'}, function(err, newIndex) {
	if (!err) {
	    textstore.index = newIndex;
	    console.log("createIndex_searchindex: %d elements", asarr.length);
	    textstore.index.concurrentAdd({},
					  asarr,
					  function(err) {
					      textstore.indexing_time = new Date().getTime() - d;
					      console.log("search-indexing complete in %d", textstore.indexing_time);
					      resolve();
					  });
	}
	else {
	    console.warn("errr", err);
	    reject();
	}
    });
});
</script>
```

**Comment by fergiemcdowall** [comment]
Hi @drzraf 

No, `search-index` does not take 10 seconds to index one document and 38 seconds for 4 documents :)

You seem to have a problem in your code. I suggest that you take a look, and maybe copy/paste from our [online demo](https://fergiemcdowall.github.io/search-index/demo), or [the tests](https://github.com/fergiemcdowall/search-index/tree/master/test)

If you want to create a cool offline search on a web page, then I would suggest creating the index once, saving it, and then replicating it out to the users (rather than generating a fresh index on every page load)

**Comment by drzraf** [comment]
the above HTML only relies upon the SearchIndex() of vanilla search-index.min.js v0.14.0 which depends upon underlying IDB implementation (there is nothing app-specific).
Just tested with firefox 57. It's takes ~2 seconds to complete which is far better.

About index maintenance, I'll avoid the hassle of download an index (which sum to original JSON), I need to index a few thousands small JS objects and lunr does it in less than a second.
The fact that it uses IDB make it almost "free" to use for subsequents page reloads (if the callbacks can help me detecting this situation).
So the only "difficulty" here, is to keep indexing time below a couple of seconds.

**Comment by drzraf** [comment]
Trying to clarify levelup <-> indexedDB wrappers during javascript aggregation:
[levelup](https://github.com/Level/levelup/) -> [level-packer](https://github.com/Level/packager) -> XXX -> [level.js](https://github.com/Level/level.js) [->](https://github.com/Level/level.js/blob/master/index.js#L126) [idb-wrapper](https://github.com/jensarps/IDBWrapper) [->](https://github.com/jensarps/IDBWrapper/blob/master/idbstore.js#L618) [Indexed DB](https://github.com/jensarps/IDBWrapper/blob/master/idbstore.js#L174) native call
