### ISSUE TITLE
More examples and documentation

### ISSUE THREAD

**Issue by yanickrochon** [fergiemcdowall/search-index#34]
For new comers wanting to try `search-index` as an indexing solution, the documentation is a bit slim and short of examples. For example, what are "facets" ? The snippets in the documentation is all but clear on their purpose and how to use them.

Could there be, at least, a full "working" example of the engine? And perhaps more than

**Q:** What is a facet? 
**R:** Allows faceted navigation.

for the different options?

Also, what is expected to get when using `teaser`? "Creates a field that shows where the search terms exist in the given field." Can an example result be given?

**Comment by fergiemcdowall** [comment]
See https://github.com/fergiemcdowall/search-index/tree/master/examples and the info on the wiki
