### ISSUE TITLE
Chaining document addition (documents can't be added concurrently)

### ISSUE THREAD

**Issue by maxime-helen-sb** [fergiemcdowall/search-index#343]
I am updating a wrapper by switching search index v0.8.15 to v0.9.6.

Everything seems ok except when I add several documents by creating readable streams and piping them to the index pipeline. I wish I could submit a PR for showing you a better explanation. 

Here is a test that I stored into ```test/general-tests``` directory: 
```javascript
'use strict';

const Readable = require('stream').Readable;
const SearchIndex = require('../../../');
const logLevel = process.env.NODE_ENV || 'error';
const sandbox = './test/sandbox/';
const should = require('should');
const stream_to_promise = require('stream-to-promise');

var si;

after('Flush database', done => {
  si.flush(err => {
    if (err) {
      done(err);
    }
    done();
  });
});


describe('simple search test', function() {
  
  var add = doc => {
      const stream = new Readable({ objectMode: true });
      stream.push(doc);
      stream.push(null);
      return stream_to_promise(stream.pipe(si.defaultPipeline()).pipe(si.add()));
  }

  it('should initialize search index', function (done) {
    SearchIndex(
      {indexPath: sandbox + '/si-search-test',
      logLevel: logLevel},
      function (err, thisSi) {
        if (err) false.should.eql(true);
        si = thisSi;
        return done();
      });
  });

  it('test 100 asset addition one by one', function (done) {
      let promises = [];
      for (let i=0; i<100; i++) {
          let asset = { name: "/assets/test+"+i };
          promises.push(add(asset));
      }
      Promise.all(promises)
        .then(() => {
            si.totalHits({ AND : ["*"] }, function (err, count) {
              should.equal(count, 100);
                done();
            });
        }).catch(done);
  });

});
```

Make sure to run ```npm install stream-to-promise``` before starting the test.

I expect the db instance to have indexed 100 documents, but it actually referenced only 3 of them. Am I doing something wrong? Why can't we add documents at a short time interval?

This is what I miss for completing my update.

**Comment by fergiemcdowall** [comment]
Maybe I'm missing something, but I think the "promisification" is unnecessary- wouldn't you be better off just using vanilla streams?

```javascript
const Readable = require('stream').Readable
const SearchIndex = require('search-index')
const dataDir = 'assets/'
const fs = require('fs')

const getFileStream = function(callback) {
  const files = fs.readdirSync(dataDir)
  const s = new Readable({ objectMode: true })
  files.forEach(file => {
    s.push(JSON.parse(fs.readFileSync(dataDir + file).toString()))
  })
  s.push(null) // end of stream
  return s
}

SearchIndex({
  indexPath: 'testindex'
}, function (err, myIndex) {
  getFileStream()
    .pipe(myIndex.defaultPipeline())
    .pipe(myIndex.add())
    .on('data', function() {})
    .on('end', function() {
      myIndex.search('fourth')
        .on('data', function(d) {
          // Yay! Search result!
          console.log(d)
        })
    })
})
```

**Comment by fergiemcdowall** [comment]
BTW: [callbackyAdd](https://github.com/fergiemcdowall/search-index/blob/master/doc/API.md#callbackyadd) works the same as the old 0.8.x `add`, so maybe that is an easier upgrade path for your code? Just replace `add` with `calbackyAdd`.

**Comment by fergiemcdowall** [comment]
Also- Im not familiar with `stream-to-promise`, but in the example you provided, you seem to be initialising a new stream in your `.add` function every time you add a doc. Things might work better if you have one stream and then just append documents to it.

**Comment by maxime-helen-sb** [comment]
calbackyAdd is fixing my problems! But I am still curious to figure this problem out.

stream-to-promise is calling 'then' callback on 'end' stream event, it doesn't change the library behaviors. When I have one stream that I feed progressively with the add method, I get this error: 
```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: stream.push() after EOF
    at readableAddChunk (_stream_readable.js:131:15)
    at IncomingMessage.Readable.push (_stream_readable.js:113:10)
    at HTTPParser.parserOnBody [as onBody] (http.js:140:22)
    at Socket.socketOnData [as ondata] (http.js:1535:20)
    at TCP.onread (net.js:510:27)
```

**Comment by maxime-helen-sb** [comment]
Nevermind I talked too fast, callbackyAdd isn't working neither. Here is the test to check my words, without other npm dependencies. 

```
'use strict';

const Readable = require('stream').Readable;
const SearchIndex = require('../../../');
const logLevel = process.env.NODE_ENV || 'error';
const sandbox = './test/sandbox/';
const should = require('should');
const stream_to_promise = require('stream-to-promise');
const fs = require('fs-extra');

var si;

after('Remove sandbox folder', done => {
  si.flush(err => {
    if (err) {
      done(err);
    }
    done();
  });
});


describe('simple search test', function() {
  
  var add = doc => {
      return new Promise((resolve, reject) => {
        si.callbackyAdd({}, [doc], function(err) {
            if (err) {
              reject(err);
            } else {
              resolve();
            }
        });
      });
  }

  it('should initialize search index', function (done) {
    SearchIndex(
      {indexPath: sandbox + '/si-search-test',
      logLevel: logLevel},
      function (err, thisSi) {
        if (err) false.should.eql(true);
        si = thisSi;
        return done();
      });
  });

  it('test 100 asset addition one by one', function (done) {
      let promises = [];
      for (let i=0; i<100; i++) {
          let asset = "/assets/test+"+i;
          promises.push(add(asset));
      }
      Promise.all(promises)
        .then(() => {
            si.totalHits({ AND : ["*"] }, function (err, count) {
              should.equal(count, 100);
                done();
            });
        }).catch(done);
  });

});
```

Sometimes I count 2 total documents, 3 in other times. Can you try the test I pasted?

**Comment by fergiemcdowall** [comment]
OK- so it definitely seems like a "race condition".

My guess is that this `for` loop:

```javascript
      for (let i=0; i<100; i++) {
          let asset = "/assets/test+"+i;
          promises.push(add(asset));
      }
```

...is adding all the promises to the array before they are being resolved, and then `Promise.all(promises)` is being invoked before the array is filled up.

**Comment by maxime-helen-sb** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise

```promises``` list contains 100 promises. The built in Promise ```all``` procedure take this array and return a new Promise. This latter executes ```then``` callback only when all of them are "resolved". If one failed, then the global promise returns a callback inside the catch braces.

Here is the exact same code of the previous test without promises:

```
'use strict';

const Readable = require('stream').Readable;
const SearchIndex = require('../../../');
const logLevel = process.env.NODE_ENV || 'error';
const sandbox = './test/sandbox/';
const should = require('should');
const stream_to_promise = require('stream-to-promise');
const fs = require('fs-extra');

var si;

after('Remove sandbox folder', done => {
  si.flush(err => {
    if (err) {
      done(err);
    }
    done();
  });
});


describe('simple search test', function() {
  
  var add = (doc, cb) => {
      si.callbackyAdd({}, [doc], function(err) {
          if (err) {
            cb(err);
          } else {
            cb();
          }
      });
  }

  it('should initialize search index', function (done) {
    SearchIndex(
      {indexPath: sandbox + '/si-search-test',
      logLevel: logLevel},
      function (err, thisSi) {
        if (err) false.should.eql(true);
        si = thisSi;
        return done();
      });
  });

  it('test 100 asset addition one by one', function (done) {
      for (let i=0; i<100; i++) {
          let document = i;
          add(document, err => {
            console.log(document);
            if (err) {
              done(err);
            } else if (document === 99) {
              si.totalHits({ AND : ["*"] }, function (err, count) {
                if (err) {
                  done(err);
                }
                should.equal(count, 100);
                done();
              });
            }
          });
      }
  });

});
```

I really think we have a problem here.

**Comment by fergiemcdowall** [comment]
That code wont work because you have an asynchronous function inside a `for` loop. Its going to initialize 100 `add` functions and then race through to `totalHIts` before they are all completed.

Try switching out your `for` loop with something like [async.eachSeries](http://caolan.github.io/async/docs.html#eachSeries)

(I dont know your exact use-case but its probably easier to simply generate an array of 100 docs, and submit them as a batch to a single `add` - using larger batches means less processing)

**Comment by maxime-helen-sb** [comment]
The use case is a web service adding a document to the index. This service is reachable by an HTTP endpoint and then its associated server procedure can be called concurrently. The test I demonstrate in this post aims to check the wrapper I wrote can experiment this use case.

Here is a new test that describes the above context, so it requires you to install restify. Note my efforts to use async, although I prefer promises as they are bundled with ES6.

```javascript
'use strict';

const restify = require('restify');
const Readable = require('stream').Readable;
const SearchIndex = require('../../../');
const logLevel = process.env.NODE_ENV || 'error';
const sandbox = './test/sandbox/';
const should = require('should');
const stream_to_promise = require('stream-to-promise');
const fs = require('fs-extra');
const async = require('async');
var si, server;

after('Flush search index', done => {
  si.flush(err => {
    if (err) {
      done(err);
    }
    done();
  });
});

before('start server', done => {
  server = restify.createServer({});
  server.use(restify.queryParser());
  server.use(restify.bodyParser());
  server.post('/add', function (req, res, next) {
      si.callbackyAdd({}, [req.body], function (err) {
        if (err) {
          res.status(500);
          res.end(JSON.stringify(err));
          next();
        } else {
          res.status(200);
          res.end();
          next();
        }
      });
  });
  server.listen(9221, done);
});

describe('Performance test', function() {

  it('should initialize search index', function (done) {
    SearchIndex(
      {indexPath: sandbox + '/si-search-test',
      logLevel: logLevel},
      function (err, thisSi) {
        if (err) false.should.eql(true);
        si = thisSi;
        done();
      });
  });

  it('test 100 asset addition one by one', function (done) {
      var client = restify.createJSONClient({url: 'http://localhost:9221' });
      var documents = [];
      for (var i=0; i<100; i++) {
          documents.push({ "foo" : i });
      }
      // documents.length === 100
      async.filter(documents, function(document, callback) {
        client.post('/add', document, function (err, req, res) {
          res.statusCode.should.equal(200);
          callback(null, !err); 
        });
      }, function (err, res) {
          if (err.length) {
            done(err);
          }
          si.totalHits({ AND : ["*"] }, function (err, count) {
            if (err) {
              done(err);
            }
            should.equal(count, 100);
            done();
          });
      });
  });

});
```
Imagine you are designing an online shopping website and you have one hundred clients from all around the world that are ordering an item at a short interval of times. This test demonstrates only one document is stored for 100 order requests.

**Comment by fergiemcdowall** [comment]
Right, but search-index has no internal queue system. When adding, you need to wait for the callback to complete before adding another document, or batch of documents. If there is a danger of adding lots of documents simultaneously you should implement some kind of queue.

**Comment by maxime-helen-sb** [comment]
This is an important information that seems mandatory to appear in the documentation.

I would expect to know all side effects of the library methods that I use, especially if a procedure doesn't accomplish its logic because I called it too soon, and without firing any errors. v0.9.6 is then not usable to my opinion.

I am going to stick with v0.8.15.

**Comment by fergiemcdowall** [comment]
Yes, 0.8.x had an internal queue, and 0.9.x doesn't. There are some good reasons for this, but I see that in this situation its a disadvantage.

**Comment by fergiemcdowall** [comment]
@maxime-helen-sb you make a valid point: the ability to index documents concurrently should be "official" functionality, since that is what users probably expect, and also what promises push users towards.

**Comment by fergiemcdowall** [comment]
`callbackyAdd` _should_ now be able to handle concurrent operations.
