### ISSUE TITLE
Stamp generated index with search-index version

### ISSUE THREAD

**Issue by fergiemcdowall** [fergiemcdowall/search-index#346]
In order to ensure that indexes work with the correct version of search-index, indexes should be stamped with the search-index version

**Comment by eklem** [comment]
This would be fantastic and make it a lot easier to [do and maintain some stuff over at nowsearch.xyz](https://github.com/eklem/nowsearch.xyz/issues/12)

**Comment by eklem** [comment]
I was thinking about this. If [read.js](https://github.com/fergiemcdowall/search-index/blob/master/src/read.js#L2) does something like:
```JavaScript
import { VERSION } from './version.js'
```
 And then at the [bottom it returns VERSION](https://github.com/fergiemcdowall/search-index/blob/master/src/read.js#L82-L95):
```JavaScript
retuirn: {
  VERSION: VERSION
}
```

Then maybe the webpack'er can generate version.js based on package.json version?
I can try this @fergiemcdowall, if you're happy with the approach?

**Comment by eklem** [comment]
Or maybe this approach has less moving parts:
https://stackoverflow.com/a/29252400/4210445

Or do you want it in the leveldb / indexeddb ?

**Comment by fergiemcdowall** [comment]
I think if there is some way to read directly from `package.json` that would be best

**Comment by eklem** [comment]
Yes, but we need it in the index as well? To compare if you have the right script to your index.

**Comment by fergiemcdowall** [comment]
Yes- that would be a good idea

**Comment by eklem** [comment]
=) Then we can do:

```JavaScript
if (scriptVersion === indexVersion) {
  // Everything is A-OK
} else {
  // Different options:
  // A: Swap to old script
  // B: Upgrade db to new format
}
```
