### ISSUE TITLE
Test: category filter filtered on set to active: true ?

### ISSUE THREAD

**Issue by eklem** [fergiemcdowall/search-index#347]
We [discussed this issue in another thread](https://github.com/fergiemcdowall/search-index/issues/325#issuecomment-255673245). search-index (through norch) [doesn't seem to](http://oppskrift.klemespen.com:3030/categorize?q=%7B%22pageSize%22%3A10%2C%22category%22%3A%7B%22field%22%3A%22Land%22%7D%2C%22query%22%3A%7B%22AND%22%3A%7B%22*%22%3A%5B%22eple%22%5D%2C%22Land%22%3A%5B%22afrika%22%5D%7D%7D%7D) return `active: true`. Could we have this? Doesn't break the streamy nature of search-index, and helps a lot in the frontend.

**Comment by eklem** [comment]
But not a big issue. I'll make a work-around for now!

**Comment by fergiemcdowall** [comment]
It _should_ flag active `categorize`-ations

**Comment by eklem** [comment]
I'll update norch and search-index soon, and re-test.

**Comment by eklem** [comment]
Still a bug, if I'm not misunderstanding something. For this link, I have filtered on `{"Land":"afrika"}, and I should get `{"key":"afrika","value":8,"active":true}`? http://oppskrift.klemespen.com:3030/categorize?q=%7B%22pageSize%22%3A10%2C%22category%22%3A%7B%22field%22%3A%22Land%22%7D%2C%22query%22%3A%7B%22AND%22%3A%7B%22*%22%3A%5B%22eple%22%5D%2C%22Land%22%3A%5B%22afrika%22%5D%7D%7D%7D

**Comment by eklem** [comment]
Do you need a test case?

**Comment by fergiemcdowall** [comment]
Its OK- I should be able tho throw one together

**Comment by fergiemcdowall** [comment]
I am wondering how this should work in the `OR` case. Can a filtered category be marked as `true` if it is only picked up by one `OR` condition?

For example:

```javascript
{
  query: [
    {
      AND: {
        '*': ['swiss', 'watch'],
        'color': ['black']
      }
    },
    {
      AND: {
        '*': ['apple']
      }
    }
  ],
  category: {
    field: 'color'
  }
}
```

```javascript
  { key: '*', value: 3 }
  { key: 'black', value: 5, filter: true } // should this be true? Only matched in one condition
  { key: 'blue', value: 2 }
  { key: 'gold', value: 1 }
```

**Comment by eklem** [comment]
Hmm, better to be true than not, definitely. But it partly breaks the beauty of having filtered categories/buckets as part of the regular query.

I think this is an example of why I feared this a little.

Anyway, enough "I told you so" =) Here's why I think like I do, and why I think we can live with that:
In your query, you have chosen an OR-search. Or in other words, two search-queries, merged into one result, and presenting filters available for these results. Most probably, the case will be that both queries have the filter applied. The query you have is a special case, and the one that needs some special treatment to work well. The regular pattern should be simpler and more straight forward.

**Comment by fergiemcdowall** [comment]
3 possible solutions:

1)  replace the `true` flag with the matching query clause:

```javascript
  { key: '*', value: 3 }
  { key: 'black', value: 5, filter: {
      AND: {
        '*': ['swiss', 'watch'],
        'color': ['black']
      }
    } } // should this be true? Only matched in one condition
  { key: 'blue', value: 2 }
  { key: 'gold', value: 1 }
```

2) Swap out `filter` with `removeFilter`:

```javascript
  { key: '*', value: 3 }
  { key: 'black', value: 5, removeFilter: [
    {
      AND: {
        '*': ['swiss', 'watch']
      }
    },
    {
      AND: {
        '*': ['apple']
      }
    }
  ] } // should this be true? Only matched in one condition
  { key: 'blue', value: 2 }
  { key: 'gold', value: 1 }
```

3) Have `filter: true`, but only on single clause queries (no `OR`)

**Comment by eklem** [comment]
Go for number 3 now. It's a solid solution and the simplest one. If we see/feel/get feedback on something else, then we can expand it. That's a better path, and we do not close any doors.

**Comment by fergiemcdowall** [comment]
Yes, thats sensible

**Comment by fergiemcdowall** [comment]
Option 3 now turned on for `categorize` queries consisting of 1 `OR` clause in `0.9.13`

**Comment by eklem** [comment]
Wohoo! Thak you, @fergiemcdowall
Is this all the way down to norch yet?

**Comment by fergiemcdowall** [comment]
Oh- not yet

**Comment by eklem** [comment]
No problem, and don't stress =)

**Comment by fergiemcdowall** [comment]
Just pushed it out anyway- version 0.8.9

**Comment by eklem** [comment]
I'll test!

**Comment by eklem** [comment]
Working just as expected and hoped for 😃
