### ISSUE TITLE
Sometimes some fields are ignored

### ISSUE THREAD

**Issue by simonecogno** [fergiemcdowall/search-index#349]
When I search into the index some fields are ignored. This doesn't happens all the time. 
Query: 
```javascript
storedIndex.search({query: {AND: {'*': ['word']}}})
...
```
also tried:
```javascript
storedIndex.search('word')
...
```
What can be the problem here? Maybe there is a minumum score that the document must have to be shown?

Edit: if I do:
```javascript
storedIndex.search({query: {AND: {'field_name': ['word']}}})
```
then it works

**Comment by fergiemcdowall** [comment]
(Could this be an uppercase/lowercase thing?)

Are you searching with the default parameters or are you doing stuff with the `searchable` flag?

Apologies for sounding like an uncaring maintainer from hell, but we really do need reproducible cases in order to debug.

**Comment by fergiemcdowall** [comment]
We are usually hanging out on https://gitter.im/fergiemcdowall/search-index - sometimes that is a good place to get help

**Comment by simonecogno** [comment]
These are the index option I use at the initialization phase:
```javascript
{
            db: 'mydb',
            indexPath: 'indexes/search_index_' + modelName,
            logLevel: 'error',
            preserveCase: false,
            nGramLength: 1
}
```

Anyways is not a problem with upper/lower case I have already tested it.

**Comment by fergiemcdowall** [comment]
An what does your data look like? Can you reproduce this error by adding say 10 docs and then searching?
