### ISSUE TITLE
Limit option for categorize seems to not be implemented?

### ISSUE THREAD

**Issue by eklem** [fergiemcdowall/search-index#351]
We lost this in one of the last big upgrades? set:true works, but limit not so much.
https://github.com/fergiemcdowall/search-index-searcher/blob/master/lib/CalculateCategories.js

**Comment by fergiemcdowall** [comment]
Ah yes. I wonder- does it make more sense to use `offset` and `pageSize` in `categorize`? Since `categorize` now takes a standard query object, it would make things more consistent

**Comment by fergiemcdowall** [comment]
maybe `limit` as well?

**Comment by fergiemcdowall** [comment]
Sorry- ignore the last two comments- it has to be `limit` :)

**Comment by fergiemcdowall** [comment]
Nooo- it can be `offset` and `pageSize` after all (too late in the day)

**Comment by fergiemcdowall** [comment]
categorize works with `offset` and `pageSize` in `0.9.14`

**Comment by eklem** [comment]
That's good, and even great news! I'm quite sure we don't need limit then. That makes it a lot easier to "show all" within a category. I can change the documentation if you agree. (remove limit, and add that categorize takes offset and pageSize.

**Comment by fergiemcdowall** [comment]
Yes- please do! At the moment, pageSize defaults to `20`. Maybe at some point it would make sense to implement `-1` for "unlimited"
