### ISSUE TITLE
Get all results for search, buckets, and categorize?

### ISSUE THREAD

**Issue by eklem** [fergiemcdowall/search-index#353]
Get all results back can be nice for some use cases / user stories. We could do this by:
```json
{"pageSize":"-1"}
```
This should be available for:
* **search**
* **buckets**
* **categories**
* and maybe **match** ?

**Comment by fergiemcdowall** [comment]
Yes, was thinking the same thing. Of course you can always use an arbitrarily large number such as `9999999999` but `-1` is definitely nicer

**Comment by fergiemcdowall** [comment]
`-1` could also be used in `search` when specifying unlimited page size

**Comment by fergiemcdowall** [comment]
This is now the default
