### ISSUE TITLE
Categorize on items in array, not just single words?

### ISSUE THREAD

**Issue by eklem** [fergiemcdowall/search-index#355]
If my data has a value that is an array of item(s), I would like categorize to recognize the item(s), not just single words.

So, an item with this key/value field:
```JSON
{"tags":
  [
    "javascript search engine"
  ]
}
```
... will result in one filter for the category `tags`, namely `javascript search engine` and not `javascript`, `search` and `engine`

**Comment by fergiemcdowall** [comment]
Yes- this would be nice and easy to understand functionality

**Comment by eklem** [comment]
A really nice effect of this would be that you don't have to, before indexing time, set up which field you want to categorize on.

**Comment by fergiemcdowall** [comment]
Now works- if fields are submitted as arrays, then they are tokenised as such. So `["javascript search engine"]` gives hits for "javascript search engine" but not "search" or "engine".

**Comment by eklem** [comment]
Wohoo! I'll test it soon.
