### ISSUE TITLE
Managing multiple instances

### ISSUE THREAD

**Issue by enceladus** [fergiemcdowall/search-index#356]
I'm trying to integrate search-index into my existing Loopback application, and I'm having a hard time.

I've created a postSearch.js module with multiple functions, like:

```js
module.exports = {
  indexExistingData: function (cb) { ... },
  indexSinglePost: function (post, cb) { ... },
  getPosts: function (query, cb) { ... }
}
```

But I'm not sure how to use my search index instance in each of them. I've tried creating it at the top of the module, like:

```js
var postIndex;
require('search-index')(options, function (err, newIndex) {
  postIndex = newIndex;
});
```

But that doesn't seem to work; `postIndex` is undefined when I call `postSearch.getPosts()` (which calls `postIndex.search()`) from another place in the application.

I've tried creating one each time, i.e.

```js
function createIndex (callback) {
  require('search-index')(options, callback);
}
... 
getPosts: function (query, cb) {
  createIndex(function (err, postIndex) {
    postIndex.search(...);
  });
}
``` 

But I get an error that it's already in use: `OpenError: IO error: lock postIndex/LOCK: already held by process`. This happens regardless of whether `postIndex.close()` is called when I'm finished with it.

Is there any way for search-index to be portable or is it just meant to be used in a single place? There's not much in the documentation about using it across an application, just in a single file.

**Comment by mewwts** [comment]
I think the reason is that requiring `search-index` is asynchronous. I.e. you call `getPosts()` before the callback to `require('search-index)` has fired. 
```Javascript
createIndex(function (err, index) {
  // the index should be defined and ready to accept function calls here.
})
// but you have no guarantees here
```

Could you elaborate @fergiemcdowall?

**Comment by fergiemcdowall** [comment]
Yes, @mewwts is right: like many node modules, `search-index` is a fickle asynchronous mistress.

You are initialising a new `search-index` every time you call `getPosts` which is leading to the `OpenError: IO error: lock postIndex/LOCK: already held by process` error.

Maybe something like this would work:

```javascript
module.exports = {
  indexData: postIndex.add,
  getPosts: postIndex.search
  // ...etc, and then use them as per the examples
}
```

**Comment by enceladus** [comment]
@mewwts — I understand that it's asynchronous, but how can I guarantee that the callback to `require('search-index')` has fired before calling `postIndex.search()`?

**Comment by fergiemcdowall** [comment]
@enceladus there are a few ways to guarantee that the index has initialised before doing anything- the documentation can be found here: https://github.com/fergiemcdowall/search-index/blob/master/doc/API.md#opening-and-closing-1

Here is one way:

```javascript
require('search-index')(options, function(err, si) {
  // si is now a new search index, and it can be talked to
})
```
