### ISSUE TITLE
nGramLength documentation?

### ISSUE THREAD

**Issue by eklem** [fergiemcdowall/search-index#357]
Do we have nGramLength documentation in order?
Its still like this if you want terms with 1, 2 and 3 words in them?
```javascript
const config = {
  nGramLength: [1,2,3]
}
```

**Comment by fergiemcdowall** [comment]
Yes, I think that _should_ work

**Comment by eklem** [comment]
I'll test a little (through norch) and document in proper places =)

**Comment by fergiemcdowall** [comment]
The way this works now is that a user can n-gramify documents on the way into the index. I will add an example to the doc
