### ISSUE TITLE
Test and document nGramSeparator

### ISSUE THREAD

**Issue by eklem** [fergiemcdowall/search-index#363]
The [nGramSeparator](https://github.com/eklem/search-index/blob/master/doc/API.md#ngramseparator) is not documented, but listed in the options TOC. I guess it's equal to the general separator. Will test and document.

**Comment by eklem** [comment]
Doesn't seem to work.

[This config works](https://github.com/eklem/vinmonopolet-crawler/blob/master/config.json), but is a bit cumbersome, so a [config like this](https://github.com/eklem/vinmonopolet-crawler/blob/master/config-test.json) would be very nice.

**Comment by fergiemcdowall** [comment]
Aha- work to do!

**Comment by eklem** [comment]
Hmm, think I misunderstood totally. What is the idea behind the nGramSeparator?

**Comment by fergiemcdowall** [comment]
I think i nGramSeparator is a relic from a past version. I have removed it for now. Yes, ngrams need to be better documented
