### ISSUE TITLE
Faceted search

### ISSUE THREAD

**Issue by cigolpl** [fergiemcdowall/search-index#366]
Hello, very interesting project and what's best - in Node.js!
I am looking for some relatively fast search engine in Node.js with full text and faceted search functionality. Similar like in eCommerce or like below picture:

![selection_008](https://cloud.githubusercontent.com/assets/1032493/24716799/7223ddea-1a30-11e7-90b7-c36166c23b1d.jpg)

Is the faceted search functionality like this also possible with  `search-index` ?

**Comment by eklem** [comment]
Yes! Buckets for year groups and categorize for the rest.

**Comment by fergiemcdowall** [comment]
Yes it is- check out the "categorise" function. https://github.com/fergiemcdowall/search-index/blob/master/doc/aggregations.md

**Comment by cigolpl** [comment]
Thanks, I'll test it out.
