### ISSUE TITLE
in browser example not working

### ISSUE THREAD

**Issue by vsmaier** [fergiemcdowall/search-index#367]
The in browser example does not work.

I suspect that the script from the /dist folder is not built for browser use. 

I did get a little bit further by building using the "dist" script but my code 
     
   ```
 const initIndex = function (err, index) {
        mySearchIndex = index;
        //search()
    }


   // initialize search-index
      SearchIndex({
        indexPath: 'si-demo',
        logLevel : 'debug',
        keySeparator: '~' // this is a websafe separator for most languages- change if weirdness occurs
      }, initIndex);

   mySearchIndex.concurrentAdd({}, search.datarecs, function(err) { alert('ready'); });

```
throws errors once I try to search

` mySearchIndex.search('beach').on('data', printResults)`

I get a log message for Key not found and afterwards the code throws an error

`err {type: "NotFoundError", name: "NotFoundError", cause: Error: NotFound
    at http://localhost:3000/js/GILSearch.js?29ec5fe5904a5cb8:19945:23
    at IDBTra…, message: "Key not found in database [DOCUMENT-VECTOR~1491518920302-165~*~]", stack: "NotFoundError: Key not found in database [DOCUMENT…t:3000/js/GILSearch.js?29ec5fe5904a5cb8:16743:17)"}
GILSearch.js?29ec5fe5904a5cb8:31974 
.....

Uncaught TypeError: Cannot read property 'beach' of undefined`

**Comment by fergiemcdowall** [comment]
Hey @vsmaier 

It seems to be to do with a new security policy that chrome has recently implemented where blocking third party cookies prevents writing to an indexedDB. See: https://github.com/w3c/presentation-api/issues/412

I'm looking at possible solutions...

**Comment by fergiemcdowall** [comment]
Compounded by rawgit not updating very fast.

**Comment by fergiemcdowall** [comment]
Bottom line: we need to fix the demo

**Comment by fergiemcdowall** [comment]
I removed the appcache functionality, and moved the hosting from rawgit (which had some issues with updating) to GitHub pages.

Now its "working for me" online, locally and on Travis.

Does it work for you?
