### ISSUE TITLE
Add benchmarking

### ISSUE THREAD

**Issue by fergiemcdowall** [fergiemcdowall/search-index#368]
It seems that indexing got slower again.

We should have some automated benchmarking of largish datasets in order to see how `search-index` is performing, so that changes to the code that create performance issues can be identified more easily.

**Comment by camillo777** [comment]
Hi!
Yes, I am trying to index 406.299 very simple objects like these:

```
{ 'Regione di origine': 'Sardegna',
  'Provincia di origine': 'Cagliari',
  'Comune di origine': 'Cagliari',
  'Sezione di destinazione': '2718',
  'Municipio di destinazione': '5' }
{ 'Regione di origine': 'Sardegna',
  'Provincia di origine': 'Cagliari',
  'Comune di origine': 'Cagliari',
  'Sezione di destinazione': '3160',
  'Municipio di destinazione': '6' }
{ 'Regione di origine': 'Sardegna',
  'Provincia di origine': 'Cagliari',
  'Comune di origine': 'Cagliari',
  'Sezione di destinazione': '3366',
  'Municipio di destinazione': '6' }
```

But it is taking really lot of time (hours).
I do not understand if it is how I am using the library.
Currently I create a huge object filled with all the docs and feed to "concurrentAdd" API.
I am not interested in stemming, bla bla, just searching exact matches in fields.
I am using standard options...

How much time is it supposed to take normally?
I tried "nedb" before and it is blazing fast (seconds); of course it is not doing categories, buckets, facets, but to me it is really slow.

I also worked before with Lucene and SphinxSearch (not with node.js) but they are really fast compared.

Thank you!
Camillo

**Comment by fergiemcdowall** [comment]
Hey @camillo777 , some users are experiencing difficulty when indexing larger datasets.

We haven't had any proper benchmarking in the test suite up until now, and in order to do so, we need some larger datasets

So, if your data is not private could you send it to us?

**Comment by camillo777** [comment]
Sure, I have it in csv format which I try to convert to json before feeding search-index, but I will try to write to disk as json if you need json.

**Comment by fergiemcdowall** [comment]
That would be great! My email is fergus@norch.io

**Comment by camillo777** [comment]
Hi, did you make any improvement to the indexing speed yet? 
Thank you 
Camillo

**Comment by fergiemcdowall** [comment]
Indexing should be generally faster these days
