### ISSUE TITLE
Cut tagged releases

### ISSUE THREAD

**Issue by blahah** [fergiemcdowall/search-index#369]
It would be helpful for debugging when issues crept in if there were tagged releases on github - this allows you to easily browse the whole codebase at a particular version. Would it be possible to do this for future releases?

**Comment by fergiemcdowall** [comment]
Yes- should be done.

**Comment by fergiemcdowall** [comment]
Should be a nice "awesome-publish" script that:

 * checks travis "just to make sure" that code has passed remote CI
 * tags code in git
 * npm publishes

**Comment by blahah** [comment]
this is what I generally use: https://www.npmjs.com/package/npm-release

it doesn't do the auto-checking of test status, but you can configure a travis task to cut the release for you on successful CI

**Comment by blahah** [comment]
This looks even better: https://github.com/semantic-release/semantic-release

**Comment by fergiemcdowall** [comment]
Noting for later: https://egghead.io/lessons/javascript-how-to-write-a-javascript-library-automating-releases-with-semantic-release

**Comment by fergiemcdowall** [comment]
Now set up with `semantic-release`- need to write a quick contributor HOWTO

**Comment by blahah** [comment]
nice work!

**Comment by fergiemcdowall** [comment]
https://github.com/fergiemcdowall/search-index/blob/master/docs/contributing.md
