### ISSUE TITLE
Can `matcher()` return docIDs along with strings?

### ISSUE THREAD

**Issue by jimkang** [fergiemcdowall/search-index#37]
`matcher` (and the whole project, really) seems very handy, but it feels like there's a gap between it and getting search results. 

In the use case of a search box with typeahead support, `matcher` will get you the suggestions to present to the user, but once the user selects one of the sections, to retrieve the actual relevant documents, you have to then call `search` with the actual selection.

It would be great if `matcher` gave you back not only matching field strings but also the docID, so you could just call `get` instead of `search`. Would the right approach for this be for `indexDoc` in indexer.js to stuff the docID in with the reverseIndex key?

**Comment by fergiemcdowall** [comment]
This now works https://github.com/fergiemcdowall/search-index/blob/master/doc/autosuggest.md
