### ISSUE TITLE
Error: The module was compiled against a different Node.js version using NODE_MODULE_VERSION 48

### ISSUE THREAD

**Issue by camillo777** [fergiemcdowall/search-index#370]
Hi,
When running my app I have got this error on 2 modules: DTrace and LevelDown.

```
Error: The module 'node_modules/dtrace-provider/build/Release/DTraceProviderBindings.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 48. This version of Node.js requires
NODE_MODULE_VERSION 53. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or`npm install`).

Error: The module 'node_modules/leveldown/build/Release/leveldown.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 48. This version of Node.js requires
NODE_MODULE_VERSION 53. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or`npm install`).
```

I tried what is suggested (npm rebuild or npm install) but it did not work.
Just wanted to understand if it is my problem and if you know how to solve it.

I am using these versions:

```
{ npm: '3.10.10',
  ares: '1.10.1-DEV',
  http_parser: '2.7.0',
  icu: '58.2',
  modules: '48',
  node: '6.10.1',
  openssl: '1.0.2k',
  uv: '1.9.1',
  v8: '5.1.281.95',
  zlib: '1.2.8' }
```
 
and these dependencies:

```
"chartist": "^0.11.0",
    "electron": "~1.6.2",
    "fast-csv": "^2.4.0",
    "nedb": "^1.8.0",
    "search-index": "^0.9.17"
```

on OSX Yosemite v.10.10.5 (14F2109).

Thank you
Camillo

**Comment by fergiemcdowall** [comment]
That can happen if there have been different versions of node available. Try removing node_modules and reinstalling. Check that you have no clashes with globally installed modules

**Comment by camillo777** [comment]
Hi, just to write how it seems to be solved:
http://stackoverflow.com/questions/42616008/node-module-version-conflict-when-installing-modules-for-electron

In your app's directory (where package.json is located at),

1. Install electron-rebuild

npm install --save-dev electron-rebuild

2. Rebuild

./node_modules/.bin/electron-rebuild

Maybe it can help others.

**Comment by fergiemcdowall** [comment]
👍👍
