### ISSUE TITLE
Nicer streaming syntax

### ISSUE THREAD

**Issue by fergiemcdowall** [fergiemcdowall/search-index#372]
At the moment you have to do all of this to add stuff into the index

```javascript
  fs.createReadStream('file.str')
    .pipe(JSONStream.parse())
    .pipe(index.defaultPipeline())
    .pipe(index.add())
    .on('data', function (data) {}).on('end', function () {
      console.log('done')
    })
```

It would be great if it was possible to do this with less boilerplate- for example:

```javascript
  fs.createReadStream('file.str').pipe(index.feed())
```

**Comment by eklem** [comment]
And the pipeline needs a documentprocessor example. One that renames a key from `url` to `id` could be good? Or maybe this is stuff for the Cookbook?

**Comment by fergiemcdowall** [comment]
@eklem yes.

**Comment by fergiemcdowall** [comment]
Fixed with 0.13.0. Still need som nice processing pipeline examples

**Comment by eklem** [comment]
Could add the Chinese tokenizer to show how to split up a block of text into words?

**Comment by eklem** [comment]
Use it as example, I mean.
