### ISSUE TITLE
Option to disable wildcard ('*') search

### ISSUE THREAD

**Issue by fergiemcdowall** [fergiemcdowall/search-index#373]
Wildcard search can be nice to have, but it creates monster arrays that slow down indexing, and bump up the size of the index. There should be an option to turn it off.

**Comment by fergiemcdowall** [comment]
Or at least reimplement wildcard logic so that it doesn't generate a monster array

**Comment by fergiemcdowall** [comment]
Fix the `{'*': ['*']}` case and also the `{myfield: ['*']}` case

**Comment by eklem** [comment]
How does indexing slow down because of "*"-search? Just curious

**Comment by fergiemcdowall** [comment]
The way it is set up now the index actually adds the wildcard character to the document vector ("this is a document vector" -> ['this', 'is', 'a', 'document', 'vector', '*']). Since every document has a wildcard- the reverse index entry for wildcard contains an array that contains every document ID. This monster Array needs to be extended and shuffled every time a new doc is added. <- SLOW!

**Comment by eklem** [comment]
I see. Any other way to do "*"-search, which is bypassing the regular search functionality? Most times when I use "*"-search, it's to be able to show categories and buckets, so the sorting of the actual documents aren't that important. And "*"-search never give you a good relevance back anyway.

**Comment by fergiemcdowall** [comment]
Yes- I think a version of search-index that allowed you to simply aggregate without sorting would be really cool, and non-sortable indexes would also be smaller/faster/simpler.

**Comment by eklem** [comment]
Nice! But also, just to have this for "show all", and make that something that isn't search, but can work on a regular search index.

**Comment by fergiemcdowall** [comment]
Exactly- "show all" sorted by ID

**Comment by fergiemcdowall** [comment]
`compositeField` and `wildcard` are now options
