### ISSUE TITLE
CLI tool

### ISSUE THREAD

**Issue by fergiemcdowall** [fergiemcdowall/search-index#374]
Twould be nice to be able to query an index on the command line

**Comment by eklem** [comment]
Somebody made something like this already. We can check if it's something we can fork.

**Comment by eklem** [comment]
https://www.npmjs.com/package/sosays

**Comment by eklem** [comment]
Would be cool if we could just expose the full API. Even if the input will be a little technical it will make the learning process a lot easier. I'll have a go later and document if any success.

**Comment by eklem** [comment]
I'm guessing we can just do an input to a function, and we don't need any `.then`-chaining, other than  a `console.log(result)` from each function.

**Comment by fergiemcdowall** [comment]
Yes, it would be nice to find some way to make a standalone binary that can play nice with other unix commandline programs using pipes and redirects.

**Comment by eklem** [comment]
Also, browser console works quite well, even if a bit different in Firefox and Chrome.
<img width="1432" alt="Screenshot 2019-03-19 at 11 03 07" src="https://user-images.githubusercontent.com/236656/54597322-af39c900-4a36-11e9-9e43-764d9fb31694.png">

**Comment by fergiemcdowall** [comment]
Oh- cool! :)

**Comment by eklem** [comment]
Firefox is working good, Chrome, just partly (.then() won't work). Good learning tool, I'll blog about it.

**Comment by eklem** [comment]
So, if I did this, would JSON stringified result be a good output? And parse input when search-index is piped to? Then you could do 
```console
si.AND <something> | si.DOCUMENTS
```
and get actual results out.

**Comment by eklem** [comment]
@fergiemcdowall, should I make it a separate module? Then search-index is kept with few dependencies. Or is it important enough to keep it in?

**Comment by eklem** [comment]
Here's how to [get data in through a pipe to search-index](https://shapeshed.com/command-line-utilities-with-nodejs/#piping-data).

**Comment by fergiemcdowall** [comment]
search-index queries are now essentially small js programs made up of promises. If it is possible just to send in a query as a "lump of javascript" then that would be the best. If possible?

**Comment by eklem** [comment]
Yes, that's a good idea. I was more thinking in the map reduce way:
```
some query | another query on returned ID's | yet another | DOCUMENTS
```
But I think your approach is better though, it's a good way of helping people get familiar with the query syntax and being easy. I can just use `eval()` or something. Will still try to keep the piping from one query to another. And do some shorthand on defining db (and name). Then you can do cool things like put a lot of data into one search-index, do a query or string of queries and put the result into another search-index.

**Comment by fergiemcdowall** [comment]
I do wonder if it would be a good idea to come up with a JSON representation of the query language though. That way it could be passed around more easily. Especially over HTTP

**Comment by eklem** [comment]
If we, for now, look at the JS-code way, I think something like `.then(result)` or .then(resultPrint)`should actually work, result/resultPrint being a function that do JSON.stringify and then console.log.

**Comment by eklem** [comment]
I'll have a go at this again when the [jsonAPI](https://github.com/fergiemcdowall/search-index/issues/475) gets stable enough =)

**Comment by eklem** [comment]
@fergiemcdowall, this means some extra dependencies. Is that okay, or should we make a separate one?

**Comment by fergiemcdowall** [comment]
One the JSON API is finished, it should be pretty easy to make a CLI app using `process.stdin` and `process.stdout`. Then you could do stuff like

```bash
# pipe data in
cat dataFile | searchIndex

# read data
searchIndex -r "{ SEARCH: [ 'search', 'terms' ] }"
```

**Comment by fergiemcdowall** [comment]
There has been a CLI example out for a while here -> https://replit.com/@fergiemcdowall/search-index-example-CLI

I now think that a CLI tool should probably be its own library, rather than baked into this one.
