### ISSUE TITLE
Limit with concurrent document addition?

### ISSUE THREAD

**Issue by maxime-helen-sb** [fergiemcdowall/search-index#375]
Thanks for this new concurrentAdd method, this is very helpful!

However, once I add 1000 documents concurrently and all callbacks are fired, I retrieve only about 330 of them with search method. Is this expected?

**Comment by fergiemcdowall** [comment]
It depends. If you are able to throw together a gist that reproduces the problem we can investigate.

**Comment by maxime-helen-sb** [comment]
[Here]((https://gist.github.com/maxime-helen-sb/368df5917bb74e3dac625e1f1fbc75c2#file-concurrent_additions-js)) is the test.

You'll need to install mocha, should and fs-extra along latest search index iteration using yarn/npm in order to make it run.

**Comment by fergiemcdowall** [comment]
OK- so you are adding `{ main: 'test.assembly'}` 1000 times, and then retrieving all 1000 docs to get the autogenerated ids, and then deleting all 1000 docs by id?

If so- that definitely _should_ work, and needs to be looked into if in fact it doesnt

**Comment by fergiemcdowall** [comment]
OK I just added a test case that covers this scenario- and it actually seems to work as expected, without errors: https://github.com/fergiemcdowall/search-index/blob/master/test/node/tape-tests/issue-376-test.js

What do you think?
