### ISSUE TITLE
Concurrent document removals

### ISSUE THREAD

**Issue by maxime-helen-sb** [fergiemcdowall/search-index#376]
I am testing following scenario:
1- Add concurrently 10 documents
2- Check they are searchable
3- Remove them
4- Check they are not searchable anymore

I am having issues with step 4, where I get the following error:

```
 Uncaught TypeError: Cannot read property 'test' of undefined
      at node_modules\search-index-searcher\lib\ScoreTopScoringDocsTFIDF.js:34:55
      at Array.forEach (native)
      at node_modules\search-index-searcher\lib\ScoreTopScoringDocsTFIDF.js:33:41
      at dispatchError (node_modules\levelup\lib\util.js:25:35)
      at node_modules\levelup\lib\levelup.js:228:14
```

Do you know what could be the problem? I get no errors when I add 1 or 2 documents.

Thanks in advance for your help!

**Comment by fergiemcdowall** [comment]
Again- that sounds like a bug that the existing tests (and there are many) dont pick up.

How do you reproduce this bug? Can you make a quick gist?

**Comment by maxime-helen-sb** [comment]
Sure! [Here](https://gist.github.com/maxime-helen-sb/368df5917bb74e3dac625e1f1fbc75c2) it is. 

You'll need to install mocha, should and fs-extra along latest search index iteration using yarn/npm in order to make it run.

**Comment by fergiemcdowall** [comment]
Hmmm, yes, I see what you are trying to do now- that definitely looks like it should work...

**Comment by fergiemcdowall** [comment]
OK I just added a test case that covers this scenario (and also #375 )- and it actually seems to work as expected, without errors: https://github.com/fergiemcdowall/search-index/blob/master/test/node/tape-tests/issue-376-test.js

What do you think?

**Comment by maxime-helen-sb** [comment]
There are two slight differences from my test:

- Documents are all unique with a common property (main).
- Documents additions/removals are made one by one and not by batches.

My intentions are to oversee simultaneous requests that call search index operations.

[Here](https://gist.github.com/maxime-helen-sb/368df5917bb74e3dac625e1f1fbc75c2#file-tape_example-js) is the updated gist.

**Comment by fergiemcdowall** [comment]
ok

**Comment by fergiemcdowall** [comment]
Basically we need a `concurrentDel` function that satisfies this test: https://github.com/fergiemcdowall/search-index/blob/master/test/node/tape-tests/issue-376-test.js#L46-L55

**Comment by maxime-helen-sb** [comment]
Sounds good to me! 

I am a bit worried about [this other issue](https://github.com/fergiemcdowall/search-index/issues/375) too. Have you experienced the same problem on your side? I am up to help you to investigate if you judge it necessary.

**Comment by fergiemcdowall** [comment]
I can't replicate the other issue. The [test](https://github.com/fergiemcdowall/search-index/blob/master/test/node/tape-tests/issue-376-test.js) seems to work when you concurrently index, delete and (try to) search 1000 documents.

Is there something I am missing?
