### ISSUE TITLE
processing pipeline example 

### ISSUE THREAD

**Issue by eklem** [fergiemcdowall/search-index#381]
See if I can get the Chinese tokenizer working in the add pipeline.

**Comment by eklem** [comment]
@fergiemcdowall, could you explain a little how a module would fit into the processing pipeline? It could take a URL key/value and duplicate it to also become an ID key with the same value.

**Comment by eklem** [comment]
Then I'll make some examples and create some documentation.

**Comment by fergiemcdowall** [comment]
Yes, you could do something like:

```javascript
fs.createReadStream('myData')
  .pipe(myAmazingProcessingStage)
  .pipe(index.feed())
```

**Comment by eklem** [comment]
I'll test. myAmazingProcessingStage doesn't need to be written streamy, or do it? I guess I have no idea what I'm heading into =)

Espen

**Comment by fergiemcdowall** [comment]
Its not toooo ridiculous- they are just transform streams. Here are some examples: https://github.com/fergiemcdowall/docproc/tree/master/pipeline

**Comment by eklem** [comment]
Thanks, I'll test based on the [IngestDoc.js](https://github.com/fergiemcdowall/docproc/blob/master/pipeline/IngestDoc.js). It seems doable.

**Comment by eklem** [comment]
Or, maybe [Spy.js](https://github.com/fergiemcdowall/docproc/blob/master/pipeline/Spy.js) is the easiest to base it on, @fergiemcdowall ?

**Comment by fergiemcdowall** [comment]
Yes, and you would of course do something with `doc` before pushing it back into the pipeline

**Comment by eklem** [comment]
Thanks. I can do this =)
I'll leave it open since its a `documentation` task and not just a question. I'll test and then document.

**Comment by fergiemcdowall** [comment]
I've added this to the list: https://github.com/fergiemcdowall/search-index/issues/458
