### ISSUE TITLE
 how to write filter for exact match for phrases? I might have more than 50 words in phrase.

### ISSUE THREAD

**Issue by AnnamrajuSarvani** [fergiemcdowall/search-index#386]
How to write to match string like this 
"SUCCESSION CERTIFICATE REGULATION, VII OF 1901, SECTION 6(1) CLAUSE (E)" ?

**Comment by fergiemcdowall** [comment]
You need to index the entire field as an ngram

**Comment by AnnamrajuSarvani** [comment]
Yes, done that but my length would be dynamic
 nGramLength: [1, 2, 3]

**Comment by fergiemcdowall** [comment]
oh- actually, another way is to specify a separator that won't split the string- that way the whole string is indexed as one token- so `separator:$$$$$$$` for example.

**Comment by eklem** [comment]
And separators can be set per field.

**Comment by AnnamrajuSarvani** [comment]
So it would be this 
separator:$$$$$$$ // instead of nGramLength

**Comment by eklem** [comment]
From @fergiemcdowall (posted in wrong place): "Yes- but do it on the field level, so that you dont affect separators on other fields"

**Comment by fergiemcdowall** [comment]
thanks @eklem too early in the morning! :)

**Comment by AnnamrajuSarvani** [comment]
Ok, let me try
