### ISSUE TITLE
how to search inside array

### ISSUE THREAD

**Issue by AnnamrajuSarvani** [fergiemcdowall/search-index#387]
Hi,
I have json object look below and searching for element inside array. If I give exact match for array element like topics have "soyabean oil" 
If I query this way I get result 
query:[
          {
            AND: {
              "*": ["Soyabean oil"] 
            }
          }
        ]
but below query doesn't return any result. Do I need add any option while indexing?
query:[
          {
            AND: {
              "*": ["Soyabean"] 
            }
          }
        ]
Data:
{   
   "topics": ["veg-oil", "linseed oil","Soyabean oil", "lin-oil", "soy-oil", "sun-oil", "soybean oil", "oilseed", 
   "corn", "sunseed", "grain", "sorghum", "wheat"],
    "places": ["argentina"],
   "id": "2"
}

**Comment by fergiemcdowall** [comment]
Thats because "soyabean" isnt a token- you would need to do some preprocessing to add "soyabean" to the array

**Comment by AnnamrajuSarvani** [comment]
How to do preprocessing? can you brief on that?
