### ISSUE TITLE
How to compare date?

### ISSUE THREAD

**Issue by AnnamrajuSarvani** [fergiemcdowall/search-index#388]
Hi,
 I have date to match in between range how to do that with search?

**Comment by eklem** [comment]
With buckets() you can get get the search result split up in ranges to filter on. But if you want to use the matcher I think you need to convert or pad the date. Are everything still strings @fergiemcdowall? 

What do you want to achieve, more specifically?

**Comment by fergiemcdowall** [comment]
Yes, the strategy would be to store dates as milliseconds, or some other sortable value, and then use filters and ranges.

**Comment by AnnamrajuSarvani** [comment]
I have date field like this: 
date:"1923-03-29T18:30:00.000Z"
I want to apply filters gte and lte and equal on this field.

**Comment by fergiemcdowall** [comment]
That should be fine- your format is alphabetically sortable

**Comment by AnnamrajuSarvani** [comment]
doesn't work returns empty results:

            AND: {
                'date': [{
                    "gte": start_date,
                    "lte": end_date
                }]
            }
        }

**Comment by fergiemcdowall** [comment]
@AnnamrajuSarvani you will need to provide a working example if you want to get feedback

**Comment by fergiemcdowall** [comment]
That is: a way to reproduce the error

**Comment by AnnamrajuSarvani** [comment]
Date is something like this in db
{"date": "1923-03-29T18:30:00.000Z"}

I am writing query like this
AND:{
	"date":[
	{
		gte:"1923-03-28",
		lte:"1923-03-29"
	}
	]
}
return empty result

**Comment by AnnamrajuSarvani** [comment]
Do I need to remove string after T?

**Comment by fergiemcdowall** [comment]
"1923-03-29T18:30:00.000Z" comes after "1923-03-29" when sorting

Appending an "X" (or some other char higher than "T") might work:

```javascript
gte:"1923-03-28",
lte:"1923-03-29X"
```

**Comment by AnnamrajuSarvani** [comment]
Ok, I will try this
