### ISSUE TITLE
How get unique result with search

### ISSUE THREAD

**Issue by AnnamrajuSarvani** [fergiemcdowall/search-index#389]
Hi,
I am using .search for getting text, if I use categorize my records are broken. How to do that?
Suppose I have few records like this
{"type":"single text"}
{"type":"single text"}
{"type":"single text"}
{"type":"single text"}
{"type":"single text"}
{"type":"multiple text"}
{"type":"multiline text"}
search will return all the records and .categorize as following:
categorize({
        query: [
          {
            AND: {'type': ['text']}
          }
        ],
        category: {
          field: 'text'
        }
      })
       returns following output:
{ key: '*', value: 4430 }
{ key: 'text', value: 4430, filter: true }
{ key: 'multiple', value: 218 }
{ key: 'multiline', value: 66 }
{ key: 'single', value: 4141 }

How to get proper text like this?
single text
multiple text
multiline text

**Comment by fergiemcdowall** [comment]
`AND: {'type': ['single text']}`, `AND: {'type': ['multiline text']}` ?

**Comment by AnnamrajuSarvani** [comment]
No, like this
AND: {'type': ['text']}

**Comment by fergiemcdowall** [comment]
You need to index the categories like so `['single text', 'single', 'text']`, so that "text" is a valid category token for the documents you want to categorise

**Comment by AnnamrajuSarvani** [comment]
So I need to use nGramLength for that?

**Comment by AnnamrajuSarvani** [comment]
I could have max 5 words so I can give nGramLength: 5?

**Comment by fergiemcdowall** [comment]
Yes, you could use `nGramLength: { gte: 1, lte: 5 }`

**Comment by AnnamrajuSarvani** [comment]
nGramLength doesn't seem to work, I am getting same output.

**Comment by fergiemcdowall** [comment]
Yes, `nGramLength` works. No, it might not be working in one specific case. If you discover a case where it does not work, please create a https://gist.github.com/ and we can take a look
