### ISSUE TITLE
Where leveldb files stored?

### ISSUE THREAD

**Issue by ahkimkoo** [fergiemcdowall/search-index#39]
Is that using leveldb to store index? So, where eveldb files stored, could I specify a location when initialize search-index?
Another question is, if I use Chinese characters， should I segment the sentence separated by a space before insets document into the index. 
just like this:

``` javascript
si.add({'doc1':{'title':"中文 字体"}}, batchName, filters, function(msg) {
  res.send(msg);
});
```

use search api like this:

``` javascript
si.search("query": {"*": ["中文 字体"]}, function(msg) {
  res.send(msg);
});
```

Is these right?

**Comment by phil294** [comment]
I don't thinkt hey are stored anywhere by default.  Doing a PUT then QUERY works fine, but on next application restart, QUERY is empty without the prior put, so it seems to stay in memory only.
