### ISSUE TITLE
How to match array elements?

### ISSUE THREAD

**Issue by AnnamrajuSarvani** [fergiemcdowall/search-index#390]
Hi,
I have data like this:
{
   "title": "NATIONAL AVERAGE PRICES FOR FARMER-OWNED RESERVE",
   "date": "26-FEB-1987 15:10:44.60",
   "topics": ["grain", "wheat", "corn", "barley", "oat", "sorghum"],
   "places": ["usa"],
   "id": "5"
} {
   "title": "ARGENTINE 1986/87 GRAIN/OILSEED REGISTRATIONS",   
   "date": "26-FEB-1987 15:14:36.41",
   "topics": ["veg-oil", "Linseed, Linpep", "lin-oil", "soy-oil", "sun-oil", "soybean", "oilseed", "corn", "sunseed", "grain", "sorghum", "wheat"],
   "places": ["argentina"],
   "id": "6"
}

Now I searching for data like this
  query:[{
            AND:{
              topics: ["linseed","linpep"]
            }
          }]
but query returns empty results what is the issue with array field? for normal fields this kind of search work fine. Please let me know what I have to do for search inside array fields.

**Comment by AnnamrajuSarvani** [comment]
can anyone suggest me something on this?

**Comment by fergiemcdowall** [comment]
@AnnamrajuSarvani you have indexed `..."Linseed, Linpep"...` and not `..."linseed", "linpep"...`

**Comment by AnnamrajuSarvani** [comment]
Yes, I have some cases like that. You are not allowing comma in array indexes?

**Comment by fergiemcdowall** [comment]
If you want to match `..."Linseed, Linpep"...`, search with `topics: ["Linseed, Linpep"]`

**Comment by AnnamrajuSarvani** [comment]
tried the same doesn't work. I am not able to get the exact reason for that.

**Comment by AnnamrajuSarvani** [comment]
can you check the test case for array fields and let me know.

**Comment by fergiemcdowall** [comment]
Closing this for just now. If you want other people to look into your problem, please provide a runnable script on https://gist.github.com/

**Comment by AnnamrajuSarvani** [comment]
https://gist.github.com/AnnamrajuSarvani/813178d9389a67df725c7f0f090bd74f

**Comment by fergiemcdowall** [comment]
@AnnamrajuSarvani can you make that gist public? That way other people having the same problem will be able to get help.

**Comment by AnnamrajuSarvani** [comment]
https://gist.github.com/AnnamrajuSarvani/bd0ac82bc946e97e989a7b91600642ca, you can try here

**Comment by fergiemcdowall** [comment]
OK- see fix here: https://gist.github.com/fergiemcdowall/734a234058e955746a62b314d0fea6ea

clone, npm install search-index and node index.js

**Comment by fergiemcdowall** [comment]
see #397
