### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by nickoffff** [fergiemcdowall/search-index#391]
When trying to install as npm install --save search-index I am getting the following error:

npm ERR! path W:\Arbeit\Development\node\index-js-test\node_modules\.errno.DELETE\node_modules\prr
npm ERR! code EEXIST
npm ERR! errno -4075
npm ERR! syscall rename
npm ERR! EEXIST: file already exists, rename 'W:\Arbeit\Development\node\index-js-test\node_modules\.errno.DELETE\node_modules\prr' -> 'W:\Arbeit\Development\node\index-js-test\node
_modules\errno\node_modules\prr'
npm ERR! File exists: W:\Arbeit\Development\node\index-js-test\node_modules\.errno.DELETE\node_modules\prr
npm ERR! Move it away, and try again.

**Comment by fergiemcdowall** [comment]
Hmmm- thats an odd issue. Are you by any chance on an older version of npm? I suspect that updating everything and reinstalling will fix it.

**Comment by nickoffff** [comment]
I updated to the last version of npm before writing. So the error persists.

**Comment by fergiemcdowall** [comment]
Can you do `npm install --save levelup`?

**Comment by nickoffff** [comment]
It does not work too. Other packages, however, are working as far as I know.

**Comment by fergiemcdowall** [comment]
Aha- Interesting! One last test- can you do `npm install --save leveldown`?

**Comment by fergiemcdowall** [comment]
...and if it is indeed a leveldown problem- you _probably_ need to set node up to run native dependencies as described here: https://github.com/Level/leveldown#tested--supported-platforms and

**Comment by nickoffff** [comment]
Thanks for the hint. I am on Windows. I installed npm install -g node-gyp and npm install --global --production windows-build-tools. But unfortunately, it still does not work.

**Comment by fergiemcdowall** [comment]
Ahh- looks like you're on the dreaded "option 2" then -> https://github.com/nodejs/node-gyp#option-2

**Comment by nickoffff** [comment]
Seems to be not trivial. I will try around. Thanks for the help.
