### ISSUE TITLE
How to close exsisting instances for index and create new?

### ISSUE THREAD

**Issue by AnnamrajuSarvani** [fergiemcdowall/search-index#395]
Hi,
I am using async request model to my api which loads the index and returns error:
IO error: lock bench_type_index/LOCK: already held by process
My API is like this:
SearchIndex(ops, function(err, index) {
    index.search(query)
        .on('data', function(data) {
            
        })
        .on('end', function() {
            index.close(function(err) {
               
            });

        })
});
So while making request for index I need to check any exsisting instance. So that I wait or kill that instance and create new. How to do this?

**Comment by fergiemcdowall** [comment]
@AnnamrajuSarvani  You shouldn't need to be killing and creating instances all the time. The constructor for search index is for better or worse asynchronous- you just have to structure your program in a way that deals with that.
