### ISSUE TITLE
Cannot make a search on all fields

### ISSUE THREAD

**Issue by Samy78** [fergiemcdowall/search-index#396]
Hello, i am new with search index in node JS and i tried to make a search engine from Json file but it doesn't work for all fields.
here is my code
```javascript
var express = require('express');
var router = express.Router();
var fs = require('fs')
var JSONStream = require('JSONStream')
var options = {
    "batchSize": 1000,
        "fieldedSearch": true,
        "preserveCase": false,
        "storeable": true,
        "searchable": true,
        "indexPath": "data",
        "logLevel": "error",
        "nGramLength": [1]
}
var searchIndex = require('search-index')
var dataset = require('../node_modules/reuters-21578-json/data/justTen/justTen.json')


/* GET users listing. */
router.get('/', function(req, res, next) {


    searchIndex(options, function(err, si) {
       // si.flush(function(err) {
        // if (!err) console.log('success!')
        //})
        si.concurrentAdd(dataset, {}, function(err) {
            if (!err) console.log('indexed!')
            else return callback(err, {})
            console.log(si.fields);
            console.log('doing a test search...')
            si.search({"query": [
                {AND: {'*':["COCOA"]}}]} , function(err, results) {
                console.log('total hits: ' + results.totalHits)
                for (var i = 0; i < results.hits.length; i++) {
                    console.log()
                    console.log('* ' + results.hits[i].document.title + ' *')
                    console.log('* ' + results.hits[i].document.date + ' *')
                    console.log()
                    console.log('--------------------')
                }
                res.status(200).send(results.hits)
            })
        })



    });

    //res.end();


    // res.end(results.hits);
});

module.exports = router;
```

**Comment by fergiemcdowall** [comment]
What happens when you search with an empty query (`si.search()`) ? Does it return all 10 docs?

**Comment by Samy78** [comment]
No is doesn't return all 10 docs, it shows me an error :
 if (!Array.isArray(q.query)) {
                      ^

TypeError: Cannot read property 'query' of undefined

**Comment by Samy78** [comment]
the document in the indexer is duplicated, for exemple if i run this query 

> {"query": [ {AND: {'places':["usa"]}}]}

I get 8 hits and it doesn't contains the first object of justTen.json which "usa"

> "places": [
      "el-salvador",
      "usa",
      "uruguay"
    ],

**Comment by fergiemcdowall** [comment]
do this:

```javascript
var SearchIndex = require('search-index')
var fs = require('fs')

SearchIndex({}, function (err, index) {
  fs.createReadStream('./node_modules/reuters-21578-json/data/fullFileStream/justTen.str')
    .pipe(index.feed())
    .on('finish', function() {
      index.search({
        query: {
          AND: {
            places: ['usa']
          }
        }
      }).on('data', function (d) {
        console.log(d)
      })
    })
})

```

**Comment by Samy78** [comment]
I have already tested this and it shows me the same error :


> .pipe(index.feed())
                        ^
TypeError: index.feed is not a function

**Comment by fergiemcdowall** [comment]
Ahh- in that case its almost certainly because you are running a slightly older version of `search-index`. Delete `node_modules` and try reinstalling `search-index@0.13.0` or above.

**Comment by Samy78** [comment]
Yes it works, but still cannot make a query with two columns for exemple:
`index.search({
                    query: [{
                        AND: {
                            places: ['usa'],
                            title:['BAHIA COCOA REVIEW']
                        }
                    }]
                })`
and when i changed the Json File there is no hits and no errors.
I tried to to inspect available fields and it shows me this :


> 222
223
224
225
226
227
228
229
23
230
231
232
233
234
235
236
237
238
239
24
240
241
242
243
244
245
246
247
248
249
25
250
251
252
253
254
255
256
257
258
259
26
260
261
262
263
264
265
266
267
268
269
27
270
271
272
273
274
275
276
277
278
279
28
280
281
282
283
284
285
286
287
288
289
29
290
291
292
293
294
295
296
297
298
299
3
30
300
301
302
303
304
305
306
307
308
309
31
310
311
312
313
314
315
316
317
318
319
32
320
321
322
323
33
34
35
36
37
38
39
4
40
41
42
43
44
45
46
47
48
49
5
50
51
52
53
54
55
56
57
58
59
6
60
61
62
63
64
65
66
67
68
69
7
70
71
72
73
74
75
76
77
78
79
8
80
81
82
83
84
85
86
87
88
89
9
90
91
92
93
94
95
96
97
98
99
body
data
date
id
places
title
topics
type

here ismy json file:

> [
  {
    "Nom": "@",
    "Type": "function",
    "Description": "Cursor and screen manipulation."
  },
  {
    "Nom": "ABORT",
    "Type": "statement",
    "Description": "Program termination."
  },
  {
    "Nom": "ABS",
    "Type": "function",
    "Description": "Returns absolute value."
  },
  {
    "Nom": "ABSS",
    "Type": "function",
    "Description": "Returns absolute value of elements in a dynamic array"
  },
  {
    "Nom": "ADDS",
    "Type": "function",
    "Description": "Adds corresponding elements in two dynamic arrays."
  }]

**Comment by fergiemcdowall** [comment]
Thats probably because "BAHIA COCOA REVIEW" is being tokenized as `['BAHIA', 'COCOA', 'REVIEW']`. The following should work:

```javascript
      index.search({
        query: {
          AND: {
            places: ['usa'],
            title: ['BAHIA', 'COCOA', 'REVIEW']
          }
        }
      }
```

(if you want to match exact phrases such as "BAHIA COCOA REVIEW", look into ngrams or pre-tokenize your input)

**Comment by Samy78** [comment]
no sorry it doesn't work, searching works only for column "places"

**Comment by fergiemcdowall** [comment]
Oh- and it needs to be lowercase:

```javascript
      index.search({
        query: {
          AND: {
            places: ['usa'],
            title: ['bahia', 'cocoa', 'review']
          }
        }
      }
```

(alternatively you could feed with `preserveCase: true`)

**Comment by Samy78** [comment]
ok thank you, now it works, but can i stream json file instead of str file ?

**Comment by fergiemcdowall** [comment]
The str file is just a newline delimited set of JSON objects. If your file is an Array of objects, or even some other format, then you can pipe() through something like JSONStream

**Comment by Samy78** [comment]
ok thank you
