### ISSUE TITLE
accents / UTF-8

### ISSUE THREAD

**Issue by drzraf** [fergiemcdowall/search-index#402]
I had hard time finding how search-index manage accentuated characters.

The web-demo does not handle them. Search for "accent" in the 3 repositories does not bring anything.
With ECMA 2015 [String.normalize()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/normalize) it's easy to transliterate an UTF-8 string, but I can't see whether search-index already handles this, and whether or not it could be (easily) added in the search/index pipeline.

The main use for such an option is"ignoring accent".
Ex: searching for _numero_ and getting results of items containing _numéro_ (french)
  (and, as a suboption in an ideal world), a search for _jeûne_ (accented) may ignore _jeune_ (unaccented)

**Comment by fergiemcdowall** [comment]
Documentation needs to be improved ( #392 )

There's an option called `normaliseCharacters` (note the 's' - UK english spelling) which invokes `String.normalize()` to do pretty much exactly what you want. Its experimental, but it should work.

**Comment by fergiemcdowall** [comment]
Character normalisation is now external by design
