### ISSUE TITLE
Migration scripts for index when code is a bit more mature?

### ISSUE THREAD

**Issue by eklem** [fergiemcdowall/search-index#403]
When people have their index with searchable data and wants to upgrade search-index to a newer version. Would it be nice (and possible) to make explanations or also scripts that converts the data to new format?

Then the users could export data, run migration script on data, upgrade search-index, and import data.

**Comment by fergiemcdowall** [comment]
This would be nice to have but a lot of work. Since users can reindex their data, I think that we can drop upgrade scripts for the time being.

**Comment by eklem** [comment]
Yes, think this is when we see a lot of active use of the library. Or we have usecases that needs this.
