### ISSUE TITLE
Filtering on values in array

### ISSUE THREAD

**Issue by poltak** [fergiemcdowall/search-index#404]
Hi there. I've seen the in some recent issues and example data the use of arrays as values within the index docs, allowing search on the values inside the array. I'm wondering if it's possible to do filters on these array values as well.

To give an example, consider adding these docs to an index, `fieldedSearch` available on `content` and `timestamp`:

```js
{
  id: '1',
  content: 'Some great writing',
  timestamps: ['3', '5', '4'],
}
{
  id: '2',
  content: 'Some more great writing',
  timestamps: ['1', '2', '3'],
}
{
  id: '3',
  content: 'Some pretty foul writing',
  timestamps: ['6', '5', '9'],
}
```

And say my query looks something like this:

```js
{
  query: {
    AND: {
      content: ['writing'],
      timestamps: [{
        gte: '5',
        lte: '10',
      }],
    },
  },
}
```

The intention of the query may be clear, but basically: 
- `content` field search should match all three as the term `'writing'` appears in all three docs' `content` fields
- `timestamp` field filter should only match docs with ID 1 and 3 (given that all the values in doc ID 2's `timestamps` array are below the `gte: '5',` part of the filter)

Have played around using queries like the above, but not getting far. Not sure if it's simply not possible or there's an expected syntax I'm not giving in the query (something like `timestamps.*` for the key?). Or maybe this type of query is just not appropriate for how the index works, and I'm thinking about it in the wrong way - still getting familiar with this stuff.

Anyway, thanks in advance for taking the time to read :)

**Comment by eklem** [comment]
Arrays are perfect for when you want to filter on your content. Your example should work, and I'm guessing you just have some small error in the syntax. 

In many situations you would do this through buckets() and categorize(). Buckets() and categorize() will show you which filters are available for your query. But this doesn't matter for this example.

Could you make a public gist so it's easy to test?

**Comment by fergiemcdowall** [comment]
@poltak you are on the right track. Everything is sorted alphabetically in `search-index`, this means that `10` comes before `5`. It should work if you do something like:

```javascript
    {
      query: {
        AND: {
          content: ['writing'],
          timestamps: [{
            gte: '4',
            lte: '9',
          }]
        }
      }
    }
```

In order to search numerically you can do a few things- the easiest is probably to "left pad" your numbers when you index and when you search

**Comment by poltak** [comment]
> Everything is sorted alphabetically in search-index, this means that `10` comes before `5`.

Ah that makes perfect sense, and fairly obvious in hindsight. Makes sense why my demo data wasn't working as I expected: was using random times from 0-15. In reality the timestamps will be in epoch time so they should work fine, assuming any time recently.

Anyway, good to know that this is possible :) I think my question is answered.

Would a PR containing a few lines in the docs regarding query ops on array values be of any use?

> In many situations you would do this through buckets() and categorize()

Yeah saw the available aggregation methods. In this query I only care if there's a match in the data to the given filter, so I think no aggregations are needed, but may be useful to me in other scenarios.

Thanks a lot for your responses. Much appreciated.

**Comment by eklem** [comment]
A PR is always welcome. If it's only a small documentation issue you can also just come with the text here and we can snap it in place.

**Comment by fergiemcdowall** [comment]
@poltak Documentation PRs are particularly welcome
