### ISSUE TITLE
Cannot get search to return any result

### ISSUE THREAD

**Issue by ValeryIvanov** [fergiemcdowall/search-index#405]
I am unable to get any results from search query, but do get all entries when I remove query object from search.

Here is main code for my app
https://github.com/ValeryIvanov/documenter/blob/master/index.js

I has some basic UI as well to add data and search for some so you can test that out if you want.

**Comment by fergiemcdowall** [comment]
There is no way to debug your problem without knowing what data you are putting in, or how you are searching for it. Since you say that an empty search returns all documents, it is almost certainly just a question of double-checking your query syntax.

**Comment by ValeryIvanov** [comment]
Data is here

https://github.com/ValeryIvanov/documenter/blob/master/data/example.json

If I search for string 'hello', I get nothing.

Here is the query I am using

```
    var q = {
        query: [{
            AND: { 'text': ['hello'] }
        }]
    };
```

**Comment by fergiemcdowall** [comment]
This works:

```javascript
require('search-index')({}, function (err, index) {
  index.concurrentAdd({}, [
    {
        "creator": "ValeryI",
        "timestamp": "Fri Aug 04 2017 15:05:36 GMT+0300 (FLE Standard Time)",
        "text": "Some random text"
    },
    {
        "text": "hello this is me again how are things going",
        "timestamp": "Sun Aug 06 2017 18:27:17 GMT+0300 (FLE Standard Time)",
        "creator": "ValeryI"
    }
  ], function (err) {
    index.search({
      query: {
        AND: {
          text: ['hello']
        }
      }
    }).on('data', function (d) {
      console.log(d)
    })
  })
})
```

**Comment by ValeryIvanov** [comment]
So what exactly is wrong with my work?

Should not this work?

```
    fs.createReadStream("data/example.json")
        .pipe(index.feed())
```

**Comment by eklem** [comment]
@ValeryIvanov I'm not sure, but I think that you need a streaming JSON format:


```
{...}
{...}
{...}
```
and not
```
[
  {...},
  {...},
  {...},
  {...}
]
```

The .concurrentAdd() can take arrays, if I'm not wrong. @fergiemcdowall Is the feed() a more basic version of add()?

**Comment by eklem** [comment]
Not sure about the difference between .feed() and .add(), but .concurrentAdd can take arrays of objects, .feed() and .add() takes a stream of objects, [line delimited](https://en.wikipedia.org/wiki/JSON_Streaming#Line_delimited_JSON).

**Comment by fergiemcdowall** [comment]
Yes @eklem I think you are correct about the formatting
