### ISSUE TITLE
Custom pipeline support with concurrentAdd

### ISSUE THREAD

**Issue by poltak** [fergiemcdowall/search-index#406]
With the standard `.add` method, it returns a Writable stream so you can easily pipe an input Readable stream to custom pipelines/Transform streams beforehand to do whatever fancy preprocessing.
 
`.concurrentAdd`, rather than returning a Writable, is just a function that accepts options, input docs, and a callback to call after async processing is done (as doc'd [here](https://github.com/fergiemcdowall/search-index/blob/master/docs/API.md#concurrentadd)). Makes things difficult to preprocess with a pipeline, as they are implemented as Transform streams (or at least docproc/`defaultPipeline` is), so you'd have to either batch up pipeline output and call `concurrentAdd` on stream `end`, or call `concurrentAdd` on every stream `data` emit, both rather awkward.

Some ideas:
- `.concurrentAdd` could return a Writable to be consistent with `.add` (may be a good reason why they are different?)
- simpler route could be accepting `pipeline` as a optional key in the already accepted` batchOptions` arg (first arg). Default value could be `defaultPipeline`.

**Comment by fergiemcdowall** [comment]
We have now moved away from streams as they haven't really been adopted outside of node-land, and therefore make life a bit more painful than necessary when using `search-index` in the browser.

Pipelines can be built up using `Promise` chains.
