### ISSUE TITLE
Setting up search-index in browser, want to add custom pipeline

### ISSUE THREAD

**Issue by chrisdmacrae** [fergiemcdowall/search-index#407]
Hey @fergiemcdowall, I'm setting up search-index for the search for a static site generated in Hugo.

The data is generated as a JSON store, which is fetched via ajax by search-index using si.concurrentAdd(...).

I prefer search-index over all other solutions, but a requirement for this search is stemming. I'd like to use porter's stemming, and add it into the doc pipeline, but I can't figure out how to make this happen.

I understand docProc is used in the backend to create the pipeline, but I don't understand how to add a custom pipeline created with docProc into search-index.

Any help you could offer would be greatly appreciated.

**Comment by fergiemcdowall** [comment]
Hey @chrisdmacrae 

You are the [second person this week](https://github.com/fergiemcdowall/search-index/issues/406) to ask about putting a custom pipeline into `concurrentAdd(...)` 😄  That functionality doesn't currently exist, but will be implemented shortly.

You can however currently do this quite easily if you place a pipeline stage before the `.feed` method:

```javascript
readStreamOfDocuments                 
    .pipe(myStemmer())
    .pipe(myIndex.feed())
```

I have been meaning to write an article about how to make a stemming pipeline for at least a year. Will do so soon.

**Comment by chrisdmacrae** [comment]
Sounds good @fergiemcdowall! It's a great library, you're doing fantastic work!

Is `.feed` supported in the browser, or is that in the Node environment where streams are available?

**Comment by fergiemcdowall** [comment]
There are exceptions, but generally speaking, if you are using `search-index` in the browser, you want to pre-compile the index on a server somewhere and then load the complete index into the browser with `.dbWriteStream()`.

Alternatively you can create streams in the browser with something like [`highland`](https://github.com/caolan/highland)

**Comment by fergiemcdowall** [comment]
...which will then allow you to use `.feed()`

**Comment by fergiemcdowall** [comment]
Oh- and thanks for the positive vibes :)
