### ISSUE TITLE
Not exactly an issue but the separator regex from options can be reduced to /[' .,\-|(\n)]+/

### ISSUE THREAD

**Issue by AmanelX** [fergiemcdowall/search-index#408]

**Comment by fergiemcdowall** [comment]
Sound reasonable- want to submit a PR?

**Comment by fergiemcdowall** [comment]
*sounds

**Comment by AmanelX** [comment]
how do you pull request on github? :)

**Comment by AmanelX** [comment]
*submit

**Comment by eklem** [comment]
@AmanelX Fork the repository, edit your fork and commit. On your fork you'll then get a "create pull request"-button in the top, just below the header/menu.

**Comment by AmanelX** [comment]
@eklem  Thanks!

**Comment by eklem** [comment]
=) Just ask more if you hit any problems on the way.

**Comment by AmanelX** [comment]
@eklem did it! :)

**Comment by eklem** [comment]
Nice, tests passed, so I requested a review from @fergiemcdowall

**Comment by fergiemcdowall** [comment]
I approved the documentation change as the suggested regex was more concise
