### ISSUE TITLE
Make demo of search-index working with hyperdb?

### ISSUE THREAD

**Issue by eklem** [fergiemcdowall/search-index#409]
How can we make a simple demo of search-index so that it works with hyperdb or on a [dat](https://github.com/datproject/dat) filesystem? Just to make us learn more on how this could work well, and what is needed from search-index' end.

**Comment by fergiemcdowall** [comment]
Yes, specifically if there is a hyperdb-down

**Comment by eklem** [comment]
Yes, I just saw that the DAT-idea was one step closer to be available, was searching for hyperdb-down, but couldn't find anything.

**Comment by eklem** [comment]
Not the first thing that will happen @fergiemcdowall, but I'll have a go at this in a while, after understanding how to [switch DB in search-index](https://github.com/eklem/designing-with-search-data/issues/4) and have [documented howto switch DB](https://github.com/fergiemcdowall/search-index/issues/464).

**Comment by eklem** [comment]
For hyperdb to store in indexeddb: https://github.com/mafintosh/hyperdb/issues/96

**Comment by eklem** [comment]
After looking around some more, this seems a bit premature. Closing for now...
