### ISSUE TITLE
Option to remove bunyan logging 

### ISSUE THREAD

**Issue by swissums** [fergiemcdowall/search-index#410]
It would be great to give an option to remove bunyan logging because when trying to run search-index in a web worker bunyan tries to access the `window` and `browser` throwing an error.

**Comment by fergiemcdowall** [comment]
What about removing bunyan logging altogether? I feel like `console.log` and `console.error` coupled with some simple log levels should suffice, and would certainly make the lib more portable. I think `bunyan` is overkill in this instance.

**Comment by fergiemcdowall** [comment]
@GiladShoham has fixed this in the latest 0.14.0 version (we just use a simple logger now)
