### ISSUE TITLE
Supplying sort arg to query

### ISSUE THREAD

**Issue by poltak** [fergiemcdowall/search-index#414]
This doesn't appear anywhere in the docs (from what I can see), so not sure if just not implemented/supported yet; possibly this is already known, but couldn't find anything.

After reading through a bit of the `search-index-searcher` code, I can see there is an option to supply `sort` field to the query object ([L104 in `search` method of `index.js`](https://github.com/fergiemcdowall/search-index-searcher/blob/master/index.js#L104)) which accepts a `field` key and (I presume) a name of a field as value (as per its use [here](https://github.com/fergiemcdowall/search-index-searcher/blob/master/lib/ScoreDocsOnField.js#L18)). Supplying `sort` field in the query leads to using the `ScoreDocsOnField` Transform stream for scoring rather than default `ScoreTopScoringDocsTFIDF` stream (L108 and L116 of `index.js`, respectively).

Problem currently seems to be that the `_transform` method in `ScoreDocsOnField` only emits docs with `id` and `score` keys ([L27 in `ScoreDocsOnField.js`](https://github.com/fergiemcdowall/search-index-searcher/blob/master/lib/ScoreDocsOnField.js#L27)). The next stream in the pipeline, `MergeOrConditions`, expects third key `scoringCriteria` in the case of the same consecutive doc in the "merge" ([L30 in `MergeOrConditions.js`](https://github.com/fergiemcdowall/search-index-searcher/blob/master/lib/MergeOrConditions.js#L30)). This leads to the same TypeError reported in #371 whenever I try to use the `sort` key in queries.

Is there any other prereq to use `sort` in queries (like the `sortable` field option, for example? not sure if this is related) that results in `MergeOrConditions` to never have the same consecutive doc in the merge, or this is a bug/unfinished aspect of the `ScoreDocsOnField` stream?

**Comment by fergiemcdowall** [comment]
How to specify a sort field in a query is not currently described in the documentation, and it really, _really_ should be. TODO.

In the meantime you can see how it works in the tests. remember that you need to make sure that `sortable: true` for the field when indexing. https://github.com/fergiemcdowall/search-index/blob/master/test/node/mocha-tests/sorting-test.js

**Comment by poltak** [comment]
Thanks @fergiemcdowall. Managed to implement explicit sorting this morning making a new `sortable` field from this info. 

Still running into that same TypeError when adding `sort` to query occasionally, but it _seems_ to be data related (i.e., comes and goes with the same sorted queries, depending on what data is in the index). If I can narrow it down and reproduce it in node, I'll let you know.

**Comment by fergiemcdowall** [comment]
We should also put in a more helpful error message if you are trying to sort on a field that is not defined as `sortable`

**Comment by poltak** [comment]
> Still running into that same TypeError when adding sort to query occasionally, but it seems to be data related (i.e., comes and goes with the same sorted queries, depending on what data is in the index). If I can narrow it down and reproduce it in node, I'll let you know.

Not sure if I should make a new issue or it can stay here, but managed to reproduce it [in this script](https://gist.github.com/poltak/308fa2f8a6c5d561c2989ad27fdec73e). So far I've only got it to happen under these conditions:
- have a `sortable` field
- `appendOnly` set to `true` in index opts
- you "reindex" a doc containing an ID already in the index
- after indexing, run a search with a query containing a `sort` clause on that `sortable` field (queries excluding `sort` should be fine)

Going by what's written in the docs [here](https://github.com/fergiemcdowall/search-index/blob/master/docs/API.md#add), when you index a doc with the same ID as an existing indexed doc (with `appendOnly` set) it "will simply overwrite the old one without deleting the previous one". Maybe the `sortable` field doesn't get processed properly on that overwrite? Or maybe this is expected behaviour and I'm not entirely clear on how `appendOnly` works

**Comment by fergiemcdowall** [comment]
`appendOnly` add documents without deleting any earlier documents with the same id. So if you are being super-advanced you can use it to add fields to an existing document, but most of the time it should only be used when you know that a document with that id is not already in the index.

**Comment by fergiemcdowall** [comment]
I just improved the sorting functionality. From `0.14.0` and onwards there is now no need to define fields as `sortable` when indexing. Sorting should also be faster.
