### ISSUE TITLE
Replacing standard chrome history

### ISSUE THREAD

**Issue by oliversauter** [fergiemcdowall/search-index#415]
It seems as if we could replace the entire chrome history page (with Worldbrain)

Future idea, but massively cool :)

<img width="1792" alt="screen shot 2017-09-12 at 17 27 23" src="https://user-images.githubusercontent.com/7870039/30363455-79f0b256-9860-11e7-9609-de68455d1e46.png">

**Comment by oliversauter** [comment]
Sorry wrong repo :/

**Comment by eklem** [comment]
No problem :-)
