### ISSUE TITLE
undefined:1 undefined ^  SyntaxError: Unexpected token u in JSON at position 0

### ISSUE THREAD

**Issue by AmanelX** [fergiemcdowall/search-index#417]
at JSON.parse (<anonymous>)
    at CreateStoredDocument._transform (/home/elanimus/Desktop/Untitled Folder 2/node_modules/docproc/pipeline/CreateStoredDocument.js:25:36)
    at CreateStoredDocument.Transform._read (_stream_transform.js:186:10)
    at CreateStoredDocument.Transform._write (_stream_transform.js:174:12)
    at doWrite (_stream_writable.js:385:12)
    at writeOrBuffer (_stream_writable.js:371:5)
    at CreateStoredDocument.Writable.write (_stream_writable.js:288:11)
    at IngestDoc.ondata (_stream_readable.js:642:20)
    at emitOne (events.js:115:13)
    at IngestDoc.emit (events.js:210:7)

**Comment by AmanelX** [comment]
var sw = require('stopword');
var searchoptions = {
    batchSize: 1000,
    fieldedSearch: true,
    fieldOptions: {},
    //appendOnly: true,
    preserveCase: false,
    storeable: true,
    searchable: true,
    indexPath: 'news',
    logLevel: 'error',
    nGramLength: 1,
    nGramSeparator: ' ',
    separator: /[' ፥«»፣።.,|(\n)]+/,
    stopwords:sw.en,
};

var Searchindex ;
var SearchIndex = require('search-index');
SearchIndex(searchoptions, function(err, inde) {
    Searchindex = inde; 
});


var allh = [];
function buildSearchI(){	
 db.ref('/ethiopia/links/').once('value').then (function(snapshot){
  try{
    var list = snapshot.val();
      var i = 0;
      for(var hash in list){
       allh.push(hash); 
       if(GAZETA.force){
        var tbi = list[hash];
        
        if(tbi.body && tbi.source!=='enagovet'){
          tbi.body = tbi.body.toString().replace(/[,]+/g,' ').replace( /\r?\n|\r/g, '' ); 
          tbi.hash = hash;
        }
        console.log(++i+':'+hash);
        store.push(tbi); 
       }
      }
    if(GAZETA.force){
     console.log('finised building search!!');
     store.push(null);  
     store.pipe(Searchindex.defaultPipeline()).pipe(Searchindex.add());
    }   
    //startIndex();
   }catch(e){
    console.log(e);
   }
  });                              
}

**Comment by AmanelX** [comment]
Here is the json that is looped in the buildSearchI() function. 
https://filenurse.com/download/e3eb0a95ab927b28c8aea91c0103d31c.html

**Comment by eklem** [comment]
@AmanelX was it solved?

**Comment by eklem** [comment]
From what I can see, it's not valid JSON array or line delimited streaming JSON.
You can add an array of objects with [concurrentAdd()](https://github.com/fergiemcdowall/search-index/blob/master/docs/API.md#concurrentadd) and a line delimited streaming JSON file (a JSON object on each line) with [add()](https://github.com/fergiemcdowall/search-index/blob/master/docs/API.md#add)

**Comment by AmanelX** [comment]
@eklem I use a Readable stream in Object mode. And the actual problem was the JSON is the wrong one. 
```
db.ref('/ethiopia/links/')
```
was to be replaced by 
```
db.ref('/ethiopia/news/')
```
which returned the example json i provided. and then i loop through that and push objects to the stream before finally closing it and pipelining it to search-index.

**Comment by AmanelX** [comment]
@eklem Thanks for the help!

**Comment by AmanelX** [comment]
@eklem https://github.com/eklem/search-index-norch-cookbook 
What portion of the cookbook isnt compatible with the latest search-index? Do you have any other cookbook-like material for search-index?

**Comment by eklem** [comment]
Looking at it now, it seems a lot is still valid, it's just not that cookbook-like.

Stuff that has changed fundamentally: How you add content (streaming), how you do queries, how you can filter on categories and buckets, that you get a stream of objects back, and that you have to query many functions and get many result-sets back.

Give me a prioritised list of what you want in the cookbook, and I'll start at the top =)
