### ISSUE TITLE
Access denied while access from application

### ISSUE THREAD

**Issue by AnnamrajuSarvani** [fergiemcdowall/search-index#418]
Hi,
I have used search index in my project with nw js. Build is running fine with nw. Now when I install my app in another machine and I am not able to access the database. It says access denied.
IO error: LockFile db\appData\cases\bench_type_index/LOCK: Access is denied.
name:OpenError"

I guess after installing my app in C: drive the issue is coming. How to fix this issue?

**Comment by fergiemcdowall** [comment]
Leveldb and search-index can both only be accessed by one process at once. If you want to access a search index with multiple processes check out https://github.com/fergiemcdowall/norch
