### ISSUE TITLE
replace bunyan with another logger library to prevent dtrace-provider issue

### ISSUE THREAD

**Issue by GiladShoham** [fergiemcdowall/search-index#420]
Hi,

Bunyan is depended upon dtrace-provider which is a library needs to be compiled against the same node version.
Otherwise, you will get an error as described here #370 
If you use search-index directly on dev machine it's very easy to remove the node_modules and reinstall them.
But usually, you ship this library as part of another product (after bundling), some time to non-technical users which you can't ask for re-run npm install.
I think it will be quite easy to replace Bunyan with another logging library such as [winston](https://github.com/winstonjs/winston) since the usage of Bunyan here is very simple.

This will solve the problem completely.

What do you think?

**Update**: just saw #410 issue, which is a similar solution but for other reasons.
do you want me to close this issue and comment over there?

Thanks.

**Comment by fergiemcdowall** [comment]
I think that `search-index` probably doesn't need logging- at this point I would be happy to remove `bunyan` altogether since I don't think its benefits outweigh its drawbacks.

If I remember rightly `winston` doesnt work in the browser, although that might have changed now.

I think the best solution would be to simply have a verbose/silent switch which would direct all info/log/trace messages to `console.log`. Errors could be directed to `console.err`.

**Comment by GiladShoham** [comment]
Thanks for your quick reply.
Are you planning to implement this soon? or do you want me to do it?
Also, I didn't see any place you actually writing anything into the log, am I missing something?

**Comment by fergiemcdowall** [comment]
By all means please feel free to do it (Its quite possible that logging has already been largely removed)

**Comment by GiladShoham** [comment]
@fergiemcdowall 
I have started to implement this, but I want to discuss some things before going on.
you can take a look on this [commit](https://github.com/teambit/search-index/commit/326e5aa5119c814308567fd57e6fc34e9131470b)

1. I saw there are some places where you call the log function from the inner lib to the outer one.
going with my direction will make it impossible. an example here:
[Line 35](https://github.com/teambit/search-index-adder/blob/master/lib/add.js#L35
)
2. currently in the tests I determine the verbose value by the node_env (make it true if it's not production) are you ok with this?

3. I set the default value of the verbose to false, do you think it should be false or true?

4. I didn't removed it from the package-lock.json because we need first to remove it from [search-index-adder](https://github.com/fergiemcdowall/search-index-adder) and [search-index-searcher](https://github.com/fergiemcdowall/search-index-searcher)
I started to do it but run into the problem described here under number 1.

I'm thinking about going with another approach -
create a logger class with methods:
trace, debug, info, warn, error
this class will get the level during the new process, and will just check the log and run console.log / err accordingly.
This will make all the API and options as it is now, and will only change the inner implementation to use very simple one. 
What do you think?

**Comment by fergiemcdowall** [comment]
1. I quite like your direction so far- its definitely an improvement over the bunyan stuff. Surely you can just pass the `verbose` flag to `search-index-searcher` and `search-index-adder`? Or am I missing something?

2. yes

3. I would vote for `false` by default

4. ok

Yes, I think that is a good idea :)

**Comment by GiladShoham** [comment]
Thanks for the feedback.
Regarding:
1. I can pass the verbose to the `search-index-searcher` and `search-index-adder` but the problem is that in line 35 above, the `search-index-adder` is calling to the log function of `search-index`. since this is no longer a function, I would have to remove it (and only log it via the `search-index-adder`)

I think we should decide about using either the verbose flag (then we should decide about the above issue). 
Or going with the simple implementation of the leveling, then not use the verbose flag, but logLevel as now.

Which one do you prefer?

**Comment by fergiemcdowall** [comment]
I prefer the 'log level' approach

**Comment by GiladShoham** [comment]
ok, no problem, I'll go with this approach.
Actually, i found 2 very lightweight modules (both has no dependencies), which is very similar to what I planned to implement (so I don't want to reinvent the wheel).
So I'm thinking of just integrate one of them.
[js-logging](https://www.npmjs.com/package/js-logging)
[js-logger](https://www.npmjs.com/package/js-logger)
The first one has more options but I think it will work only for node v6 or above (maybe it will work also for lower version, but I think they didn't test it).
With the second one, i think there will no constraints.
which one do you want me to use?

**Comment by fergiemcdowall** [comment]
So cool that you are fixing this! They both look like good libs- I would go with js-logger since it is newer and has more downloads

**Comment by GiladShoham** [comment]
sure:)
ok, I'll try to do it tomorrow, but if I won't make it, I won't be available until Sunday so it might be only next week.

**Comment by fergiemcdowall** [comment]
👍👍

**Comment by GiladShoham** [comment]
Done,
PRs are ready:
https://github.com/fergiemcdowall/search-index-searcher/pull/10
https://github.com/fergiemcdowall/search-index-adder/pull/13
https://github.com/fergiemcdowall/search-index/pull/422

Few notes:
1. we will have to recommit the package-lock.json after publishing a new version of each library (so the bunyan won't be there. currently because searcher dependent on adder and adder in the current npm version still use bunyan, it's still there)

2. I changed the 
`const logLevel = process.env.NODE_ENV || 'error'`
to 
`const logLevel = process.env.LOG_LEVEL || 'error'`
since the NODE_ENV when set will be usually production which is not a valid logLevel.

3. If you can publish a new release for all the modules soon, it will be great for me, since i really need this. 

4. I'll be available for few more hours today and maybe few hours on Friday, than only on Sunday, so feel free to ask any question regarding those changes.

Thanks a lot.

**Comment by fergiemcdowall** [comment]
Nice fix- this is something that a lot of people have wanted for a long time!

Your improvements should now be published and available in search-index@0.14.0

**Comment by GiladShoham** [comment]
Thanks @fergiemcdowall !!!
(I just found out that maybe it won't really solve my problem because leveldb itself is an npm module which require build). so the same error might come up again because of this.

**Comment by fergiemcdowall** [comment]
To avoid the build for `level` you can try to change out the "leveldown" datastore to something that doesnt require compilation.

See https://github.com/fergiemcdowall/search-index/blob/master/test/node/mocha-tests/sqlite-test.js

If you are running `search-index` in the browser you can use `level-js` for example

**Comment by GiladShoham** [comment]
I'll check this out.
I'm using it on node environment (not in the browser).
Do you have any recommendation for other datastore?

**Comment by fergiemcdowall** [comment]
It totally depends on your situation- the complete list is here: https://github.com/Level/awesome/#stores

**Comment by GiladShoham** [comment]
@fergiemcdowall looks great, thanks.
I'll check this out.
