### ISSUE TITLE
How to search by id?

### ISSUE THREAD

**Issue by AnnamrajuSarvani** [fergiemcdowall/search-index#426]
Hi,
I am trying to search by id using .get(ids)--->ids=[]
.get returns empty results even after ids are present in index.

**Comment by fergiemcdowall** [comment]
Is `ids` an Array? Are you sure that the IDs you are looking for exist in the index?

**Comment by AnnamrajuSarvani** [comment]
Yes, ids is an array type. yes, I have in existing index. Normal search give result but with .get returns empty.

**Comment by AnnamrajuSarvani** [comment]
Does it look for id field or _id?

**Comment by fergiemcdowall** [comment]
It looks for the document saved in the index as `DOCUMENT￮<id>￮`

You can debug by looking at the contents of your index with a tool like `level-out`.

**Comment by AnnamrajuSarvani** [comment]
Can you share documention link of level-out

**Comment by fergiemcdowall** [comment]
do `level-out -h`

**Comment by AnnamrajuSarvani** [comment]
Yes, I can see the index with level-out. My question is .get looks for _id field or id field?

**Comment by fergiemcdowall** [comment]
It looks for the `id` field

(am I missing something? What is the `_id` field? Where does `_id` come from?)

**Comment by AnnamrajuSarvani** [comment]
_id is coming from pouchdb. I have done conversion from pouchdb so I was looking for the same...

**Comment by AnnamrajuSarvani** [comment]
_id is the index field in pouchdb. seems you are using id for indexes

**Comment by fergiemcdowall** [comment]
Oh, I see- yes, you would have to map `_id` to `id`

**Comment by AnnamrajuSarvani** [comment]
Yea, got it. Thanks :)
