### ISSUE TITLE
search with number doesn't work

### ISSUE THREAD

**Issue by AnnamrajuSarvani** [fergiemcdowall/search-index#427]
Hi I am having query like this but doesn't seem to work.
db.search(
[
{
AND:{
price:{gte:10, lte:15}
}
}
]
)

**Comment by fergiemcdowall** [comment]
Does quoting your strings help? "10" and "15"

**Comment by AnnamrajuSarvani** [comment]
Tried, but no.

**Comment by fergiemcdowall** [comment]
This should now work
