### ISSUE TITLE
How to identify that a local / offline index is not in sync with the server?

### ISSUE THREAD

**Issue by eklem** [fergiemcdowall/search-index#428]
If the case is that you run a combination of a search-index server (i.e. norch) and a search-index running in the browser where the browser version is updated from the server version. Two questions: 
* How to best identify that they're out of sync?
* How to best update the browser version?

**Comment by fergiemcdowall** [comment]
The simplest way would be to timestamp the last time that the index was sync'ed.

If you wanted to be even more thorough, you could also do a checksum of the index (probably not worth it though?)

**Comment by eklem** [comment]
Thanks! I was hoping to avoid to do the accounting myself with timestamps etc, but you are probably right about checksum not being worth it. At least not in every day usage. If I make a timestamp on the server, and just store the same timestamp in the browser when sync is done it will be easy to keep it synchronized. 

I think I'll first make it possible to sync manually and manually switch between searching a norch server and the in-browser index. Then I'll take a look at how to do the automatic synchronization later.

Maybe search-index could store a checksum when indexing? And then you could have an API for querying just that. And same with norch? Anyway, I'm good for now =)

**Comment by eklem** [comment]
If we would get a function like this, I think it would make it a lot easier to start making online/offline hybrid search solutions. It doesn't need to be perfect when it comes to figure out if the two indexes are identical.

What about a library that could create a checksum for all indexed documents on user defined fields. So if you choose ID and indexedAtDateAndTime you're basically home free?

**Comment by fergiemcdowall** [comment]
Yes, I agree, a low-level db sync would be really good functionality
