### ISSUE TITLE
'Like' or 'Contains' in search or match

### ISSUE THREAD

**Issue by ajcarracedo** [fergiemcdowall/search-index#432]
I have seen that in the Match option I can use an 'beginswith' but I need a 'Contains'. I think that currently you can not, what would be the best way to implement this myself?

Sorry for my English.
You are doing a great job!!

**Comment by fergiemcdowall** [comment]
Thanks! Theres currently no super easy way to do substring match.

If you feel like implementing it, the relevant file is here: https://github.com/fergiemcdowall/search-index-searcher/blob/master/lib/matcher.js.

A lot of people ask for this functionality so I would love to implement it if/when there is some free time!

**Comment by fergiemcdowall** [comment]
Matching in `search-index` is now more basic and more extendable

This is a pretty big topic, and there are a few different approaches, but basically you need to get all of the possible word tokens out of the index using `DICTIONARY()` and then write an appropriate matcher, or simply feed it into a 3rd party lib.
