### ISSUE TITLE
how to search in Chinese?

### ISSUE THREAD

**Issue by Trinyoung** [fergiemcdowall/search-index#439]

**Comment by fergiemcdowall** [comment]
Hi @Trinyoung if you index text in Chinese, then you should be able to search in Chinese. You just need to make sure that your text is properly tokenised- probably the easiest way to do this is to break your sentences into arrays before indexing.

**Comment by everlose** [comment]
> Hi @Trinyoung if you index text in Chinese, then you should be able to search in Chinese. You just need to make sure that your text is properly tokenised- probably the easiest way to do this is to break your sentences into arrays before indexing.

Are there any examples？How to  set index text ？

**Comment by everlose** [comment]
Example: you should break Chinese word into arrays

```
searchDB.PUT([
  {
    text: "This is a Tang poem 春眠不觉晓处处闻啼鸟",
    idx: [ "This", "is", "a", "Tang", "poem", "春眠", "不觉", "晓", "处处", "闻", "啼鸟" ],
    _id: "wasdfasd5c6s7Aw435768ITmX9erht"
  }
])
```

then if I want to search the Tang poem，I should break Chinese word into arrays too，see the following code

```
searchDB.QUERY('春眠').then(console.log)

// {RESULT: Array(1), RESULT_LENGTH: 1}

searchDB.QUERY(
    {
      SEARCH: ['春眠', '不觉']
    }
  ).then(console.log)

// {RESULT: Array(1), RESULT_LENGTH: 1}
```

**Comment by eklem** [comment]
Maybe this [chinese tokenizer](https://github.com/yishn/chinese-tokenizer/tree/master/tests) will do? Haven't tested it, just looked around for one at a point in time.
