### ISSUE TITLE
How to search in other languages, except English

### ISSUE THREAD

**Issue by Trinyoung** [fergiemcdowall/search-index#440]

**Comment by eklem** [comment]
Hi @Trinyoung!
I think most languages are straight forward. You add documents, and choose which stopword-language to use. But when you don't have space between the characters, you need to tokenize the text before adding it, if I'm not wrong. At least to [remove stopwords](https://github.com/fergiemcdowall/stopword). Or maybe you can configure a different [separator](https://github.com/fergiemcdowall/search-index/blob/master/docs/API.md#separator) for when searching? @fergiemcdowall, can you help here?

**Comment by eklem** [comment]
Also, you don't have to remove stopwords, it justs makes your index smaller, and give you less uninteresting results. ButI don't know if you need to tokenize the text to use the matcher and search functionality.

**Comment by fergiemcdowall** [comment]
@eklem 👍
