### ISSUE TITLE
Is there a way to know which field returned a positive match?

### ISSUE THREAD

**Issue by gueneler** [fergiemcdowall/search-index#443]
Hi,

I would be interested in knowing which field made the positive match when performing the autosuggest functionnality, in order to eventually filter out some of them.

To take back your example in [the autosuggest doc](https://github.com/fergiemcdowall/search-index/blob/master/docs/autosuggest.md), we would ideally obtain a result like this:
```
['london', [['1', 'fieldX'], ['3', 'fieldY']],
 ['long beach', [['1', 'fieldY'], ['5', 'fieldZ']],
...
```

Another way to easily work around that would be the possibilty to do something like this in the `field` options:
```
var options = {
  beginsWith: "lon",
  field: "*" but 'fieldY',
  threshold: 2,
  type: 'count'
}
```

It may already be doable, but I didn't find it!

Anyway, thanks for your answer and for your awesome work on this project.

**Comment by fergiemcdowall** [comment]
Hey @gueneler thats a good question. I can't think of a good 1-step way to do that out of the box. But there are several ways to do it by using two steps- you could wire the matcher up to `.get` for example.

That said- I think that this would be a great improvement. There should probably also be a possibility to specify `type: document` in the matcher, to return the entire document

**Comment by eklem** [comment]
Would this be easier achieved with the new version of search-index, @fergiemcdowall ?

**Comment by fergiemcdowall** [comment]
If you have squashed named fields into one composite field during indexing, then you will never be able to unsquash them afterwards (although you can do some fancy logic to get all of the indexed fieldnames, and then iterate through them)

The new version takes a less opinionated view of how to do matching. You would basically do ´index.DISTINCT('<startswith>')´ and then process it as you want.

**Comment by fergiemcdowall** [comment]
The new API makes positive matches much more explicit.
