### ISSUE TITLE
TypeError: mySearchIndex is undefined

### ISSUE THREAD

**Issue by eklem** [fergiemcdowall/search-index#445]
Firefox Quantum
59.0.2 (64-bit)

![skjermbilde 2018-05-01 kl 20 57 03](https://user-images.githubusercontent.com/236656/39488374-57694888-4d82-11e8-894c-5aa724edfe07.png)

Seems Firefox Quantum isn't so happy about the way things are defined.

**Comment by eklem** [comment]
I'll [look into it](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Unexpected_type?utm_source=mozilla&utm_medium=firefox-console-errors&utm_campaign=default) myself a bit, maybe I'll figure it out.

**Comment by eklem** [comment]
Will it work to do the following:

```javascript
var mySearchIndex = {}
```

**Comment by fergiemcdowall** [comment]
OK- cool- will roll out a fix

F

**Comment by eklem** [comment]
I'll test at home too. Can't seem to reproduce the bug on the computer I'm on now...

**Comment by eklem** [comment]
A-oops. My mistake. I had set it to "Always private browsing", thus not storing anything. Un-checking, restarting and it works =)

![skjermbilde 2018-05-02 kl 19 27 05](https://user-images.githubusercontent.com/236656/39539097-10b01648-4e3f-11e8-8de2-412a67fbd8ca.png)

**Comment by fergiemcdowall** [comment]
Aha- good to know!!
