### ISSUE TITLE
[request for comment] move to promises-based API?

### ISSUE THREAD

**Issue by fergiemcdowall** [fergiemcdowall/search-index#446]
Aloha search-indexers!

Today search-index is based on callbacks and streams. This was a decision that was made a few years ago when it looked like streams were "the future".

However I feel like streams often "get in the way" of making this lib fun and useful. 

I propose that we move towards promises.

### Streams:

Streams have never quite made it into the mainstream (pun sort of intended), and the main disadvantage of them is that they are not natively supported by javascript. Therefore search-index cannot easily be used in a browser, or other non-Node environment. Also, they are pretty fearsome for beginners. I think we should have a goal to make search-index as beginner-friendly as possible. Although in theory there is a performance benefit to streams, I am not sure if it is real, and in any is probably less significant than the effect of sharding and replication (meaning that its better to spread the workload amongst 10 slightly less performant instances, rather than trying to wring every last bit of performance out of one instance)

### Promises vs callbacks

Callbacks beat promises because they can report "progress". Promises beat callbacks because of Promise.all(). I think novices find promises less intimidating because code can be written without getting their head around "functions as variables".

### Proposal

Streams should be removed from the next version of the API. I propose that all operations use promises, with the option of using a progress-tracking callback for read operations.

**Comment by eklem** [comment]
If you still can keep the performance at a decent level, I'm all for it. I'm not so good at programming, and have had some issues with streams.

**Comment by fergiemcdowall** [comment]
@eklem glad to hear it! And I think you are pretty OK at programming! ;)

**Comment by eklem** [comment]
But there was a huge speed increase and memory decrease when swapping to a streamy API, wasn't it?

**Comment by fergiemcdowall** [comment]
The memory/speed problems were only on the indexing side. Although that got better when we implemented streams, I think the speedups mainly came from improvements in other areas. Under the hood you have to do indexing in "batches" anyway because of the nature of tf-idf, so I think it would work just as well with promises

**Comment by eklem** [comment]
Cool! As long as small devices still can index a lot of documents I'm happy. Try to keep most of the high end stuff and get better at entry level usability.

**Comment by eklem** [comment]
I like the idea better and better. And keeping usability for high volume stuff can be done with an additional streamy indexer module.

When can we have this? =)

**Comment by fergiemcdowall** [comment]
Working on it now :)

**Comment by charandas** [comment]
Did this get somewhere @fergiemcdowall? Really excited about using this project in one of my customer's webapps. Promises do come easier to me as well.

**Comment by fergiemcdowall** [comment]
@charandas I'm using loads of time on work at the moment, so the open source stuff is not getting the love that it deserves

That said- I'm well into a ground up rewrite of search-index and it does indeed use promises.

**Comment by charandas** [comment]
I will start with the current implementation, and switch it out some other day with the newer promise-based one. Thanks!

**Comment by eklem** [comment]
Shout out if you need some help, @charandas

**Comment by fergiemcdowall** [comment]
Promises API now out
