### ISSUE TITLE
Upgrading level

### ISSUE THREAD

**Issue by darobin** [fergiemcdowall/search-index#447]
Are there any plans to upgrade to a more recent version of the level* ecosystem? On Node v10 the old leveldown no longer build. I tried to take a stab at it, but it's transitively everywhere (and working with browsers might prove hard).

**Comment by jruchaud** [comment]
Hello

We have the same issue. You can try to run yarn in my case with `yarn install --ignore-optional` and install your version of level.

Regards

**Comment by fergiemcdowall** [comment]
@darobin @jruchaud thanks for the feedback. Will update the deps asap.

**Comment by eklem** [comment]
I'll have a look.

**Comment by eklem** [comment]
Sorry, this wasn't straight forward for me. Any PR on this?

**Comment by fergiemcdowall** [comment]
Now running on level@5
