### ISSUE TITLE
[Queries] OR inside AND

### ISSUE THREAD

**Issue by gueneler** [fergiemcdowall/search-index#448]
Hi,

I would like to apply filters-like requests on the indexes and I encountered the following problem. Let's take an example, the user wants to apply the following filters on a index:

```
"type": "paper" OR "plastic"
AND
"city": "Aix" OR "Marseille"
```
So we would like an AND operator between two blocks where an OR operator separates each elements of the blocks.

However, and if I read the doc well, the current queries are built in the opposite way, OR operators separating blocks where each elements are linked via AND.

So for this request, I have for now two possibilities, which seem equally inefficient.

**1) Compute every permutations.**

My query would be:
```
q.query = [
	{
		AND: {
			'type': ['paper'],
			'city': ['Aix']
			}
	},
	{
		AND: {
			'type': ['paper'],
			'city': ['Marseille']
			}
	},
	{
		AND: {
			'type': ['plastic'],
			'city': ['Aix']
			}
	},
	{
		AND: {
			'type': ['plastic'],
			'city': ['Marseille']
			}
	}
];
```
This would be OKish for this very limited example, but filters will be much larger in real cases. Can be more values and/or more filters, which would make such queries a pain as the number of possible permutations would be much higher.

**2) Separate each queries and fetch common results**

```
qONE.query = [
	{
		AND: {
			'type': ['paper'],
			}
	},
	{
		AND: {
			'type': ['plastic'],
			}
	}
];

qTWO.query = [
	{
		AND: {
			'city': ['Aix'],
			}
	},
	{
		AND: {
			'city': ['Marseille'],
			}
	}
];
```
We compute the two queries and get the docs Ids on results. Then, the final results of our request would be the docs present in both queries' results array.

The efficiency is here impacted by the number of operations needed to be made: it is now one query per filter block + one final query to get documents from the array of Ids we got that way.

**Possible solution?**

I was really hopeful when I saw that query format:
```
q.query = {
  AND: {'*': ['usa', 'reagan']}
}
```
Before seeing that each array elem are separated by an AND. Would there be a way to change that in the code somewhere? So that each elem of such arrays are separated by an OR?

So my query could be something like that, and it would be perfect for me:
```
q.query = [
	{
		AND: {
			'type': ['paper', 'plastic'],
			'city': ['Aix', 'Marseille']
			}
	}
];
```

So anyway, what are your thoughts on this problem? Is there a way to do such queries right now that I missed? Is there something I could change in the code to make it work the way I want?

Thank you for your answer.

**Comment by fergiemcdowall** [comment]
Hi @gueneler ! Sorry for the unforgivably late reply. Infinitely nesten AND/OR/NOT statements are a feature of the next (1.0.0) release of search-index

**Comment by fergiemcdowall** [comment]
Now out @gueneler
