### ISSUE TITLE
TypeError: Cannot read property 'filter' of undefined

### ISSUE THREAD

**Issue by Kushmajum801435** [fergiemcdowall/search-index#450]
Hi,
I am new to this Angular framework and i am trying to create a cascading dropdwon list of country, state and cities which will be fetched from the database.
Below is my code for component.ts and component.html:

import { Component } from '@angular/core';
import { DonorRegistrationService } from "../../services/donorregistration.service";
import { StatesService } from "../../services/states.service";
import { DistrictService } from "../../services/district.service";
import { CitiesService } from "../../services/cities.service";
import { filter } from "rxjs/operators";

import { HttpErrorResponse } from "@angular/common/http";

@Component({
  selector: "app-donorregistration",
  templateUrl: "./donorregistration.component.html"
})

export class DonorregistrationComponent{

  private result_country:any;
  private result_state:any;
  private result_city:any;
  private result:any;
  private selectedCountry = 0;
  private selectedState = 0;
  private states = [];
  private cities = [];
 
  constructor(private _service:DonorRegistrationService, private _stateService: StatesService, private _distService: DistrictService, private _citiesService: CitiesService) { }

  public onSelectCountry(country_id: number):any {
    this.selectedCountry = country_id;
    this.selectedState = 0;
    this.cities = [];
    this.states = this.getStates().filter((item) => {
      return item.state_id === Number(country_id)
    });
  }
 
  public onSelectState(state_id: number) {
    this.selectedState = state_id;
    this.cities = this.getCity().filter((item) => {
      return item.city_id === Number(state_id)
    });
  }
 
  ngOnInit(){
    this._stateService.getStates().subscribe(res=>{
      this.result_country=res;
    }, (err:HttpErrorResponse)=>{
      if(err.error instanceof Error){
        console.log("Client side error!");
      }
      else{
        console.log("server side error!");
      }
    });

    return this.result_country;
  }
 
  public getStates():any {
    this._distService.getDistrict().subscribe(res=>{
      this.result_state=res;
    }, (err:HttpErrorResponse)=>{
      if(err.error instanceof Error){
        console.log("Client side error!");
      }
      else{
        console.log("server side error!");
      }
    });

    return this.result_state;
  }
 
  public getCity():any {
    this._citiesService.getCities().subscribe(res=>{
      this.result=res;
    }, (err:HttpErrorResponse)=>{
      if(err.error instanceof Error){
        console.log("Client side error!");
      }
      else{
        console.log("server side error!");
      }
    });

    return this.result;
  }

    public register(obj:any):any{
      this._service.registerDonor(obj).subscribe(res=>{
        this.result=res;
      }, (err:HttpErrorResponse)=>{
        if(err.error instanceof Error){
          console.log("Client side error!");
        }
        else{
          console.log("server side error!");
        }
      });
    }
}

component.html:
<!doctype html><html lang="en">
  <body>
<input type="number" [(ngModel)]="pid"><br><br>
<input type="text" [(ngModel)]="pname"><br><br>
<input type="number" [(ngModel)]="pcost"><br><br>
<div class="form-group">
  <label class="control-label" for="Country">Country:</label>
  <select *ngIf="result_country" [(ngModel)]="selectedCountry" (change)="onSelectCountry($event.target.value)" class="form-control input-lg" id="country">
     <option value="0">Select Country</option>
    <option *ngFor="let country of result_country" value= {{country.id}}>{{country.name}}</option>
  </select>
</div>

<div class="form-group">
  <label class="control-label" for="States">States:</label>
  <select *ngIf="states" [(ngModel)]="selectedState" (change)="onSelectState($event.target.value)" class="form-control input-lg" id="state">
      <option value="0">Select State</option>
    <option *ngFor="let state of states" value= {{state.id}}>{{state.name}}</option>
  </select>
</div>

<div class="form-group">
  <label class="control-label" for="City">City:</label>
  <select class="form-control input-lg" id="city">
      <option *ngIf="!selectedState" value="0">Select City</option>
      <option *ngFor="let city of cities" value= {{city.id}}>{{city.name}}</option>
  </select>
</div>
</body>
</html>

i'm getting "Cannot read property 'filter' of undefined" in console. Please suggest

**Comment by Kushmajum801435** [comment]
[html component.txt](https://github.com/fergiemcdowall/search-index/files/2336584/html.component.txt)
the component.html is attached

**Comment by eklem** [comment]
Hi @Kushmajum801435,
Are you commenting in the right library?

**Comment by eklem** [comment]
We used to have (it's outdated) an [Angular-app](https://github.com/fergiemcdowall/norch-angular-app) that ran on top of the Norch server (which is a server side search engine using search-index library).

**Comment by Kushmajum801435** [comment]
@eklem I'm actually really new in Angular. Can you please elaborate!

**Comment by eklem** [comment]
The reason I asked if you were commenting in the right library is that [search-index](https://github.com/fergiemcdowall/search-index/) doesn't have anything to do with Angular, and it seemed you were asking questions about Angular. Search-index is a search engine library written in JavaScript. It can be combined with Angular, which is a framework for creating web applications, but it's a while since @fergiemcdowall had a working example through the [norch-angular-app](https://github.com/fergiemcdowall/norch-angular-app).

**Comment by eklem** [comment]
I close this, since it doesn't seem to be about search-index. Feel free to open it again and elaborate =)
