### ISSUE TITLE
concurrentAdd callback won't return

### ISSUE THREAD

**Issue by charandas** [fergiemcdowall/search-index#453]
@eklem Thanks for the encouragement on the other thread. Yes, I do need your help!

I am trying to use `search-index` in the browser (Chrome). Do you happen to know why `concurrentAdd`'s callback would never return. I am trying to add about 5k items in 1 swoop.

```
this.index.concurrentAdd(this.options, batch, (err) => {
            if (!err) {
              console.log('indexing done')
            } else {
              console.log('error is', err)
            }
          })
```
Lastly, when I search without arguments, I get exactly 20 items, when I check in devtools `Application => IndexedDB` tab, I see all 5k items in there in the index.
```
this.index.search().on('data', function (item) {
        console.log(item)
      }).on('end', function () {
        console.log('search ended') // does print
      })
```

If there is a way to enable some verbose logs, that would surely be helpful.

**Comment by eklem** [comment]
How concurrentAdd works I'm not able to say much about. But only getting 20 items back... Do you have some default options set to 20 results. It's [pageSIze](https://github.com/fergiemcdowall/search-index/blob/master/docs/API.md#search) that controls this. Also, could you check [totalHits](https://github.com/fergiemcdowall/search-index/blob/master/docs/API.md#totalhits) for the same query?

**Comment by eklem** [comment]
I think logging was taken out because what was used didn't work in the browser.

**Comment by eklem** [comment]
Actually, looks like there may be something in there: https://github.com/fergiemcdowall/search-index/issues/420

**Comment by charandas** [comment]
@eklem that helped. I was able to find out what was happening by enabling debug logs.

It was just super slow, which I am now beginning to find is expected in the browser. Enabling `appendOnly` seemed to have made a big difference, and I get it indexed in 20seconds.

The thing I am not sure about now is when I reload the page (lets say, I comment out my `concurrentAdd`, I can confirm IndexedDB has the generated index from last time): why would `totalHits` API return 0. I am pretty sure, I am using a correct query.

Is there something I am missing as to how sync works when index already exists in the browser.

For example, all 5k items have a `body` prop of `demobank`, and yet the following query does not return anything:
<img width="1012" alt="screen shot 2018-10-22 at 5 02 15 pm" src="https://user-images.githubusercontent.com/542168/47319449-b4782080-d61c-11e8-9859-f1ce96e9fd16.png">

```
this.index.totalHits({
        query: [{
          AND: {
            '*': ['demobank']
          }
        }]
      }
```

Also, the `search()` without an argument also does not return anything in this reload page scenario. Which is telling me, it isn't really about the query on `totalHits`.

I have tried both using `si()` constructor with the same `indexPath` as used during seeding, as well as initializing the correct levelup db, and specifying in `indexes`, but no go.

```
levelup('search_data', {
      valueEncoding: 'json',
      db: leveljs
    }, (err, db) => {
      if (err) {
        return console.error(err)
      }
      si({
        'indexes': db,
        'appendOnly': true,
        'batchsize': 10000,
        'logLevel': 'debug',
        'wildcard': false,
        'compositeField': true
      }, this.indexData)
```

Thoughts?

**Comment by eklem** [comment]
Hmm, do you get any results on any queries? Also, demobank is a key, isn't it? I don't think that will give any results back.

I've experienced myself that getting the first query to work takes some tries before I get it right. If you give me a small reproducible example (gist or something), I'll have a look.

**Comment by charandas** [comment]
@eklem I was able to get results once I understood the confusion created by the prefix that various levelup versions apply to db in IndexedDB. More recent `level-js` versions for example apply `level-js-`, while older versions applied `IDBWrapper-`. I had both instances in my store, and I was dialing into the wrong one.

One thing to note, is if I use `indexes` to supply a `leveldb` instance, using `levelup` latest version `3.1.1`, my browser window just crashes. I see the Chrome Helper on my mac's activity monitor get near 2Gi in memory use, and that's when it crashes. My guess would be that, a user won't run into this problem if they just use `indexedPath` as the browser dist is shipped with compatible level deps.

Perhaps, I should not be using such newer leveldb versions, and will weigh my options more carefully.

**Comment by eklem** [comment]
Nice! Good to hear tou got it working.
