### ISSUE TITLE
A simple TypeScript example?

### ISSUE THREAD

**Issue by chillwinston** [fergiemcdowall/search-index#454]
Hi - I'm trying to use search-index in a TypeScript project, and have found the .d.ts file for the definitions.  I've also included the line:

import { SearchIndex } from "search-index"
declare const SearchIndex: SearchIndexConstructor

The code all compiles.  All is theoretically well with the world.  When it runs however, SearchIndex is null.  I'm relatively new to TypeScript and the debugger in my project isn't permitting me to easily understand why the above isn't working.

Are you able to provide source code that is a very simple TypeScript app please?  I'm happy to contribute some of learning-style TS code once I get to that point in exchange.   As TypeScript grows in popularity over raw JS it'l be more important to have these bindings more clearly expressed

Thank you

**Comment by eklem** [comment]
We got the TypeScript definition [file handed to us in a PR](https://github.com/fergiemcdowall/search-index/pull/430) by @gburgett, so we don't have much more than that, sorry. If you get something going, I'm more than happy to include something.

**Comment by eklem** [comment]
@gburgett Do you have time to give some pointers to @chillwinston, and I'll include the simple example we come up with?

**Comment by gburgett** [comment]
Hi @chillwinston !  Are you trying to load this in a browser context?  Or are you trying to run this on nodejs?

If you are trying to run it in nodejs, you should require it like this:

```ts
const ctor = require('search-index') as SearchIndexConstructor
```

If you are trying to use it in a browser context, then unfortunately you cannot simply `require` it.  The browser version is not packaged as a module, it is provided as a separate minified file.  You must include that script on your page [according to the instructions here](https://github.com/fergiemcdowall/search-index/blob/master/docs/browser.md).

The line `declare const SearchIndex: SearchIndexConstructor` only tells TypeScript that `SearchIndex` is a thing that exists in the global context.  It is the job of the minified library file to create that constructor object.

**Comment by gburgett** [comment]
Right, in a web browser context you *cannot use the require line*.  That will require the nodejs version of the module, which depends on leveldown, which does not work in the browser.

The maintainer has created a separate minified javascript file that you must include on your page instead of requiring the library.  Please see the documentation that I linked above.

**Comment by eklem** [comment]
Closing this for now, but feel free to open it again, @chillwinston , if you have a go at it again.
