### ISSUE TITLE
how to get the positions of the term matches

### ISSUE THREAD

**Issue by trish123** [fergiemcdowall/search-index#455]
Is there a way to enable the positions of term matches like lunr.  I would like to use the data for highlighting

**Comment by fergiemcdowall** [comment]
The current version of `search-index` doesn't support positional matching. The upcoming version hopefully will :)

**Comment by trish123** [comment]
Thanks for the update

**Comment by 4R53N** [comment]
@fergiemcdowall any updates on this?

**Comment by fergiemcdowall** [comment]
You could possibly do some magic when indexing. What is your use case?

**Comment by eklem** [comment]
You could add highlighting after you get the search result back. I've made a library for that, but it may not fit your use case?
[hit-highlighter](https://eklem.github.io/hit-highlighter/demo/)
