### ISSUE TITLE
[Announcement] Breaking changes coming!

### ISSUE THREAD

**Issue by fergiemcdowall** [fergiemcdowall/search-index#456]
Hello search-indexers!

A new version of search-index that has an API based on Promises will shortly be released. This version will be faster and easier to use but unfortunately it will be completely incompatible with the current 0.15.x versions.

Feedback welcome!

F

**Comment by fergiemcdowall** [comment]
Yes, the documentation (as always) could be improved. It would be great to have some kind of interactive demo up as well

**Comment by eklem** [comment]
I'll try to make something interactive. The documentation is one thing, but now we have something that is _actually_ simple, then it's less job to make low threshold examples and interactive stuff.

**Comment by eklem** [comment]
And we've gotten a long way if one or more CDN-versions are the ones that are used the most.

**Comment by eklem** [comment]
I'll do some documentation when I get going with the new version (browserified / webpack'ed).

**Comment by fergiemcdowall** [comment]
Changes have dropped
