### ISSUE TITLE
Documenting new version (v1.0.1)

### ISSUE THREAD

**Issue by eklem** [fergiemcdowall/search-index#458]
Start filling in the gaps

* [ ] Mini-example for webpack
* [ ] n-grams
* [ ] Document processing using Promise chains
* [ ] Example of using stopwords
* [x] Autosuggest / autocomplete strategies
* [x] Browser demo
* [x] Browser-based sample app
...

**Comment by fergiemcdowall** [comment]
Having thought about it, I feel like this is actually a potential article?

**Comment by eklem** [comment]
How do you mean? Describing all the things you can do and how? I would love that! https://medium.com/norch ?

**Comment by eklem** [comment]
Yes, @fergiemcdowall . Having looked at it, seeing that the "pieces" are more low level, I think it would be good with an article/explanation on how things are meant to be combined.

**Comment by eklem** [comment]
Think I will change the docs a little. Wasn't super happy with how the division between API and examples came out. I think the API-part should contain:
* what each part does
* what it returns
* some simple examples

... and the example part can be changed into how to use the different API's together for meeting user needs, like auto-complete, pagination, filtering etc.

**Comment by fergiemcdowall** [comment]
I guess we should close this issue since we are now on to `v2.0.0` 🙂
