### ISSUE TITLE
Minimal browser example

### ISSUE THREAD

**Issue by eklem** [fergiemcdowall/search-index#460]
Index and search data. No framework, only plain javascript.

**Comment by fergiemcdowall** [comment]
:+1:

**Comment by eklem** [comment]
I'll try, and ask for help if I need it. That way I learn it better =)

**Comment by eklem** [comment]
Check what that can be reused from [earlier example](https://github.com/fergiemcdowall/search-index/commit/4b1f53dba01e5a4f505ea2c9013216bf3c121fef)

**Comment by fergiemcdowall** [comment]
The docs should now explain how to use search-index from a <script> tag- are they clear enough?

**Comment by eklem** [comment]
Yes! I'll just need to pull in your latest to my fork and also generate ID's, then we'll have the browser example. You can test it at https://eklem.github.io/search-index/demo/ First document you index won't work.

**Comment by eklem** [comment]
Got it working

**Comment by fergiemcdowall** [comment]
🎉🎉🎉🎉🎉👍

**Comment by eklem** [comment]
The demo is still the old one, because I don't have access to settings for the repo. Think you just have to turn GitHub pages off and on again I think, then this will work: http://fergiemcdowall.github.io/search-index/demo/

**Comment by eklem** [comment]
Here's how it should look and workhttps://eklem.github.io/search-index/demo/

**Comment by fergiemcdowall** [comment]
Yes, there seems to be something up with the page generation at http://fergiemcdowall.github.io/search-index/ - will investigate...

Demo looks great btw!

**Comment by eklem** [comment]
Thanks, thought that putting a little effort into CSS was okay as long as the HTML is minimal and the JavaScript only about search.

**Comment by eklem** [comment]
I'll blog about the new version when you get the page generation for 
http://fergiemcdowall.github.io/search-index/ working.

**Comment by eklem** [comment]
@fergiemcdowall I think maybe if you change from the `/docs`-folder to just `master branch`, then it will work?

<img width="781" alt="screenshot 2019-03-01 at 14 35 56" src="https://user-images.githubusercontent.com/236656/53641517-8a201a80-3c2f-11e9-8b5f-f99ad61b0487.png">
