### ISSUE TITLE
Autocomplete / Auto-suggest / Prefix-Matching

### ISSUE THREAD

**Issue by gtsoukas** [fergiemcdowall/search-index#462]
Could you give an example of how to implement autocomplete with the current API, e.g. returning all words starting with a given prefix?

**Comment by fergiemcdowall** [comment]
Hi @gtsoukas 

For that you would use `DICTIONARY` (there was a little bug here that has just been fixed in 1.0.3). This can give you all tokens in the index, or tokens that are greater than and/or less than a given value.

```javascript

// get all tokens in the index
idx.DICTIONARY().then( /* array of tokens */ )

// get all tokens in the body.text field
idx.DICTIONARY('body.text').then( /* array of tokens */ )

// get tokens in the body.text field that starts with 'cool'
idx.DICTIONARY('body.text.cool').then( /* array of tokens */ )

// you can also use gte/lte ("greater/less than or equal")
idx.DICTIONARY({
  gte: 'body.text.a',
  lte: 'body.text.g'
}).then( /* array of tokens */ )

```

If you want to do fancy stuff with levenstein distance, or other forms of fuzzy matching, then you can use `DICTIONARY` to export tokens into a third party lib of your choice.

**Comment by eklem** [comment]
I'll test and add to the documentation.

**Comment by gtsoukas** [comment]
Thanks a lot for the quick fix and the hint on fuzzy matching! Works perfect now.

**Comment by fergiemcdowall** [comment]
:+1:

**Comment by KonradLinkowski** [comment]
@gtsoukas how did you implement fuzzy matching?

**Comment by eklem** [comment]
Hi @KonradLinkowski,
Not sure how @gtsoiukas solved it, but you can use the `idx.DICTIONARY` to get all tokens and then use i.e. [leven-match](https://github.com/eklem/leven-match) to expand your search query if words from the dictionary is within a given Levenshtein distance to your query words.

You could do the dictionary lookup every time you start your server, or every time you have indexed new documents and store it in memory. If you're running it in the browser, then each time you load the page?

If you're doing an OR-search, you just flatten the array returned from leven-match and use that as your query. If you want to do an AND-search, it's a bit more complicated, but still no problem. You just have to create several AND-searches and OR'ing between them.

So for this leven-match example:
```
const lvm = require('./index.js')
const index = ['return', 'all', 'word', 'matches', 'between', 'two', 'arrays', 'within', 'given', 'levenshtein', 'distance', 'intended', 'use', 'is', 'to', 'words', 'in', 'a', 'query', 'that', 'has', 'an', 'index', 'good', 'for', 'autocomplete', 'type', 'functionality,', 'and', 'some', 'cases', 'also', 'searching']
const query = ['qvery', 'words', 'levensthein']
 
lvm.levenMatch(query, index, {distance: 2})
//[ [ 'query' ], [ 'word', 'words' ], [ 'levenshtein' ] ]
```

you would have to create these AND-searches, and OR'ing between them:
```
idx.AND('query', 'word', 'levenshtein')

idx.AND('query', 'words', 'levenshtein')
```
