### ISSUE TITLE
Split documentation into one part API and one part simple code examples?

### ISSUE THREAD

**Issue by eklem** [fergiemcdowall/search-index#463]
@fergiemcdowall , should we split up the documentation in two (three) like before?
* Simple example on how to get something going in README.md
* one API.md
* one a bit more descriptive with JavaScript examples?

Or do you have an other suggestion for splitting it up a bit?

**Comment by fergiemcdowall** [comment]
Yes- good idea. Quickstart, API, and a few working examples would be great.

**Comment by eklem** [comment]
Need to add the search-part to a .then-step, but it's getting a little closer, check out the [demo-and-doc](https://github.com/fergiemcdowall/search-index/tree/demo-and-doc) branch.

**Comment by eklem** [comment]
https://github.com/fergiemcdowall/search-index/pull/468

**Comment by eklem** [comment]
I made it a  bit easier, since I don't have a use case for initialising, indexing and searching as three steps happening automatically in a synchronous flow. But maybe we need it to get people going?

**Comment by eklem** [comment]
I'll update the PR to get an example where you can get a result console logged =)
