### ISSUE TITLE
Case insensitive queries

### ISSUE THREAD

**Issue by eklem** [fergiemcdowall/search-index#465]
Is there an easy/proper way to define lowercase of the documents only for the index references and not the documents stored?

I'll update the documentation when I have the answer

**Comment by fergiemcdowall** [comment]
So that you can do case-insensitive queries?

Not at the moment- but I agree that this would be nice functionality to have...

**Comment by eklem** [comment]
Yes, case insensitive queries.

**Comment by eklem** [comment]
I guess a workaround would be create additional fields (key/value) with lowercase text and do the search on these fields, but show the original ones. A bit messy, but totally doable.

**Comment by fergiemcdowall** [comment]
This should work as intended in v2.0.0 by setting the `caseSensitive` option to `false`
