### ISSUE TITLE
Document how to split query into words and do an AND-search on all of them

### ISSUE THREAD

**Issue by eklem** [fergiemcdowall/search-index#466]
Split the query string into an array and do an AND query on all words in the array. Make it a function to make the example more readable.

**Comment by fergiemcdowall** [comment]
At the moment you should be able to do the following ->

```javascript
idx.SEARCH([ 'one', 'two', 'three' ])
// or
idx.SEARCH('one two three'.split(' '))
```

**Comment by eklem** [comment]
Nice! No need for a function. Good way of not having to deal with splitting into words within the search engine. Makes it more language agnostic. I like the approach for v1.x =)

**Comment by eklem** [comment]
It doesn't take arrays, just comma-separated strings:
So this works:
```javascript
idx.SEARCH(['one', 'two', 'three' )
```

but not this:
```javascript
idx.SEARCH(['one', 'two', 'three' )
```

Should an array work? Seems both more elegant and simple.

**Comment by fergiemcdowall** [comment]
Oh sorry- yes you are right- so you could use [spread syntax](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax)

```javascript
idx.SEARCH(...['one', 'two', 'three'])
```

**Comment by eklem** [comment]
That works, thanks. Still a lot to learn about JavaScript =)

**Comment by eklem** [comment]
I'll fix it later and upgrade the documentation a bit.

**Comment by eklem** [comment]
https://github.com/fergiemcdowall/search-index/commit/ebcb0cbe863fce45c54ee0f307cebbf1be6e658f
