### ISSUE TITLE
possible error when ID is generated by search-index

### ISSUE THREAD

**Issue by eklem** [fergiemcdowall/search-index#467]
Using the web script.

When you add one and one doc, you get docs with keys like this:
`DOC 0` `DOC 2` `DOC 3` `DOC 4` `DOC 5`

`DOC 1` is missing, and all word references points to 2 or higher, so you will never get `Doc 0` as a result and get results (`DOC 2`) for stuff only found in `DOC 0`.

How to reproduce: take the web demo and remove the ID generation stuff.

Not a big problem. The workaround was to generate ID's based on a hash of title string + body string.

**Comment by fergiemcdowall** [comment]
Hmmm- strange, will investigate...

**Comment by eklem** [comment]
I can set up a demo if you want.

**Comment by eklem** [comment]
Install + remove hash-generating ID's on a Digital Ocean machine + describe the steps.

**Comment by eklem** [comment]
Steps to reproduce:
```console
npm i search-index
cd search-index/demo
ln -s ../dist/search-index.1.0.3.js search-index.js
```
Last line is because the symlink doesn't appear to survive in the NPM package.


In `search-app.js`, change this:

```javascript
  if ((docTitle + docBody).length > 0) indexData({ _id: docId, title: docTitle, body: docBody })
  console.log({ _id: docId, title: docTitle, body: docBody })
```

...to this:
```javascript
  if ((docTitle + docBody).length > 0) indexData({ title: docTitle, body: docBody })
  console.log({ title: docTitle, body: docBody })
```

Go to the web page, and add title `first title`, and text `first text`.

If you look under `storage` in the inspector, the doc is stored, but the words reference doc2.

<img width="1366" alt="screenshot 2019-02-26 at 09 28 23" src="https://user-images.githubusercontent.com/236656/53398195-4fa54c00-39a9-11e9-9c53-b0b1f27cf0ba.png">

Then, add title `second title`, and text `second text` and search for `first`, and you'll get the second document added as a result
<img width="695" alt="screenshot 2019-02-26 at 09 33 16" src="https://user-images.githubusercontent.com/236656/53398334-a6ab2100-39a9-11e9-8c67-08c04bc3b0ba.png">

You can also check out http://nowsearch.xyz/

**Comment by fergiemcdowall** [comment]
OK- I'll take a look!

**Comment by MpMeetPatel** [comment]
Hi, just to tell you guys, I used uuidV4 for id generation and used _id for assignment in the search-index PUT method. All issues just related to Id just disappeared and worked fine.

**Comment by fergiemcdowall** [comment]
Great- thanks for the feedback @MpMeetPatel 👍🙂

**Comment by fergiemcdowall** [comment]
I think that this should be working now. Will take the chance and close the issue, but please reopen if this problem resurfaces

**Comment by eklem** [comment]
Yes. I'm sure I'll get to test this and other past issues too =) Let the v2 testing begin!
