### ISSUE TITLE
symlink ./dist/search-index.js doesn't survive in NPM package

### ISSUE THREAD

**Issue by eklem** [fergiemcdowall/search-index#469]
`./dist/search-index.js` is gone in the NPM package.

Not sure why. Need to read up to figure out.

To reproduce / test:
```console
npm install search-index
cd node_modules/search-index/dist/
ls -la
```

The symlink `search-index.js` is missing. It's there if you clone.

**Comment by eklem** [comment]
Sent a question to NPM, so then we'll figure out if it's possible to get it working.

**Comment by eklem** [comment]
There is hope!
[...]
If the file is in the same package, symlink would not be required, you can map the path to the file in package.json.

Tech Support
npm, Inc
[...]

**Comment by eklem** [comment]
If I don't get this to work, I'll change the demo so that it webpack the search-app and search-index.[version].js into one file in the demo-folder.

**Comment by fergiemcdowall** [comment]
Thats strange- I'll investigate...

**Comment by eklem** [comment]
I'm on it =) Can let you know if I have to throw in the towel.

**Comment by eklem** [comment]
No luck with the NPMJS support answer. I'll fix the demo-issue with linking to latest in `/dist` forlder from `demo`-folder like this: `"../dist/search-index[version].js"`. What do you suggest we do with the `search-index.js`, @fergiemcdowall? Forget about it for now, or copy from `search-index[version].js` to `search-index.js`?

**Comment by eklem** [comment]
Fixed. So far, no search-index.js copy, just leaving the symlink in, but not using it for anything. https://github.com/fergiemcdowall/search-index/commit/53a6ede2cf43530a0897bb4045300600fd5494ea
