### ISSUE TITLE
Make a browser demo w/ memdown

### ISSUE THREAD

**Issue by eklem** [fergiemcdowall/search-index#472]
Together with [documenting howto use memdown](https://github.com/fergiemcdowall/search-index/issues/464).

**Comment by fergiemcdowall** [comment]
There is a [bit about this](https://github.com/fergiemcdowall/search-index/blob/master/docs/FAQ.md#can-i-use-another-backend-like-mysql-or-redis) in the documentation and which uses `memdown` as an example and links through to a test.
