### ISSUE TITLE
JSON representation of the query language

### ISSUE THREAD

**Issue by fergiemcdowall** [fergiemcdowall/search-index#475]
In order to make passing queries around more practical (command line, http, etc)

**Comment by eklem** [comment]
Yes! =)

**Comment by eklem** [comment]
Also, it will make it easier to keep the modularity/versatility in tools built on search-index.

**Comment by eklem** [comment]
I think what made me able to start with search-index was norch and the JSON query object, so this will make it available for a lot more.

**Comment by fergiemcdowall** [comment]
The JSONification API checklist

Writing
- [ ] DELETE
- [ ] PUT

Composable querying
- [ ] AND
- [ ] DOCUMENTS
- [ ] GET
- [ ] NOT
- [ ] OR

Searching
- [ ] SEARCH

Tokenisation
- [ ] DICTIONARY

Aggregation
- [ ] BUCKET
- [ ] BUCKETFILTER
- [ ] DISTINCT

Accessing the underlying index
- [ ] INDEX

**Comment by eklem** [comment]
This means we can get an updated `norch` eventually?

**Comment by fergiemcdowall** [comment]
@eklem yes :)

**Comment by fergiemcdowall** [comment]
Implemented in `v2.0.0`
