### ISSUE TITLE
Should we do Greenkeeper or similar again?

### ISSUE THREAD

**Issue by eklem** [fergiemcdowall/search-index#479]
I know it gets a little chatty, but without we easily end up where fixing vulnerabilities and keeping up with node versions is really hard.

**Comment by fergiemcdowall** [comment]
We possibly should.

**Comment by eklem** [comment]
Nice, new profile photo =)
Think it's turned on under "Setting > Applications"

**Comment by eklem** [comment]
Actually, we can try GitHub's new automated security fixes. You can activate it under the security-tab (beta)

**Comment by fergiemcdowall** [comment]
Yes, I set it up on fergies-inverted-index a while ago and [just got a PR](https://github.com/fergiemcdowall/fergies-inverted-index/pull/9). Seems to work in a more nuanced and less overwhelming way than Greenkeeper

**Comment by fergiemcdowall** [comment]
I'm a bit unsure if "Automated security fixes" was set to "on" on `search-index` before, but in any case it is now.

**Comment by eklem** [comment]
Okay to close this now, isn't it?
