### ISSUE TITLE
Complement the .npmignore file

### ISSUE THREAD

**Issue by MrRefactoring** [fergiemcdowall/search-index#482]
At the moment, along with the package downloading a lot of extra files.

I think we should do the following `.npmignore` file:

```gitignore
src
test
.gitignore
.travis.yml

demo
docs
.babelrc
_config.yml
rollup.config.js
search-index-logo.png
webpack.config.babel.js
```

This way we can reduce the size of this package (client will not download extra files).
If you approve this change, then I can make PR

**Comment by eklem** [comment]
Sounds good to me. Can't at the moment think of any use scenario that needs the src and docs in the NPM-package, which was my only concern.

Makes the difference by cloning/forking and NPM'ing clearer.

**Comment by fergiemcdowall** [comment]
Looks good
