### ISSUE TITLE
get stopword removal for the index back 

### ISSUE THREAD

**Issue by eklem** [fergiemcdowall/search-index#486]
Be able to remove stopwords from the other index, making the stored index smaller.

In the light of how search-index is now (lots of building blocks on a lower level), I guess just the option to do this is what we should have?

**Comment by eklem** [comment]
On the query side this is just a question about setting up a little query processing and that task is cookbook stuff.

**Comment by eklem** [comment]
So, I guess what I'm asking for is the ability to define if a field is indexable or not.

**Comment by fergiemcdowall** [comment]
Yes, it would be great to be able to initialize the index with the stopwords that you want (rather than baking lots of stopwords for every language into the lib itself).

**Comment by eklem** [comment]
If fields are indexable (searchable) or not, we could do this outside search-index. Just remove stopwords an add the remaining text to fields that are searchable.

**Comment by eklem** [comment]
Just don't want stuff to be to opinionated, just make the stuff needed for a search engine feasible. Anyway =)

**Comment by fergiemcdowall** [comment]
Its back! (in `v2.0.0`) 🙂

**Comment by eklem** [comment]
Cool, and we support 54 languages now. Thinking I should make stopword-trainer run in the browser (needs to be re-written) so you can then get a custom list of stopwords before you add your content.
