### ISSUE TITLE
how to index stuff with n-grams?

### ISSUE THREAD

**Issue by eklem** [fergiemcdowall/search-index#487]
So we can make beautiful autocomplete forms. Is it possible today, with some extra code?

**Comment by fergiemcdowall** [comment]
Yes, its possible, but its no longer a part of the core lib. You would need to do a pre-processing stage.

```javascript
{
  text: ['one', 'two', 'three']  // si takes arrays or strings so this is equivalent to 'one two three'
}
```

->

```javascript
{
  text: ['one', 'two', 'three', 'one two', 'two three', 'one two three']
}
```

**Comment by eklem** [comment]
Nice! I'll test when I get a chance, and can make s recipe in the cookbook

**Comment by eklem** [comment]
This can be done with the [ngraminator](https://github.com/fergiemcdowall/ngraminator), can't it?

**Comment by eklem** [comment]
I could maybe make a document processor library that is easy to configure and depend on stuff like [stopword](https://github.com/fergiemcdowall/stopword), [ngraminator](https://github.com/fergiemcdowall/ngraminator) and [eklem-headline-parser](https://github.com/eklem/eklem-headline-parser), so you easily can get stuff like matcher with several words, stopword removal and automatic generated keywords to filter on. I'll make this for [nowsearch.xyz](https://github.com/eklem/nowsearch.xyz).
