### ISSUE TITLE
dist-files:Only CommonJS and Ecmascript modules ?

### ISSUE THREAD

**Issue by eklem** [fergiemcdowall/search-index#501]
I see there is no browser version if I'm not to use the ESM-version? Which can be a bit cumbersome to get going, needing a server to serve the files, etc. Was it on purpose, or just a mishap?

**Comment by fergiemcdowall** [comment]
Oh- thats a mishap (I think). Its definitely there in the new (2.x.x) version.

This seems to be the offending commit -> https://github.com/fergiemcdowall/search-index/commit/37b0bae67083468fec36f260c538ecf669733001#diff-2a6d07eef8b10b84129b42424ed99327

**Comment by eklem** [comment]
Cool =) It's still available through URL, so I'll close this for now =)

**Comment by eklem** [comment]
Here's the link if someone needs it:
https://fergiemcdowall.github.io/search-index/dist/search-index.1.0.6.js
