### ISSUE TITLE
make ESM version work with Svelte

### ISSUE THREAD

**Issue by eklem** [fergiemcdowall/search-index#502]
Had some issues  making it work with Svelte, seemed some node stuff was still present. Anyway, I'll ad some specific issues regarding Svelte if it's interesting, @fergiemcdowall ?

**Comment by eklem** [comment]
And why Svelte? I started looking around after Vuejs has just grown a lot, so basing something on Vuejs will make it a lot about some framework instead of search and search-index. Svelte helps with binding HTML and JavaScript together, but has a really small footprint. Cool if search-index could just be imported in the Svelte interactive shell/repl and work. https://svelte.dev/repl/hello-world

**Comment by fergiemcdowall** [comment]
havent checked out Svelt yet- will do ASAP! :)

**Comment by eklem** [comment]
I'll set up a project to try to make search-index work in a Svelte-build.

**Comment by eklem** [comment]
Seems it will work with existing. Stuff will end up here. 
https://github.com/eklem/svelte-idx-components

Just got a proof I can index, but only working in Chrome so far =)

**Comment by eklem** [comment]
Skipping this for now, only working halfway it seems. Can index, but don't get a message back when promise is resolved, and search comes back empty. So will stick with the Vue-project :-)
