### ISSUE TITLE
No results when moving away from a dataset

### ISSUE THREAD

**Issue by doriandrn** [fergiemcdowall/search-index#504]
Hello! Amazing job with the project, love it, please keep it up! I am really looking forward to v2!

I've built a plugin for RxDB using SI and whilist it's working pretty fine, I am right now encountering a strange behaviour:

I have multiple datasets / taxonomies / collections (call them whatever); I am instancing SI for each at creation time. Whenever a document gets inserted / upserted, I add / update it with PUT and if removed, I DELETE it and there are ways to index all / a custom selection of them.

My app runs the .SEARCH command on all datasets at the same time, on input; 

So far so good, if I focus on one dataset, add documents to it, and then search, it works as expected. If I move away to another dataset and do CRUD operations to it, .SEARCH works only for this and not anymore for the others. If I manually try to .SEARCH on any other dataset, getting the same, no results;

.DICTIONARY() seems to be returning the right words and work ok, while .SEARCH, .GET, .AND simply return empty results. If I go ahead and PUT a new document to the collection, and run any of the above again, it works.

Any ideas why this could be happening? Is instancing SI for every dataset the wrong approach? Should I instance it per the entire DB and then add something like `{ collection: name }` to the data fields and then filter them out based on collection?

**Comment by fergiemcdowall** [comment]
Hi @doriandrn 

Yes, what you are describing seems to be a bug. You dont by any chance have some sort of test code that recreates this error?

**Comment by doriandrn** [comment]
Hey, thanks for the quick answer!

In fact [I do, I have just written them](https://github.com/doriandrn/rxdb-search/blob/multiple-datasets-test/src/__tests__/multiple.spec.ts) - it's in the context of the plugin but it should make some sense as it is. They're failing as they are. You may test yourself by cloning the repo and using `jest multiple` command after a `npm i`. You may also see the other 9 passing tests by running 'jest' or 'jest search' - there is also an issue here with one of them failing sometimes, i'm assuming it's the same issue. A sidenote here, `collection.search` is an alias to `collection.si.SEARCH`.

Both tests will pass if you change in the code collections to be only 1 in length.

It appears to me that there is a conflict when instancing SI multiple times even it has different names.

The error I'm getting is:

```js
 TypeError: Cannot read property 'then' of undefined
        at /Users/dorian/Cod/rxdb-search/node_modules/search-index/dist/search-index.cjs.js:101:31
        at processTicksAndRejections (internal/process/task_queues.js:79:21)

  console.log node_modules/search-index/dist/search-index.cjs.js:100
    Error {}
```

It points to L101 of `search-index.cjs.js`:
```js
util(fii$$1).calibrate().then(resolve);
```

**Comment by fergiemcdowall** [comment]
That looks like a cool project! In these tests there are too many layers of abstraction for me to easily see what the error is or how I would go about fixing it at the search-index level.

FWIW Running multiple indexes at once is a use case that is [specifically tested for in v2 ](https://github.com/fergiemcdowall/search-index/blob/v2.x.x/test/src/PUT-test.js)(out soon!).
