### ISSUE TITLE
More flexibility in the processing pipeline

### ISSUE THREAD

**Issue by marcoancona** [fergiemcdowall/search-index#505]
Hi! I like a lot the simplicity of this library. I see that v2 is planned to have a `caseSensitive` option. 
In my opinion, the preprocessing of the tokens (and the query) could be more general. For example, [lunr.js](https://lunrjs.com/) offers the possibility to define an arbitrary chain of functions for this. 

For this library, the following two lines could be replaced by a function passed by the user. https://github.com/fergiemcdowall/search-index/blob/421c8213958ef76bd139f0900c85c88968848be8/src/write.js#L44-L45 
The same function should be also applied to the query tokens.

My use-case is the need for phonetic encoders (e.g. https://github.com/nextapps-de/flexsearch#encoders) in languages other than English. For example, a token like `Björn` could be matched by the user query `bjorn` (notice that both case-insensitiveness and phonetic normalization are needed).

**Comment by fergiemcdowall** [comment]
Hi @marcoancona 

The general approach is to normalise tokens in the indexing and indexing pipelines using [`.normalize()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/normalize).

**Comment by marcoancona** [comment]
Hi @fergiemcdowall, do you mean pre-processing the fields of the documents before passing them to the PUT method of `search-index`? 

Of course this could be handled at the level of the library user, but we would need to implement the recursive logic to process all the (nested) fields which is already implemented in `search-index`. Instead, if the library could take as input an arbitrary pre-processing function, that would be much more convenient from a user perspective and would make the index much more flexible.

**Comment by fergiemcdowall** [comment]
Yes, that was what I meant, but I see what you mean. Being able to pass an arbitrary processing function to `search-index` might be a good way to solve this.

I wonder if this should be in the lib itself, or in an external indexing lib?

**Comment by eklem** [comment]
Create two building blocks that people can choose to use?
* Empty function/step for indexing side
* Empty function/step for query side

And an easy way to communicate and use  these two with existing functions / building blocks? Could be external as long as it's easy to plug in.

**Comment by eklem** [comment]
So this one should maybe be an example for `search-index` and for libraries that builds on search-index, it can be actual (empty) functions.
