### ISSUE TITLE
GET does not accept an object

### ISSUE THREAD

**Issue by marcoancona** [fergiemcdowall/search-index#506]
The documentation seem to suggest that GET can receive an object (i.e. to search for `gte` / `lte`)
https://github.com/fergiemcdowall/search-index/blob/master/docs/API.md#get

However, this causes an error:
```
Uncaught TypeError: t.slice is not a function
```

**Comment by fergiemcdowall** [comment]
OK- thanks for the message. In the meantime it should work with `GET([ object ])`

**Comment by fergiemcdowall** [comment]
`GET` is now called `_GET` and can be invoked with an object. See https://github.com/fergiemcdowall/search-index/blob/master/test/src/GET-test.js
