### ISSUE TITLE
Match case and match whole word features with different languages

### ISSUE THREAD

**Issue by irfancnk** [fergiemcdowall/search-index#510]
As stated in the documentation, with 2.0.0 searching words with case insensitive option is now supported. I wonder how does this feature work with different languages. Does current library only work with English? Also is it possible to match whole word rather than prefix or suffix with current version? Meaning that if my index has
"searching"  as data.
Calling "search" should return no results.

**Comment by fergiemcdowall** [comment]
`caseSensitive` should work with all languages.

Search indexes typically only match entire words, although `search-index` allows you to match [ranges of words](https://github.com/fergiemcdowall/search-index/blob/master/docs/API.md#find-within-a-range).

You cant match by suffix out of the box, but if this is important then there are various ways you can make this work.

**Comment by irfancnk** [comment]
Thank you for quick response.  There is also another thing that might be a issue. In the demo page: 
https://fergiemcdowall.github.io/search-index/demo/
When I search for word "ordinary" I got a matching result, however when I search for word "your" which occurs in the left hand side of the word "ordinary" I got 0 hits. Is this expected?

**Comment by fergiemcdowall** [comment]
Yes that is because [stop words](https://en.wikipedia.org/wiki/Stop_word) have been removed. You can customize the stop words to be excluded from your index by using the `stopword` [option](https://github.com/fergiemcdowall/search-index/blob/master/docs/API.md#sioptions).
