### ISSUE TITLE
Typescript definitions

### ISSUE THREAD

**Issue by marcoancona** [fergiemcdowall/search-index#511]
Types were added with https://github.com/fergiemcdowall/search-index/pull/430 but are not there anymore in the latest release.

**Comment by fergiemcdowall** [comment]
The short answer is that `search-index` is a Javascript and not a Typescript library.

Type definitions were in for a while, but were later removed because we never managed to make any tests to verify that they were correct.

Maybe a wrapper lib is the answer (`search-index-ts`)? Or simply using `search-index` "as is"?

**Comment by marcoancona** [comment]
Indeed the library is simple enough that definitions might not strictly necessary but still, in 2021 I would expect them from any production-ready JS library. Our stack has hundreds of libraries and none of them lacks some kind of typescript support, either by including the definitions or via https://github.com/DefinitelyTyped/DefinitelyTyped

I also believe nobody expects the definitions to be "tested". I doubt most of the definitions in DefinitelyTyped are. As for any other bug, if some discrepancy is found they can be reported here as an issue and eventually fixed. This is just my opinion of course.

**Comment by fergiemcdowall** [comment]
> in 2021 I would expect them from any production-ready JS library.

Surely you expect them for any TS lib? Thats fair enough, but this is a JS lib. There are lots of users here who are working outside of the TS/VSCode ecosystem.

> via https://github.com/DefinitelyTyped/DefinitelyTyped

Yes, I think that the DefinitelyTyped route is probably the way to go- something similar to the [lodash](https://www.npmjs.com/package/@types/lodash) lib perhaps?

> I also believe nobody expects the definitions to be "tested"

There are often small updates and changes that alter the topography of the API in ways that are hard to predict. We need to test every piece of the the API to make sure that it is not broken/stale/incorrect.

**Comment by fergiemcdowall** [comment]
[Here is the (failed) PR  for DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/21792). I actually wasnt aware that it had not been accepted- in retrospect we should have made the changes to get this through.

Also, I have had a quick scan through the ["most depended" upon packages in npm](https://www.npmjs.com/browse/depended), and it seems like very few of them include TS definitions in the module itself (Although this was a completely unscientific clicking of random modules that I use/like, so it could be a sampling error)

TS support is definitely a good thing and it seems as if an external (DefinitelyTyped) lib is the way to go. If you, or anyone else wants to have a go at it, then that would be greatly appreciated, and I will support it as much as I can.

**Comment by fergiemcdowall** [comment]
This is now on the roadmap https://github.com/fergiemcdowall/search-index/issues/527

**Comment by fergiemcdowall** [comment]
It seems that type definitions for search-index have actually been available for a few months -> https://www.npmjs.com/package/@types/search-index
