### ISSUE TITLE
Fix `docs/examples`

### ISSUE THREAD

**Issue by eklem** [fergiemcdowall/search-index#513]
Fix all the code examples to work with the newest version of search-index (v2.1.0). Valuable to get people going I think.

**Comment by eklem** [comment]
https://github.com/fergiemcdowall/search-index/issues/512

**Comment by eklem** [comment]
Progress here https://github.com/fergiemcdowall/search-index/tree/fix-examples/docs/examples

**Comment by eklem** [comment]
Two questions, @fergiemcdowall 
1. The last example in [BUCKETS.js](https://github.com/fergiemcdowall/search-index/blob/fix-examples/docs/examples/BUCKET.js#L113-L121) I don't know how to express with newest version of search-index.
2. Is GET still a thing (GET IDs or something) ?

**Comment by fergiemcdowall** [comment]
I went ahead and fixed `BUCKETS.js`. No GET is no longer a part of the API (although it is still available as `_GET`).

The rest of the examples should now work
