### ISSUE TITLE
How can I delete all documents?

### ISSUE THREAD

**Issue by everlose** [fergiemcdowall/search-index#518]
It seems that the API DELETE must receive an array parameter.
How can I delete all documents, I don't want to use ALL_DOCUMENTS() and traverse it.

**Comment by fergiemcdowall** [comment]
At the moment you have to do

```javascript
// where 'db' is the name of your index
db.INDEX.STORE.clear()
```

(In the future it would be great to have this as a top-level function like `db.FLUSH()` or similar)

**Comment by everlose** [comment]
> At the moment you have to do
> 
> ```js
> // where 'db' is the name of your index
> db.INDEX.STORE.clear()
> ```
> 
> (In the future it would be great to have this as a top-level function like `db.FLUSH()` or similar)

Thanks

**Comment by fergiemcdowall** [comment]
👍👍
