### ISSUE TITLE
search-index upgrade 0.x to 2.x => refactor

### ISSUE THREAD

**Issue by jeromelarman** [fergiemcdowall/search-index#521]
Hello,

I am migrating search-index and I try to refactor my code to be compliant with 2.2.0 search-index.

Previously I use a 0.x version ...

I try to find the ability so specify old feature nGramLength, which was supplied on index initialization throught the 0.x search-index.

How can I reproduct this feature ? Thanks in advance.

**Comment by fergiemcdowall** [comment]
Hi @jeromelarman 

Support for N-grams is is not actually built into search-index@2.x.x any more, but perhaps it should be?

**Comment by eklem** [comment]
@jeromelarman Here and now you can create the ngrams you need with [ngraminator](https://github.com/fergiemcdowall/ngraminator/), and add them to your document object before indexing.

@fergiemcdowall I think it's okay to keep out, or at least that you are able to turn it off with some config. But it seems it's a missing feature when we don't have any downstream libraries implementing this.

**Comment by fergiemcdowall** [comment]
@eklem yes, I agree that even if it is not core functionality, there should at least be some easy way to do it

**Comment by eklem** [comment]
So, if an external funkction / library, a function that takes an object (of data) and input on ngram-lengths and then adds a key/value like `_si_ngrams: '[array of ngram arrays]'` ?

**Comment by eklem** [comment]
And maybe the ability to tell which fields to do this on? Default to all, and then the possibility to instead just do it on some that is defined.

**Comment by eklem** [comment]
I could build a library on top of ngraminator?

**Comment by jeromelarman** [comment]
I discover this lib while I try to implements this feature in front of indexing data.

https://github.com/fergiemcdowall/term-vector

I can't achieve that easily because I need to insert document and I don't see how I can insert multiple "version" of the original string to index... insert multiple time the document for each combination of string value ? It seems to be complex.

**Comment by eklem** [comment]
What I was thinking of making is transforming an object (document) that you would feed to the search-engine before you send it.

So, if you have i.e.:
```javaScript
{
  _id: '123923882',
  title: 'A document title',
  body: 'A lot of text making it a document body. Enough text so it is actually interesting'
}
```
I could make a library that transform it into
```javaScript
{
  _id: '123923882',
  title: 'A document title',
  body: 'A lot of text making it a document body. Enough text so it is actually interesting'
  _si_ngrams: [['actually','interesting'],['body','enough'],['body','enough','text'],['body','enough','text','so'],['document','body'],['document','body','enough'],['document','body','enough','text'['document','title'],['document','title','lot'],['document','title','lot','text'],['enough','text'],['enough','text','so'],['enough','text','so','actually'],['lot','text'],['lot','text','making'],['lot','text','making','document'],['making','document']]
} // and a lot more...
```

**Comment by jeromelarman** [comment]
This is the current document format i use with search-index 0.1.X

{ 'id': ... ,
  'favoritecity': ... ,
  'favoritedescription':  ... ,
  'favoritename': ... ,
  'favoritestuffcool':  ... ,
...

The ngGramLength was defined at global index scope, so each properties inherit of nggram feature.

So with your purpose, i need to transform each business properties and add the transformation result sequentially to the core _si_ngrams properties.

**Comment by eklem** [comment]
@jeromelarman Got a little unsure of what you are trying to do. Are you converting the index content or upgrading the search engine and adding the documents again?

**Comment by eklem** [comment]
Also, from my example. Then you have the nGrams, but will still need to set up how the autocomplete works. You can get some [hints on autocomplete/search suggestions from the demo](https://github.com/fergiemcdowall/search-index/blob/master/demo/src/search-app.js#L92-L102).

**Comment by jeromelarman** [comment]
Thanks for your support.

{
  _id: '123923882',
  title: 'A document title',
  body: 'A lot of text making it a document body. Enough text so it is actually interesting'
  author : 'john doe',
  editor : "purple book"
}

If my document was like this format, how i can control indexation : 
    - purple john ( no indexation ) 
    - document book ( no indexation )
    - document title ( ok indexation ) 
    - actually interisting ( ok indexation ) 

I need to preserve fields logic "gram".

Is it possible ?

**Comment by fergiemcdowall** [comment]
Although this could also be solved by ngrams, perhaps a simpler approach is just to used fielded search?

```javascript
QUERY({
  AND('body:actually', 'body:interesting')
})
```

**Comment by eklem** [comment]
@jeromelarman Like @fergiemcdowall shows, you can search on specific fields. Or you can do OR-searches, each search on a field with your query input.

The nGrams will only match something within a field, as long as you don't join all the field values as one string before doing the ngramination-part. If you set the nGram-length to 2, remove stopwords before ngramination and process each field on its own before joining them you will get something like this:
```javaScript
[
  ['document', 'title'],
  ['text', 'making'],
  ['making', 'document'],
  ['document', 'body'],
  ['body', 'enough'],
  ['enough', 'text'],
  ['text', 'actually'],
  ['actually', 'interesting'],
  ['john', 'doe'],
  ['purple', 'book']
]
```

Typing `text` you will get two suggestions: `text making` and `text actually`

You can add all the ngrams to a field in your document and do the typeahead lookup on this field only.

**Comment by jeromelarman** [comment]
I am working on search-index migration, and I try to use DICTIONNARY feature ( ie. like old match function 0.X ) 

When I try to use this DICTIONNARY function, if I index 'jerome larman' then i has 'jer' input for example, the DICTIONNARY function return ['jerome', jeromelarman']. 

How can I keep the space character on DICTIONNARY return result ? 

My goal is to have as result  ['jerome', jerome larman'] which will available while search autocompletion.

**Comment by fergiemcdowall** [comment]
@jeromelarman this is ngrams functionality which was actually taken out of v2.x because it was thought that not many people were using it. I think a return of ngrams should be a high priority for version 3.x

**Comment by fergiemcdowall** [comment]
Since this is not a "breaking change" it may also make sense to push into v2.x.x

**Comment by jeromelarman** [comment]
I implement ngram before indexing each of my document properties but it not take effect on how search-index integrate data.

It seems that ngram must to be applied internally by index-search.

If thats's wrong, how ca I implement DICTIONNARY to support space indexation, and not trim space in its response.

**Comment by fergiemcdowall** [comment]
This would be the general strategy:

```javascript
(async function() {

  const si = require('search-index')
  const ng = require('ngraminator')

  const text = "So let it out and let it in hey Jude begin Youre waiting for someone to perform with And don't you know that it's just you hey Jude you'll do The movement you need is on your shoulder"

  const { ALL_DOCUMENTS, PUT, PUT_RAW, DICTIONARY } = await si()

  // create ngrams (le)
  const ngrams = ng(text.split(' '), [1, 2, 3, 4]).map(arr => arr.join(' '))

  // index all of the ngrams
  await PUT([{
    _id: 1,
    text: ngrams
  }])

  // override the document with an un-grammed version
  await PUT_RAW([{
    _id: 1,
    text: text
  }])

  // document looks normal
  console.log(await ALL_DOCUMENTS())

  // dictionary contains ngrams
  console.log(await DICTIONARY())

}())

```

**Comment by jeromelarman** [comment]
Hi, 

Apologize !!! I didn't understand the use of PUT_RAW. It helps me to implements my autocomplete list like your exemple explain. 

Thanks for your help !!!

I will soon recover all my 0.x feature ! 

Now, the last feature missing to recover all my 0.x scope, is the boost flag.

Could you help me to implement that ?

**Comment by fergiemcdowall** [comment]
@jeromelarman Glad we got it fixed! :)

What kind of scoring do you want to do? Can you give us your use case

**Comment by jeromelarman** [comment]
Below, a sample of my search-index@0.X configuration.

```
            {
                fieldName: 'favoritename',
                weight: 3,
            }, {
                fieldName: 'favoritecityName',
                weight: 4,
            }, {
```

           Sometimes the same search 'keys' could be present in several input.

            Use case : search key in input 'london butcher'

            indexed data : 

```
            favoritename : butcher 
            favoritecityName : liverpool

            favoritename : doctor
            favoritecityName : london

```
             If no ponderation set on each properties then the result of QUERY : SEARCH : { ... will be unpredicable

             In this case I want to focus on favorite available in london, so i want the doctor was more revelant for this search key 'london butcher'

**Comment by fergiemcdowall** [comment]
I think I would boost 'london' by using and `QUERY` `OR` combined with the `SCORE` and `SORT` options:

```javascript
(async function() {

  const si = require('search-index')

  const { PUT, QUERY } = await si()

  // pretty print
  const p = obj => console.log(JSON.stringify(obj, null, 2))
  
  // index some businesses
  await PUT([{
    _id: 1,
    business: 'baker',
    location: 'liverpool'
  }, {
    _id: 2,
    business: 'butcher',
    location: 'aberdeen'
  }, {
    _id: 3,
    business: 'butcher',
    location: 'liverpool'
  }, {
    _id: 4,
    business: 'butcher',
    location: 'london'
  }])

  // search for all butchers
  await QUERY({
    OR: ['business:butcher']
  }).then(p)

  // search for all butchers and all london locations
  await QUERY({
    OR: ['business:butcher', 'location:london']
  }).then(p)

  // search for all butchers and all london locations,
  // SCORE and SORT so that documents that are both
  // "business:butcher" and "location:london" come to
  // the top
  await QUERY({
    OR: ['business:butcher', 'location:london']
  }, {
    SCORE: 'SUM',
    SORT: {
      TYPE: 'NUMERIC',
      DIRECTION: 'DESCENDING',
      FIELD: '_score'
    }
  }).then(p)
  
}())
```

**Comment by jeromelarman** [comment]
When the user input a key ( ie. butcher london ), I think, that you don't know wich field is concerned, so this is difficult to map the current key with the appropriate field to apply predicate.

I think, the correct way to implements its, is to apply a booster factor to increase score of the field if it match. 

Perhaps, I misunderstood your working example.

**Comment by fergiemcdowall** [comment]
In the examples above you could simply do `OR: ['butcher', 'london']` to search all fields. When you set `SCORE: 'SUM'` it then assigns a higher score to those documents that match both. But yes I see that maybe setting a boost on London might be a cleaner way of achieving this.

Boosts and blocks were taken out of the core lib in the 2.x release but maybe it might be nice to have them back.

**Comment by fergiemcdowall** [comment]
We covered a lot of ground in this issue, but n-grams are now back in `search-index@3` without the need for external libraries.
