### ISSUE TITLE
Initiate search-index without async/await?

### ISSUE THREAD

**Issue by eklem** [fergiemcdowall/search-index#529]
Hi @fergiemcdowall!
For the browser, is it possible to initiate search-index in a more lazy way, not doing the async/await? Or has that gone away in the latest version?

I'm asking since it would make it a bit easier to make the code modular.

**Comment by eklem** [comment]
The thing I want to avoid doing this part
```javaScript
const { PUT } = await SearchIndex()
```
... each time I run a search-index function. Like this [basic browser example from the idx-tests](https://github.com/eklem/idx-tests/blob/idx-v2/running-in-browser/search-app.js#L5-L18).

**Comment by fergiemcdowall** [comment]
I'm not sure if I totally understand the question, but maybe this would help?:

```javascript
const SearchIndex = require('search-index')

const mySi = await SearchIndex()

// can now use mySi.PUT, mySi.QUERY, etc...

```

**Comment by eklem** [comment]
Cool, yes! I'll try this version. Since it's the browser the scripts load way before a user does much.
