### ISSUE TITLE
Tests should be in a seperate repo

### ISSUE THREAD

**Issue by fergiemcdowall** [fergiemcdowall/search-index#532]
Ideally the tests should be in a separate repo so that accidental changes and omissions to tests dont find their way into the main repo

**Comment by fergiemcdowall** [comment]
I dont think that this is a good idea any more

**Comment by eklem** [comment]
@fergiemcdowall Not the actual tests, but thought of having a separate test-framework module. So it will be less noise and less work when the dev-dependencies (which would then be dependencies) get an update. I.e. webpack. Just update it once every second week or so, and then the other modules will get one update when the test-framework module gets a new npm package.
