### ISSUE TITLE
How to disconnect search-index db？

### ISSUE THREAD

**Issue by everlose** [fergiemcdowall/search-index#534]
I'm connected to DB，I need to change my db connection after a while，but how to disconnect origin connection？

```
const searchDB = await si({name: 'xxx'})

searchDB.disconnect() // ???

await si({name: 'yyy'})
```

**Comment by fergiemcdowall** [comment]
This isnt really something that we have considered necessary- what is your use case? Why do you need to disconnect?

Maybe you could [close the underlying store](https://www.npmjs.com/package/level#close)? In `search-index` `si.INDEX.STORE` points to the underlying level store so you would run `si.INDEX.STORE.close()`

**Comment by everlose** [comment]
em...Yes, It doesn't need to be closed manually, forget it.
