### ISSUE TITLE
Building index by calling PUT once for each document does not return all matches in query afterwards

### ISSUE THREAD

**Issue by elega9t** [fergiemcdowall/search-index#537]
Hi,

I am building my index by async loading files and calling a PUT for each file once its loaded.

The QUERY on the index behaves inconsistently. Eg, lets say the number of matching documents for a query is 3; sometimes the query returns 1 match, sometimes 2; never 3.

I have tried changing the code to collect all documents in an array and doing just 1 PUT. In such a case, the query returns all 3 documents.

I do not want to load all documents in memory at once, thus would want to revert back to calling PUT for each documents when its loaded.

Any insights on this issue would be very much appreciated.

Thanks.

**Comment by fergiemcdowall** [comment]
It sounds like you may have some basic issues with the way you have set `search-index` up.

If you can post the code here, then we can try to help you.

**Comment by elega9t** [comment]
Hi, here are the relevant extracts of code;

`
      const { PUT, QUERY } = await si({
        db: memdown('journals')
      });

   const files: Array<string> = [...]; // List of files

    const indexingPromises = [];
    _.forEach(files, (file: string) => {
      indexingPromises.push(this.indexFile(file));
    });
    Promise.all(indexingPromises)
      .then(() => {
        console.log(moment.utc().format() + ': Finished building journal search index');
      })
      .catch((err) => {
        console.log(moment.utc().format() + ': Failed building journal search index', err);
      });
`
and

`
indexFile(file) {
    return new Promise((resolve, reject) => {
      const promises = [];

      const readStream = fs.createReadStream(file);

      readStream.on('data', (chunk) => {
        let str = chunk.toString();

        if (readStream._invalidLine) {
          str = readStream._invalidLine + str;
        };

        const entries = str.split('\n');
        readStream._invalidLine = entries.splice(entries.length - 1, 1)[0];

        _.forEach(entries, (v: string) => {
          const entry = JSON.parse(v);
          promises.push(PUT(entry));
        });
      });

      readStream.on('end', () => {
        if (readStream._invalidLine) {
          const entry = JSON.parse(readStream._invalidLine);
          promises.push(PUT(entry));
        }

        Promise.all(promises)
          .then(() => {
            resolve();
          });
      });

      readStream.on('error', (err) => {
        reject(err)
      });
    });
  }
`
Hope this explains the setup I am using. Thanks

**Comment by fergiemcdowall** [comment]
How about arranging your code like this:

```javascript
(async function() {
  const fs = require('fs')
  const si = require('search-index')
  const memdown = require('memdown')

  const { PUT, QUERY } = await si({
    db: memdown('journals')
  })

  const batch = fs.readdirSync('journals').map(
    j => JSON.parse(fs.readFileSync('journals/' + j))
  )
  
  await PUT(batch)

  console.log(JSON.stringify(await QUERY({
    OR: ['dag', 'emmey', 'dorie', 'cordell', 'gregoire']
  }), null, 2))
  
}())
```

I put together an [example repo](https://github.com/fergiemcdowall/search-index-issue-537). As you can see the query always returns a consistent result.

**Comment by elega9t** [comment]
Hi thanks for taking a look. I wanted to use streams and promise because each file can have multiple json entries and the files themselves could be huge (gigs). So, reading the entire content in memory at once is not something feasible.

I'll create a branch on the example repo and update the code and sample data to resemble what I am working with.

**Comment by elega9t** [comment]
Hi, I have updated the code in fork https://github.com/elega9t/search-index-issue-537

If you run the code multiple times, you would notice the inconsistent results being returned.

Based on the query, it should return 3 results, however you would notice that sometimes it returns 1 and sometimes 2.

Thanks

**Comment by fergiemcdowall** [comment]
The problem here is that you can't `PUT` documents concurrently so [this line ](https://github.com/elega9t/search-index-issue-537/blob/15d13232872786e42005379412b268cc6ecfd796/index.js#L34) is creating the problem. You should wait for the previous `PUT` to finish before starting a new `PUT`. This should probably be better explained in the documentation.

Generally its best to `PUT` batches of documents rather rather than individual documents, so the best approach here would probably still be to `PUT` all the objects in the file at once, rather than `PUT`ing them individually.

Iterating over collections of Promises withing the context of streams remains a tricky thing to do, so personally I avoid streams for document processing even though they seem like a reasonable approach at first glance.

**Comment by elega9t** [comment]
Thanks a lot for looking into this issue. I will write a flatMap utility to queue PUTs for now.

**Comment by elega9t** [comment]
Hi, I have chained Promises so that they run sequentially rather than concurrently. However, now I get 2 results consistently, rather than expected 3.

    function readFile(file) {
      return new Promise((resolve, reject) => {
        let readStream = fs.createReadStream('journals/' + file).pipe(split(JSON.parse, null, { trailing: false }));
  
        const promise = Promise.resolve();
        readStream.on('data', (entry) => {
          promise.then(() => {
            console.log('Indexing: ' + JSON.stringify(entry));
            return PUT([ entry ]);
          });
        });
  
        readStream.on('end', () => {
          promise.then(() => resolve());
        });
  
        readStream.on('error', (err) => {
          reject(err)
        });
      });
    }
  
    let promise = Promise.resolve();
  
    fs.readdirSync('journals').forEach(file => {
      promise = promise.then(() => { return readFile(file); });
    });
  
    await promise;
  
    const results = await QUERY(
      { SEARCH: [ 'Chaudron' ] },
      { DOCUMENTS: true, PAGE: { NUMBER: 0, SIZE: 20 } }
    );
  
    console.log(JSON.stringify(results));

Please, can you take a look at this and suggest a workaround for now.

**Comment by fergiemcdowall** [comment]
A sensible approach would be to do something like this:

```javascript
(async function() {
  const fs = require('fs')
  const split = require('split')
  const stream = require('stream')
  const si = require('search-index')
  const memdown = require('memdown')

  const { PUT, QUERY } = await si({
    db: memdown('journals')
  });

  const readFile = file => new Promise(resolve => {
    let batch = []
    let readStream = fs.createReadStream('journals/' + file).pipe(
      split(JSON.parse, null, { trailing: false })
    ).on(
      'data', d => batch.push(d)
    ).on(
      'end', () => resolve(batch)
    )
  })

  for (f of fs.readdirSync('journals')) {
    await PUT((await readFile(f)))
  }
  
  const results = await QUERY(
    { SEARCH: [ 'Chaudron' ] },
    { DOCUMENTS: true, PAGE: { NUMBER: 0, SIZE: 20 } }
  );

  console.log(JSON.stringify(results))
  
}())

```

**Comment by elega9t** [comment]
Hi, the bug in my sequenced code was to update the promise once document has been PUT. I really dont want to accumulate all documents in memory, so returning array and then doint a PUT is not suitable.

      let promise = Promise.resolve();
      readStream.on('data', (entry) => {
        promise = promise.then(() => {
          console.log('Indexing: ' + JSON.stringify(entry));
          return PUT([ entry ]);
        });
      });

Now I am getting all 3 documents as expected. cheers!

**Comment by fergiemcdowall** [comment]
Just to reiterate- PUTing batches is computationally less expensive than PUTing those documents individually- so it will always be quicker to use batches. Start off with the batch approach, and only switch to individual PUTs if/when you run out of memory.

Also, if memory use is a pain point, then dont use `memdown`- just stick with the default `leveldown`/`leveljs`.

In the forthcoming `search-index@3` it is possible to `PUT` in parallel.

Anyway- glad to hear that you got it working! 👍🙂
