### ISSUE TITLE
can't figure out how to load on observable

### ISSUE THREAD

**Issue by trebor** [fergiemcdowall/search-index#547]
I was hoping to use the tool on [Observable](observablehq.com) but I was unable to load the package.  They have a module loading tool here:

https://observablehq.com/@observablehq/module-require-debugger?module=search-index

which tries a number of approaches.   I have also created a [toy-notebook](https://observablehq.com/@trebor/test-load-of-search-index) to show my (very simple) attempt to load the module.

**Comment by fergiemcdowall** [comment]
‘search-index’ is a vanilla, non-compiled node module with the entry point described in ‘package.json’ under ‘main’. Observable is new to me, do I cant give any more help unfortunately.

What is your high level aim here?
