### ISSUE TITLE
Trying to delete after every search 

### ISSUE THREAD

**Issue by sidugboe** [fergiemcdowall/search-index#551]
Good evening ,
I am a student who is currently trying to use your search-index creation to search through an array of large objects. 
It works exactly how I want it to; however, the query results are saved each time I perform a search. 
This is a problem because it prevents me from displaying relevant information relating to what the user has most recently searched for, instead, it just displays everything that the user has ever searched for.
I have tried deleting the database after each search by using fs.rmdir(), however, some setting in the lock file prevents this.

Thank you, and please help me out if you can

**Comment by fergiemcdowall** [comment]
hi @sidugboe - I'm sorry, but I dont understand the problem- do you have any code you could show us?

**Comment by sidugboe** [comment]
Hello sir @fergiemcdowall, thank you so much for your response. This is a snippet of the code i am currently working on, I left a lot of comments describing what I am trying to do.



```
searchFunction(userInput) {
	//user Input is the value of what is inputted in the text box

const si = require('search-index')
(async () => {

	let documents = 0;

	//here, I am basically getting all my xml files, converting them into js objects, then pushing into an arrau
	for(let i = 0) {
		let xmlFile = fs.readFileSync(files[i], 'utf8');
		let jsobj = parser.xml2js(xmlFile, {compact: true, spaces: 4});

		documents.push(jsobj)
	}

	//This is the stuff you showed us how to do
	const db = await si({ name: 'SEARCH' })
	await db.PUT(documents)

	console.log('\nSEARCH-ing ->')
	await db.QUERY({
		SEARCH: [''+userInput+'']

	}).then(

	result => {
		console.log(result) //just logging result for now

		//attempting to get rid of SEARCH database which is the database of results.(below)
		//"result" keeps track of past results as well, rather than only results from most recent, which is why I am trying to delete it everytime the user inputs something

		let requiredPath = path.join(_dirname, '../SEARCH')

		fs.rmdir(requiredPath, () => {
			console.log("Deletion done")
		});

		//This does not work as it just returns an error saying "Error: EBUSY: resource busy or
 locked" or "OpenError: IO error:LockFile"
		//Has something to do with the file being locked


	}


	)
})()
}
```

I was wondering, is there some sort of in built mechanism to do this instead?

**Comment by sidugboe** [comment]
Also the documents array has this basic structure if it helps at all.

```
[{ dmodule: { identAndStatusSection: [Object], content: [Object] } },

  { dmodule: { identAndStatusSection: [Object], content: [Object] } },

  { dmodule: { identAndStatusSection: [Object], content: [Object] } },

  { dmodule: { identAndStatusSection: [Object], content: [Object] } },

  { dmodule: { identAndStatusSection: [Object], content: [Object] } },

  { dmodule: { identAndStatusSection: [Object], content: [Object] } },

  { dmodule: { identAndStatusSection: [Object], content: [Object] } },

  { dml: { identAndStatusSection: [Object], dmlContent: [Object] } },

  { pm: { identAndStatusSection: [Object], content: [Object] } },

  { pm: { identAndStatusSection: [Object], content: [Object] } },

  { pm: { identAndStatusSection: [Object], content: [Object] } },

  { pm: { identAndStatusSection: [Object], content: [Object] } }]
```

**Comment by eklem** [comment]
So you are trying to delete your index for each time you run your script? I'm guessing the files are locked by search-index, so you can't delete them that way from within your script. But that is your index or "search database", isn't it, not your search results.

**Comment by eklem** [comment]
Not sure I understand the use case, but that doesn't matter =) To empty the index, you can use [FLUSH:](https://github.com/fergiemcdowall/search-index/blob/master/docs/API.md#flush):

```javaScript
await FLUSH()
```

Here is an  example from [FLUSH-test.js](https://github.com/fergiemcdowall/search-index/blob/dbf652a405cafad9bbc4803385e5519f38b7a288/test/src/FLUSH-test.js#L95)

**Comment by sidugboe** [comment]
Yes sir I was trying to delete my index "db" every-time the function was called!🙂  
The await db.FLUSH() was exactly what I was searching for, Thank you!

However, there is minor problem - if the user calls the function too quick consecutively, this node error gets thrown - "(node:12760) UnhandledPromiseRejectionWarning: OpenError: IO error: LockFile SEARCH/LOCK: The process cannot access the file because it is being used by another process."

I could solve it by getting the button to timeout for about 10 seconds after it has been clicked, however, I just wanted to check if you maybe had a better solution?

**Comment by eklem** [comment]
I guess you need to chain the promises. So after you know that the other stuff is finished, you can flush the index. Async/await or .then-chaining?

**Comment by fergiemcdowall** [comment]
Yes, at the moment an instance of search-index can only be owned by one process.

**Comment by sidugboe** [comment]
@fergiemcdowall sounds good, thank you for this amazing package anyways. Its very useful and there actually aren't any similar ones to this.
