### ISSUE TITLE
Release of Version 3

### ISSUE THREAD

**Issue by tonprince** [fergiemcdowall/search-index#556]
I was wondering if there is a roadmap for the release of version 3, as I am looking for support of query like: "koh tao", phrase with 2 words.

With version 2 it is not supported, and even the workaround to put a delimiter like '_' or '-' does not work.

I tried to check with milestone from version 3, but it seams it is not stable yet as basic query does not work.

**Comment by fergiemcdowall** [comment]
Hi @tonprince

Phrase search only works if you index the phrase.

So:
```javascript
{
  text: ['koh', 'tao']    // only gives hits for 'koh' and 'tao'
}
```

and:

```javascript
{
  text: ['koh', 'tao', 'koh tao']    // gives hits for 'koh' and 'tao' and the phrase 'koh tao'
}
```

Use something like [ngraminator](https://www.npmjs.com/package/ngraminator) to create the phrases (n-grams).

[Here is the scrum board for search-index@3](https://github.com/fergiemcdowall/search-index/projects/3)

**Comment by eklem** [comment]
For some reason you need to reload the page to not only get an empty scrumboard =)

**Comment by tonprince** [comment]
Thanks
