### ISSUE TITLE
weights don't work

### ISSUE THREAD

**Issue by naveen9** [fergiemcdowall/search-index#561]
As i used your example for  SCOREd query with WEIGHT then , it is not giving any response  to me 

My JSON data
[
{
    "id":"1",
    "project":"title",
    "message":"test"
},
{
    "id":"2",
    "project":"test",
    "reviewinstruction":"this is test"
}
{
    "id":"3",
    "project":"my project",
    "reviewinstruction":"review"
},
{
"id":"4",
"project":"title",
"message":"test  your are the best way"
},
];

weight AND queries

QUERY({
  SEARCH: [ 'test' ]
}, {
  SCORE: {
    WEIGHT: {
      'reviewinstruction': 2        // reviewinstruction  is  field
    }
  }
})

Am i missing something in SCOREd query with WEIGHT ?

**Comment by fergiemcdowall** [comment]
Hi @naveen9 

Sorry for the late reply!

WEIGHTing has been slightly rejigged in version 3. You can see[ the new API](https://github.com/fergiemcdowall/search-index/blob/master/docs/API.md#weight) and checkout out [the tests](https://github.com/fergiemcdowall/search-index/blob/master/test/src/WEIGHT-test.js) for examples
