### ISSUE TITLE
Code examples link is broken

### ISSUE THREAD

**Issue by sdrib** [fergiemcdowall/search-index#567]
https://replit.com/repls/folder/search-index%20examples

gives me `Unable to fetch repls. Please try again.`

should it be: https://replit.com/@fergiemcdowall ?

**Comment by sdrib** [comment]
Yeah I was able to create my own `search-index examples` folder. The link then works. But of course there's nothing int he folder.

**Comment by sdrib** [comment]
https://replit.com/talk/ask/Share-a-whole-folder/32734 this seems to confirm this. ( though it  _is_ a 2 year old question )

**Comment by fergiemcdowall** [comment]
Oh- thanks for looking into that- I didnt realise that you couldnt share a folder. I will fix ASAP
