### ISSUE TITLE
Indexing documents with empty object props

### ISSUE THREAD

**Issue by jakobsa** [fergiemcdowall/search-index#571]
When documents contain properties with empty objects `PUT` will throw an exception originating from charwise.

I have modified the CLI example by adding such a property here: [forked and modified Cli Example](
https://replit.com/@jakobsa1/search-index-example-CLI#index.js)

As I am just getting to know your search-index package I am a bit reluctant to open an issue for the first obstacle I encounter.
However I did not find documentation or discussion on this behavior. I would like to know if this behavior is expected.

**Comment by fergiemcdowall** [comment]
Thanks for the feedback @jakobsa , I really value it, so don’t feel any reluctance! 🙂. I am a bit busy with family stuff at the moment but will try and take a look at this soon.

**Comment by fergiemcdowall** [comment]
This should now be fixed in `search-index@3.0.3` 

Does it work for you @jakobsa ?

**Comment by jakobsa** [comment]
I can confirm that my test case is now working without `delete objToIndex.emptyObj` workaround.

**Comment by fergiemcdowall** [comment]
Good to hear! 👍
