### ISSUE TITLE
Token parsing doesn't accommodate for values that include `:`

### ISSUE THREAD

**Issue by mistermoe** [fergiemcdowall/search-index#582]
Flagging Issue: fergiemcdowall/fergies-inverted-index#40
Supporting PR: fergiemcdowall/fergies-inverted-index#41

**Comment by fergiemcdowall** [comment]
I have just published `fergies-inverted-index@10.0.6` to npm. Hopefully the magic of semver makes this improved functionality appear in the current version of `search-index`.

**Comment by fergiemcdowall** [comment]
If not, I can publish a new version of search-index that explicitly includes 10.0.6

**Comment by mistermoe** [comment]
@fergiemcdowall thanks! `fergies-inverted-index` is hard-locked to `10.0.5` in [`package.json`](https://github.com/fergiemcdowall/search-index/blob/master/package.json#L73), so it looks like you'll have to publish a new version that explicitly includes `10.0.6`. If you want semver to work in the future you'll want to include a `^` before the version number

**Comment by mistermoe** [comment]
Went ahead and PR'd the version bump.

**Comment by fergiemcdowall** [comment]
Great- thanks! 👍

**Comment by fergiemcdowall** [comment]
3.1.2 is now out on npm
