### ISSUE TITLE
switch to `abstract-level` from `abstract-leveldown`

### ISSUE THREAD

**Issue by mikaelkaron** [fergiemcdowall/search-index#585]
It looks like the level community is deprecating [`abstract-leveldown`](https://github.com/Level/abstract-leveldown) in favor of [`abstract-level`](https://github.com/Level/abstract-level). They published some [nice upgrade guides](https://github.com/Level/community#how-do-i-upgrade-to-abstract-level) that look straight forward enough.

**Comment by fergiemcdowall** [comment]
Thanks for the heads up @mikaelkaron 👍
