### ISSUE TITLE
Bundling a little better?

### ISSUE THREAD

**Issue by eklem** [fergiemcdowall/search-index#609]
I was thinking of trying to bundle CJS, ESM and UMD versions + minified of search-index. And also make sure they have named exports. I'm having some difficulties using the existing ESM-version in the browser because of default export.

**Comment by eklem** [comment]
I guess UMD is out of the question, since the build process has to split the result on either levelDB for node or indexedDB for the browser. But ESM for the browser is good. And named exports.

**Comment by eklem** [comment]
And it seems I can look at how the browsers are doing imports now.
https://twitter.com/wesbos/status/1640722393688600578

**Comment by eklem** [comment]
It seems the bundled version pulls in the whole package.json-file. Does it need that?

And shouldn't `main` and `browser` in package.json point to files in the dist-folder?

**Comment by eklem** [comment]
And nother question: Where do you define that you build with browser.js? Or is that just for browser-tests?

**Comment by fergiemcdowall** [comment]
I think that `main` and `browser` are correct, and that the only file that should be in the dist folder is that stand-alone version that can be included in a script tag. That said, I am not really an expert on package bundling, so it could be that there is a better way to do this.

**Comment by fergiemcdowall** [comment]
I also think that we should probably be using shipping without a `dist` folder and instead make `dist` magically appear on installation by adding `npm prepare` to `package.json`. The UMD version could then be made available directly from GitHub for anybody wanting to bypass bundlers (and/or use it directly from a `<script>` tag)
