### ISSUE TITLE
si.del callback err is true ?

### ISSUE THREAD

**Issue by sbiaudet** [fergiemcdowall/search-index#61]
Why err param from si.del callback is at true when all is ok ?

In deleteDoc it isn't better to return callback(null, true) instead of return callback(true);

**Comment by fergiemcdowall** [comment]
In the following case, `err` should be falsey when then document is successfully deleted, and true if there is a problem:

```javascript
si.del(docID, function(err) {
  if (!err) console.log('success!');
}); 
```

Is that how it works for you or is this broken?

**Comment by sbiaudet** [comment]
For me it doesn't respect callback pattern from nodejs as explain err https://www.joyent.com/developers/node/design/errors 

>You're familiar with programming in Node.js. You're comfortable with asynchronous operations and with the **callback(err, result)** pattern of completing an asynchronous operation. You should know why this pattern:

**Comment by fergiemcdowall** [comment]
So there should always be a `result` placeholder even if it can never be filled? I'm not convinced that people want or expect that. `callback(err)` seems OK for non-returnable functions, or is that wrong?

Thats a great link. search-index **needs** to implement this:
> 2. Use Error objects (or subclasses) for all errors, and implement the Error contract.

**Comment by sbiaudet** [comment]
If you just want return is an error occurred or not. In success, you just wrote callback(null); 

I don't know if people want this but this a dev pattern. With this convention, all nodejs library work in the same way. This morning I've wrote this code with your framework. I search 20 min why my unit test failed with a valid Id. Just because err is not an error.

si.del(key, function(err){
    if(err)
        return callback(err)
 
    .....
});

Sébastien BIAUDET

**Comment by fergiemcdowall** [comment]
Thanks for pointing it out, its clear that there is some further work to do with errors.

Would you agree with this article? https://docs.nodejitsu.com/articles/errors/what-are-the-error-conventions

**Comment by sbiaudet** [comment]
Yes exactly this is the good pattern. I'm full agree with that ;)

**Comment by fergiemcdowall** [comment]
Excellent!

**Comment by sbiaudet** [comment]
If you wan't I can help you to refactoring

**Comment by fergiemcdowall** [comment]
Yes, please do!

**Comment by fergiemcdowall** [comment]
@sbiaudet I guess this fixed now?

**Comment by sbiaudet** [comment]
I hope ;)

**Comment by fergiemcdowall** [comment]
Hehe! :) OK closing then...
