### ISSUE TITLE
Browser: Uncaught SyntaxError: ambiguous indirect export: si

### ISSUE THREAD

**Issue by eklem** [fergiemcdowall/search-index#618]
Hi @fergiemcdowall! I'm trying to import the ESM-version to run in the browser, but not sure what's exported from `search-index-esm-4.0.0.js`?

In HTML:
```html
<script type="module" src="./geo-search-app.mjs"></script>
```

In geo-search-app.mjs
```javaScript
import { si } from './search-index-esm-4.0.0.js'
const idx = await si()
```

Then I get an error-message, saying
```console
Uncaught SyntaxError: ambiguous indirect export: si
```

That's why I'm wondering what search-index is exported as?

**Comment by eklem** [comment]
But the ESM-version is maybe only made for NodeJS and not the browser?

**Comment by fergiemcdowall** [comment]
I think it should just be availavle as a global variable `SearchIndex` :)

**Comment by eklem** [comment]
It is in search-index-4.0.0.js (UMD), but not the ESM - search-index-esm-4.0.0.js

**Comment by fergiemcdowall** [comment]
Ah right yes. [In the newest version](https://github.com/fergiemcdowall/search-index/tree/v5.0.0), it is ESM compatible by default.

**Comment by fergiemcdowall** [comment]
on npm as `search-index@5.0.0-rc1`

**Comment by eklem** [comment]
If that works, I can also start on a simple service worker for seach-index, importing the different things you need into the service worker.

**Comment by fergiemcdowall** [comment]
I can't remember exactly why I did that, but I probably published it as the latest version by accident, and then depredated it in a panic just to make sure that nobody actually used it! (strictly speaking it should be published with tag:next)

**Comment by eklem** [comment]
Is it possible with a `5.0.0-rc2` with the `next` tag? So i can play around with the geo-search library =)

**Comment by fergiemcdowall** [comment]
Sorry that I missed that last question @eklem !

`search-index@5.0.0` is now out and this should all just work (let me know if it doesnt 🙂)
