### ISSUE TITLE
empty function do not use indexPath

### ISSUE THREAD

**Issue by sbiaudet** [fergiemcdowall/search-index#62]
If you define an indexPath in options, the empty function rm 'si' folder and recreate a new db with 'si' as name. The database defined in options is never emptied.

**Comment by fergiemcdowall** [comment]
That is as it should be. If you define `indexPath` to be an index that exists, then `search-engine` will open the existing index, with the existing contents.

If you want a fresh clean index, you need to delete and then reinitialize it

**Comment by fergiemcdowall** [comment]
Or am I missing something? :)

**Comment by sbiaudet** [comment]
I'm talking about your function empty(). There is a bug. You don't use indexPath parameter. You have hardcode 'si' value to rm folder and recreate indexes variable.

Sébastien BIAUDET

**Comment by fergiemcdowall** [comment]
Ahh- the index name is hardcoded in the `empty` function. Yes, I see that now. Thanks- will fix! (pull requests welcome)
