### ISSUE TITLE
Time/date navigators

### ISSUE THREAD

**Issue by eklem** [fergiemcdowall/search-index#66]
To be able to set a time range (from time/date to time/date) as a filter/navigator would be great! This is the upstream version of this issue, over at `Norch`:
https://github.com/fergiemcdowall/norch/issues/65

**Comment by eklem** [comment]
And @fergiemcdowall has made a more generic issue for this:
https://github.com/fergiemcdowall/search-index/issues/67

**Comment by fergiemcdowall** [comment]
Maybe good to have this issue open? I like that it is a specific use case for the generic "range navigation" improvement

**Comment by eklem** [comment]
:thumbsup:

**Comment by fergiemcdowall** [comment]
This now works, although some documentation and demos need to made.

**Comment by eklem** [comment]
Does the Reuters or World Bank data set contain date-stamps? If not, I'll make a Twitter data set with nicely formatted date stamps.

**Comment by fergiemcdowall** [comment]
https://raw.githubusercontent.com/fergiemcdowall/search-index/master/test/datasets/worldBankDataFormatted.json contains lots of nice date stamps

**Comment by eklem** [comment]
Great!
