### ISSUE TITLE
Ability to facet and filter on a _range_ of values

### ISSUE THREAD

**Issue by fergiemcdowall** [fergiemcdowall/search-index#67]
At the moment you can facet and filter on single values, but not value 'buckets' or ranges. This functionality was present in earlier builds, but has fallen out of the most recent build because of lazy documentation (my bad) and gaps in the test coverage (also my bad).

**Comment by eklem** [comment]
This would be great stuff @fergiemcdowall ! Would make some of my ideas for "Your life, searchable" a lot easier: http://lab.klemespen.com/2014/11/25/idea-your-life-searchable-with-norch-node-search-ifttt-and-google-drive-spreadsheets/

**Comment by fergiemcdowall** [comment]
should be fixed in master

**Comment by eklem** [comment]
:+1:
