### ISSUE TITLE
Index should be smaller

### ISSUE THREAD

**Issue by fergiemcdowall** [fergiemcdowall/search-index#70]
It should be possible to make the index much smaller. Try to do this.

**Comment by fergiemcdowall** [comment]
https://github.com/fergiemcdowall/reuters-21578-json/tree/master/data/full creates a snapshot.gz of 45mb

**Comment by eklem** [comment]
Nice!

**Comment by fergiemcdowall** [comment]
@mewwts ? any ideas?

**Comment by mewwts** [comment]
I've not had proper time to think properly about this. A nice point is that feature-stripping, e.g. read only indexes or non-fielded search indexes, will reduce the size significantly. I do, however, feel that we should spend some time with the leveldb structure just to ensure that it is as space and computationally efficient as possible. Perhaps we can find time to sit down again in the next following weeks.

**Comment by fergiemcdowall** [comment]
Yes, lets have a sit down the week after next to go over the structure

**Comment by fergiemcdowall** [comment]
Index can now be made much smaller
