### ISSUE TITLE
Multicore processing

### ISSUE THREAD

**Issue by fergiemcdowall** [fergiemcdowall/search-index#71]
Make the mapreduce more powerful by using multicore functionality where available

https://nodejs.org/docs/v0.12.0/api/cluster.html

http://blog.carbonfive.com/2014/02/28/taking-advantage-of-multi-processor-environments-in-node-js/

**Comment by fergiemcdowall** [comment]
This is probably too much functionality to dump into the search-index core. It makes more sense to have a separate module on top that can handle clustering.

**Comment by eklem** [comment]
:+1:
