### ISSUE TITLE
weights don't work

### ISSUE THREAD

**Issue by Holger-Will** [fergiemcdowall/search-index#72]
Weights don't seem to work.
i created a simple testcase. My test docs look like this:
    
    [
	{
		"id":"1",
		"title":"title",
		"body":"test"
	},
	{
		"id":"2",
		"title":"test",
		"body":"body"
	}
    ];

once i have the word test in the body, and once in the title. when i now search with:

    var q={
    "query": {"*":["test"]},
    "weight": {"title": ["100"]}
    }

i get the result:
   
     [
      {id:1, score:0.5, document:[object]},
      {id:2, score:0.5, document:[object]}
    ]

I get the same result when i search for `"weight":{"body":["100"]}` or don't use weight at all.
Am i missing something or are weights broken somehow?

**Comment by fergiemcdowall** [comment]
Hmmmm- thanks for the feedback- I will take a look

**Comment by fergiemcdowall** [comment]
You need to manually specify the field that you are weighting on in order to do a weighted query.

```
var q={
"query": {"title":["test"], body:["test"]},
"weight": {"title": ["100"]}
}
```

It would probably be better if you could do a field weighting without having to specify that field first. On the todo list.
