### ISSUE TITLE
running tests

### ISSUE THREAD

**Issue by Holger-Will** [fergiemcdowall/search-index#76]
this might be a stupid Question, but how do i run the tests? i forked the repository and cloned it to a local one.

**Comment by fergiemcdowall** [comment]
Good question!

short answer: You run `npm test` from the root directory of the cloned repository

longer answer: `npm test` is defined in `package.json` under `scripts.test`. There you see all the commands that are run (there is probably a much cleaner way of running all the tests with only one command, so if you notice a better way to do it- please let us know!)

**Comment by fergiemcdowall** [comment]
This means that you can test only indexing by running `jasmine-node --verbose test/spec/0indexing-spec.js` and so on for each command

**Comment by Holger-Will** [comment]
Perfect, thanks! I will add some test and see what i can do.

**Comment by Holger-Will** [comment]
theoreticaly `jasmine-node test/spec/` should work. the problem is that the separat spec files are not run synchronously. So when some data gets indexed, it locks the levelDown process (at least thats how i understand it) and then jasmin fails silently when a second test tries to index a file.
There are several way to solve this issue:

* write a test runner that runs the test synchronously (that is basically what you do right now)
  but i could write a script that scans the folder for spec files and the run them one after the other.
* file a bug report/enhancemant request with jasmine-node
* switch to a test framework that supports asynchronous testing of multible files.
* compile one large test file from seperate spec files with asynchronous test (which works perfectly well with jasmine-node)
* have seperate spec fiels, but only one for indexing, and the rest that uses that one index. Then do `jasmine-node index-spec.js && jasmine-node test/spec/`. that should run the indexing first, and all other test after that.

writing a test runner would be the fastest solution, and one that would automaticly work on windows as well. Had some problems getting the test to run on windows...i had to install rm for windows, which unfourtunately behaves differently on Win than on Linux :-(

one other thing i noticed is that the test takes quite a while to run. I tried running the test on a raspberry pi and failed miserably due to timeouts. Smaller test and less test data would be great to speed up testing.

What do you think is the best way moving forward?

**Comment by fergiemcdowall** [comment]
The tests should run on a pi, so please feel free to increase the timeouts to PI-suitable values and submit a pull request.

I think the test runner thing is something that should be fixed. Its something that I guess a jasmine expert could do in 10 minutes. Personally I have really struggled with it, maybe Im just missing something. Pull requests welcome.

The ´rm -rf´ could be changed to a node program which would work on all platforms. Please feel free to submit a version that works on Windows.

**Comment by Holger-Will** [comment]
I'm currently investigating vowsJS as an alternative to jasmine.
The advantage of vowsJS is that its truely async, and works with callbacks.
would you mind switching? of course i will rewrite all existing test.

**Comment by Holger-Will** [comment]
the first test would look something like this, though i didn't use the right test data in this case
```javascript
var vows = require('vows'),
      assert = require('assert'),
      fs = require('fs'),
      si = require('../')({indexPath:'si-test1'});

vows.describe('indexing and search').addBatch({
	'should index one file of test data': {
		topic: function () {
			var data=[
						{
							'id':'1',
							'title':'A really interesting document',
							'body':'This is a really interesting document about potatos',
							'about':'potatos',
							'metadata':['red', 'potato']
						},
						{
							'id':'2',
							'title':'Another interesting document',
							'body':'This is another really interesting document that is a bit different',
							'about': 'vegtables',
							'metadata':['yellow', 'potato']
						}
					]
						
			si.add({'batchName': 'test1',
				     'filters': ['metadata','about']},
				     data, 
				     this.callback
			)

		},
		'err not to be empty (search err returned)': function (err) {
			assert.isUndefined(err);
		},
		'should be able to search in indexed data':{
			topic:function(){
				si.search({'query': {'*': ['potato']},
				'facets': ['metadata','about']},
				this.callback);
			},
			'searchResults is defined':function (err,searchResults){assert.isNotNull(searchResults)},
			'and should return 2 results':function(err,searchResults){assert.equal(searchResults.hits.length,2)},
			'facet metadata should be defined':function(err,searchResults){assert.isNotNull(searchResults.facets.metadata)},
			'first facet should be potato':function(err,searchResults){assert.equal(searchResults.facets.metadata[0].key,'potato')},
			'first facet should have a value of 2':function(err,searchResults){;assert.equal(searchResults.facets.metadata[0].value,2)},
			'there should be 3 facets':function(err,searchResults){assert.equal(searchResults.facets.metadata.length,3)},
			'the id of the first document in the result set should be 1':function(err,searchResults){assert.equal(searchResults.hits[0].id,1)},
			'the id of the second document in the result set should be 2':function(err,searchResults){assert.equal(searchResults.hits[1].id,2)},
		},
		'faceting for about should work even though input is not in array format':{
			topic:function(){
				si.search({'query': {'*': ['potato']},
				'facets': ['about']},
				this.callback);
			},
			'searchResults is defined':function (err,searchResults){assert.isNotNull(searchResults)},
			'and should return 2 results':function(err,searchResults){assert.equal(searchResults.hits.length,2)},
			'facet about should be defined':function(err,searchResults){assert.isNotNull(searchResults.facets.about)},
			'first facet should be potatos':function(err,searchResults){assert.equal(searchResults.facets.about[0].key,'potatos')},
			'first facet should have a value of 1':function(err,searchResults){assert.equal(searchResults.facets.about[0].value,1)},
			'there should be 2 facets':function(err,searchResults){assert.equal(searchResults.facets.about.length,2)}
		}
	}
	
}).export(module)
```

**Comment by fergiemcdowall** [comment]
We could definitely mix tests. Some could be jasmine and some could be vows.

**Comment by Holger-Will** [comment]
Ok, so there would be another test runner script in packege.json, but where should the vows test files go?

**Comment by fergiemcdowall** [comment]
You just change the value for 'test': there should be a long string of 'jasmine' commands seperated by '&&'- you simply append a vows command

-- 
Apologies for brevity- this message was sent from my mobile

**Comment by fergiemcdowall** [comment]
Im going to close this issue, since the original question is answered. Please submit improvements to the test suit if you have the time and inclination.
