### ISSUE TITLE
indexPath not respected

### ISSUE THREAD

**Issue by Holger-Will** [fergiemcdowall/search-index#77]
While rewriting the test i came across a strange behaviour:

i have two test files. in the first file i require serach-index like so:

```javascript
var si = require('../')({indexPath:'si-test1'});
```
this will create a dictionary called "si-test1", with the index inside.
then i add some docs to the index an perform some searches...
when running this test standalone everything runs as expected.

In a second test file i have:

```javascript
var si2 = require('../')({indexPath:'si-test2'});
```
but here i don't do anything with the index...( just test for 1==1)
both test run parallel. 

Strangely now all docs are in the index in directory "si-test2" but still accessable via si. 
si2's index is still empty, only the data is somehow bleeding over to the second folder.

Is this the expected behaviour?
should this be tested against, or should the tests avoid such circumstances?

**Comment by fergiemcdowall** [comment]
Yes, I _thought_ that this was recently fixed. Does it still fail if you clone the most recent version from github?

**Comment by Holger-Will** [comment]
Yes, still fails on master branch...

**Comment by fergiemcdowall** [comment]
OK- I'll take a look

**Comment by fergiemcdowall** [comment]
fixed in unpublished master branch
