### ISSUE TITLE
Use checksum to make adding duplicate docs less "expensive"

### ISSUE THREAD

**Issue by fergiemcdowall** [fergiemcdowall/search-index#78]
As of now, when a user adds a doc that is identical to a doc in the index, the doc is deleted and reindexed. This is expensive and unnecessary. 

It would be better to determine document existance by using checksum or similar, so that deletion and indexing only occur when a document is new or altered.

**Comment by eklem** [comment]
This is really useful for my project. Will make me have to write a lot less code :-)

**Comment by fergiemcdowall** [comment]
This should be handled outside of the lib by doing a get() and then comparing the existing doc with the incoming doc using the method of your choice. This has the advantage that partial matches can be handled, and that `search-index` is leaner.
