### ISSUE TITLE
Better weighting

### ISSUE THREAD

**Issue by fergiemcdowall** [fergiemcdowall/search-index#81]
At the moment, weighted searches are limited to fields that are specified in the query:

```
var q={
"query": {"title":["test"], "body:["test"]"},
"weight": {"title": 100}
}
```

This should work, but doesnt:

```
var q={
"query": {"*":["test"]},
"weight": {"title": 100}
}
```

Make the latter work.

**Comment by fergiemcdowall** [comment]
Perhaps the most versitile fix here is implementing an OR syntax:

```
var q={
"ORquery": [{"title":["test"]}, {"body:["test"]"}],
"weight": {"title": ["100"]}
}
```

**Comment by fergiemcdowall** [comment]
Better syntax:

```
var q={
"ORquery": [["title",["test", "words"],[100]}, ["body",["test", "words"]]}]
}
```

**Comment by fergiemcdowall** [comment]
Fields can now be weighted during indexing

**Comment by eklem** [comment]
This could solve some nice things together with field search and OR-queries. Opening again, but

**Comment by fergiemcdowall** [comment]
Have now implemented boosting at the `OR` level. See tests here https://github.com/fergiemcdowall/search-index/blob/master/test/node/general-tests/boost-test.js (docs to be updated)

There may be a case for implementing boosting on individual fields within each `OR` clause. Dont want to over-engineer a solution at this point.

**Comment by eklem** [comment]
Nice! I'll test and try to document.
23. mai 2016 11.50 a.m. skrev "Fergus McDowall" <notifications@github.com>:

**Comment by fergiemcdowall** [comment]
Weighting is with `boost` functionality is fairly robust

**Comment by eklem** [comment]
Wohoo! Will test =)
