### ISSUE TITLE
Search returning no results

### ISSUE THREAD

**Issue by dweberlj** [fergiemcdowall/search-index#85]
With a very simple data set the Search() routine returns an empty hits array.

var docs = [
 {
    'id':'1',
    'title':'A really interesting document',
    'body':'This is a really interesting document',
    'metadata':['red', 'potato']
  },
  {
    'id':'2',
    'title':'Another interesting document',
    'body':'This is another really interesting document that is a bit different',
    'metadata':['yellow', 'potato']
  }
];

si.add({'batchName': 'testdata', 'filters': ['metadata']}, docs, function(err) {
	  if (!err) console.log('indexed!');
	  
	  var query = {
		"query": {"*": ["*"]}
	  };
	  
	  si.search(query, function(err, results) {
		  console.dir(results);
	  });
});

**Comment by fergiemcdowall** [comment]
Thanks for the feedback.

Hmmm, this _should_ work. Will take a look ASAP.

**Comment by dweberlj** [comment]
Thanks for the quick reply!

**Comment by fergiemcdowall** [comment]
Seems to be working in `master`, although may be broken in npm. Am closing bug, but please reopen if it doesnt work for you in master

**Comment by fergiemcdowall** [comment]
should also now work in latest npm version
