### ISSUE TITLE
Make a user manual

### ISSUE THREAD

**Issue by fergiemcdowall** [fergiemcdowall/search-index#86]
a la http://hypothesis.readthedocs.org/en/latest/quickstart.html

**Comment by eklem** [comment]
Make it as a repo of it's own, then it's easier to make a site direktly from markdown?

**Comment by fergiemcdowall** [comment]
Its useful to have someway to tether the manual to the code. Especially now while the API is undergoing breaking changes. It seems like the only way to do this is to have the manual as part of the codebase. This would be in line with the unix philosophy of installing `man`-pages with applications.

**Comment by eklem** [comment]
True. Make a webpage from the readme.md and a "build"-process for the page that makes it look nicer (menus etc) ?

**Comment by fergiemcdowall** [comment]
done
