### ISSUE TITLE
Breaking change from 0.4.16 -> 0.4.17 .empty() undefined

### ISSUE THREAD

**Issue by adamkdean** [fergiemcdowall/search-index#89]
Bit late with this report, considering [I posted it in the wrong library](https://github.com/isagalaev/highlight.js/issues/817#issuecomment-90891264).

Anyway, I'm using search-index on my current site, and it works on 0.4.16, but I've just installed it on my current dev machine and it installed 0.4.17 (because that ~0.4.16 essentially), and it is broken.

It spits it's dummy out when I try to do searchIndex.empty( ... ), saying it's undefined. I specifically went back to 0.4.16 and it works fine. Is this due to me using .empty() wrong? Or is this a breaking change? If so, shouldn't the major be updated?

Thanks though, thought I'd report it. I'm frozen on 0.4.16 for now though.

**Comment by mgtp** [comment]
This seems to be related to #88. After doing the suggested workaround it worked for me.

**Comment by fergiemcdowall** [comment]
Thanks for the bug report.

There is quite possibly some broken-ness in 0.4.17.

0.5.0 is much more stable, and `empty` in particular is now more robust that in 0.4.x versions. There is a slightly different API in 0.5.0, but it is generally better.

**Comment by eklem** [comment]
Tested a little, and it works with:
```javascript
require('search-index')()
```
You only need to add `()`

**Comment by fergiemcdowall** [comment]
+1

**Comment by fergiemcdowall** [comment]
Im sticking the "wont fix" flag on this since a workaround appears to exist, and this pertains to an older experimental version
