### ISSUE TITLE
When to Use Search-Index vs Norch?

### ISSUE THREAD

**Issue by coommark** [fergiemcdowall/search-index#90]
When do you use search index or norch? If I want to index local blog posts, and allow users to search it, which should I use?

Maybe what I want to know is the differences.

**Comment by mewwts** [comment]
Search-index is the module you use within your own node application, where you perhaps define your own REST API routes as well as custom behaviour. Norch already has routes/endpoints for most search applications, like index, search, etc, and can be thought of as a stand alone application that you interact with over HTTP.

**Comment by coommark** [comment]
Thank you @mewwts! Exactly the info I was looking for. So now I know I need search-index, not norch. I was simply looking for a lucene-like module. Thank you a million.

**Comment by mewwts** [comment]
Cool! Have a good one :+1:
