### ISSUE TITLE
use in front-end?

### ISSUE THREAD

**Issue by pianoboysai** [fergiemcdowall/search-index#92]
I think the search engine algorithm could be independent of node.js.
since there are many pure JS data storage libraries,  and  the performance and function of  browser is getting  powerful.  
I think it's doable and valuable for supporting  to use in front-end directly?  also,  it could be used in mobile app.

**Comment by pianoboysai** [comment]
some pure js data storage.
https://github.com/bebraw/jswiki/wiki/Storage-libraries
most of them are K/V or document data storage.

one representative is  pouchdb.
https://github.com/pouchdb/pouchdb

**Comment by eklem** [comment]
Not documented yet, but it is possible to run `search-index` in the browser through `browserify`.

**Comment by fergiemcdowall** [comment]
Hi @pianoboysai 

Yes, you are right. There is still some work to do here, but it is actually possible with the current version. Follow the instructions in the wiki: https://github.com/fergiemcdowall/search-index/wiki/Browserify

Myself and Dale (author of pouchDB) will be giving presentations at the Webrebels conference in may. I have already had a request to make a demo that demostrates indexing of a pouchdb table into search-index, so expect some more info on this within the next few weeks.

**Comment by pianoboysai** [comment]
awesome~~~

**Comment by fergiemcdowall** [comment]
See here for some examples of how to run a search index in the front-end:

https://github.com/fergiemcdowall/search-index/tree/master/examples
