### ISSUE TITLE
Indexing is very slow

### ISSUE THREAD

**Issue by mgtp** [fergiemcdowall/search-index#93]
I've been experimenting with search-index for a bit and found it to be a very good fit for our needs. So thanks for making this available! However, indexing itself is quite slow. On my machine it took about 4 mins to index the reuters-000.json data, which is only 1MB. The data set I'm currently working with is about 60MB, i.e. it may take 4 hours to index. Our data set is still in development and can change multiple times a day, so waiting for several hours every time is not really feasible. Ideally it should take less than 2 mins to index 60MB (120x faster...). And eventually we would want to scale up to indexing several GBs of data. I did a quick profile and found that 99% of the time is spent in incrementallyCalibrate(). I really don't know much about the inner workings of search engines and indexing. Is there anything that can be done to make indexing faster? Thanks!

**Comment by fergiemcdowall** [comment]
I put in a recent update that recalibrates after every doc is indexed. It seems that this has led to slowness. I will take a look

**Comment by mgtp** [comment]
Thanks!

**Comment by fergiemcdowall** [comment]
Just to expand on the reason for this:

Earlier iterations of search-index could index "batches" and then do a bulk calibration. This was faster, but led to issues with concurrancy, and didnt handle mixtures of adds and deletes very well. A better batching system would have a good "queue", and probably distinguish between add-batches and delete-batches.

Revisiting the batching issue should be the focus of a forthcoming significant release

**Comment by thiyaga123** [comment]
I am also have same slow indexing issue . We index 8M records daily once.. so the Batch indexing will fit my use-case. can you pls let me know how /what to change in-order to get old version that uses batch indexing.. 

Thanks for the wonderful module..

**Comment by fergiemcdowall** [comment]
The current version of Norch (https://www.npmjs.com/package/norch) uses a slightly older version of search index that is somewhat faster for indexing. You might be able to use that in the meantime.

Speeding up indexing has top priority

**Comment by fergiemcdowall** [comment]
Now faster in master

**Comment by thiyaga123** [comment]
Thank you very much again. I will check it out ;)
