### ISSUE TITLE
Usage Examples

### ISSUE THREAD

**Issue by thiyaga123** [fergiemcdowall/search-index#95]
Thanks for the excellent module
Can you please let me know how to achieve below features ?

1. Case-Insensitive Search
2. Partial Word match. (I tried, Search-index only matches whole word and i dont know how to set option so that search-index does include partial match also.. Ex: title: "really". If we search "real", it doesnot return anything in my system)
3. Do you recommend to feed search-index with 5 million records (4 fields per doc) and search ? Is it capable of doing that ? 
 
Thanks for  great module ..again..

**Comment by fergiemcdowall** [comment]
First of all- maybe checkout https://github.com/fergiemcdowall/norch ?

1. Its case insensitive by default (I think)

2. Use the 'matcher' endpoint to generate autosuggest fields. Like all search-engines, `search-index` doesnt provide indexing for partial words, it just provides an autosuggest feature.

3. I recently pushed some changes that sacrificed indexing speed for consistency. Indexing might go more slowly as the index grows, but search should always be fast.

**Comment by fergiemcdowall** [comment]
And yes, point taken about examples! :)

**Comment by fergiemcdowall** [comment]
See https://github.com/fergiemcdowall/search-index/tree/master/examples

**Comment by thiyaga123** [comment]
Thank you very much :)
