### ISSUE TITLE
[Question] customize matcher

### ISSUE THREAD

**Issue by larsvoigt** [fergiemcdowall/search-index#96]
Hey,
I have been looking for a good search engine and found the following project.
It is named "search-index" and doing a good job. Now my issue/ question is: 
When searching a word in epub3-books using your engine it is matching all sources at the same time. Is it possible to limit the process to exactly one book? (for example via a given docID)

Thanks, Lars

**Comment by fergiemcdowall** [comment]
Does `get` work? https://github.com/fergiemcdowall/search-index#get

**Comment by larsvoigt** [comment]
I think I need to put my problem more clearly. I index the content of all my epubs. Epub is like a container with many html-files inside. Now I would like to provide an instant search in my application, where I can use the matcher only for one book/ one collection of html files. At moment the instant search show my all hits form every ebook. But I want to see only the hits of the currently open book.
Is it possible to say the matcher to look only into one restricted area?

Or if I got your right I have to build my own matcher for this scenario.  If I fetch all docIds from the current ebook do I have to use ```get``` in order to match within the result index entries?

**Comment by mewwts** [comment]
I think a filter should do the trick here?

**Comment by larsvoigt** [comment]
Do you have practical thoughts for this. Can you share this with me? :-) 
The search index has an api function for this? Or you mean I write an own filter?

**Comment by fergiemcdowall** [comment]
I'm not totally clear what the usecase is, but you can limit search to a range of documents in your index by using a filter (or several filters)

```
'filter': {
  'fieldToFilterOn': [['StartOfRange', 'EndOfRange']]
}
```

A matcher on the other hand is a dictionary of words from the whole index. It will order by the popularity of the word

**Comment by larsvoigt** [comment]
Okay I understand it can only limit the search, but not the matcher. 
Do you see an option to limit the matcher to a range of docs?

**Comment by fergiemcdowall** [comment]
Hei Lars- its great to get feedback from people using search-index in the field! :)

As far as I understand it you want to present "hits" (links to documents)- **in that case you definitely want search with a filter.** If in fact you are only trying to suggest words for the user to search for, then go with a matcher. Matchers can presently not be filtered on, although this may be desirable functionality to develop in the next version

**Comment by larsvoigt** [comment]
Okay thanks for your time. I'm looking forward to this functionality :).

**Comment by fergiemcdowall** [comment]
Your use case can almost certainly be solved with the currently available version of `search-index` using filters. If you want to, you can send me some sample data (say- 2 ePubs), and I can show you how to fix this

**Comment by larsvoigt** [comment]
Great @fergiemcdowall! 
Here you can find examples https://github.com/IDPF/epub3-samples/tree/master/30 .
Sorry that there are a bit more than 2 examples :-)

**Comment by fergiemcdowall** [comment]
Ahh- I see that this is more work that I anticipated

The first task is to parse the data you want to index into JSON. After that we can index into `search-index`.

BTW- I took a quick look and couldnt find a great deal of text. Are these whole books, or just metadata? If so, where is most of the searchable content?

**Comment by larsvoigt** [comment]
Here is the path to the content that needs to be indexed:
https://github.com/IDPF/epub3-samples/tree/master/30/moby-dick/OPS
An example for searchable content can be found in the ops-folder 
-> all chapter files (e.g. ```chapter_001.xhml, ...```).

Here a quick and dirty example to index an epub or more than one:
Note: At the moment the example doesn't consider to store
 the meta information:```bookname``` as a part of an id. E.g.: ```docID = "moby-dick:chapter_001"```
So it is not possible to filter for a specific ebook. I am programming this part at the moment.

```javascript
var fs = require('fs');
var path = require('path');
var cheerio = require('cheerio');
var SearchIndex = require('search-index');
var si = new SearchIndex();

// add your path here
var contentPath = '/path/to/epub/folder(s)'

console.log('folder to be indexed: ' + contentPath);
var docs = getContent(contentPath);
console.log('found ' + docs.length + ' docs that can be indexed');

for (var i in docs) {

    console.log('transform file ' + docs[i] + ' to index format');
    var jsonDoc = htmlToJSON(docs[i]);
    console.log('transformation is ready\n');

    var options = {};
    options.filters = [];
    //options.batchName = 'batch' + Date.now();
    options.batchName = jsonDoc.id;
    
    si.add(options, [jsonDoc], function (err) {
        if (err)
            console.log(err);
    });
}
console.log('all is done');


function htmlToJSON(file) {

    var doc = {};

    try {
        var html = fs.readFileSync(file);

        var $ = cheerio.load(html);

        $("title").each(function (i, e) {
            var title = $(e);
            doc['title'] = title.text();
        });
        $("body").each(function (i, e) {
            var body = $(e);
            doc['body'] = body.text().replace(/\s+/g, ' ');
        });

    } catch (err) {
        console.error(err);
    }
    doc.id = path.basename(file, '.xhtml');
    doc.id = path.basename(doc.id, '.html');

    return doc;
}

function getContent(dir) {

    var results = [];

    fs.readdirSync(dir).forEach(function (file) {

        file = dir + '/' + file;
        var stat = fs.statSync(file);

        if (stat && stat.isDirectory()) {
            results = results.concat(getContent(file))
        } else {
            if (path.extname(file) === '.html' || path.extname(file) === '.xhtml')
                results.push(file);
        }

    });
    return results;
};
```

**Comment by fergiemcdowall** [comment]
Closing  the discussion. We are going to be looking at matcher functionality soon, so please propose an ideas and pull requests
