### ISSUE TITLE
'indexed xx' and 'deleted xx' messages shown with console.log()

### ISSUE THREAD

**Issue by gomezbl** [fergiemcdowall/search-index#97]
Hi, just to mention that when you use the module with add method, 'indexed' and 'deleted' messages are shown using console.log() instead of using winston module. (deleter.js, line 112)

**Comment by fergiemcdowall** [comment]
I had to unwinstonify search-index in order to get the module to run in browsers.

The plan is to go over to bunyan as per #94

**Comment by fergiemcdowall** [comment]
should be fixed in master
