### ISSUE TITLE
Matcher - Customization

### ISSUE THREAD

**Issue by thiyaga123** [fergiemcdowall/search-index#98]
This is just question not an issue.

Is it possible restrict matcher to match on specific column(s). I have 3 columns in indexer db. 
Also is it possible to make the threshold to 2 in following code in matcher.js ?

```javascript

var threshold = 3; //only give matches for strings longer or equal to than this number

```

**Comment by fergiemcdowall** [comment]
Not at the moment, but generally beefing up the matcher functionality could be the focus of a coming release.

**Comment by lannka** [comment]
+1 
Be able to customize the threshold will be very helpful. In my case, I'm creating a index for Chinese people names, a normal Chinese name consist of 2-3 unicode chars. So, I'd like to have a threshold of 1.

Be able a match specific column is also a good to have, if it doesn't significantly increase storage size.

**Comment by fergiemcdowall** [comment]
Yes, It would be good to be able to send an options object to the matcher. At a minimum with:

Threshold
Column (fieldname)
Count/set (the total, or the set of the actual IDs)

**Comment by lannka** [comment]
Have we thought about removing the "threshold" validation? I feel it's something that we can let client to control, if it's harmless to the search-index. Client can always gate the queries in whatever way it wants.

**Comment by fergiemcdowall** [comment]
Yes, the client should definitely be able to control the matcher threshold

**Comment by lannka** [comment]
So do you think we should remove the validation in matcher.js, so that client can have the full control?

However, it might break apps that currently depend on search-index to do the validation, though I don't think that's the right way to do so, as client side validation is preferred to save a client-server round trip.

**Comment by fergiemcdowall** [comment]
Matcher threshold and field are customisable in version `0.6.4`
